### ISSUE TITLE
default_format for Rest not working

### ISSUE THREAD

**Issue by thetrompf** [fuel/core#1001]
Hi, I recently upgraded from fuel 1.1 to 1.2
But in my fuel/app/config/rest.php which I copied from the fuel/core/config/rest.php, I have changed the default_format to json, but it doesn't have any effect, I still have to explicitly tell the controller the format of the request by suffix the request with .json

**Comment by frankdejonge** [comment]
In the rest config you can set the `ignore_http_accept` setting to false, and it will work like expected.

**Comment by WanWizard** [comment]
To add to this, the "default_format" is, as the name implies, a default value, not an override. So it is only used when the format could not be determined by other means.

**Comment by thetrompf** [comment]
Thanks for the help, and the quick response.
