### ISSUE TITLE
Debug::headers(); error on Nginx

### ISSUE THREAD

**Issue by indigofeather** [fuel/core#1002]
``` php
ErrorException [ Error ]: Call to undefined function Fuel\Core\getAllHeaders()

COREPATH/classes/debug.php @ line 351
```

I get an error when I use Debug::headers();

```
http://php.net/manual/en/function.getallheaders.php
```

The php manual said:

> This function became available under FastCGI. Previously, it was supported only when PHP was installed as an Apache module.

If only Apache can work?

**Comment by Stelian** [comment]
getAllHeaders() is actually an alias for apache_request_headers() so it is rather bound to Apache. However it should not trigger an fatal error, rather gracefully degrade into a return array().

**Comment by Daniel15** [comment]
This can be implemented for non-Apache servers on PHP versions before 5.4 by looping through `$_SERVER` and getting all the values where the key starts with `HTTP_`.

This implementation was posted to the comments of [getallheaders](http://au.php.net/getallheaders), but I haven't tested it so can't verify that it works:

``` php
if (!function_exists('getallheaders')) 
 {
     function getallheaders() 
     {
        foreach ($_SERVER as $name => $value) 
        {
            if (substr($name, 0, 5) == 'HTTP_') 
            {
                $headers[str_replace(' ', '-', ucwords(strtolower(str_replace('_', ' ', substr($name, 5)))))] = $value;
            }
        }
        return $headers;
     }
 }
```
