### ISSUE TITLE
Form::textarea generates incorrect textarea content

### ISSUE THREAD

**Issue by ghost** [fuel/core#1005]
Form::textarea generates incorrect textarea content in case value is "0"

The problem is in this check:
core/classes/form/instance.php ~433
$value = empty($attributes['value']) ? '' : $attributes['value'];

because empty("0") === true

personally I don't see why such check is necessary..

**Comment by ghost** [comment]
Sorry, may be I don't understand, but why to check:
strlen($attributes['value']) == 0 and then return ''

isn't:
$attributes['value'] = (string) $value
and 
strlen($attributes['value']) == 0

already mean that $attributes['value'] === '' ?

**Comment by Stelian** [comment]
The initial check was for empty(); empty(0) returns true so another check is in order to preserve the empty() check. The length of the 0 character however is 1, so adding those two conditions, that only returns true only when the variable is trully empty.

**Comment by jschreuder** [comment]
I'm closing this one, further discussion can be done in the pullrequest #1007
