### ISSUE TITLE
Input::protocol() doesn't work properly on Nginx

### ISSUE THREAD

**Issue by Daniel15** [fuel/core#1015]
Input::protocol() checks if the page is being accessed via SSL by performing this check:

``` php
if ((static::server('HTTPS') !== null and static::server('HTTPS') != 'off')
    or (static::server('HTTPS') === null and static::server('SERVER_PORT') == 443))
```

Nginx doesn't have $_SERVER['HTTPS'], so Input::protocol() always returns "https" on Nginx. This should probably be checking if static::server('HTTPS') is explicitly set to on instead of checking if it's not set to off.

I've worked around this by hardcoding the HTTPS variable to "off" in my Nginx configuration:

```
        location ~ \.php$ {
                fastcgi_pass php;
                fastcgi_param FUEL_ENV production;
                fastcgi_param HTTPS off;
                include fastcgi_params;
        }
```

But this would obviously not work if I ever enable HTTPS on this site.

These test cases should all pass:
- Apache, http, standard (80) and custom ports - Should return "http"
- Apache, https, standard (443) and custom ports - Should return "https"
- Nginx, http, standard (80) and custom ports - Should return "http"
- Nginx, https, standard (443) and custom ports - Should return "https"

**Comment by huglester** [comment]
Just upgraded to nginx 1.2.1 and had the same issue until I added the
'fastcgi_param HTTPS off;' to the config as author noticed.

thank you

**Comment by WanWizard** [comment]
I have an issue understanding this logic.

If $_SERVER['HTTPS'] doesn't exist, static::server('HTTPS') will return null. So the first part of the if evaluates to false because of that. The second part evaluates to false if the SERVER_PORT is something else then 443. So Input::protocol() should always return 'http' on a default nginx install, not 'https'.

Nginx suggests to use this in your config:

```
map $scheme $php_https {
   default '';
   https on;
}

fastcgi_param HTTPS $php_https;
```

which will emulate the apache style of detection used in most PHP apps today.

**Comment by Daniel15** [comment]
Ah I found the problem. For some reason, my nginx configuration defines $_SERVER["HTTPS"] with an empty string for the value (so it doesn't equal null, and doesn't equal off - Matches the first condition). See http://lisa.youareaninja.com/phpinfo.php. It's the default Debian nginx configuration.

I'll add that bit to my config and see if it helps.

Thanks!

**Comment by WanWizard** [comment]
I think this suggestion does exactly the same.

Could you replace Input::protocol() with this, and see if it fixes it for you?

```
public static function protocol()
{
    if (( static::server('HTTPS', '') !== '' and static::server('HTTPS') != 'off')
        or (static::server('HTTPS', '') === '' and static::server('SERVER_PORT') == 443))
    {
        return 'https';
    }

    return 'http';
}
```

It should be able to deal with both an empty string and a NULL value (i.e. it's not present in the $_SERVER array).

**Comment by huglester** [comment]
Hello,

@WanWizard, just checked this, removed the option from FCGI config - and in generates non ssl links - BRAVO !:)

Thank you :)

**Comment by WanWizard** [comment]
Cool. Thanks for the feedback.
