### ISSUE TITLE
Core mysql failure - Database_Query->execute() and MySQL SELECT in parenthesis 

### ISSUE THREAD

**Issue by engrangeorge** [fuel/core#1022]
Fuel\Core Database_Query->execute() uses the first six characters of the SQL statement to identify if the query object should be marked as type SELECT.  If this is not done, the select results are inaccessible.  However, in MySQL, a Select query can start with an opening parenthesis i.e. (select.....  This is the recommended syntax for selects with unions (see MySQL reference documentation for 5.5, section 13.2.9.4 Union Syntax.

There are many very simple ways to fix this e.g. by adding an additional  
case '(SELEC':
immediately after: 
case 'SELECT':
to give: 

```
public function execute($db = null)
{
    if ( ! is_object($db))
    {
        // Get the database instance
        $db = \Database_Connection::instance($db);
    }

    // Compile the SQL query
    $sql = $this->compile($db);

    switch(strtoupper(substr($sql, 0, 6)))
    {
        case 'SELECT':
        case '(SELEC':
            $this->_type = \DB::SELECT;
            break;
        case 'INSERT':
        case 'CREATE':
            $this->_type = \DB::INSERT;
            break;
    }
```

.....
Apologies if this has already been noted/fixed.

Thanks.

**Comment by WanWizard** [comment]
Standard SQL doesn't allow for parentheses here.

MySQL has made a propriatary exception to this because it supports ORDER BY on each of the selects in a UNION, which isn't SQL standard as well.

**Comment by WanWizard** [comment]
@FrenkyNet Can you take this into account in the new DBAL MySQL driver?
