### ISSUE TITLE
Inline routes problem

### ISSUE THREAD

**Issue by ghost** [fuel/core#1025]
The problem in how such routes are executed .

On first Request run (in index.php) Request resolves routes, and in case of inline route - user func is executed, which, by documentation, should return new Request instance. That request instance will be passed to Response later, without actually executing that new Request !

So in config/routes.php I have to call execute() on newly created Request instance before returning it.

**Comment by WanWizard** [comment]
I have to agree the documentation isn't exactly clear at this point.

An inline route, like controller methods, should return a Response object. Which you either create in the closure, or create using a manual Request, which indeed means you should not only forge it but execute it too.

I'll update the documentation to make this clear.
