### ISSUE TITLE
Migration::up() doesn't work when there are no previous migrations

### ISSUE THREAD

**Issue by MacTwister** [fuel/core#1026]
Migration::up() doesn't work when there are no previous migrations.

Specifically had issue in creating a new module, and was using the migrate:up command to go through the migrations.

Also:

php oil r migrate:down
In Logs:

Debug - 2012-06-15 13:18:40 --> Migrate class initialized
Info - 2012-06-15 13:18:40 --> Migrating to version: 0
Info - 2012-06-15 13:18:40 --> Migrated to 0 successfully.

When i migrated down from 008_Balhbalh

**Comment by WanWizard** [comment]
On which FuelPHP version?

**Comment by MacTwister** [comment]
I think v1.2. I'm not beside my source at moment to check. (is there a way to check looking at files?) I have 2 projects 1 with 1.2-RC1 and other 1.2 (the newest one I had problem with above ) :)

**Comment by WanWizard** [comment]
In both cases the Migrate code is the same. I'll have a look.
