### ISSUE TITLE
Viewmodel doesn't work with the Parser package

### ISSUE THREAD

**Issue by WanWizard** [fuel/core#1034]
When the Parser package is used, you can no longer use Viewmodels due to the extension needed to select the correct parser.

example:

```
// normal call to load a mustache view
\View::forge('hello/world.mustache');

// this doesn't work
\Viewmodel::forge('hello/world.mustache');
```

Viewmodel::forge() doesn't strip the extension when looking for the Viewmodel class, which it should do to be compatible.

**Comment by frankdejonge** [comment]
@WanWizard shouldn't this be an issue for the parser package?

**Comment by frankdejonge** [comment]
Probably the parser package would extend the viewmodel as well, handling the extension part.

**Comment by WanWizard** [comment]
Too late. But I can revert it if you want.

You have the same without Parser.

```
 View::forge('test.php');  // works
 Viewmodel::forge('test.php'); // doesn't work
```

**Comment by frankdejonge** [comment]
@WanWizard Looks like a nice solution :)

**Comment by bakert** [comment]
As the initial reporter of this issue on IRC yesterday I can confirm that this version fixes my problem.

A workaround that doesn't involve going bleeding edge or waiting for a public release is to use:

```
ViewModel::forge('hello/world');
```

and then in the View_Hello_World ViewModel class adding a public var:

```
public $_view = 'hello/world.mustache';
```
