### ISSUE TITLE
Cache_Storage_File::_get Times out on Solaris

### ISSUE THREAD

**Issue by iturgeon** [fuel/core#1036]
It looks like flock acts a little differently on Solaris, the file must first be opened with read and write permissions in order to lock the file.

http://www.php.net/manual/en/function.flock.php#93400

**Comment by WanWizard** [comment]
Are there still people using Solaris? Isn't that dead yet? ;-)

**Comment by iturgeon** [comment]
@WanWizard I wish we weren't, but thanks to the university's IT policies/staff/reluctance.  I get to help find every projects Solaris conflicts.  

The same issue is occurring in the session file handler

**Comment by shulcsm** [comment]
It's not just Solaris also had this issue on unknown BSD box. It freezes everywhere where flock() is used. All Fuels file operations do this.

**Comment by WanWizard** [comment]
Hmmm... Great. Going on the todo list then...

**Comment by WanWizard** [comment]
Just checking to see if I understand the issue:

If opening the file for read, we should use LOCK_SH, if opening for write, use LOCK_EX. Correct?

**Comment by iturgeon** [comment]
Thanks guys, I was out of reach last week, but your solution works perfectly.

**Comment by shulcsm** [comment]
Isn't that while redundant?

**Comment by WanWizard** [comment]
The while() waits until it gets a lock. Which could be if there is an EX lock on it by some other process.

**Comment by shulcsm** [comment]
by default flock is blocking itself

**Comment by WanWizard** [comment]
You have a point.
