### ISSUE TITLE
Controller Response Property

### ISSUE THREAD

**Issue by gizzmo** [fuel/core#1039]
Shouldn't the `response` property of the Controller class be fully gone deprecated? I still see it being used in [Response](https://github.com/fuel/core/blob/1.2/master/classes/request.php#L383), [Controller](https://github.com/fuel/core/blob/1.2/master/classes/controller.php#L35) and  [Controller_Template](https://github.com/fuel/core/blob/1.2/master/classes/controller/template.php#L63)

**Comment by WanWizard** [comment]
We haven't found a proper alternative for it that we liked, so it's still there.
