### ISSUE TITLE
Hybrid Controller Browser View Source Displays REST JSON

### ISSUE THREAD

**Issue by cdelorme** [fuel/core#1042]
Building a system where normal page loads and AJAX requests request the same information from the DB and have the same processing logic.  To organize my code and eliminate redundancy I used a Hybrid controller, where operations have the same routes.  For example action_news() renders html and get_news() renders a json response.  The operations themselves work fine.

While debugging some CSS I used "View Source" expecting to see HTML.

Both FireFox and Chrome are showing the JSON Response.

**Comment by WanWizard** [comment]
The Hybrid controller uses the REST controller. And that will only convert the results to JSON if the request was an ajax call, which it isn't if you request it using a browser.

Currently, this is by design, but may be reviewed for 2.0.
