### ISSUE TITLE
Mongo modifier operations don't seem to be supported

### ISSUE THREAD

**Issue by davidfsmith** [fuel/core#1043]
Working with Mongo under FuelPHP and it seems that the db.php file whilst initially easy to use doesn't fully support the functions provided by the PHP driver.

For instance $push, $pushAll, $pop, $pull, $pullAll aren't available.

Does anyone have any thoughts about how these could be added in (as I'm happy to look at the coding required), however before starting is it a case that no one is that interested in using Mongo/DB from FuelPHP and uses the native PHP handler, or is Mongo not that widely used with FuelPHP ?

**Comment by frankdejonge** [comment]
The Mongo_Db class is still very small atm. For the next release of fuelphp I'll be working on a query builder which includes mongo support. I have yet to start on the mongo part, but you can follow the progress here: https://github.com/FrenkyNet/Cabinet

**Comment by davidfsmith** [comment]
Looks interesting, will follow, and help where I can
