### ISSUE TITLE
Git tag releases

### ISSUE THREAD

**Issue by mmodler** [fuel/core#1046]
Can you please "git tag" the releases of fuel/core and packages because if you use git submodules it makes updating more comforable.

Thanks!

**Comment by frankdejonge** [comment]
+1 from me, @WanWizard (aka the release master) ?

**Comment by WanWizard** [comment]
We've never done it as it adds another layer of complexity to the release process.

We have a different branch for every version, the correct submodule reference will always be HEAD (the last commit). And fuel/fuel (the app repo) of a particular branch will always contain the correct submodule references.

To update your submodule references in case of an existing project: 
- git submodule git checkout [newbranch]
- git submodule git pull
- git commit -a -m "update submodule references to [newbranch]"

Obviously if your install contains submodule references to other repo's you might want to do the first step by hand.

(edit: github filtered some text)

**Comment by frankdejonge** [comment]
Point taken,

**Comment by mmodler** [comment]
Thanks for the explanation, i'll try the update workflow with the next release.
