### ISSUE TITLE
Upload::is_valid()

### ISSUE THREAD

**Issue by Solovej** [fuel/core#1048]
if (Upload::is_valid()) {

```
            Upload::save();
```

}

Upload::is_valid() - does not work with many files if they will upload by iframe (ajax) and if one file will have bmp type.

array('0'=>'man.jpg', '1'=>'girl.bmp','2'=>'kids.jpg')

Will save just man.jpg, because BMP is not supported, and therefore kids.jpg wil not saved.

**Comment by WanWizard** [comment]
is_valid() will only return true if all files uploaded are valid. If the upload contains a non-valid file, nothing should be saved.

**Comment by WanWizard** [comment]
No further reaction. closing issue.
