### ISSUE TITLE
Cache::delete_all removes non-cache items

### ISSUE THREAD

**Issue by agentphoenix** [fuel/core#1049]
Driver: File

The `delete_all` method in the Cache class removes _everything_ in the `cache` directory, including non-cache files. This causes problems when using version control (Git) to keep files up to date since, now, my .gitkeep file (or index.html file) are removed whenever the cache is cleared with delete_all.

The method should remove only items with a `.cache` extension. (The other solution would be to create the cache directory if it doesn't exist.)

**Comment by huglester** [comment]
Hey,

I've met similar problem. But haven't found good solution in my head so I didn't fire up an issue on github.,,

Smth like this would be an overkill I think, see an example:

you cave cache/dir1/non-cache.files.txt
and have cache/dir2/cache.file.cache
and have cache/dir3/cache.file.cache together with cache/dir3/non-cache-file.txt.. 

How the delete_all() should work? search every directory for specific files *.cache... and after removal check if directory is empty - remove it?

Let's see what other has in their opinions..
