### ISSUE TITLE
Debug::dump() toggle doesn't work!

### ISSUE THREAD

**Issue by billmn** [fuel/core#1061]
In some cases the new <code>static::$js_displayed</code> is already true and it doesn't "echo" the JS function to toggle dumps.

So ... when I click to open the toggle I see in console :
"fuel_debug_toggle is not defined"

In my case I've a Twig extension that dump a variable like {{ variable|dump }}. This extension only run :

<pre>return \Debug::dump($variable);</pre>

**Comment by billmn** [comment]
And I think that can be useful have a configuration where a developer can choose to have, or not, the toggle on dumps

**Comment by huglester** [comment]
Agree on that. I personally don't like toggling it, because mostly if I turn the debug on, I would like to see the dump right away

What do others think?

**Comment by WanWizard** [comment]
@billmn Can you give an example of these "some cases"? I can't see a reason why `static::$js_displayed` would be `true` but the JS function isn't echo'd.

**Comment by billmn** [comment]
I've created a Twig extension using this class :

<pre>
class FuelTest_Twig extends Twig_Extension
{
    public function getName()
    {
        return 'fueltest';
    }

    // Filters
    public function getFilters()
    {
        return array(
            'dump' => new Twig_Filter_Function(__CLASS__ . '::filter_dump'),
        );
    }

    //--------------------------------------------------------------------------
    // FILTERS
    //--------------------------------------------------------------------------
    /**
     * Debug a variable
     *
     * @param  any  Variable to debug
     * @return void Debug dump
     */
    public static function filter_dump($var)
    {
        return \Debug::dump($var);
    }
}
</pre>


In my Twig template I've :

<pre>
{{ variable|dump }}
</pre>


This is my case @WanWizard

**Comment by WanWizard** [comment]
Debug::dump() doesn't return anything, it echo's out. 

If a twig filter needs to return the output, you need to encapsulate the Debug::dump() call in an output buffer block, capture the contents, and return that.

**Comment by billmn** [comment]
Ok ... I've found the problem but there isn't related to the output buffer.

I found a dump in my view source ... my bad!!! :

<pre>
...
&lt;!--
{{ test_var|dump }}
-->
...
</pre>


After this I have a question ... I think that this situation (a few lines of html comment) may also occur to other developers and that can create problems (cannot toggle a dump is a big problem !)

Perhaps, I think, it is best to always declare the Javascript function to each dump

**Comment by WanWizard** [comment]
Sounds more like a hack then a solution.

We're thinking about a new debugging/profiling solution that doesn't rely on data in the HTML output, which becomes less and less useful (think about HMVC calls, REST or SOAP, etc).

**Comment by billmn** [comment]
Ok ... for the HTML comment now is not a big problem.
But the option to choose the "toggle" mode of dump I think is important (like  @huglester )

what do you think about it?

**Comment by billmn** [comment]
@WanWizard Any news about toggle mode?

**Comment by WanWizard** [comment]
@billmn sorry, forgot all about this one.
