### ISSUE TITLE
Incorrect <label> tag for check boxes and radio buttons

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#1062]
I'm not sure if I'm missing something or this is a bug. The following is based on v1.2.1.

If I create a fieldset that has check boxes or radio buttons, a label tag appears that should not be there. For example, if I create a fieldset:

```
$fieldset = Fieldset::forge('form_example')->add_model('Model_Mexamples', $example_id, 'set_form_fields_example');
```

and then add a field:

```
// Checkboxes
$form->add('checkbox_id',
 'Checkbox Test',
 array(
  'type' => 'checkbox',
  'options' => array('1' => 'Red', '2' => 'Green', '3' => 'Blue'),
  'value' => array('1', '2'),
 ),
 array(
 )
);
```

The output looks similar to this:

```
<table>
<tr>
<th class=""><label for="">Checkbox Test</label></th>
<td class="">
<input type="checkbox" value="1" id="checkbox-id_0" name="checkbox_id[0]" > <label for="checkbox-id_0">Red</label><br >
<input type="checkbox" value="2" id="checkbox-id_1" name="checkbox_id[1]" checked="checked" > <label for="checkbox-    id_1">Blue</label><br >
<input type="checkbox" value="3" id="checkbox-id_2" name="checkbox_id[2]" checked="checked" > <label for="checkbox-    id_2">Green</label><br >
</td>
</tr>
</table>
```

Note the label tag in the th just before the "Checkbox Test." The label tag should not be there. A few versions of Fuel ago, there was a bug report for this, and I vaguely remember that it was going to be fixed along with a whole bunch of other issues with the fieldset/form template. 

So, is still a bug or am I missing some changes that occurred in v1.2 and I'm doing something wrong?

**Comment by WanWizard** [comment]
I think that label is there (instead of just the text) to allow you to use CSS style all your TH labels uniformly instead of having to do something different for checkbox labels.

**Comment by Mitchell64** [comment]
Unfortunately, the label inside the th tags is invalid html and will generate a validation error. Also, it would probably confuse screen readers since it doesn't reference anything.

**Comment by WanWizard** [comment]
If that is an issue for you it can easily be remedied by removing `{group_label}`from the `multi_field_template` field of the form template definition.

**Comment by Mitchell64** [comment]
This doesn't quite fix the problem because by removing {group_label} from the multi_field_template, it not only removes the <label> tag, it also removes the label itself. I do have a workaround from Fuel v1 where I remove the <label> tags for checkboxes and radio buttons, but I was hoping this had been fixed in v1.2.

With {group_label}:

```
<tr>
<th class=""><label for="">Checkbox Test</label><abbr class="required" title="required">*</abbr></th>
<td class="">
<input type="checkbox" value="1" id="checkbox-id_0" name="checkbox_id[0]"> <label for="checkbox-id_0">Red</label><br>
<input type="checkbox" value="2" id="checkbox-id_1" name="checkbox_id[1]"> <label for="checkbox-id_1">Green</label><br>
<input type="checkbox" value="3" id="checkbox-id_2" name="checkbox_id[2]"> <label for="checkbox-id_2">Blue</label><br>
</td>
</tr>
```

Without {group_label}:

```
<tr>
<th class=""><abbr class="required" title="required">*</abbr></th>
<td class="">
<input type="checkbox" value="1" id="checkbox-id_0" name="checkbox_id[0]"> <label for="checkbox-id_0">Red</label><br>
<input type="checkbox" value="2" id="checkbox-id_1" name="checkbox_id[1]"> <label for="checkbox-id_1">Green</label><br>
<input type="checkbox" value="3" id="checkbox-id_2" name="checkbox_id[2]"> <label for="checkbox-id_2">Blue</label><br>
</td>
</tr>
```

**Comment by huglester** [comment]
Strange, because I think <label> is the correct solution. 
Having <label for="checkbox_id"> will let you 'activate' checkbox when you click on both checkbox or the label.

**Comment by Mitchell64** [comment]
I believe that the <label for=""> inside the <th> tags is invalid html because the <label> tag doesn't relate to anything (also it's empty). For check boxes and radio buttons the <label> tags relate to the <input> tags.

I'm using html5, and If you run the above code through the html5 validator, it will generate 2 errors:
1. Error: Bad value  for attribute for on element label: An ID must not be the empty string.
2. Error: The for attribute of the label element must refer to a form control.

**Comment by Mitchell64** [comment]
I just tested this in V1.4 and the problem with the misplaced <label> tag is still there.

**Comment by WanWizard** [comment]
The problem is in Form::label. 

If "auto_id" is true in the config, it will add a "for" to all labels, which for the group label it will add the "auto_id_prefix", followed by nothing (because the 'id' is set to null). I think it should only add the "for" if a valid "id" is present.

I assume you have auto_id enabled, and the prefix set to empty string (since you checkboxes don't seem to have a form prefix)?

**Comment by Mitchell64** [comment]
You are correct that I have auto_id set to true and auto_id_prefix set to empty string. I'm not sure I understand the ramifications of how these config variables are set, but I don't think in any case there should be label tags outside of the <input> tags for checkboxes, i.e. in my example above, 

Not correct:

```
<th class=""><label for="">Checkbox Test</label></th>
```

Correct:

```
<th class="">Checkbox Test</th>
```

**Comment by WanWizard** [comment]
It is not a supported setup. The empty label is generated because of this.

If auto_id is set to `true`, auto_id_prefix must have a value. If you don't want a prefix, set auto_id to `false`.
