### ISSUE TITLE
Fieldset add_before() and add_after() do not work correctly

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#1063]
If you try to add a field, the resulting fieldset->fields array is incorrect. For example, if you use the old add() function to add an initial field, something like:

```
$fieldset->add('name', 'Name', array('value' => 'John'));
```

Then you try to add a new field like:

```
$fieldset->add_after('age', 'Age', array('value' => '20'), array(), 'name');
```

Instead of getting:

```
$fieldset->fields = array('name', 'age')
```

you get:

```
$fieldset->fields = array('name', 0)
```

The problem appears to be in arr.php function insert() when array_splice() is called. I don't think array_splice handles associative arrays. Probably need to use array_slice() instead.

**Comment by WanWizard** [comment]
@FrenkyNet Do you have time to check out Arr::insert()?

**Comment by frankdejonge** [comment]
@WanWizard on it
