### ISSUE TITLE
Module's bootstrap is never called

### ISSUE THREAD

**Issue by axelitus** [fuel/core#1066]
The Module's load function adds the module but it never calls the bootstrap file (if present). This should work as the Package's load method (which works fine).

The problem is (comparing to the Package class) that on [Line 98](https://github.com/fuel/core/blob/1.3/develop/classes/module.php#L98) there should be a call to the module's bootstrap file. (I'm not sure if a bootstrap file is enforced in modules as it is in packages, but if not a simple `if(file_exists($path.'bootstrap.php'))` would suffice to check if it exists.

This line exists in Package's file on [Line 93](https://github.com/fuel/core/blob/1.3/develop/classes/package.php#L93) as: `\Fuel::load($path.'bootstrap.php');` and should be also present in Module's file.

**Comment by WanWizard** [comment]
bootstraps are not supported for modules, so it's logical no one is called.

**Comment by axelitus** [comment]
Didn't know that... any particular reason? (As this restrain is not technical)

**Comment by WanWizard** [comment]
It was something that was decided in the past. And 2.0 doesn't really have (this type of) modules anymore, so introducing it now would create a backward compatibility issue when it's time to migrate.

I work around it by calling Module::loaded(), and for each of the loaded modules, I call an init class in the module (in a try/catch in case the class doesn't exist).

**Comment by axelitus** [comment]
Oh, alright. I thought it was something that was missing (as I said, comparing it to the packages class).

As you say, it will be dumb to introduce this change if it'll break things later on while migrating, there are other workarounds for me to try, it just seemed like a good place to init the whole module :)

Thanks for the response and kudos for the great work... can't wait to see the first "official release" of 2.0 (although maybe it won't happen for a relatively long time) it sounds like a major improvement of awesomeness!
