### ISSUE TITLE
Named parameter in beginning of Route not routed

### ISSUE THREAD

**Issue by JaapRood** [fuel/core#1067]
It looks like whenever a named parameter in a route is the first segment, it's not properly routed or available as a param from the Request.

``` php
<?php
return array(
    '_root_'  => 'welcome/index',  // The default route
    '_404_'   => '404',    // The main 404 route

    ':name(/:any)?' => '$1', // get rid of the first segment
);
```

The above code results in a 404 when requesting `example.com/test/welcome/index`. However, when instead of `:name` you use `:segment` it does work.

Some background info on why I'd use this: I'm rewriting `subdomain.example.com` to `example.com/subdomain` so that I can have branded subdomains for an app I'm building. I realise you could just use the first segment, as this is where the subdomain will be, but a named parameter seems like a bit more robust.

**Comment by WanWizard** [comment]
Underlying problem is that named parameters are translated to subpatterns in the route match regex. Which means that it doesn't matter that the named param isn't in brackets, it's still counted as the subpattern must be in brackets. So you need

```
':name(/:any)?' => '$2', // get rid of the first segment
```

to make this work. I guess this needs to be documented better...

**Comment by JaapRood** [comment]
It's all so logical once you know ;) The documentation says nothing about it, so a change there should prevent others from running into the same problem. Cheers!

**Comment by WanWizard** [comment]
I'll leave this one open until this has been documented.

**Comment by WanWizard** [comment]
Documented here: https://github.com/fuel/docs/commit/ce0ba54febe0a42cfce8bc6bfef92b512ab379a2
