### ISSUE TITLE
Idea: inherit Response::redirect() segments

### ISSUE THREAD

**Issue by zoe-edwards** [fuel/core#1069]
So reasonably often I want to do a redirect to a method within the controller I’m already in, or sometimes the same method but with different arguments. I found something similar to this in Magento and thought it was quite useful, but wanted to get feedback if anybody thought it would be useful if I developed it.

Something like

```
Response::redirect('*/*/success');
```

Would automatically redirect to the controller and method (or whatever routing you have). It would be the equiverlent of writing:

```
Response::redirect(Uri::segment(1).'/'.Uri::segment(2).'/success');
```

**Comment by ppawiggers** [comment]
Why not use:

``` php
Response::redirect(Uri::string().'/succes');
```

Or Input::uri(), don't know the difference.

**Comment by zoe-edwards** [comment]
That does solve the problem sometimes, but it’s for when you’re at `checkout/basket/payment` or similar, and need to switch across.

**Comment by WanWizard** [comment]
Downside of implementing this in the core is that on every redirect you'll have to explode, check, optionally lookup and replace, and implode again. For a feature that not everyone will need, and will not need on every redirect.

If we vote this into the core, it should be a Uri class method, so you can do something like:

```
Response::redirect(Uri::complete('*/*/success'));
```

**Comment by WanWizard** [comment]
@FrenkyNet what do you think?

**Comment by frankdejonge** [comment]
Definitely not in the Response class, it would be the Uri class for sure. Then second thing, *'s don't match current url, what then, exception? That'll fly with me.

**Comment by WanWizard** [comment]
You mean if the current URI doesn't have two segments so a \* can't be matched? I would say exception, yes.

**Comment by dbpolito** [comment]
+1. Loved the idea.

**Comment by zoe-edwards** [comment]
Thanks @WanWizard!
