### ISSUE TITLE
Class 'ModuleNotFoundException' not found

### ISSUE THREAD

**Issue by MacTwister** [fuel/core#1071]
If I run Module::load('mymodule'); in my rest_controller.

I get:

ErrorException [ Error ]: Class 'ModuleNotFoundException' not found in module.php class in core.

**Comment by WanWizard** [comment]
The error is quite clear: It means the module can't be found. 

Does a folder with the name "mymodule" exist in any of the paths defined in your config.php as module locations? In lower case (which is required)?

**Comment by MacTwister** [comment]
Sorry, I wasn't clear, think its an error in core.

I think it should display ModuleNotFoundException: Module 'mymodule' could not be found at..... in core/classes/module.php

But instead it shows PHP error cant find the ModuleNotFoundException class. Just thought maybe it was tiny tiny bug.

I dont have a problem in my application, as when i add the write module name i have it works all fine.
