### ISSUE TITLE
Minify HTML Output

### ISSUE THREAD

**Issue by dbpolito** [fuel/core#1077]
Maybe something like this https://github.com/EllisLab/CodeIgniter/pull/965 would be great for fuel.

**Comment by mwager** [comment]
nice idea but i think devs should use build tools like https://github.com/h5bp/ant-build-script/ for this. works great with fuel. else maybe as a package?

**Comment by WanWizard** [comment]
I don't think this should be part of the core, it's an add-on that belongs in a package.

Have a package class capture the "request_finished" event, grab the response of the active request, process it and write it back.

**Comment by polmartinez** [comment]
I'm using:

```
    public function compress_html($html)
    {
        $html = preg_replace('/(<[a-z\\-]+)\\s+([^>]+>)/i', '$1 $2', $html);
        $html = preg_replace('/^\\s+|\\s+$/m', '', $html);
        $html = preg_replace('/\\s+(<\\/?(?:area|base(?:font)?|blockquote|body'
            . '|caption|cite|col(?:group)?|dd|dir|div|dl|dt|fieldset|form|input|textarea'
            . '|iframe|h[1-6]|head|nav|section|header|shr|html|legend|link|menu|meta|script'
            . '|ul|ol|li|opt(?:group|ion)|p|param|t(?:able|body|head|d|h||r|foot|title)?'
            . ')\\b[^>]*>)/i', '$1', $html);
        $html = preg_replace('/(<[a-z\\-]+)\\s+([^>]+>)/i', '$1 $2', $html);

        return $html;
    }

```

**Comment by mwager** [comment]
ok, looks good but this is server overhead on every request. 
why not use build tools as they are especially developed for this use case ?

**Comment by lukearmstrong** [comment]
@fredda I use ant to concatenate and minify my CSS / JS. How on earth can you use "build tools" to minify html when it is generated by PHP, when that HTML will be different for every request?

**Comment by mwager** [comment]
@lukearmstrong ok, you're right with dynamically generated output but for normal views with little use of php you can use tools like the ant build script noted above. They are using [htmlcompressor](http://code.google.com/p/htmlcompressor/)

I'm using this with fuel and tell the ant script to use **all** the files in `fuel/app/views`, run `ant minify` and all the html in those php files is compressed (using `--preserve-php`)

i think using something like `compress_html($html)` for lot of content is too much overhead on every request, maybe combining these would be a good idea

**Comment by lukearmstrong** [comment]
@fredda looking at all the options of [htmlcompressor](http://code.google.com/p/htmlcompressor/) it seems you can remove quite a lot, I assumed it would just be removing whitespace.

**Comment by shulcsm** [comment]
don't do this please, if you really want it make a package

**Comment by WanWizard** [comment]
Read this over, and looked at what CI was doing there. This is definately not something that I consider to be part of the core.

It would not be difficult to use something like https://github.com/tylerhall/html-compressor in a package, and in your index.php do something like

``` php
// replace
$response->send(true)

// by something like
$response->send_headers();
echo \Htmlcompressor\Htmlcompressor::compress($response);
```
