### ISSUE TITLE
Strange variable test in Model_CRUD.

### ISSUE THREAD

**Issue by gander** [fuel/core#1085]
Line: https://github.com/fuel/core/blob/1.3/develop/classes/model/crud.php#L685
Test: http://ideone.com/jcYk6

static::$_rules should be empty array, not "maybe existing variable"...

**Comment by frankdejonge** [comment]
This works perfectly. It checks wether the propperty is there, if not, don't bother. If the isset() is false, the count will never run, so no worries.
