### ISSUE TITLE
Latest version of bootstrap.css and bootstrap.js

### ISSUE THREAD

**Issue by sezzell** [fuel/core#1086]
It seems like the repository needs to be updated with the latest version of the bootstap.css and bootstrap.js files.

I created a project this morning and when using the oil generate admin XXXXX request, everything works fine. When you go to the page in the browser, it's missing the css classes for the navbar. 

I pasted in the latest CSS and JS from http://twitter.github.com/bootstrap/index.html and everything looks correct now.

I'm sure I'm probably doing something wrong. 

Great work guys.

**Comment by WanWizard** [comment]
Related to https://github.com/fuel/oil/issues/136
