### ISSUE TITLE
Saving a single config item?

### ISSUE THREAD

**Issue by lukearmstrong** [fuel/core#1088]
I'm trying to get a migration in a package to update the `always_load.packages` array in `/fuel/app/config.php`, but it doesn't seem to work unless I want to save the entire config file, which I don't as this file contains useful comments which would be lost.

``` php
<?php

$packages = \Config::get('always_load.packages', array());

if ( ! in_array('admin', $packages)) {
  $packages[] = 'admin';
  \Config::set('always_load.packages', $packages);
  \Config::save('config', 'always_load.packages');
}
```

Am I doing it wrong?

**Comment by WanWizard** [comment]
You can not save a single item, you can only save an entire config file (as the file contents will be generated).
