### ISSUE TITLE
YAML Parser outdated or incomplete

### ISSUE THREAD

**Issue by marvinroger** [fuel/core#1092]
Hello,

About 4 hours ago, I receive an email from Transifex saying that the YAML parser was updated. (before, the parser was very instable, now it's stable).

When I import an Transifex exported YAML into FuelPHP, it doesn't work very well. I got :  `Notice! ErrorException [ Notice ]: Array to string conversion`
 for the multilines string. And when I print_r() the __(), here is what I got :
`Array
(
    [0] => \ La particularité de QMCE est le fait de pouvoir développer dans tous ces\
    [1] => \ langages, pour tous les supports !"
    [2] => \ La particularité de QMCE est le fait de pouvoir développer dans tous ces\
    [3] => \ langages, pour tous les supports !"
)`

But the string was : `IDE de développement web et logiciel ouvert à de nombreux langages. La particularité de QMCE est le fait de pouvoir développer dans tous ces langages, pour tous les supports !`
We can see the that the first sentence is not on the array and the second sentence is duplicated. Maybe the parser is outdated or incomplete, but it is a quie big problem because Transifex is one of the best known localization platform.

Here is the .yml generated by Transifex : http://pastebin.com/XKF07Pj9
It is valid, you can check it with http://yaml-online-parser.appspot.com/, in the JSON at the right everything is correct, even the multilines string.

Thanks in advance !

**Comment by kenjis** [comment]
Spyc supports YAML 1.1? https://github.com/mustangostang/spyc/
But the YAML is 1.2? http://www.yaml.org/spec/1.2/spec.html

**Comment by marvinroger** [comment]
You're right on both points. In my opinion it needs to be updated, localization is one of the most importants thing in the choice of a framework. And, Transifex is one of the most best known localization platform, and it uses the 1.2 spec.

**Comment by marvinroger** [comment]
I found https://github.com/symfony/Yaml, I don't know if dev can use that, but it could be a possibility.

**Comment by pachico** [comment]
If you guys ever profile Spyc you will have enough reasons not to use it every again.
If you really need yaml you should get native functions/modules to handle it.

**Comment by WanWizard** [comment]
Appearently the best one around is Symfony's YAML class, which supports the 1.2 spec. As it's PSR compliant, it can be autoloaded by the autoloader when you define the namespace as PSR.

This is not going to be addressed in 1.3.

**Comment by frankdejonge** [comment]
This has been adressed in 2.0
