### ISSUE TITLE
Use ViewModel with themes

### ISSUE THREAD

**Issue by timurbakarov** [fuel/core#1095]
I wanted to use ViewModel with themes but it seems not impossible right now without tweaking the core. It would be good it there was such an option.

**Comment by WanWizard** [comment]
Using Viewmodels is not a problem  All theme class methods accept strings (which will be converted to a View object by the Theme class, or anything else that can be cast to string.

Note that as your theme views are not in the standard location, the Viewmodel won't be able to autoload the view. Instead, you will have to load it manually in the Viewmodel. See http://docs.fuelphp.com/general/viewmodels.html#/changing_view
