### ISSUE TITLE
Can't use Log::write() as documented

### ISSUE THREAD

**Issue by kenjis** [fuel/core#1096]
Documentation says:

```
// and finally, we create a log entry with a custom $level
Log::write('Link', 'More info on http://fuelphp.com/')
```

But it does not work.

The first param is int and must be set in `$loglabels`.

The documentation is right or wrong? I hope the function as decumented.

**Comment by kenjis** [comment]
I sent Pull Request: https://github.com/fuel/core/pull/1097

**Comment by WanWizard** [comment]
Pull request merged.
