### ISSUE TITLE
form auto id generates invalid ids

### ISSUE THREAD

**Issue by shulcsm** [fuel/core#1099]
If you supply nested names without an id to form elements it generates something like id="name[field]" and that's not a valid id
http://www.w3.org/TR/html4/types.html#type-name

**Comment by thetrompf** [comment]
No it's not a valid id in the HTML 4 standard, but I'm quite sure that it is valid in HTML 5 http://mathiasbynens.be/notes/html5-id-class

**Comment by shulcsm** [comment]
Oh. I opened this issue because javascript libraries have trouble with these kind of selectors. I guess it won't hurt to dumb down ids even if they are html5 compatible now.

**Comment by kriansa** [comment]
It should convert the [] into -, like Zend helpers.

So name[field] would be name-field, name[subfield][field] would be name-subfield-field and so on. Even though is a valid HTML5 ID tag, it became hard for javascript to distinguish the content inside the brackets.

#name[field] is translated to <input id="name" field="">

**Comment by WanWizard** [comment]
I'm not sure that's a good approach, that will not allow you to use arrays anymore. There are plenty of cases where that is absolutely not handy, for example when dynamically adding elements...

**Comment by WanWizard** [comment]
Ran a test, but this seems to be implemented at some point, without closing the issue.
