### ISSUE TITLE
Cache class does not work with $dependencies array

### ISSUE THREAD

**Issue by huglester** [fuel/core#1101]
Hello everyone :)

I have played more with cache class, but seems it does not count the $dependencies array.
I spotted that items in the cache aren't expired, when the dependency is expired/deleted.

I tried to look into it, but so far no luck.

Current cache command is:
\Cache::call('vip_images', array('\Profiles\Model_Profile', 'vip_photos'), array(\User::$id), null, array('vip_users'));

I tried doing like this: \Cache::delete('vip_users') - but was still getting the old results,
until I used \Cache::delete('vip_images');

**Comment by WanWizard** [comment]
You might have other issues, as I can not reproduce this.

My test:

```
// step 1
\Cache::set('test1', 'contents of test 1');
\Cache::set('test2', 'contents of test 2', false, array('test1'));

// step 2
\Cache::delete('test1');
\Cache::get('test2');
```

Which gives me an expired exception on the get() of 'test2', as expected.

**Comment by huglester** [comment]
Hello,

just played a bit, also was getting the correct results.
Then I realised that production is useing memcached as a driver, and correct - memcached has this problem.

FILE driver:

``` php
$ php oil c
Fuel 1.3-dev - PHP 5.3.10-1~dotdeb.1 (cli) (Feb  2 2012 23:25:47) [Linux]
>>> \Cache::set('test1', 'contents of test 1');
>>> \Cache::set('test2', 'contents of test 2', false, array('test1'));
>>> \Cache::delete('test1');
>>> \Cache::get('test2');
Error - expired in COREPATH/classes/cache/storage/driver.php on line 293
```

And switched to MEMCACHED driver:

``` php
$ php oil c
Fuel 1.3-dev - PHP 5.3.10-1~dotdeb.1 (cli) (Feb  2 2012 23:25:47) [Linux]
>>> \Cache::set('test1', 'contents of test 1');
>>> \Cache::set('test2', 'contents of test 2', false, array('test1'));
>>> \Cache::delete('test1');
>>> \Cache::get('test2');
contents of test 2
```

**Comment by huglester** [comment]
Thank you, that worked!

**Comment by huglester** [comment]
Probably this line should be fixed too, in APC driver:
https://github.com/fuel/core/blob/1.3/develop/classes/cache/storage/apc.php#L128

Redis:
https://github.com/fuel/core/blob/1.3/develop/classes/cache/storage/redis.php#L163

**Comment by WanWizard** [comment]
Done.
