### ISSUE TITLE
Add the possibilty to overwrite values of Database_Query_Builder_Insert

### ISSUE THREAD

**Issue by AurelHub** [fuel/core#1111]
Hi everybody !

In the Database_Query_Builder_Insert class, method "public function values(array $values)", the comments say : Adds or overwrites values.

But currently, it is not the case for the overwrite function.

If values are allready sets, it is impossible to overwrite them, but the "values" method add a new record in the query.

Related topic in fuelphp forum : http://fuelphp.com/forums/topics/view/10495

Thanks

**Comment by WanWizard** [comment]
@FrenkyNet Can you have a look before 1.3 release?

**Comment by huglester** [comment]
Comments in the core were changed:
https://github.com/fuel/core/commit/798edb9bbb8e48afc99816a76985b549d3c86831

But don't you guys think it would be better to overwrite too?

**Comment by frankdejonge** [comment]
@huglester it could be added as functionality, but it now handles multiple rows for inserts. If you would overwrite, and handle multiple rows, which one does is overwrite?

**Comment by frankdejonge** [comment]
Closing since the actual issue isn't valid anymore, further discussion should be done in a feature request issue.
