### ISSUE TITLE
Theme::get_info() error if $var doesn't exists

### ISSUE THREAD

**Issue by billmn** [fuel/core#1112]
I have a theme ("Theme1") and the fallback ("Default") with info file ... if I try to use get_info() method specifying an undefined $var I get an Error from the Arr class because <code>$this->fallback['info']</code> is false and Arr::get() expect an array.

Check this line : https://github.com/fuel/core/blob/1.3/develop/classes/theme.php#L526

This happening because $theme["info"] is populated by the load_info() method :
https://github.com/fuel/core/blob/1.3/develop/classes/theme.php#L763

but the load_info() use Config::load($file, false) that can returns false :
https://github.com/fuel/core/blob/1.3/develop/classes/theme.php#L622

I've solved the issue using \Config::load($file, false, true) to force the reload of the info file but I'm not sure if is a good practice.

**Comment by WanWizard** [comment]
If the root cause of this case is the fact that Config::load() returns false on subsequent load() calls, then this can be closed, as the current Config class no longer does that, it now returns the already loaded config.
