### ISSUE TITLE
\Config::get() doesn't return the correct default.

### ISSUE THREAD

**Issue by peter-fritchley** [fuel/core#1119]
Now that config has been changed to cache config items in a static property, the default parameter only ever works the first time you get a particular item.

The problem can be reproduced easily with the following code:

``` php
$foo = \Config::get('does.not.exist', 'foo');
$bar = \Config::get('does.not.exist', 'bar');

var_dump($foo, $bar);
```

The problem is caused because the result of the first call to \Arr::get() is cached, no matter whether the item existed in the array or the default was used.

**Comment by WanWizard** [comment]
Fixed after fixiing that pull request.
