### ISSUE TITLE
[Feature] Log Enhancements

### ISSUE THREAD

**Issue by dbpolito** [fuel/core#1125]
I think that would be a great addition to the framework some enhancements to log:
1. Changes Log to be Driver-Based
   - Makes possible to have logs stored on file or database simply changing on config (similar to session).
2. Makes easier to understand custom levels.
3. Creates an Event (log_called for example) so we can easily use that for example to send an e-mail if we get error log.

Let me know what do you think about this so i can send pull requests.

**Comment by tomschlick** [comment]
+1 from me. Logging can definitely be improved via drivers. Code it up!

**Comment by kenjis** [comment]
+1
Driver is Good!

**Comment by bproctor** [comment]
+1
Great ideas! Sounds good to me

**Comment by dbpolito** [comment]
I'm closing this issue as we can continue this on the pull request above.
