### ISSUE TITLE
View::get()  - either fix in-code usage example or method functionality

### ISSUE THREAD

**Issue by initializard** [fuel/core#1127]
View::get() has the following usage example:

```
 $value = $view->get('foo', 'bar'); 
```

However, you can't actually pass in a string as the second parameter. 

From IRC discussion with WanWizard: "you should be able to pass a literal as default value, it's often the logical choice."

**Comment by WanWizard** [comment]
Grr.. stupid typo. Didn't fix PHP. Fixed PHP Notice error... :(
