### ISSUE TITLE
Asset class couldn't find elements

### ISSUE THREAD

**Issue by billmn** [fuel/core#113]
After WanWizard commit ( e14bc5af42976bfaaf3d  - Today ) Asset class couldn't find elements
Before the commit all works fine.

**Comment by jschreuder** [comment]
One correction to this, you were on RC2 before not latest develop - this may not be due to that change.

**Comment by WanWizard** [comment]
The Asset class doesn't use Fuel::find_file() to locate files, it has it's own logic.

**Comment by jschreuder** [comment]
@billmn
Could you further check what seems to cause your issue and give more info? I was wrong about it using Fuel::find_file() but the wrong assumption of the cause doesn't eliminate your bugreport. That being said, the total lack of information about what is wrong makes this an "invalid" issue. There is no way for us to check anything as you don't provide code examples, explanation or error messages.

**Comment by billmn** [comment]
@jelmer

I found the problem ... I saw ticket closed and I haven't advise you. 
In a million of files replacement for testing parser package I set a wrong folder name. 

I correct this and all works fine. 
Thank you guys and excuse me for my error
