### ISSUE TITLE
IE Ajax Caching

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#1131]
We've recently experienced an issue where once IE (v8) has made an AJAX request, it religiously caches the result. This appears to persist even through browser restarts. We overrode \Fuel\Core\Controller so a reasonable fix seemed to be to put something along the lines of this in the before().

``` php
<?php
if (\Input::is_ajax()) {
      header('Cache-Control: no-cache, no-store');
}
```

Is this something that would be useful in the core controller? Possibly controlled by a config param.

**Comment by Altreus** [comment]
This was only for GETs, of course; should that be added explicitly or won't it matter?

**Comment by phil-lavin** [comment]
We didn't try POST but that shouldn't cache either. I don't see the harm in having this header present either way.

**Comment by thetrompf** [comment]
Not for rest controllers anyway, but of cause I doesn't make any sense for
hybrid and template controllers.. Where you actually want to cache stuff..
But often you don't want to cache rest stuff, because it is usually used
for dynamic content.

**Comment by WanWizard** [comment]
I'm closing this request.

It is very application specific, and it's not a lot of work to add this header to the main response in your index.php before it is rendered.

``` php
Input::is_ajax() and $response->set_header('Cache-Control', 'no-cache, no-store');
$response->send(true);
```

Job done.

**Comment by phil-lavin** [comment]
I'd really suggest re-considering this. We've just had the same issue on another site where it appears iPhones now religiously cache requests to .json files to the extent that it takes manually clearing the cache to issue the request a second time.

Although not a problem of the framework, I really think it's something the framework should do as standard to ease the debugging pain that people will suffer.
