### ISSUE TITLE
The before() method does not execute if requested method does not exist

### ISSUE THREAD

**Issue by axelitus** [fuel/core#1139]
[In the docs](http://docs.fuelphp.com/general/controllers/base.html#/before) it states that:
"This method will be executed before the method from the URL is called on your controller, even if that method turns out not to exist."

Well this is not true. If the requested method does not exist, an `HttpNotFoundException` is thrown before it can execute the `before()` method.

I've tracked the issue to [Line 418](https://github.com/fuel/core/blob/1.3/develop/classes/request.php#L418) of the Request class file. That line invokes the before function of the Controller. The problem is that this line is [inside an if](https://github.com/fuel/core/blob/1.3/develop/classes/request.php#L406) that verifies if the method exists or not, so if it does not exist, this line is never reached.

¿Shouldn't this line be outside that if? At the moment either the code is wrong or the description in the docs is wrong.

IMO the before should behave as the docs say, that way one can check for some calls that can be "fixed" or re-routed if they do not exist.

**Comment by WanWizard** [comment]
I would say that the behaviour is correct, and the docs are outdated. If the method requested does not exist, it's no point calling the controller. 

The before() method is a pre-method prepping method. If you're in a situation where the requested method might not exist, or you need in-controller routing decisions, you should use the router() method.

I'll update the docs accordingly.

**Comment by axelitus** [comment]
That makes a lot more sense because if the method does not exist then it is actually a routing decision. So it is then like this:

router() to catch all the controller's routing (this executes first)
before() executes only if the method exists to prep things
action_*() the actual action method
and then the after() method

**Comment by frankdejonge** [comment]
Actually before the action_ it'll do a [http-method]_* check before it, like in the restfull controller. If not there fall back to action_
