### ISSUE TITLE
None escaping of boolean type in PHP for default value in Mysql

### ISSUE THREAD

**Issue by StarpTech** [fuel/core#1144]
The dbutil core class escaped all default values for the mysql string. If you want to set a default value as boolean in php so you cant do it.its just possible if yout write "0" or "1" as equivalent to false and true. For better programming and natural PHP thinking.

dbutil.php - Line 335

//No escaping for boolean Types in PHP
if(is_bool($attr['DEFAULT'])){

$sql .= ' DEFAULT '.($attr['DEFAULT'] ? 'true' : 'false');

}

**Comment by WanWizard** [comment]
This would create

```
DEFAULT true
```

or false, which is invalid for a lot of RDBMS engines. It would be better to replace them with '0' or '1', but that would break dbutil for platforms which DOES support a boolean data type.

So the best solution is to code your dbutil create() correctly for your intended platform.
