### ISSUE TITLE
View->get_Data() should be public, not protected

### ISSUE THREAD

**Issue by axelitus** [fuel/core#1145]
If we need to get the data array from the View from within a `ViewModel` inside the `view()` method for example, we can only do `$this->_view->get('myvar');` for each of the values we want to gather (if we need the whole array and it's really big or we don't really know what's in the array (dynamic) then this becomes an issue).

It would be really helpful if the `get_data()` method from the `View` class was public instead of protected, so we can reach the data from within the `ViewModel`.

The use case is when we need our page to be split into several layout chunks (header, nav, content, footer) and we need to piece them together later. So instead of repeating everything in each controller method, a layout ViewModel is set and it glues the puzzle together (mostly just the layout content changes, but it could easily be extended):

```
public function action_index()
{
    // Set the page contents' view
    $data = array(
        'layout_content' => 'content/main',
        'other_data' => 'some other value'
    );

    // Build the page (as the ViewModel class does not allow to pass in a data array, we need to set each item)
    $viewmodel = ViewModel::forge('layout');
    foreach($data as $key => $val) {
        $viewmodel->set($key, $val);
    }

    return Response::forge($viewmodel);
}
```

The `$this->_view` property inside the ViewMiodel contains the data we just set. Now from within the `view()`method of the ViewModel we could do to pass along the variables to other views if they need:

```
public function view()
{
    $data = $this->_view->get_data();
    $this->layout_header = View::forge('layout/header', $data);
    $this->layout_nav = View::forge('layout/nav', $data);
    $this->layout_content = isset($data['layout_content'])? View::forge($data['layout_content'], $data) : '';
    $this->layout_footer = View::forge('layout/footer', $data);
}
```

So the main layout is created when the `ViewModel::forge('layout');` method is called and within that view there are several pieces which are built with different Views, but the $data is passed along each one of them as it is accesible.

**Comment by WanWizard** [comment]
You don't want to use get_data() for this, as that would return cleaned data. By passing that to another view the data will get cleaned twice, which can lead to double encoding issues.

It also merges global data, so calling it and passing it on will make global data local.

It would be a better open op allow get() to be used without parameter, and return the entire array if you do.

**Comment by axelitus** [comment]
Indeed you're right with all this get_data() cleaning data twice... I see your solution but I think this should also affect ViewModel's get method too so one can get the whole array from a ViewModel object. I think that's missing still...

**Comment by WanWizard** [comment]
Good point, done.
