### ISSUE TITLE
[Feature] Routes defined by annotations in controllers

### ISSUE THREAD

**Issue by tmihalik** [fuel/core#1148]
Read annotations from controllers to define routes

**Comment by WanWizard** [comment]
Don't expect annotations in FuelPHP any day soon. Code has no place in comments, and searching for and parsing annotations will ruin the frameworks speed.

**Comment by tmihalik** [comment]
I meant this to be an option or module, user can decide to use it or not.
Routes generated from annotations could be cached to a file, so it won't ruin the speed.
It also can be used for acl, view, cache, request.
This technique is already implemented in Symfony framework, and has several advantages:
http://symfony.com/doc/master/bundles/SensioFrameworkExtraBundle/index.html
