### ISSUE TITLE
Inflector friendly_title() problem with Arabic characters

### ISSUE THREAD

**Issue by billmn** [fuel/core#1150]
The friendly_title() method doens't support Arabic characters ... try :

<pre>
Inflector::friendly_title('مرحبا العالم')

Variable #1:
  (String): "" (0 characters)
</pre>

Personally, I do not know Arabic ... I think, however, that it is important to provide a method that work with this type of characters. I've found a similar problem in a PyroCMS issues tracker :
https://github.com/pyrocms/pyrocms/issues/145

What do you think would be the best solution?
Integrating conversion Arabic => English through this library ( http://www.ar-php.org/ar-example-Transliteration-php-arabic.html ) or introducing a transliteration out-of-the-box ??

any experience ??

**Comment by WanWizard** [comment]
Not easy to fix I'm afraid, as there are a lot of non-latin characters, and all need to be translated.

**Comment by huglester** [comment]
I think the best bet would be here, that someone knowing arabic could make this happen.

**Comment by billmn** [comment]
Add a translation dictionary for any language is very difficult and require a lot of work for non-latin languages.
It can be a feature for FuelPHP 2.0 ?

However, for the <b>current version</b>, I don't think that return an empty string is a good idea considering the <a target="_blank" href="http://en.wikipedia.org/wiki/Internationalized_domain_name">Internationalized domain name ( IDN )</a>.

I've changed the method to clean, as much as possible, the input string and return non-latin characters if are impossible to convert in ASCII.

Take a look here : http://www.snipr.it/~o0

Is a bad idea?
Security problems could arise?

**Comment by shulcsm** [comment]
What about intl? Can't we use that if available?

**Comment by billmn** [comment]
any idea about this?

**Comment by kenjis** [comment]
I feel  returning non-latin characters in stead of empty string is better.

**Comment by billmn** [comment]
@kenjis I agree ... waiting for an opinion from the CORE team

**Comment by frankdejonge** [comment]
I've made a non-strict mode, where these chars are allowed. If you need actual translation I'd suggest using a dedicated library to do so.

**Comment by billmn** [comment]
I think that this code can create some problems :

<pre>
if ($allow_non_ascii)
{
    // Strip regular special chars.
    $str = preg_replace("#[\.;:'\"\]\}\[\{\+\)\(\*&\^\$\#@\!±`%~']#i", '', $str);
}
...
</pre>

An example :

<pre>
$title = "وقود هو مجتمع مدفوعة إطار شبكة الإنترنت";
$slug = Inflector::friendly_title($title, '-', true, true);
// result :  "لوقود-هو-مجتمع-مدفوعة-إطا?-شبكة-الإنت??ت"
</pre>

Note question marks.
Without '±' symbol the slug is ok : <code>لوقود-هو-مجتمع-مدفوعة-إطار-شبكة-الإنترنت</code> 

Better to remove or can cause other problems?
How about adding some tests for this method to test also the new parameter "allow_non_ascii"?

**Comment by billmn** [comment]
@FrenkyNet 

I've tested the regex that you have give me (<code>"#[.;:'\"]}[{+)(*&^\$#@!\±`%~']#i"</code>) ... but the result is the same

**Comment by kenjis** [comment]
@billmn 

The string is utf-8, so "u" is needed.

`preg_replace("#[\.;:'\"\]\}\[\{\+\)\(\*&\^\$\#@\!±`%~']#iu", '', $str);`

**Comment by kenjis** [comment]
Yes, we need more and more tests for all core class, and packages.
