### ISSUE TITLE
Rest Controller Not Returning Value

### ISSUE THREAD

**Issue by jtwebb** [fuel/core#1151]
print_r'ing $this->response($array); produces a value, however, when trying to retrieve the data without print_r'ing there is no value. It doesn't matter if you've browsed to the url or are trying to get the data through curl, the value is nothing. At the very least, there is an issue with the docs, which I'd be happy to fix once I know what's going on, because even the example there doesn't produce any results.

The exact same code worked for 1.2, now it's not working for 1.3.

**Comment by WanWizard** [comment]
I can not reproduce this.

```
public function get_index()
{
    $this->response(array('test', 'test'));
}
```

returns ["test","test"] as expected.
