### ISSUE TITLE
Date Timezone incorrectly handled

### ISSUE THREAD

**Issue by axelitus** [fuel/core#116]
I'm currently working with dates but I had an issue were the dates I was getting were offseted by 5 hours or so.

I checked my php.ini file to verify that my `date.timezone` value was correctly set, and it was set to America/Mexico_City which is correct, but I was getting dates from another timezone. I then looked into `date_default_timezone_get()` and realized that the timezone was set to UTC (at this moment I didn't know why this was happening as I had America/Mexico_City set as the default timezone). After some time looking around for this I stumbled across the date config file inside Fuel core but there was nothing there that was messing this up... I then looked into the APPATH folder inside the config.php file and found this on line 59:

```
* default_timezone      optional, if you want to change the server's default timezone
```

so I set the new key in the array after the `'server_gmt_offset = 0,`:

```
'default_timezone' => 'America/Mexico_City',
```

I refreshed the site and nothing happened. I still was getting the wrong dates. Well, after more digging I found that in the app's bootstrap.php file are this lines of code:

```
/**
 * Set the timezone to what you need it to be.
 */
date_default_timezone_set('UTC');
```

I think those lines should not exist at all there. I mean, it always overrides the configuration set in php.ini regardless if I want it to or not. What would be more helpful is this:
- The code should run in the timezone specified by the php.ini file (that's the default_timezone)   UNLESS...
- If, and only if default_timezone is specified inside the config.php array, then it should be change to that one.

If the default_timezone configuration is specified I think the timezone change should be called inside the `Fuel::init()` function. The way it currently works is a little bit misleading and does not achieve the flexibility you are aiming at...

**Comment by philsturgeon** [comment]
Right you are. We shouldn't be setting UTC as a hardcoded value at all, but then there are two options:

Either do a get timezone check, see if its missing then set UTC if it is.
Otherwise, set the timezone based on the config (if set)

That way if you config has nothing we dont interfere, and if you server is set up badly it will use UTC.

Some hand holding is required, as the number of issues people raise over this gets ridiculous.

**Comment by philsturgeon** [comment]
Merged, thanks

**Comment by axelitus** [comment]
I kept thinking about what you said about having a fallback in case there's no timezone configuration anywhere, so I just commited that fallback to the same[ branch fixes/timezone in my repo fuel-core](https://github.com/axelitus/fuel-core/commit/6557ddda13342d9c69d900ab38a2c9cd21e9a668)...

I think that should do it so we can get rid of the hard-coded call to `date_default_timezone_set('UTC');`
