### ISSUE TITLE
Cookies and domain option.

### ISSUE THREAD

**Issue by huglester** [fuel/core#1162]
Hello everyone,

I am using simpleauth, and met one problem.
I have a main domain www.site.com and m.site.com for mobile version, and while I switch between both subdomains I loose the login.

My cookie.domain option is set to: '.site.com' (there is  a leading dot)
I spotted, that cookies I create with \Cookie:set('foo', 'bar') are correct, because cookies are created under the .site.com domain - which makes them accessible from different subdomains.

But when fuel creates auth cookie, called fuelcid, it is bound to www.site.com (I believe it takes the base url). 

Does anyone spot such an issue or I am missing something here?

Thank you

**Comment by huglester** [comment]
Hello again!

With help of Frenky we have debugged some more information on this.

If we do:

``` php
    public static function set($name, $value, $expiration = null, $path = null, $domain = null, $secure = null, $http_only = null)
    {
        var_dump($domain);die();
```

Results is: string(0) "" string(0) "" 
Note the var_dump is run twice, probably because of handlers?

I have changed the 'session.cookie_domain' to null (which by default is '', and probably should be null by default) - but this also did not solve the problem. var_dumping gives same $domain = ""

**Comment by kenjis** [comment]
How about this?

Copy config/session.php into your app folder, and set cookie_domain.

**Comment by huglester** [comment]
I tried changing the cookie_domain in the app, then in core/config/session.php with no luck. I always copy config to the app/config/ folder before starting to work with them

**Comment by WanWizard** [comment]
The session drivers all use

```
    // write the session cookie
    if ($this->config['expire_on_close'])
    {
        return \Cookie::set($this->config['cookie_name'], $payload, 0, $this->config['cookie_path'], $this->config['cookie_domain'], null, $this->config['cookie_http_only']);
    }
    else
    {
        return \Cookie::set($this->config['cookie_name'], $payload, $this->config['expiration_time'], $this->config['cookie_path'], $this->config['cookie_domain'], null, $this->config['cookie_http_only']);
    }
```

to set the cookie, so it does use 'cookie_domain'. Currently it has to be a string value, hence the "" default.

**Comment by huglester** [comment]
I have changed not the 'cookie_domain'  => '.site.com', and now can easily navigate between:
site.com www.site.com m.site.com etc after login.

but with the cookie_domain = '' or null it was binding to site.com, or www.site.com - whatever I had visited - not allowing to navigate between versions of site - is it desired behaviour? 

Thank you

**Comment by WanWizard** [comment]
That is how the RFC writers have decided cookies should work, not something we can control. That's why there is a config file available so you can define the domain restriction so that it suits your application. By default, cookies are restricted to "hostname only".
