### ISSUE TITLE
Core\Uri - Possible issue with method segments()

### ISSUE THREAD

**Issue by ghost** [fuel/core#1163]
I am facing an issue with uri segments in a context of multiple requests :

In a multiple requests process, the request's uri objects and their `segments` var are, as expected, different.
I found though an unexpected behavior of the method `segments()`.
It does return a the same unique array, when called from 

```
\Request::active()->parent()->uri->segments()
```

should return `array('exhibition','edit','42')` but unexpectedly return `array('artworks')` that is actually the expected returned value of

```
\Request::active()->uri->segments()
```

Here is a dumped excerpt of Uri objects :
\Request::active()->uri

```
  (Object): Fuel\Core\Uri ↵

    protected uri (String): "artworks" (8 characters)
    public segments (Array, 1 element) ↵
         0 (String): "artworks" (8 characters)
```

\Request::active()->parent()->uri

```
  (Object): Fuel\Core\Uri ↵

    protected uri (String): "exhibitions/edit/42" (19 characters)
    public segments (Array, 3 elements) ↵
         0 (String): "exhibitions" (11 characters)
         1 (String): "edit" (4 characters)
         2 (String): "42" (2 characters)
```

Any explanation ? Is this a bug ?

**Comment by WanWizard** [comment]
This is by design, Uri::segment() and Uri::segments() return the segments of the active request. They are static methods, so they don't have any context.

Use get_segment() / get_segments() instead, which run on the current URI object.

**Comment by ghost** [comment]
Ok, to me this still seems odd as it is really not expected to get a value that is not the one you can see in the Uri object. But, luckily, there is the get_segments method. I'm going to check using it. Thanks for the answer.

**Comment by WanWizard** [comment]
That's the common issue with a static interface, you don't have any context. One of the reasons we're going to drop the static API for version 2.0.

In hindsight it would have been more logical to make segment()/segments() non-static and use something else for the static methods. But changing that would break BC, which we don't do in minor releases.

**Comment by ghost** [comment]
Ok, thanks for the insights. While waiting for the big jump to the promissing 2.0, get_segments() makes it for me !
