### ISSUE TITLE
Date::time_ago returning extra years, again but with a twist ;)

### ISSUE THREAD

**Issue by danielrodriguezac** [fuel/core#1164]
So i found this "issue" a couple of days ago when trying to display the age of an user, i noticed users whose birthdays were within less than six months would appear to be 1 year older, this is not very good when dealing with ages.

Before submitting this issue i made a quick search and found this:
https://github.com/fuel/core/pull/244

It had already been addressed and disregarded, as something that "you can easily override"(i'm paraphrasing), but the thing is, that it makes little sense to round a time_ago value and simonberube explains it very well in that issue. Now jschreuder had a good point, adding parameters to a function should not be the first choice, since you may end up with a function and 20 parameters, or with a broken interface. I doubt however that adding more parameters to it would be complicated, since we could simply:

<pre><code>
public static function time_ago($timestamp, $from_timestamp = null, $unit = null, $options = null)
{}
</code></pre>

Where <code>$options</code> is an associative array with all parameters that may ever be passed to this function and so, never will it ever need another parameter for lil things like round or floor. As with most things in life, this can be fixed with an array.

Now, about triviality, is there any need for this? well no, because we can override it right?... Sooort of right, but by adding this $options we can extend the functionality of a function without modifying much of its code or breaking anything, look at this:

<pre><code>
$options = array('rounding_function' => 'floor', 'an_option' => 'a value for that option');
time_ago($timestamp, $from_timestamp, 'years', $options);

// assuming that the actual difference is about 2 years and 7 months we get something like "2 years ago"
//we could then do something like

time_ago($timestamp, $from_timestamp, 'months', $options);

//and we get something like "31 months ago" we could then easily make some scanf to extract those numbers and do:

$months_not_years = $months - ($years * 12)

//we get a 7, and that mixed with some concatenation can turn into:
// 2 years and 7 months ago
//without having to modify the function too much
</code></pre>

This is obviously a lot easier than calculating it with round, since round can both add and substract depending on the value passed to it, while floor can only substract.

I know it might not be the best implementation, but i hope that the idea is understandable.

**Comment by WanWizard** [comment]
I'm trying to understand the reasoning behind this request.

You will never get a result back in years if it's less then a year, even if you request so. It stops dividing when the result becomes less then 1.

``` php
// will return "3 months ago", even if you want to see years.
Date::time_ago(strtotime('79 days ago'), null, 'year')
```

**Comment by WanWizard** [comment]
If you want to do this calculation yourself, you can always request the result in months, and do the maths yourself, like you propose.

``` php
// will return '2 years ago'
Date::time_ago(strtotime('18 months ago'), null, 'year')

// will return '18 months ago'
Date::time_ago(strtotime('18 months ago'), null, 'month')
```

You can do your scanf on that, and you get the result you want, without the need to modify the core class.

**Comment by danielrodriguezac** [comment]
So, if i want to get an exact amount of years i have to request months and calculate based on that? not very intuitive or descriptive, but then again, you know better :tongue:, anyways, i was just wondering if this could be improved and extended, specially for the 2.0, would be nice to have something with a bit more kick. However if you can recommend me any good package to use as a replacement, that would be cool :dancer:

**Comment by WanWizard** [comment]
The point is that this method isn't intended to calculate people's age's, it's meant to calculate a rough estimate of a relative date in the past, for example a blog post or like github does with commits ("aprox. so long ago").

I can understand the need for something like that, i'll think about how to implement that.
