### ISSUE TITLE
Use Arr for Fieldset's get_config and set_config

### ISSUE THREAD

**Issue by Altreus** [fuel/core#1169]
Currently the only way (that I can see) to add an attribute to the form is

```
$fieldset->set_config('attributes', $fieldset->get_config('attributes') ?: [] + [ 'attr' => 'val' ]);
```

Arr is used everywhere else, so I would simply do:

```
$fieldset->set_config('attributes.attr', 'val');
```

Equivalent for get.

An add_class method on Fieldset would also be useful since class attributes are a) commonly set and b) special in their behaviour.

I'll knock together a patch a bit later on.

**Comment by WanWizard** [comment]
set_config() sets fieldset configuration values. What are you exactly trying to do here? You mean "form_attributes"?
