### ISSUE TITLE
Default app configuration file should contain all Core used settings

### ISSUE THREAD

**Issue by pachico** [fuel/core#1173]
Core classes extensively use configuration values that are not set by default in app config.php.
Examples:

Security::htmlentities

```
\Config::get('security.htmlentities_flags', ENT_QUOTES);
\Config::get('security.htmlentities_double_encode', false);
```

View::_construct

```
\Config::get('security.auto_encode_view_data', true);
```

The config class doesn't know that a previously searched config value is not defined, therefore, it will always try to search for it in the config.php $items and $itemcache arrays. This creates an unnecessary overhead.

Just by adding these 3 values in the app configuration file the number of function calls (Fuel\Core\Fuel::value and Fuel\Core\Arr::get) dramatically decreases.

As a note for developers, it should be considered as good practice not to abuse of Config::get's default values usage.

Profiling applications with and without all these settings values set provides a clear view of the benefits.

**Comment by pachico** [comment]
Quick addition. It's pointless to assert specific performance improvement figure since it depends on each application, however, in applications I've tested number of function calls and CPU usage is reduced between 10% and 19%.

**Comment by WanWizard** [comment]
Went through the entire code, added all missing config key defaults (and one entirely missing file).

**Comment by pachico** [comment]
Great, thanks for your time, mate!
