### ISSUE TITLE
Session::key('session_id') returns false first time it is called

### ISSUE THREAD

**Issue by nnichols38** [fuel/core#1180]
The following simple controller highlights the issue I am having -

``` php
<?php

/**
 * Test Controller.
 *
 * @package  app
 * @extends  Controller_Rest
 */
class Controller_Test extends Controller_Rest {

    public function before() {
        parent::before();
        $this->session = \Fuel\Core\Session::instance();
    }

    public function action_test() {
        $this->session->set('user_id', 12345);
        $this->response(array('sessionId' => $this->session->key('session_id')));
    }
}
```

I need to be able to retrieve the key so that it can be sent as part of a JSON response as the client does not support cookies.  The first time that I call /test/test I receive -
`{"sessionId":false}`
but on subsequent requests it generates -
`{"sessionId":"9dddf3fcb058c181bee70e0238581880"}`

**Comment by jyggen** [comment]
The session is written (or saved) with `Session_<driver>::write()` during Fuel's shutdown event. This method calls `Session_<driver>::create()` if no session exists which is the method that create the `session_id` key.

You can confirm (and work around) it by doing this:

``` php
<?php
class Controller_Test extends Controller_Rest {

    public function before() {
        parent::before();
        $this->session = \Fuel\Core\Session::instance();
    }

    public function action_test() {
        $this->session->set('user_id', 12345);
        $this->session->write();
        $this->response(array('sessionId' => $this->session->key('session_id')));
    }
}
```

**Comment by nnichols38** [comment]
Thanks for your comment jyggen.

That makes sense but it would mean having to include that workaround in every controller method that might be responsible for initiating a session.  Furthermore, it would double the number of session related database writes.  With our current traffic that would mean an extra 400-700 writes per second.

**Comment by frankdejonge** [comment]
@nnichols38 correct me if I'm wrong, but what you're trying to do requires a session. So that's not really a valid argument not to solve it that way. Why would you want to use a session key and not have a session?

**Comment by jyggen** [comment]
@nnichols38 Yeah, I understand that. Just pointing out the source of the issue and how one could workaround it :)

**Comment by nnichols38** [comment]
@jyggen - thanks. I appreciate you taking the time to point out that work around.

@FrenkyNet  - I would have thought the doubling of database writes was very valid justification for not solving it that way.

**Comment by frankdejonge** [comment]
@nnichols38 doesn't have to be that way exactly, for instance, you can write when the id is false, and re-fetch the id, that will only create a 'extra' (which is not really an exta) write one time in the entire session.

**Comment by nnichols38** [comment]
@FrenkyNet - Thank you. Of course. I was being a bit dim. All I need to do is modify the before method.

``` php
<?php

/**
 * Test Controller.
 *
 * @package  app
 * @extends  Controller_Rest
 */
class Controller_Test extends Controller_Rest {

    public function before() {
        parent::before();
        $this->session = \Fuel\Core\Session::instance();
        if (!$this->session->key('session_id')) {
            $this->session->write();
        } else {
            $this->session->rotate(false);
        }
    }

    public function action_test() {
        $this->session->set('user_id', 12345);
        $this->response(array('sessionId' => $this->session->key('session_id')));
    }
}
```

**Comment by frankdejonge** [comment]
Closing this issue as `false` is the correct return value.

**Comment by nnichols38** [comment]
@FrenkyNet - I appreciate that the work around serves its purpose but do you not think it would make sense to modify the driver so that the session_id is assigned at instantiation, if required?

**Comment by WanWizard** [comment]
I will take this issue with me for the rewrite of the session classes that is already on the roadmap.

**Comment by nnichols38** [comment]
@WanWizard - thank you.
