### ISSUE TITLE
ErrorException [ Error ]: Class 'Fuel\Core\Exception' not found

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#119]
I'm experimenting with the Upload class and purposefully set the upload path to something nonexistent and set 'create_path' to false to see what happens when a file upload fails. 

It looks like the code tries to throw an Exception in classes/upload.php line 446:
'Can\'t move the uploaded file. Destination path specified does not exist.'

However the error reported is actually:
ErrorException [ Error ]: Class 'Fuel\Core\Exception' not found

I'm not sure, but it looks like it's expecting to find an "Exception" class?

**Comment by philsturgeon** [comment]
That should be Fuel_Exception I believe. Try changing it to that.

**Comment by WanWizard** [comment]
You might want to upgrade to the latest develop branch, this has been fixed on May 2nd.

**Comment by Mitchell64** [comment]
I downloaded the latest core code yesterday and see that classes/upload.php line 444 has been changed to Fuel_Exception. I just tried again and received the same failure. I've included a little more information:

Fuel\Core\Fuel_Exception [ Error ]: Can't move the uploaded file. Destination path specified does not exist.
COREPATH/classes/upload.php @ line 444

439            @mkdir($path, static::$config['path_chmod'], true);
440            umask($oldumask);
441        }
442        if ( ! is_dir($path))
443        {
444            throw new \Fuel_Exception('Can\'t move the uploaded file. Destination path specified does not exist.');
445        }
446
447        // now that we have a path, let's save the files
448        $oldumask = umask(0);
449        foreach($files as $key => $file)

Backtrace

```
APPPATH/classes/controller/admin/news.php @ line 58
COREPATH/classes/request.php @ line 370
DOCROOT/index.php @ line 49
```

**Comment by Mitchell64** [comment]
Sorry, I inadvertently hit the "Comment and Close" button instead of "Comment."

**Comment by Mitchell64** [comment]
One other thing. I would have thought that trying to upload a file to a nonexistent path would have resulted in a validation error and not an exception.

**Comment by WanWizard** [comment]
Validation is about the uploaded files, an non-existent path is about incorrect configuration that puts the Upload class into a state where it's impossible to continue. And therefore an error is thrown. 

The only thing that might be up for debate is if the path should be checked in process() instead of in save(), but in both cases it would result in an error being thrown.

Catch the error if you don't want your app to abort. This is how Fuel works (most classes throw errors).

**Comment by Mitchell64** [comment]
Sounds reasonable to me. Thanks,
