### ISSUE TITLE
Config::load($file, false) Should not return false

### ISSUE THREAD

**Issue by peter-fritchley** [fuel/core#1191]
The comments for \Config::load suggest that when $group is set to false, the items are not stored - doesn't seem to be the case.

When the group is false - it should be assumed that $reload is true, and therefore the contents of the file should always be loaded fresh and be returned.

This code executes if config has already encountered the file, causing false to be returned.

``` php
if ($group === null or $group === false or ! isset(static::$items[$group]))
{
    return false;
}
```

So the problem can be solved by either not saving the file into the static::$loaded_files array if the group is false, or setting $reload to true if the group is false.

**Comment by WanWizard** [comment]
I don't agree with you that `$group === false` implies that ``$reload === true`. Those are two different features and should be treated as such.

You only get in this branch of code if you first load the config file normally (so it is cached), and after that load the same file with `$group === false`.

It would be better to remove the `false` check from this if, check if the file is cached, and return the cached file if so. This goes wrong if you first load the file into a specific group, and later use `false` as group for the same file. I don't really get why you want want to do that.

Perhaps it's better to think about how we store the combination of file and group so we know into what group a file is loaded, and can return the correct data.

**Comment by peter-fritchley** [comment]
The specific problem that i had was with the Theme class loading it's info file. I see that this has now been changed to use reload, but i still feel like the config class has a problem.

I don't think i agree with you about removing the false check as this would return all items that have been loaded with group being false. The comments at the top of the file suggest that the result of loading the file is not stored in the config array when group is false - implying that even testing if it has already loaded, or checking the $items array is redundant.

**Comment by WanWizard** [comment]
To solve this issue permanently the classes need to be refactored, as the main problem is that the caching is done based on the filename, while the data storage is done on group name, and there is no relation between the two.

Ideally you would like to load each config file only once, cache that result, and use some kind of reference system to have groups point to the loaded data.

I've put fixing this on the roadmap.

**Comment by frankdejonge** [comment]
This is handled in the 2.0 version
