### ISSUE TITLE
HTML attribut value="0" is ignored in all form elements

### ISSUE THREAD

**Issue by sloubi** [fuel/core#1196]
This code 

``` php
Form::input('name', 0);
```

returns

``` html
<input name="name" type="text" id="form_name">
```

instead of 

``` html
<input name="name" value="0" type="text" id="form_name">
```

It is the same with `Form::hidden()`, `Form::select()`, etc.

I think the error is in the base.php, in array_to_attr() function.

**Comment by ghost** [comment]
Form::input() explicitly casts $value as String.
In this situation, array_to_attr() gets 0 as '0' and '0' is considered as an empty value.

**Comment by WanWizard** [comment]
Changed it to only reject NULL and FALSE. I don't see why empty string would be an invalid value too...

**Comment by Savageman** [comment]
Can this be back-ported into 1.4 please? It's a real regression from 1.3.
