### ISSUE TITLE
Development migrations

### ISSUE THREAD

**Issue by zoe-edwards** [fuel/core#1197]
When working on projects with other people we all seem to have different local database settings. Almost every project I use I have to (or forget to, then try and shoehorn in later) add fuel/app/config/development/migrations.php to gitignore – is this something other people would appreciate?

**Comment by WanWizard** [comment]
I think a better solution would be to allow any arbitary environment, so every dev on the project can have their own environment folder.

The basis of this is already implemented, but I'm not sure it already works everywhere (think about oil).

**Comment by zoe-edwards** [comment]
Is that because Oil only allows the set FuelPHP environments?

**Comment by WanWizard** [comment]
I have to go though all code to see if there are any restrictions set.

**Comment by WanWizard** [comment]
Sorry, forgot about this. I haven't tested 1.4, but 1.5/develop does not have any restriction. I have a project where every developer has his own development config folder, and they just used their username for the environment.

You do have to ignore them if you don't want those folders propagate to staging and/or production.
