### ISSUE TITLE
Undefined class constant 'STAGE'

### ISSUE THREAD

**Issue by Miguel-Herrero** [fuel/core#120]
With new installation, after adding some code lines that retrieve info from the Db it gives this error:

ErrorException [ Error ]: Undefined class constant 'STAGE'[/code]
APPPATH/config/db.php @ line 61

My (new) application only consists on a simple Model function with this code:

return DB::select()->from('books')->as_object()->execute();

And this Controller:

$data = array();
$data['result'] = Model_Books::all_books();
$this->response->body = View::factory('books/index', $data);

After adding codeline "const STAGE = 'stage';" to fuel/core/classes/fuel.php it works perfectly.
Is it correct?

**Comment by jschreuder** [comment]
Actually: [it's already there](https://github.com/fuel/core/blob/develop/classes/fuel.php#L48)

I think you either downloaded fuel/fuel and fuel/core from different branches or you didn't update your submodules after updating the fuel repo and fuel/core is out of sync.

**Comment by WanWizard** [comment]
What did you install?

My copy has the constant defined on line 48 of fuel.php. This was introduced in the develop branch on April 23rd. It is not present in RC2 (which was released on April 16th if memory serves me).

Install the develop branch or wait until RC3 is released.
