### ISSUE TITLE
action_404 is not reached in Controller_Hybrid

### ISSUE THREAD

**Issue by mamor** [fuel/core#1201]
In Controller_Hybrid, when action does not exist, action_404 is not reached.
It reaches, if it is a Controller_Template and Controller.

**Comment by WanWizard** [comment]
I can not reproduce this. If I swap Controller in the welcome controller for Controller_Hybrid (and provide a template), it still works as it should.

Can you make sure it's not an application error, and if you do post a controller that we can use to reproduce the error on http://scrp.at?

**Comment by mamor** [comment]
app/config/routes.php
'_404_' => 'index/404',

Access index/action in Controller
http://scrp.at/bWy
'action not found.' displayed.

Access index/action in Controller_Template
http://scrp.at/bWz
'action not found.' displayed.

Access index/action in Controller_Hybrid
http://scrp.at/bWx
'action not found.' not displayed.

It seems to have reached after(), without passing along no action.

**Comment by WanWizard** [comment]
I still can not reproduce that. It displays "action not found" just fine (on a stock 1.5/develop install).

Apart from that, using exit/die in a Fuel application is a bad idea, it would interrupt the application flow, and might have impact on the event processing which will be done even in the case of an exit/die.

**Comment by WanWizard** [comment]
Tested on a 1.4 installation too, and there it works fine as well. You may have a local issue.

**Comment by mamor** [comment]
I understand.
I investigate local environment.

Now, I procedure 1.4/master and 1.5/develop.

My procedure for reproducing.
1: oil create fuelphp

2: I added fuel/app/views/template.php that's empty file.

3: I modified fuel/app/classes/controller/welcome.php

```
    $ git diff
    diff --git a/fuel/app/classes/controller/welcome.php b/fuel/app/classes/controller
    index 2c27a81..9eafd87 100644
    --- a/fuel/app/classes/controller/welcome.php
    +++ b/fuel/app/classes/controller/welcome.php
    @@ -9,7 +9,7 @@
      * @package  app
      * @extends  Controller
      */
    -class Controller_Welcome extends Controller
    +class Controller_Welcome extends Controller_Hybrid
     {

            /**
```

4: I accessed xxx/index and it works fine. Controller does not exists.

5: I accessed welcome/xxx and Nothing is displayed on a browser. Action does not exists.

**Comment by WanWizard** [comment]
Still not reproducable here.

Have you setup the template View? 

For browser requests, Controller_Hybrid reacts like Controller_Template. If you haven't setup the template view, you get `The requested view could not be found: template`, which if error_reporting is disabled will become a blank page.

Closing this as invalid.
