### ISSUE TITLE
1.4/fuel/core/classes/request.php - language problem in execute() method

### ISSUE THREAD

**Issue by ghost** [fuel/core#1203]
While updating a Fuel 1.3 application to 1.4, I encountered a problem retrieving language with Config::get('language').

I work in a multi-lingual environment, so the language in config.php is set to null and the very first request is the one that will set up a language.

Here is the way to reproduce the problem in an empty fuel app:
1. In my fuel/app/config/config.php file, I have:
   'language'    => null, // Default language
2. In fuel/app/classes/controller/welcome.php, I have:
   public function action_index()
   {
       \Config::set('language','fr');
       echo 'language'.\Config::get('language');
       return Response::forge(View::forge('welcome/index'));
   }
3. In fuel/app/views/welcome/index.php, I have:
   &lt;head&gt;
   &lt;body&gt;
       &lt;?php echo 'language'.\Config::get('language'); ?&gt;
       &lt;div id="header"&gt;

The echo in the controller (point 2) successfully displays the language that has been set while the echo in the view (point 3) doesn't display anything.

For clarification, here is the functional behaviour I'm expecting :
1. A main request is called and define a language for the very first time (e.g. based on URL first segment, browser, session language settings);
2. The main request launches sub-requests that will by default use the language set up in the main request. Some of these sub-requests might switch to another language if they needed to.

The problem I see in the management of language in fuel/core/classes/request.php with the execute() method is that for this very first request, there is no language previously defined (the config language being set to null). So, at the end of the execute method, the language is set back to… null. Template rendering occuring after the execute have therefore a null language instead of the one defined during the main request.

Someone suggested to me to set the language before this first request instead of inside it. This seems to be an interesting solution. I might do that in bootstrap.php. What do you think about that ? Should that be the good way to manage language when it is defined to null in the config file ?

By the way, in the execute method, at line 358, there is a problem with the default value argument :
    $current_language = \Config::get('language', 'en');
Although, there is a default value given, this returns null (when no language has been defined in the config.php). Additionally, I think than instead of using 'en' it should use the language_fallback defined in config.

**Comment by WanWizard** [comment]
Problem is that the language is now part of the request context. It get's saved when the request starts, and the original language is restored when the request is finished. Since Views and Viewmodels are by default lazy rendered, the code in them will only be executed long after the request has finished, the request context is then no longer available.

**Comment by ghost** [comment]
OK. I actually did render the view in the main request and everything works fine this way.

Thanks for highlighting this lazy rendering effect.

Note : There might still be improvements to do with the execute method, at line 358, as there is a problem with the default value argument :
$current_language = \Config::get('language', 'en');
Although, there is a default value given, this returns null (when no language has been defined in the config.php). Additionally, instead of using 'en' it should use the language_fallback defined in config.

**Comment by WanWizard** [comment]
The language class will use the fallback internally, no need to use that here.

In your case it returns null, because there is a difference between "not defined" (which will return the set default) and "defined as null" which will return null...

**Comment by ghost** [comment]
OK. Thanks.

**Comment by WanWizard** [comment]
Let us know if you have a chance to test it.

**Comment by ghost** [comment]
Test passed with success ! Thanks !

**Comment by WanWizard** [comment]
Thanks for the feedback!
