### ISSUE TITLE
Image::load() fails with all GIFs and PNGs

### ISSUE THREAD

**Issue by lukearmstrong** [fuel/core#1225]
I was using 1.4/develop, and got this exception when uploading a GIF or PNG, and doing \Image::load()

> imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error

Tried loads of different GIF/PNGs, all get the same error.

Then I updated fuel/core to 1.5/develop, as I noticed some updates had been made to the image class files, and then I started getting this exception.

>  COULD NOT GET THE IMAGE CHANNELS FOR:

Great. Looks like that [commit](https://github.com/fuel/core/commit/e8751dc35afd743382fd4390838757d927241671) didn't really achieve anything.

I can only assume that the problem is because the Image class seems to think that my PNG or GIFs are JPEGs, therefore is using the JPEG versions of the GD functions.

**Comment by lukearmstrong** [comment]
Some clarification...

What I am trying to do is allow someone to upload a JPG, PNG or GIF, and then I will load that file, then save it as a JPG.

```
$uploaded_image = \Image::load($files[0]['saved_to'].$files[0]['saved_as']);
$uploaded_image->save(Menu::custom_image_path().$size.DS.'source'.DS.$filename.'.jpg', 0777);
```

This always used to work.

The first `\Image::load()`, the `image_extension` property is set to `png`.

Then when `\Image::save()` is called, it runs `reload()` which runs `load()` again. The second `load($filename, true)` then runs `check_extension(filename, true)` which changes the `image_extension` property to `jpg` (as that is what I am saving the image to), so it then runs the jpeg versions of the GD functions.

Which naturally fails when running on anything other than a JPG.

If I comment this line, then it works perfectly. Loads the PNG, saves as a JPG.
https://github.com/fuel/core/blob/1.5/develop/classes/image/driver.php#L764

This appears to be related to this Issue:
https://github.com/fuel/core/pull/1206

**Comment by lukearmstrong** [comment]
This also appears to fix it, as it prevents the `reload()`

```
$uploaded_image = \Image::forge(array('persistence' => true));
$uploaded_image->load($files[0]['saved_to'].$files[0]['saved_as']);
$uploaded_image->save(Menu::custom_image_path().$size.DS.'source'.DS.$filename.'.jpg', 0777);
```

**Comment by WanWizard** [comment]
@quetzyg, looks like your change has a side-effect. Could you have a look at it?

**Comment by quetzyg** [comment]
@WanWizard, I only noticed the side effect afterwards, that's why I did another pull request reverting my changes 10 days ago: https://github.com/fuel/core/pull/1206

Like I explained, the problem happens when the persistence config value is set to false (default in app/config/image.php), forcing all the Image instance values to be reverted to their initial state except the file extension.
Having that, if the initial file extension is different from the final, the wrong imagecreatefrom*() function gets called.

**Comment by lukearmstrong** [comment]
@WanWizard whilst the exception message @quetzyg contibuted is shown, it wouldn't be (?) if save didn't default to reloading, and check_extension didn't set a parameter and did what it should do and return bool.

What does persistence mean? I spotted it in the code, and luckily it resolved my problem, but it isn't documented.

I don't want to accidentally use something that I shouldn't, though it does seem to be a suitable temporary fix.
