### ISSUE TITLE
View->set_safe() doesn't work consistent.

### ISSUE THREAD

**Issue by tevfik6** [fuel/core#1226]
View->set_safe() works fine with simple ORM queries. But It still filters related queries anyway. Though, It shouldn't filter.

For example;

``` php
$entries = Model_Article::query()
    ->order_by('create_time', 'DESC')
    ->rows_offset($pagination->offset)
    ->rows_limit($pagination->per_page)
    ->related("tags")
    ->where("tags.name", $tag_name)
    ->get();
```

``` php
echo View::forge('articles/list')->set_safe("entries", $entries);
```

**Comment by WanWizard** [comment]
I can not reproduce this.  

I recreated this structure, added some html to the tags record, and it arrives in the view unencoded.

**Comment by tevfik6** [comment]
Did it work when you print a field from article table in the view? I'm having issue on the article fields. not tag fields.

To see that I don't touch anywhere, just do comment two line;

``` php
$entries = Model_Article::query()
    ->order_by('create_time', 'DESC')
    ->rows_offset($pagination->offset)
    ->rows_limit($pagination->per_page)
    //->related("tags")
    //->where("tags.name", $tag_name)
    ->get();
```

And It comes unfiltered.. But when put these two relation line. It does filter..

I tried many time..

**Comment by WanWizard** [comment]
I still can't reproduce it.

Created a parent->child setup, gave both a field called 'name' containing HTML, and passed it to the view. If I use set(), both 'name' fields are encoded, if I use set_safe(), both are not. Changing the query doesn't make any difference.

**Comment by tevfik6** [comment]
Because of relation I was having only one tag.(which I searched). To fix that I manipulated on the way. I figured out those lines ruined set_safe. Why I can't re-set tags? 

Here is the code that I wrote right after query.;

``` php
$entries = Model_Article::query()
    ->order_by('create_time', 'DESC')
    ->rows_offset($pagination->offset)
    ->rows_limit($pagination->per_page)
    ->related("tags")
    ->where("tags.name", $tag_name)
    ->get();

foreach ($entries as $entry) {
    $entry->tags = Model_Tag::query()
        ->related("articles")
        ->where("articles.id", $entry->id)
        ->get();
}
```

**Comment by WanWizard** [comment]
I don't see this making any difference to the set_safe() behaviour. With or without the foreach, $entry->tags will be an array of Model_Tag objects.

**Comment by tevfik6** [comment]
It will be hardcore solution but I change the query like this everythings works fine now. But there must be something wrong.. About relational results when we manipulate something set_safe doesn't work. Anyway maybe I have local problem. This is a Issue that i couldn't solve with a normal way. 

``` php
$entries = Model_Article::query()
    ->related("tags")
    ->where("tags.name", $tag_name)
    ->order_by('create_time', 'DESC')
    ->rows_offset(0)
    ->rows_limit(2)
    ->get();


foreach ($entries as $entry) {
    $tags = DB::query("select * from `tags` t1 left join `articles_tags` at1 on at1.`tag_id` = t1.`id` where at1.`article_id` = ".$entry->id)
        ->as_object("Model_Tag")
        ->execute();
    $entry->tags = $tags;
}
```

**Comment by WanWizard** [comment]
I still can't reproduce it. So I'm clueless to why you have this issue.

**Comment by tevfik6** [comment]
WanWizard I don't know why I'm having this but Today I realize that When i use ::query() I'm having it.. I'm still digging about it time by time.

**Comment by tevfik6** [comment]
@WanWizard Today, I made some test. I download files. Build a project. Common controller and another controller extended from common controller. Then try to create same senerio..

Definetely something going wrong.. Please try this;

Here is the all files that i used in the project. https://gist.github.com/4380527
When you run this files. It will give you filtered datas, though I used set_safe..  

And then please comment out 

``` php
->related("articles")
->where("articles.language", "tr")
```

lines in `before()` method in `Controller_Common`. You will see that that it will come without filter. Everything works normal. 

The weird stuff; That related query effects another queries.. As you see, I'm trying the print articles in the list view. But my relation in the Tags! which is in common controller. Directly inserts to layout.php..

These are my test results. Now, I'm gonna try to dig inside of ORM package. 

Please give a response about this situation. Maybe I'm using something wrong..

**Comment by tevfik6** [comment]
@FrenkyNet  Solved the problem!

Quick explanation; As I understand, I didn't set my variable with set_safe in Controller_Template variable. Because of lazy loading it effect the other queries. 

Before I used like this;

``` php
$this->template->tags = Model_Tag::query()
    ->related("articles")
    ->where("articles.language", "tr")
    ->order_by("count", "DESC")
    ->limit(10)
    ->get();
```

This fixed my problem;

``` php
$this->template->set_safe('tags', Model_Tag::query()
    ->related("articles")
    ->where("articles.language", "tr")
    ->order_by("count", "DESC")
    ->limit(10)
    ->get());
```

Thanks alot @FrenkyNet and @WanWizard
