### ISSUE TITLE
V1.4 change to array_to_attr() causes a problem

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#1227]
I recently started testing v1.4 and found the following problem with form dropdowns. 

In core/classes/form/instance.php, function select(), line 561 calls the function html_tag() (in core/base.php) which then calls function array_to_attr() (also in core/base.php). 

Function array_to_attr() was changed from v1.3 so that empty values are ignored. This has the unfortunate side effect of breaking a default value for a dropdown form field when used in the following way.

Instead of generating html code like in v1.3.

```
<option value="" style="text-indent: 0px;" selected="selected">Select an option</option>
```

v1.4 generates the following code without any value set. Subsequent code can no longer check if the dropdown value is empty because there is no value.

```
<option style="text-indent: 0px;" selected="selected">Select an option</option>
```

The key change was that v1.3 uses

```
if (is_null($value))
```

while v1.4 uses

```
if (empty($value))
```

Also curious what the rationale behind this change was.

**Comment by WanWizard** [comment]
There wasn't, it was a cock-up, and has been fixed: https://github.com/fuel/core/blob/1.5/develop/base.php#L91 in 1.5/develop. You can backport base.php to 1.4 without problems.
