### ISSUE TITLE
Config::save() consistency with Config::load()

### ISSUE THREAD

**Issue by Savageman** [fuel/core#1229]
Config::load() uses Finder::search('config', $this->file, $this->ext);

Config::save() uses Finder::search('config', $file_with_extension, null);

save() should construct the driver passing the filename as first parameter, for consistency.

**Comment by Savageman** [comment]
Great. You aim to please, as always. Thanks!

**Comment by it-can** [comment]
It seems that when I run:

```
php oil refine migrate

--
Performed migrations for app:default:
001_create_users
```

It creates a file: 
_app/config/development/migrations_

should this not be:

_app/config/development/migrations.php_

?
