### ISSUE TITLE
Problem with autoinit of autoloaded class

### ISSUE THREAD

**Issue by imunhatep** [fuel/core#1239]
In file "somewhere/a.php":
<?php
class A
{
  private static $phrase = 'Oops';

  public static function _init(){
    static::$phrase = "Hello world!";
  }

  public static function sayPhrase()
  {
    print static::$phrase;
  }
}

In file "somewhereelse/b.php":
<?php
class B
{
  public static function sayHi()
  {
     \A::sayPhrase();
  }
}

If i'll call \B::sayHi(), I'll get "Oops", because of autoloader have set static::$auto_initialize to "B", and A::_init() will never be called...

**Comment by WanWizard** [comment]
Re-created your example setup here, and I get "Hello world!" here. 

So I think you need to look at your local setup.
