### ISSUE TITLE
Migrations file with no extension

### ISSUE THREAD

**Issue by it-can** [fuel/core#1241]
It seems that when I run:

```
php oil refine migrate

--
Performed migrations for app:default:
001_create_users
```

It creates a file: 
_app/config/development/migrations_

should this not be:

_app/config/development/migrations.php_

I think it has to do with this commit: https://github.com/fuel/core/commit/bc026b9d52118e98a275dcba6a841e1c14e13130

**Comment by WanWizard** [comment]
Has been fixed in https://github.com/fuel/core/commit/5253cc5114d2c95b1a407eb6a47bf67566238b03
