### ISSUE TITLE
Add MongoDB driver for session

### ISSUE THREAD

**Issue by dennislean** [fuel/core#1249]
I would like to suggest that add MongoDB driver for the Fuel Session.

Since FuelPHP already support Memcache and Redis, I believe it is not that hard to add MongoDB.

**Comment by tomschlick** [comment]
While I agree that this would be a nice feature to have, keep in mind that at the present time MongoDB has database level locking so using it for something like sessions is kind of a bad idea performance wise until they get to collection/document level locking.

I use mongodb for a ton of stuff but sessions is not one of them at the present time. I would strongly encourage you to take a look at using redis/memcached for sessions until the mongo stuff is up to the task.

**Comment by WanWizard** [comment]
Closing this as not useful to implement at the moment.
