### ISSUE TITLE
Add environment constants

### ISSUE THREAD

**Issue by omissis** [fuel/core#125]
Hi,
  in my development process I usually have local, dev, stage, test and prod environments, which are partly mapped by the environment constants found in Fuel class.
I was wondering if it is possible to either add them or find a more flexible solution to solve this problem whatever the number and the name of the environments somebody wants to use.

**Comment by WanWizard** [comment]
The best place to do that whould be in app/config/config.php, that's where I do it. Based on the environment I run in I set the config keys 'environment' (which also selects the correct database for that environment), 'profiling' and 'log'.

You can add any code you want before the return statement.

**Comment by dhrrgn** [comment]
Simple:

Add the file app/classes/fuel.php.  In that PHP file do this:

``` php
<?php

class Fuel extends Fuel\Core\Fuel {
    const PROFILING = 'profiling';
    const LOG = 'log';
    // Add as many as you want
}
```

Done.

**Comment by omissis** [comment]
hmm I was thinking more of a config/dependency injection rather than inheritance, but still that should do, thanks.

**Comment by dhrrgn** [comment]
Making them configurable/using (stupid) Dependency Injection would just overcomplicate things.

**Comment by omissis** [comment]
hehe I see :)

**Comment by jondavidjohn** [comment]
Don't you also need to add it to the Autoloader::add_classes in the application bootstrap file?

**Comment by philsturgeon** [comment]
Yep, application bootstrap is where the logic goes for assigning which environment is currently live.

**Comment by dhrrgn** [comment]
Actually @philsturgeon and @jondavidjohn, no, you don't.  The Fuel classes is loaded prior to the app bootstrap.  We do an auto-check for app/classes/fuel.php prior to autoloader loading, so no need to add it there.  It is a weird thing that will change eventually, but for now, no need.

Sadly this also means that the Fuel class can only be "overriden" by the app...no packages.  Obviously extensions are still possible by packages...but the core will not use those extensions.

**Comment by jondavidjohn** [comment]
could it create problems if I manually add it to the autoloader? have any effect?

**Comment by dhrrgn** [comment]
@jondavidjohn  It will have no affect.
