### ISSUE TITLE
count(static::$_rules) < 0 in class Model_Crud

### ISSUE THREAD

**Issue by dennislean** [fuel/core#1250]
I found this line of code in class Model_Crud, protected function run_validation:
//Line: 709 and Line 687 on version 1.4
if ( ! isset(static::$_rules) or count(static::$_rules) < 0)
{
 return true;
}

According to PHP Manual: http://www.php.net/manual/en/function.count.php
The return values for function count:
- Returns the number of elements in var. If var is not an array or an object with implemented Countable interface, 1 will be returned. There is one exception, if var is NULL, 0 will be returned.

The count function never return value less than 0.

So, if the static::$_rules is set, then the count(static::$_rules) < 0 will always return false because (the smallest number) 0 < 0 is false.

So, why compare the count(static::$_rules) < 0 ? Is this a bug?

**Comment by frankdejonge** [comment]
This is done because it can or cannot be defined. it can also be adjusted to be an empty array. When it's not set count(static::$_rules) will raise an error because $_rules is not defined.
