### ISSUE TITLE
Gearman Support

### ISSUE THREAD

**Issue by excalibur1976** [fuel/core#1254]
I suggest to add full gearman support to the fuelphp core.

"Gearman is a generic application framework for farming out work to multiple machines or processes. It allows applications to complete tasks in parallel, to load balance processing, and to call functions between languages."

For hightraffic webpages it is useful, to let gearman handle tasks like video-converting, uploading large files in the background. The user can still continue using the webpage / application and after the task is finished he can retrieve a response.

Gearman also check wich worker is "free" and can do the requested task.

See also: http://de2.php.net/manual/en/intro.gearman.php

**Comment by tomschlick** [comment]
What entails adding "full gearman support"? Are you not just adding hooking into your own apps for queuing things such as email sends & other events? What more can the framework do other than abstracting gearman further?

**Comment by excalibur1976** [comment]
Some examples: with oil it can be easy to create gearman workers. the integration with the fuelphp framework will make it easier to use without "leaving" the framework and so on. there exists already gearman components, utility classes or gearman bundles in other frameworks like ZF, symfony2 or yii. so why not also for fuelphp.

**Comment by WanWizard** [comment]
This is application or implementation specific, and it therefore does not belong in the core. But it sounds like an excellent idea to make it into a Fuel package.

**Comment by kenjis** [comment]
For your information: https://bitbucket.org/takyam/fuel-gearman

**Comment by huglester** [comment]
Probably would be a good idea to put it on github, so It can be forked to: https://github.com/fuel-packages
