### ISSUE TITLE
html_tag / empty

### ISSUE THREAD

**Issue by shox** [fuel/core#1257]
Hi,

Using empty php inside array_to_attr:\core\base.php line#91 function create problem when dealing with zero values, for example when we need to generate a select box from Form class:fuel\core\classes\form\instance.php line#562 with &lt;option value="0"&gt;Test&lt;/option&gt;, because empty consider zero as empty value, the problem i fixed in fuel\core\base.php line #91
 if (empty($value)  )  changed to if (empty($value) &&  (int)$value !== 0 )
http://php.net/empty
http://stackoverflow.com/questions/732979/php-whats-an-alternative-to-empty-where-string-0-is-not-treated-as-empty

Thanks & BR

**Comment by WanWizard** [comment]
This has already been fixed in 1.5/develop: https://github.com/fuel/core/commit/dfe71da5da48557c33c3c21f484f716649144ce1
