### ISSUE TITLE
[apc] dynamic inheritence

### ISSUE THREAD

**Issue by it-can** [fuel/core#1262]
Hi guys,

I am using PHP 5.4.10 + APC 3.1.14 and sometimes I am seeing this error:

```
Error - 2013-01-08 09:54:54 --> 2 - include(): Dynamic inheritance detected for class model_blog in /home/test/public_html/fuel/core/classes/autoloader.php on line 282
```

When this error is thrown the script stops working...

Does someone know how to fix this?

**Comment by WanWizard** [comment]
Restart your webserver. And preferably disable APC. 

APC caches your code, and doesn't play ball very well with constantly changing code in a development environment.

Using an opcode cache in development is not a good idea anyway, it might leave you with the false notion that your code is faster then it actually is... A development environment should reflect the worst-case imho.

**Comment by it-can** [comment]
Yeah, I know, but this was on my live machine... I switched to xcache and the problem is gone... Seemed like APC would hang on that error message somehow...

**Comment by WanWizard** [comment]
It's a known error with APC. Haven't got a clue what causes it.
