### ISSUE TITLE
strip_extension doesn't work as expected

### ISSUE THREAD

**Issue by ghost** [fuel/core#1266]
I'm having problems with the `strip_extension` config setting.

Controller:

``` php
class Controller_Test extends Controller
{
    public function action_index($param = false)
    {
        var_dump($param);
        var_dump(Input::extension());
        exit;
    }
}
```

When I set `strip_extension` to `true` in config and I visit `test/index/12345.json` I get the following results, as expected. So far so good.

```
string '12345' (length=5)
string 'json' (length=4)
```

However, when I now set `strip_extension` to `false` I get the same results. I was expecting to see the extension as a part of `$param` now.

```
string '12345' (length=5)
string 'json' (length=4)
```

It still strips the extension. 

Only when I add a route like `'test/(:segment)' => 'test/index/$1'` and I visit `test/12345.json` I get the following result, which is as expected.

```
string '12345.json' (length=10)
string 'json' (length=4)
```

Conclusion: `strip_extension` only seems to work when using routes, it should work without a custom route too.

**Comment by WanWizard** [comment]
Good catch.

When no route can be found that matches, a new route object is constructed using the current URI, which is then used to find the controller. As URI, $request->uri->get() is used, which returns a URI with a stripped extension.

I'll look into it.

**Comment by WanWizard** [comment]
Looked at the code. 

Route explicitly strips the extension when it's a non-routed request, which I assume is for a purpose. I need to find that purpose before I can change it, it might have side effects that impact compatibiilty.
