### ISSUE TITLE
New log package

### ISSUE THREAD

**Issue by it-can** [fuel/core#1267]
Hi @WanWizard , seems the new log package is logging all (using the latest commit f2b4b5479fcdcad5ffd19e255850fc84836e9c5b)...

my config:

``` php
'log_threshold'    => Fuel::L_WARNING,
'log_path'         => APPPATH.'logs/',
'log_date_format'  => 'Y-m-d H:i:s',
```

my log:

``` php
<?php defined('COREPATH') or exit('No direct script access allowed'); ?>

INFO - 2013-01-12 11:09:49 --> Fuel\Core\Request::__construct - Creating a new Request with URI = ""
INFO - 2013-01-12 11:09:49 --> Fuel\Core\Request::execute - Called
INFO - 2013-01-12 11:09:49 --> Fuel\Core\Request::execute - Setting main Request
```

**Comment by WanWizard** [comment]
Still working on it. ;-)

**Comment by it-can** [comment]
okay,I'll be patient... ;-)

**Comment by WanWizard** [comment]
Should be fixed now.

**Comment by it-can** [comment]
@WanWizard there seems to be an issue with unit testing:

```
PHP Fatal error:  Class 'Monolog\TestCase' not found in /fuel/packages/log/tests/Monolog/Formatter/JsonFormatterTest.php on line 18
Error - Class 'Monolog\TestCase' not found in PKGPATH/log/tests/Monolog/Formatter/JsonFormatterTest.php on line 18
```

**Comment by frankdejonge** [comment]
@IT-Can if you want to run the tests for that particular package you'll have to clone it yourself. We don't need all the development files. (which requires `$ composer install --dev`)

**Comment by it-can** [comment]
I am just running: _php oil test_
and then the errors shows up. But I understand!

Also this file needs to be removed: https://github.com/fuel/core/blob/1.5/develop/tests/log.php
