### ISSUE TITLE
Flash message behaviour has changed

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#1285]
Raised on IRC, i'll re-raise here for posterity:

(12:00:00) <Phil-Work> hm, WanWizard... when you are. Are you aware that https://github.com/fuel/core/commit/50d6e07e4436fc2e1528697be93fe12448b16f9a changed the behaviour of flash messages in such that they won't expire on the same request whereas they used to do such?
(12:01:31) <Phil-Work> if so, is it worth considering maintaining compatibility with 1.4 in such that the usecase of wanting to view a flash message on both the current page and the next is less frequent than wanting to only view it on the current page?
(12:02:01) <Phil-Work> default of $expire should probably be true
(12:02:28) <Phil-Work> this also seems related: https://github.com/fuel/core/commit/1c3dc2a
(12:03:27) <Phil-Work> I think 1c3d changed the behaviour and 50d6 added a way to override per get_flash()

**Comment by WanWizard** [comment]
Fixed in c74ec5a8a426a4dc72e67a6008a62276a5e12feb / b0d5cda001bb71c637d4182c99098f30903c4020
