### ISSUE TITLE
When run unit test, "development/config.php" will be loaded instead of "test/config.php"

### ISSUE THREAD

**Issue by mamor** [fuel/core#1287]
When run unit test, "core/bootstrap_phpunit.php" will be loaded.
Then, "app/bootstrap.php" will be loaded in "core/bootstrap_phpunit.php".
And Fuel::DEVELOPMENT is set to Fuel::$env.
Therefore, "development/config.php" will be loaded.
Other configuration files will be loaded in the "config/test" directory.

**Comment by mamor** [comment]
I sent Pull Request https://github.com/fuel/core/pull/1288

**Comment by kenjis** [comment]
This is because, oil `require APPPATH.'bootstrap.php';`
The Pull Request works fine?

**Comment by mamor** [comment]
Works fine. Because, unit test run as another process by passthru() in command.php

**Comment by mamor** [comment]
When set FUEL_ENV by phpunit.xml, the following code in "core/bootstrap_phpunit.php" may be unnecessary.

```
// Set the environment to TEST
Fuel::$env = Fuel::TEST;
```

**Comment by WanWizard** [comment]
Can you check if that is the case, and if so, send a PR to remove it?

**Comment by mamor** [comment]
Thank you for the merge.

Okay. I check the code that set Fuel::$env in "core/bootstrap_phpunit.php". And if it work fine, I will send PR.

**Comment by WanWizard** [comment]
Thanks!

**Comment by mamor** [comment]
Thank you for the merge. https://github.com/fuel/core/pull/1289

This issue has now been resolved.

**Comment by kenjis** [comment]
@mp-php I've confirmed. You're right.
