### ISSUE TITLE
Debug::dump() can not dump 'UTF-8' encoding string in 1.5 ?

### ISSUE THREAD

**Issue by indigofeather** [fuel/core#1296]
in Debug::format() @ line: 194

``` php
        elseif (is_string($var))
        {
            $return .= "<i>{$scope}</i> <strong>{$name}</strong> (String): <span style=\"color:#E00000;\">\"".htmlentities($var)."\"</span> (".strlen($var)." characters)\n";
        }
```

It use <code>htmlentities()</code> to encode the string. If the content of string  is 'UTF-8' encoding, it will become unreadable result. Ex:

``` php
Debug::dump('中文', 'あ');
```

result:

``` php
Variable #1:
  (String): "ä¸­æ��" (6 characters)


Variable #2:
  (String): "ã��" (3 characters)
```

According to http://www.php.net/manual/en/function.htmlentities.php.

I try to fix it:

``` php
htmlentities($var, ENT_COMPAT, 'UTF-8')
```

result is OK:

``` php
Variable #1:
  (String): "中文" (6 characters)


Variable #2:
  (String): "あ" (3 characters)
```

**Comment by WanWizard** [comment]
I can not reproduce that, it displays fine here. Are you use your mbstring extension is installed and activated?

**Comment by SDpower** [comment]
in the http://php.net/manual/en/function.htmlentities.php say...

```
 Like htmlspecialchars(), htmlentities() takes an optional third argument encoding which defines encoding used in conversion. 
If omitted, the default value for this argument is ISO-8859-1 in versions of PHP prior to 5.4.0, and UTF-8 from PHP 5.4.0 onwards. 
Although this argument is technically optional, you are highly encouraged to specify the correct value for your code. 
```

I recommimt fixed it to be

``` php
htmlentities($var, ENT_COMPAT, \Fuel::$encoding);
```

To suport for php5.4 early version.

**Comment by WanWizard** [comment]
So you say it goes wrong in PHP 5.3.3 -> 5.4.0? I'll run some more tests.

**Comment by kenjis** [comment]
@SDpower is right. htmlentities() needs 3rd param in PHP 5.3.

`\Security::htmlentities()` is better.

**Comment by indigofeather** [comment]
My PHP version is:

```
PHP Version 5.3.10-1ubuntu3.5
```

When I use 5.4, the problem is gone.

**Comment by rob-bar** [comment]
you should use 5.4, it has some very handy upgrades.
I think it's harder when you done some things in 5.4 to go back to 5.3 
I hope the fuelphp developers are very aware of those php changes.

## 

Robbie Bardijn
Front-end Developer

Mobile: 0472 / 79.88.63
robbie.bardijn@gmail.com

**Comment by SDpower** [comment]
@kenjis is better!!

**Comment by WanWizard** [comment]
Agreed!
