### ISSUE TITLE
Return $this in View::set_global()

### ISSUE THREAD

**Issue by Art4** [fuel/core#1298]
Is it possible to return $this in set_global() in view.php to combine the calls?

Example:

``` php
Theme::instance()->get_template()
    ->set_global('current_user', $this->current_user);
    ->set_global('another_var', 'some_value')
    ->set_global('foo', 'bar');
```

**Comment by WanWizard** [comment]
set_global() is a method on the View object. It is a static method, so you can't return $this to chain, as it doesn't have an object context.

**Comment by Art4** [comment]
Oh, I see... Thank you.
