### ISSUE TITLE
Undefined method Database_Query_Builder_Delete::delete() using many to many

### ISSUE THREAD

**Issue by amomedia-arjen** [fuel/core#130]
I have a model set up with the ORM with multiple many to many relations. However, when I try to delete a record using $model->delete() I'm getting the following error:

ErrorException [ Error ]: Call to undefined method Fuel\Core\Database_Query_Builder_Delete::delete()
PKGPATH/orm/classes/manymany.php @ line 297

Seems this is being called: $query->delete(); Which is a Database_Query_Builder_Delete object.

**Comment by jschreuder** [comment]
This has been fixed in the develop branch, and issues about the Orm should go to fuel/orm not fuel/core.

**Comment by amomedia-arjen** [comment]
Will do! Thanks.
