### ISSUE TITLE
upload class error

### ISSUE THREAD

**Issue by corbosman** [fuel/core#1302]
When I upload one specific file, i get the error:

ERROR - 2013-01-25 21:42:49 --> 8 - Undefined offset: 1 in /Users/cor/xfiles/fuel/core/classes/upload.php on line 380

The mimetype for this file is not properly recognized:

[mimetype] => Composite Document File V2 Document, No summary info

But that shouldnt lead to a php error.  And even without detecting the filetype, since I have no black or whitelists, it should just pass right?

**Comment by WanWizard** [comment]
That is not a valid mimetype, which should always be in the format "something/else". 

What generates that mimetype? And what OS? My guess would be that it's Windows that borks again...

**Comment by corbosman** [comment]
This is on both OSX and Debian Squeeze. On Debian:

root@xfiles-dev:~# file AnnaCreditdossier2012.xlsx 
AnnaCreditdossier2012.xlsx: CDF V2 Document, No summary info

This is a password protected excel file, generated by some office tool. The file opens just fine as an excel sheet. 

I can understand not being able to do much with it, but at least it shouldnt cause a php error. And if there are no black/whitelists, it could just pass anyways, even without knowing the type.

**Comment by corbosman** [comment]
Oh, the mimetype from the original post is a Log::error from right within Fuel, running on Debian/Apache.

**Comment by WanWizard** [comment]
I agree with the error bit, currently looking at it. But it's a workaround for something else that's wrong.
