### ISSUE TITLE
File::create_dir issue

### ISSUE THREAD

**Issue by venomjke** [fuel/core#1309]
Reading the code of this method i found this 

``` php
$recursive = (strpos($name, '/') !== false or strpos($name, '\\') !== false);
```

Why do not specify parameter 'recursive' true by default?

``` php
return mkdir($new_dir, $chmod, true);
```

Result will be the same, not so right?

**Comment by WanWizard** [comment]
Hmm... Where does that code come from?

There used to be code in there that recusively created every directory in the path individually. And the reason for that is that you have to chmod() every one individually, not only the last one in the path.

So this code doesn't actually work in all circumstances. I list this as a bug.

**Comment by dmyers** [comment]
@WanWizard That looks to be the file class.

https://github.com/fuel/core/blob/1.6/develop/classes/file.php#L159

I believe I ran into issues with that myself though I can't recall why.

**Comment by WanWizard** [comment]
If you can remember what the issue was? Because other then some redundancy, there is nothing wrong with this code...
