### ISSUE TITLE
Conflict between Fuel\Core language file name and language key defined in application language file. 

### ISSUE THREAD

**Issue by ghost** [fuel/core#1311]
I have a language file in my application that contains the following line: 
`'upload' => 'télécharger'`
When the Fuel\Core\Upload class is called, it loads a language file named 'upload':   `\Lang::load('upload', true);`
and I have an:
`InvalidArgumentException [ Error ]: Arr::merge() - all arguments must be arrays`
It seems to occur because the language group 'upload' is conflicting with my key 'upload'.

As a workaround, I changed the key in my language file but this kind of conflict might occur for other cases that I'm not aware of. So my question is : 
Shouldn't we have some sort of "protection" on language group names to avoid such conflicts ?

**Comment by WanWizard** [comment]
You should never load language strings into the global table, you can wait for conflicts like this. Always use a group name, or 'true' if your group name is equal to the language filename.

Every Fuel core class that uses languages load this way, and most if not all packages too.
