### ISSUE TITLE
be able to alias a module route to the root path

### ISSUE THREAD

**Issue by mrDlef** [fuel/core#1313]
If I have a module my_interface for example.

I want to be able to configure my routes to do that :
/my_controller = /my_interface/my_controller

If we do that in the route or router class we also need to refrator Uri class to generate the proper url.

**Comment by WanWizard** [comment]
`'my_controller(.*)' => 'my_interface/my_controller$1',`

Don't see why that is a problem?

You can use reverse routes to generate the correct URI's for in views, that they currently work only for routes without a regex.

**Comment by mrDlef** [comment]
Yes I understand but I would be able to do that :

``` php
Html::anchor("module/controller", "My link");
```

And it output : http:://website.com/controller
So it would be cool to have an automatic reverse routing without the need of a named route.

**Comment by WanWizard** [comment]
You can already do that, using named routes: `Router::get('my_controller');`. 

This requires you to name your routes, so they can be looked up. A lookup on route target is very difficult, it can be is lots of formats, and contain regex variables with makes a match impossible.
