### ISSUE TITLE
Pagination: current_page evaluation

### ISSUE THREAD

**Issue by Baldinof** [fuel/core#1319]
When I instanciate a Pagination with the config `total_items` setted before `per_page`, the current page is not correctly calculated.
# example

``` php
$config = array(            
    'pagination_url' => 'the_url',
    'total_items'    => 12,
    'per_page'       => 3,
    'uri_segment'    => 3,
);

$pagination = Pagination::forge('myPagination', $config);
```

If I go to the page 4, the `current_page` in `$pagination->config' is 2 and not 4.

If I do

``` php
$config = array(            
    'pagination_url' => 'the_url',
    'per_page'       => 3,
    'total_items'    => 12,
    'uri_segment'    => 3,
);
```

All is good.

It seems to be the way that current_page is calculated in `_recalculate()`. (CORE/classes/paginations.php)

**Comment by WanWizard** [comment]
Which version are you talking about? And if not 1.6/develop, can you try that? It recalculates on every config change, so by the time all config values are processed, the current_page value should be correct.

**Comment by Baldinof** [comment]
I was using Fuel 1.4.
I have made some tries with 1.6/develop and the issue is still there.

The probleme is `$this->config['current_page']` is not recalculate if it's more than 1 : 
In [pagination.php line 426](https://github.com/fuel/core/blob/1.6/develop/classes/pagination.php#L426)

``` PHP
if (is_string($this->config['uri_segment']))
{
    $this->config['current_page'] = ($this->config['total_items'] > 0 and $this->config['current_page'] > 1) ? $this->config['current_page'] : \Input::get($this->config['uri_segment'], 1);
}
else
{
    $this->config['current_page'] = ($this->config['total_items'] > 0 and $this->config['current_page'] > 1) ? $this->config['current_page'] : (int) \Request::main()->uri->get_segment($this->config['uri_segment']);
}
```

So if the `current_page` is evaluated to more than 1, and after the config changes, the `current_page` won't be recalculated.
If I do just

``` PHP
if (is_string($this->config['uri_segment']))
{
    $this->config['current_page'] = \Input::get($this->config['uri_segment'], 1);
}
else
{
    $this->config['current_page'] = (int) \Request::main()->uri->get_segment($this->config['uri_segment']);
}
```

It works.

[Here](https://gist.github.com/Baldinof/4770285) is an action if you want to test.

With 1.6, I get another issue with the `pagination_url` combined to `uri_segment` config. 

My project url is "http://localhost/dev/fuel/public".

If i set `pagination_url` to _http://localhost/dev/fuel/public/welcome/page_ (`Uri::create('welcome/page')`), I have to set `uri_segment` to 6. 
I think it should be relative to the base url (so `uri_segment` = 3). If the `uri_segment' is 3, my generated pages link are _http://localhost/dev/fuel/{pagenum}/welcome/page_.

Is it an intended behaviour ?

**Comment by WanWizard** [comment]
No, it should take base_url into account. I never have segments in my base_url's, so I hadn't noticed.

I'll have a look.

**Comment by WanWizard** [comment]
This is going to take a while to re-think. Problem is that config values can come from anywhere (config array on forge, property access on the forged object, from URI data) and in any sequence. Also, if you pass the current_page, it should not check the value in the URI. You can also not wait to recalculate until render, as you may want to fetch the property values before you render (like for example total_pages), so you need those calculated on every update.

Complex to get it right.

**Comment by Baldinof** [comment]
It's ok, the class remains usable for me.
