### ISSUE TITLE
I want to use webroot string

### ISSUE THREAD

**Issue by hackoh** [fuel/core#1322]
fuel/fuel doesn't have 'Issues', so I write here. 

If I need webroot string (for example, at View), then I often use `Uri::base(false)`
This method returns URL containing a scheme and a host name.

However, I think this solution has two problems.
- The method call is expensive for the execution time.

```
I tryed echo Uri::base(false) 1000 times. 
The execution time is 4ms at my computer.

And I tryed echo BASE (defined for test) 1000 times.
The execution time is 0.3ms at my computer.
```
- URL containing a scheme and a host name is expensive for data length.

Can anyone resolve this issue?

**Comment by WanWizard** [comment]
Nobody's stopping you from defining a constant in your index.php.

Although I would advice you not to do that, but use the app bootstrap for this purpose.
I don't see a reason for having this as part of the framework, it's application specific, and is not generic enough.

**Comment by hackoh** [comment]
Thanks!
I understood your advice.

I am finding best practice for this purpose.

**Comment by kenjis** [comment]
How about defining constants in config.php?

**Comment by WanWizard** [comment]
You can define them where ever you want. If you only need them in the app, config.php is loaded later then the app bootstrap, but early enough in the boot process not to be a problem.

The danger with a config file is that it can be saved (which will delete your constants), or loaded twice (if you force a reload), both will cause a lot of misery when it happens...

**Comment by hackoh** [comment]
@kenjis 
Thanks for your advice.
I thought that solution too.
But I think, configuration file is a place to set up the operating environment,
so I don't want to do other thing.

I will create a package named 'webroot' containing 
only 'bootstrap.php' written a code about WEBROOT defining.
(Maybe, you will think "grandiose solution!")

**Comment by WanWizard** [comment]
In the end, it's what you feel comfortable with, and what is suitable for your application. If you want something more portable, a package is fine too.

**Comment by hackoh** [comment]
Thanks for all.
