### ISSUE TITLE
latest_fuel.zip orm incorrect

### ISSUE THREAD

**Issue by LimeBlast** [fuel/core#133]
Sorry if this is the wrong place to post this, but the http://fuel.frenky.net/latest_fuel.zip download is incorrectly putting the oil package in place of the orm package.

**Comment by jschreuder** [comment]
You gotta ask @FrenkyNet about this, even though he's part of the team it's not an "official" download.

**Comment by frankdejonge** [comment]
Like jschreuder says, it's not an official download, but it has been fixed. It's just a shortcut to the latest develop of all branches.
