### ISSUE TITLE
Router implementation breaks compat

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#1331]
https://github.com/fuel/core/commit/69b7c1539ff4a8396192544a0927930a0ed7771e#L0R47

Can the array type hinting be removed from here? It's causing compatibility errors with router() methods written before this was put in.

**Comment by WanWizard** [comment]
What previous implementation? $params is passed to router() by Request, and it is always an array?

**Comment by phil-lavin** [comment]
It's that implementations of router() in app classes won't type hint array and as such aren't compatible with their new parent. PHP throws an error.

Phil

Sent from my iPhone

On 15 Feb 2013, at 18:47, "Harro Verton" <notifications@github.com<mailto:notifications@github.com>> wrote:

What previous implementation? $params is passed to router() by Request, and it is always an array?
