### ISSUE TITLE
Ampersands in URLs cause blank page

### ISSUE THREAD

**Issue by rzhw** [fuel/core#1338]
It appears that ampersands are unable to be used in URLs. By inserting an ampersand anywhere in the FuelPHP uri (outside of the query string), a blank page results with status code 400. Encoding the ampersand as %26 appears not to work either, as the same occurs.

This can be replicated on a fresh copy of FuelPHP 1.5.2, e.g. visiting `/fuelphp-1.5.2/public/foo&bar` will show the blank page + 400 instead of a 404.

I'm not absolutely certain this is a bug; trying the same with the FuelPHP website (which I'm assuming does run on FuelPHP) e.g. http://fuelphp.com/&, http://fuelphp.com/%26 just show an error.

> An Error Was Encountered
> The URI you submitted has disallowed characters.

However, the forums (Vanilla?) don't suffer from the same issue.

In the event that this isn't a bug, I've looked around to see if there's any documentation on this and don't seem to have found anything.

**Comment by dmyers** [comment]
The error on fuelphp.com I think is from CodeIgniter. I tested on one of my sites and I get 404.

**Comment by WanWizard** [comment]
The & is illegal in the URL, apart from as a query string seperator. 

Having said that, I don't have an issue with it whatsover, I tested on a fresh FuelPHP installation, and URI's like "/welcome&" or "/welcome/index&" gives me the standard 404 page, as it should.

The website doesn't use FuelPHP, it runs a commercial CMS. So your assumption is wrong there.

**Comment by rzhw** [comment]
Forgive me if my knowledge of URLs is incorrect here, but `%26` shouldn't be invalid as part of one, should it?

That being said, if this isn't an issue you can replicate, I'll try doing so with a different server setup and see what happens.

**Comment by WanWizard** [comment]
If I use a URI like "/welcome/index/foo%26bar", and I dump the first parameter of the index() method, it gives me "foo&bar". Even, although not legal as per RFC, "/welcome/index/foo&bar" works.

So it looks like the issue is indeed at your end. There is no code in the framework that would generate a 400 error.
