### ISSUE TITLE
Theme set_chrome() should return View

### ISSUE THREAD

**Issue by Art4** [fuel/core#1339]
I'm not sure if this is a bug in core or in documentation.

The [documentation says that in Theme class set_chrome() returns a View](http://fuelphp.com/docs/classes/theme/methods.html#method_set_chrome) but in fact [it returns nothing](https://github.com/fuel/core/blob/1.6/develop/classes/theme.php#L387).

It would be nice if set_chrome() returns the template view for easy chaining, so instead of using a workaround with get_chrome() like this

``` php
Theme::instance()->set_chrome('sidebar', 'main/sidebar', 'widgets');
Theme::instance()->get_chrome('sidebar')
    ->set('foo', 'bar');
```

I could simply do this:

``` php
Theme::instance()->set_chrome('sidebar', 'main/sidebar', 'widgets')
    ->set('foo', 'bar');
```

**Comment by dmyers** [comment]
Probably a copy paste from get_chrome().

**Comment by WanWizard** [comment]
set_chrome() currently doesn't have a return value, so the docs are wrong.

However, since set_template() and set_partial() both do return the view or viewmodel object, it is logical that set_chrome() does the same.

**Comment by Art4** [comment]
Thank you!
