### ISSUE TITLE
Migrate Class Should Use Config

### ISSUE THREAD

**Issue by bencorlett** [fuel/core#135]
The migrate class should probably utilise a config - for the table name used (sometimes I want to put the session and migrate classes under fuel_sessions and fuel_migrations just to keep them together).

Do you think this is a good idea?

**Comment by jonstuebe** [comment]
I agree

**Comment by jschreuder** [comment]
Sure, go ahead and write it up + pull-request ;)

**Comment by bencorlett** [comment]
Yay for delmot!
