### ISSUE TITLE
Allow setting body on Request_Curl

### ISSUE THREAD

**Issue by Altreus** [fuel/core#1351]
Request_Curl is a pretty useful interface around the horror of the only PHP interface to curl, but the only way to set the POST body is to use set_params (it doesn't appear to look in the options property for CURLOPT_POSTFIELDS at any point).

Since it is not imperative that the body of a POST request is in this format (you can post anything!) this leaves us with no way to send arbitrary data, such as XML, binary files or simply some nonstandard crap like we have to deal with from so-called professionals all the time. It would be useful to have a simple way of setting the request body instead of having it constructed from parameters.

**Comment by dmyers** [comment]
I may be wrong, but there is some parsing on the postfields based on the `Content-Type` header if you allow autodetecting formatting (which is enabled by default).

https://github.com/fuel/core/blob/1.6/develop/classes/request/curl.php#L274

**Comment by WanWizard** [comment]
@Altreus Is this still relevant? You know you can do

`$curlrequest->set_options(array('POSTFIELDS' => $myweirdpostcontents));`

to set CURLOPT_POSTFIELDS?
