### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by it-can** [fuel/core#1352]
Time: 1 second, Memory: 29.50Mb

There were 4 failures:

1) Fuel\Core\Test_Pagination::test_uri_segment_first_page
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<span class="active"><a href="#">1</a></span><span><a href="http://docs.fuelphp.com/welcome/index/2">2</a></span><span><a href="http://docs.fuelphp.com/welcome/index/3">3</a></span><span><a href="http://docs.fuelphp.com/welcome/index/4">4</a></span><span><a href="http://docs.fuelphp.com/welcome/index/5">5</a></span><span><a href="http://docs.fuelphp.com/welcome/index/6">6</a></span>'
+'<span class="active"><a href="#">1</a></span><span><a href="http://docs.fuelphp.com/welcome/index/2">2</a></span><span><a href="http://docs.fuelphp.com/welcome/index/3">3</a></span><span><a href="http://docs.fuelphp.com/welcome/index/4">4</a></span><span><a href="http://docs.fuelphp.com/welcome/index/5">5</a></span>'

/fuel/core/tests/pagination.php:206

2) Fuel\Core\Test_Pagination::test_uri_segment_nextlink_inactive
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<span><a href="http://docs.fuelphp.com/welcome/index/6">6</a></span><span><a href="http://docs.fuelphp.com/welcome/index/7">7</a></span><span><a href="http://docs.fuelphp.com/welcome/index/8">8</a></span><span><a href="http://docs.fuelphp.com/welcome/index/9">9</a></span><span class="active"><a href="#">10</a></span>'
+'<span><a href="http://docs.fuelphp.com/welcome/index/6">6</a></span><span><a href="http://docs.fuelphp.com/welcome/index/7">7</a></span><span><a href="http://docs.fuelphp.com/welcome/index/8">8</a></span><span><a href="http://docs.fuelphp.com/welcome/index/9">9</a></span>'

/fuel/core/tests/pagination.php:239

3) Fuel\Core\Test_Pagination::test_query_string_first_page
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<span class="active"><a href="#">1</a></span><span><a href="http://docs.fuelphp.com/?p=2">2</a></span><span><a href="http://docs.fuelphp.com/?p=3">3</a></span><span><a href="http://docs.fuelphp.com/?p=4">4</a></span><span><a href="http://docs.fuelphp.com/?p=5">5</a></span><span><a href="http://docs.fuelphp.com/?p=6">6</a></span>'
+'<span class="active"><a href="#">1</a></span><span><a href="http://docs.fuelphp.com/?p=2">2</a></span><span><a href="http://docs.fuelphp.com/?p=3">3</a></span><span><a href="http://docs.fuelphp.com/?p=4">4</a></span><span><a href="http://docs.fuelphp.com/?p=5">5</a></span>'

/fuel/core/tests/pagination.php:439

4) Fuel\Core\Test_Pagination::test_query_string_nextlink_inactive
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<span><a href="http://docs.fuelphp.com/?p=6">6</a></span><span><a href="http://docs.fuelphp.com/?p=7">7</a></span><span><a href="http://docs.fuelphp.com/?p=8">8</a></span><span><a href="http://docs.fuelphp.com/?p=9">9</a></span><span class="active"><a href="#">10</a></span>'
+'<span><a href="http://docs.fuelphp.com/?p=6">6</a></span><span><a href="http://docs.fuelphp.com/?p=7">7</a></span><span><a href="http://docs.fuelphp.com/?p=8">8</a></span><span><a href="http://docs.fuelphp.com/?p=9">9</a></span>'

/fuel/core/tests/pagination.php:468

FAILURES!
Tests: 342, Assertions: 377, Failures: 4.

**Comment by it-can** [comment]
@WanWizard can you take a look at this?

**Comment by WanWizard** [comment]
Ah. People should stop writing tests to match results. This was a bug that was fixed, so clearly the tests were wrong... Fix is on the way.

**Comment by it-can** [comment]
Ok, well good to know ;-)
