### ISSUE TITLE
Run Task from any Package

### ISSUE THREAD

**Issue by andrewwheal** [fuel/core#1358]
It would be handy to be able to run a task from any Package.

Currently only module tasks can be called using the `module_name::task_name` syntax and loaded packages can be called without a prefix.

However, there is no way of running the tasks of a Package that is not always loaded (or loaded by an always loaded package).

Auto discovery of all package paths would be as hard as module paths, which I guess is why module names can be prefixed, so adding -p and -m options might be a way forward (like migrations use)?

**Comment by WanWizard** [comment]
Not sure if this is going to be fixed in 1.x. 

For 2.0, tasks are callable classes, which fixes this issue. You would still have to load though, otherwise the namespace isn't known.

**Comment by andrewwheal** [comment]
As long as there is a way to dynamically load like with modules at the moment then that is fine. Just didn't want to have to always load anything with a task :anguished:

Can you suggest any sensible work around for 1.x if it isn't going to be fixed?

**Comment by WanWizard** [comment]
Packages can be loaded dynamically, that has always been there.

At the moment I don't have a workaround, it has to be fixed in oil (so this is the wrong repo), so if you need this, be my guest and PR... :smile:
