### ISSUE TITLE
\DBUtil::set_connection unused $db and weird test

### ISSUE THREAD

**Issue by mrDlef** [fuel/core#1359]
In the set_connection method of \DbUtil the second parameter $db is never used.

Also the method test if the $connection is an instance of Database_Connection and if it's true throw a \FuelException to say it need to be a Database_Connection...

``` php
/**
 * Sets the database connection to use for following DBUtil calls.
 *
 * @param  string|object  string connection name or \Database_Connection object, null for default
 */
public static function set_connection($connection, $db = null)
{
    if ( ! is_string($connection) and ($connection instanceof Database_Connection))
    {
        throw new \FuelException('A connection must be supplied as a string or a Database_Connection object.');
    }

    static::$connection = $connection;
}
```

**Comment by WanWizard** [comment]
Looks like the instanceOf should be a "not", and the second parameter should not be there. Looks like a copy/paste error...

**Comment by mrDlef** [comment]
However be careful if you try to correct it because Database_Connection::instance doesn't get other thing than a string for $name parameter.

**Comment by WanWizard** [comment]
Best option it to simply remove the option of passing a Database_Connection instance. Even if you could do that now, it would break when instance() is called, so nobody uses that...

**Comment by WanWizard** [comment]
Fix merged.
