### ISSUE TITLE
DBUtil::truncate_table always return "0"

### ISSUE THREAD

**Issue by billmn** [fuel/core#136]
Function :
DBUtil::truncate_table('table_name'); 

erase table successfully but always return 0 (ZERO) rather than number of affected rows

**Comment by WanWizard** [comment]
What DB driver do you use? In case of MySQL, which table engine is used?

**Comment by billmn** [comment]
I'm using MySQL with InnoDB

**Comment by WanWizard** [comment]
Thought so. According to the MySQL manual:

Truncation operations do not return a meaningful value for the number of deleted rows. The usual result is “0 rows affected,” which should be interpreted as “no information.” 

So, works as designed. A workaround could be "DELETE FROM table", that should return a count.

Also, please note that all counters for InnoDB are approximate, the InnoDB engine doesn't keep an interal row counter.
