### ISSUE TITLE
Bug in File::create_dir

### ISSUE THREAD

**Issue by pro85** [fuel/core#1363]
On line 169
<code>
$path .= (empty($dir)?'':DS).$dir;
</code>
 error on Windows systems.

**Comment by WanWizard** [comment]
Can you be more specific? Which error? Which parameters did you use when you called create_dir() ?

**Comment by pro85** [comment]
In windows path begin with <code>c:\path</code>. Code on line 169 add DS to begin of path like <code>\c:\path</code> and this show file system error.

**Comment by okhayat** [comment]
I tested on Windows the issue is still there.
Fixed by changing L#169 to:
$path .= ((empty($dir) or strpos($dir, ':') == 1)?'':DS).$dir;

**Comment by WanWizard** [comment]
That was the old code. Thanks for testing the fix, and confirming it works on IRC.
