### ISSUE TITLE
Validation error : match_pattern with "or" in the preg regex

### ISSUE THREAD

**Issue by jhuriez** [fuel/core#1364]
Hi, i want to use the validator "match_pattern". My input must contains "AAA" or "BBB", so the preg regex is "/AAA|BBB/"

My line in my model : 

``` php
        $val->add_field('myInput', 'myInput', 'match_pattern[/AAA|BBB/]');
```

The message error : 

<pre>
ErrorException [ Notice ]: Undefined offset: 1

COREPATH/classes/validation.php @ line 190
</pre>

**Comment by WanWizard** [comment]
The docs state it has to be a full regex, so I assume that includes delimiters. Try this instead:

```
        $val->add_field('myInput', 'myInput', 'match_pattern[#/AAA|BBB/]#');
```

**Comment by jhuriez** [comment]
Nop, again the same error message

**Comment by jhuriez** [comment]
In add_field function you split rules with "|", so the preg regex is splitted to.

``` php
is_array($rules) or $rules = explode('|', $rules);
```

If i put the rule in array, it's work : 

``` php
 $val->add_field('myInput', 'myInput', array('match_pattern[/AAA|BBB/]'));
```

**Comment by WanWizard** [comment]
This is documented: "We also provide a shorter syntax which is very limited in comparison. It will not accept array-callbacks, closures or parameters other than strings." That includes no patterns...

I'll add clarification to the docs.
