### ISSUE TITLE
Upload 'randomize' broken in 1.6

### ISSUE THREAD

**Issue by itsa-sh** [fuel/core#1368]
Since upgrading to 1.6 the upload class stopped generating random filenames.  I briefly went through the `vendor/fuelphp/src/FuelPHP/Upload/File.php` and noticed something like:

``` php
if( ! array_key_exists('filename', $this->container))
{
    if ($this->config['randomize'] ...

         $this->container['filename'] = md5(serialize($this->container));
    }

    else
    {
         // something about normalize here
    }
```

Then I gave up.

**Comment by WanWizard** [comment]
Instead of giving up and moan, you could have assisted by doing a var_dump($this->container), and check if 'filename' is present.

This bit of code says that if a fixed filename is set, no random one will be generated. So the question is, is there one set?

**Comment by WanWizard** [comment]
Issue should be fixed: https://github.com/fuelphp/upload/commit/fdba921e861a2d8824269301beb8f45d003ae915

You'll have to run a composer update to pull the chages in.
