### ISSUE TITLE
\Arr::multisort - reference error

### ISSUE THREAD

**Issue by dercoder** [fuel/core#1369]
This example:
http://fuelphp.com/docs/classes/arr.html#/method_multisort

$collection = array(
        'i5' => array(
            'name' => 'Carl',
            'age' => 17,
            'points' => 30,
            'arr' => array(
                'key' => 10,
            ),
        ),
        'i7' => array(
            'name' => 'carl',
            'age' => 17,
            'points' => 20,
            'arr' => array(
                'key' => 10,
            ),
        ),
        'i2' => array(
            'name' => 'Bert',
            'age' => 20,
            'points' => 30,
            'arr' => array(
                'key' => 10,
            ),
        ),
    );

```
$collection = \Arr::multisort($collection, array(
    'name' => SORT_ASC,
    'points' => array(SORT_ASC, SORT_NUMERIC),
    'age' => array(SORT_ASC, SORT_NUMERIC),
));
```

gives me an error:
Parameter 1 to array_multisort() expected to be a reference, value given

**Comment by WanWizard** [comment]
Just tried this example  on 1.6/develop, PHP 5.4.11, and no problem, no errors. I've checked the commit history, but it hasn't been changed since it was introduced.

Which version of Fuel are you on, which PHP version, and which line exactly gives this error?

**Comment by dercoder** [comment]
I use Fuel 1.5 and PHP 5.3.3

![5138a7bfe4b042563c9eeeaf](https://f.cloud.github.com/assets/1737685/232463/a2484b2e-8735-11e2-8833-928fe6433ae1.png)

**Comment by WanWizard** [comment]
On 1.5 no problems here either.

There were some bugs in early PHP 5.3.x, which is for example why line 734 is there. Perhaps you've hit another bug. Given the fact that 5.3.3. is quite old (the absolute minimum to use FuelPHP), is there a possibility for upgrade to a later version?

**Comment by dercoder** [comment]
Ok, i will try to upgrade

**Comment by WanWizard** [comment]
Ok, let me know how things go, I'll keep this open for the moment.

**Comment by frankdejonge** [comment]
seeing that there is no response, I'm closing this.
