### ISSUE TITLE
Pagination class, no last page

### ISSUE THREAD

**Issue by visavi** [fuel/core#1384]
Develop in version 1.6 does not display the last page

![9f7c9ff04d6f0cee1c946d4c2c46ab56](https://f.cloud.github.com/assets/826831/291683/f98dcc00-930c-11e2-990f-6622f4999ef7.png)

Before this change, all worked fine
https://github.com/fuel/core/commit/6a4deb2a99dc0f25f1cab74a024eaa4af3bd5e42

**Comment by WanWizard** [comment]
Was fixed in 621f7a72a06a2ebe54e5aae0c447a6a08c748833
