### ISSUE TITLE
Uri::segment_replace() does not work as expected

### ISSUE THREAD

**Issue by imunhatep** [fuel/core#1392]
Input:
http://localhost/*/auth/login

Output:
http/localhost/admin/auth/login

The problem is in part where url is reassembled.

**Comment by frankdejonge** [comment]
Could you give a little more feedback on this issue? I don't know the routes/controller/expectation and result.

**Comment by imunhatep** [comment]
Problem in output, specifically in first part http/localhost... where it should be http://localhost, returned url isn't correct.
Uri::segment_replace($url) method in the end call implode() on url parts, but, i guess, it should call http_build_url()

**Comment by frankdejonge** [comment]
@Imunhatep I still don't know what the problem is ....

**Comment by imunhatep** [comment]
Incorrect URL is returned, that's the problem.

**Comment by emlynwest** [comment]
@Imunhatep How are you calling `segment_replace()`?

**Comment by imunhatep** [comment]
Like that: \Response::redirect('*/somepath');
