### ISSUE TITLE
Inflector::humanize does not complement friendly_name

### ISSUE THREAD

**Issue by Altreus** [fuel/core#1393]
It seems like Inflector::friendly_name turns a human string into a machine one; it uses hyphens for spaces.

It seems reasonable, then, that humanize would turn hyphens back into spaces as well.

Current behaviour is great; but hyphens would be good too.

Whatever friendly_name does for actual hyphens could be tested for as well.

**Comment by frankdejonge** [comment]
@Altreus pull-request?

**Comment by WanWizard** [comment]
This is because friendly_title() uses the hyphen as default separator, while humanize() uses the underscore as default separator. 

To get reverse behaviour, use `Inflector::humanize('this-is-a-string-with-hyphens', '-');`

**Comment by Altreus** [comment]
Ah, sorry, totally failed to RTFM on that. Thanks!
