### ISSUE TITLE
Should a ViewModel have access to all global data?

### ISSUE THREAD

**Issue by Altreus** [fuel/core#1399]
A ViewModel is in a curious limbo between real views and the controller. The controller has the option of setting a variable on itself as well as setting it global on a view (I'm thinking in terms of templates, but the concept is generically applicable) but a ViewModel used in place of a View doesn't get to see those variables in its `view()` method.

Is there any reason why it shouldn't (as opposed to it being difficult to implement)? If not I will spend some time looking into making it do so.

**Comment by WanWizard** [comment]
It's not, really. A Viewmodel can be used to abstract pre-processing logic away from the view, so you don't have to put code in your view (which, if you use a template engine, is not possible). And as it's code specific for the view, you don't want it in the controller either.

Having said that, the Viewmodel does have access to all global variables. It doesn't use it's own variable store, it uses the one from the associated View object, so set() and get() operate on the View, not the Viewmodel. Which means that `->get('globalkey')` will return a value from the global view data.

**Comment by Altreus** [comment]
OK that makes sense. I was surprised to learn that a View is not written in terms of a default ViewModel that assigned all the global variables to the view itself before processing it, which is where the thought came from.

**Comment by WanWizard** [comment]
No, global view variables are stored statically in the View class.
