### ISSUE TITLE
Call to undefined method Redis::connection()

### ISSUE THREAD

**Issue by superhero** [fuel/core#1406]
I believed I followed the steps really well in the docs (http://four.laravel.com/docs/redis) but I still get a fatal error exception thrown.

**Comment by frankdejonge** [comment]
@erik-landvall ... you do know that Laravel !== FuelPHP right? ;)

**Comment by frankdejonge** [comment]
@erik-landvall I think I didn't make it clear enough. FuelPHP is not the same as Laravel. They are different frameworks so when you try to use Laravel inside FuelPHP it doesn't work and never will.

**Comment by indigofeather** [comment]
@erik-landvall  http://fuelphp.com/docs/classes/redis.html

**Comment by superhero** [comment]
omg!!! how did I end up here. I thought I was reporting for laravel.. sorry for wasting your time :D
