### ISSUE TITLE
Session upload progress in PHP 5.4

### ISSUE THREAD

**Issue by SRWieZ** [fuel/core#1407]
How i can be access to this feature in Fuel PHP :
http://php.net/manual/en/session.upload-progress.php

I think it will be good to add an function on Upload class or Session class in FuelPHP 2.0
Actually I use APC and it work's but in Debian 7.0 I am going to need update PHP to 5.4 version and APC won't work in PHP 5.4.

Thanks to   consider my issue.

**Comment by WanWizard** [comment]
FuelPHP currently doesn't use $_SESSION at all. Besides that, FuelPHP is PHP 5.3+ at the moment, so such a feature can't be introduced until we lift the requirement to 5.4, which will be for FuelPHP 2.0.

I've moved this feature request to 2.0
