### ISSUE TITLE
Make Fieldset Tabular Form Instance Names and Attributes more unique?

### ISSUE THREAD

**Issue by benplummer** [fuel/core#1408]
When more than one tabular form is used where the '$relation' parameters (e.g. 'items') are the same on a single page, errors are thrown stating 'Fieldset already has a parent, belongs to <instance>'. This is because if there are two fieldsets both with tabular forms with the same $relation name on the same page, when the blank fields are created it means each blank field in one fieldset will practically be a duplicate (in terms of instance name and attributes) of a blank field that is in the other/s. 

To get around this, information specific to the parent fieldset (e.g. $this->get_name()) could be appended to the front of each row fieldset instance name where each is added on line 831 (and 813) of the Fieldset class.

This would allow multiple fieldsets with the same named tabular form relation on the same page. Despite the duplicate instance names being fixed by the solution above, there would still be duplicates in regards to the id and name attributes on the individual fields of the separate tabular forms thus they cannot be processed properly. I guess this problem resides with the attributes being generated by the Fieldset add_model($model) function? Is there a way to get around this?

**Comment by WanWizard** [comment]
There is currently no support for generating duplicate fieldsets, I flagged this as a feature request.

**Comment by benplummer** [comment]
Thanks. In the long run I thought it could be useful if a 'prefix' could be passed to the add_model function in some way or another and appended to the beginning of the relevant attributes to make them unique. The 'prefix' could have a default value related to the parent fieldset if it exists, so eventually the POST values are simple to process.

**Comment by WanWizard** [comment]
Moved it to the 2.0 feature list.
