### ISSUE TITLE
When use Redis driver with Cache and use try{} catch{}, got problem

### ISSUE THREAD

**Issue by indigofeather** [fuel/core#1413]
``` php
class Test_Instance
{
    public function aaa()
    {
        try {
            $aaa = Cache::get('foo');
        } catch (\CacheNotFoundException $e) {
            // assum array('a' => 1, 'b' => 2)
            $aaa = Model_Test::find();
            Cache::set('foo', $aaa, 300);
        }

        return $aaa;
    }

    public function bbb()
    {
        try {
            $bbb = Cache::get('asd');
        } catch (\CacheNotFoundException $e) {
            // bbb is the result of merge 2 array
            $aaa = $this->aaa();
            $bbb = array_merge($aaa, array('z' => 9));

            // has dependency
            Cache::set('asd', $bbb, 300, array('foo'));
        }

        return $bbb;
    }

    public function set_aaa()
    {
        Cache::delete('foo');
        // Model_Test do update something

        // return result
        return $this->aaa();
    }
}
```

step 1: get 'aaa':

``` php
$aaa = Test::instance()->aaa();
```

in redis <code>fuel:index:.key</code> will get:

``` php
a:1:{s:3:"foo";a:2:{i:0;s:57:"fuel_133379521930505746713054259271101826896517e0b5601d6e";i:1;N;}}
```

step 2: get 'bbb':

``` php
$bbb = Test::instance()->bbb();
```

I get:

``` php
a:2:{s:3:"foo";a:2:{i:0;s:57:"fuel_133379521930505746713054259271101826896517e0b5601d6e";i:1;N;}s:3:"asd";a:2:{i:0;s:58:"fuel_1313560836176661545812101216721946682404517e0b79152c6";i:1;i:N;}}
```

step 3: the data of aaa has changed:

``` php
Test::instance()->set_aaa();
```

step 4: and get 'bbb' again:

``` php
$bbb = Test::instance()->bbb();

// The result will be old cache
array('a' => 1, 'b' => 2, 'z' => 9);
```

and **COREPATH/classes/cache/storage/redis.php @ line: 162**

``` php
// key found and newer?
if ($key === false or $key[1] > $this->created)
{
    return false;
}
```

The problem is:
If use the try catch structure, the created timestamp($key[1]) will be **null**.
This cause <code>check_dependencies()</code> will not work correctly.

**Comment by WanWizard** [comment]
Confirmed, I can reproduce this. 

It seems to be a generic issue, I can also reproduce this with the file driver and the memcached driver. The file driver uses filemtime() to get the real last update timestamp, so I don't think it's a key value issue, it must be deeper then that.

**Comment by WanWizard** [comment]
Not sure this test is correct.

Diving into the dependency check, I see it's done on timestamp, which means is has a granularity of 1 second. If both cache entries are created in the same second (and therefore have the same timestamp), the dependency is considered to be met and no forced expiry will happen.

In this test, you create aaa, then bbb, then flush and recreate aaa, all within the same second. So when it gets to the dependency check on the second bbb, it finds it still valid. 

In my test I run:

``` php
        \Cache::delete('cache_a');
        \Cache::delete('cache_b');

        \Debug::dump($this->set_a());
        \Debug::dump($this->set_b());
        sleep(5);
        \Cache::delete('cache_a');
        \Debug::dump($this->set_a());
        \Debug::dump($this->set_b());
```

and then the dependency check works fine with the file driver.

With both redis and memcached it fails due to the missing key value, so I have to look into that.

**Comment by indigofeather** [comment]
@WanWizard  Thanks for your test, I tried to find the reason, but still not sure what cause it.
Narrowed the scope, the different two case:

case 1: at first, <code>get</code> and throw exception, and <code>set</code>, the key will be **null**

``` php
try {
    Cache::get('foo');
} catch (\CacheNotFoundException $e) {
    Cache::set('foo', $data, 300);
}
```

``` php
a:1:{s:3:"foo";a:2:{i:0;s:57:"fuel_125041858316904965507731404191596792911517e5c8189451";i:1;N;}}
```

case 2: just <code>set</code>, it works correctly

``` php
Cache::set('foo1', $data, 300);
```

``` php
a:1:{s:4:"foo1";a:2:{i:0;s:53:"fuel_44151688349346519861347009494881661517e5cd903882";i:1;i:1367235801;}}
```

so I guess __construct or forge() may be the direction.
