### ISSUE TITLE
_init not called automatically

### ISSUE THREAD

**Issue by jeroenbourgois** [fuel/core#1414]
I just downloaded the 1.5.3 fuel version and did a small test. In the config I enabled some packages (email for instance) that have an _init() function, but when I put a trace inside ( a simple `system('echo')` ) it is never reached. Should the init not be called automatically?

**Comment by WanWizard** [comment]
Yes, it should. The autoloader will call it on class load, for every class. Nothing would work if there was a bug in this mechanism.

But enabling a package doesn't load or call anything, so it's logical that it's not executed?

**Comment by frankdejonge** [comment]
If you want code executed on package load, you can use the bootstrap.php file in the package root. The `_init` method can be seen as a static constructor, as @WanWizard explained, it's only fired on first usage (thus load).

**Comment by jeroenbourgois** [comment]
I understand it better now, but I am still facing strange behaviour I already had before. So now I use the `Log` package. If I put a trace inside the Log class inside the `_init` function it get's called multiple times. I use the `Log` class inside my package.

If inside of `core\base.php` I add multiple calls to the log instance, just before the return of the `logger` function (line number 91) than my output (which is a simple system() echo call) is just one line. That means the `_init` function is called just once, Great! 

But then inside my package when I call the instance again, the `_init` function is called again! And thus the `handlers` array contains only 1 item again... I am writing a small RavenClient package to log to Sentry.

The order of execution seems to be:

1) My package is loaded and I init the logger there.
2) the logger is initiated a second time inside `core\base.php` (thus the handler I added to Monolog inside my package is gone :(  )
3) the log is logged only to the default log and not to my logger.

So for now (as I put inside an issue inside the log repository) all I can do is add a check inside the `_init` function to see if the instance already exists...

update: the reason I'd rather not fiddle inside the log package is because I really don't want to be altering packages that are part of fuel. Now my framework setup users the fuel core and packages as git submodules that I pull in...
