### ISSUE TITLE
Incorrect logic for PDO reconnect on query()

### ISSUE THREAD

**Issue by imunhatep** [fuel/core#1419]
Shortly: it totally does not work!
1. 
   It doing 4 attempts, not 3
2. 
   In "if" statement, we should check "$attempts" count, and only in positive case check for "Mysql has gone away" error message
   otherwise: we are left with undefined $result variable and misleading error message
3. 
   Before doing reconnect by calling  $this->connect(), we should call $this->disconnect() to reset $this->_connection property
   4.
   In connect() method of the same class, connection configuration is cleared for security?! reasons... so we are unable to make reconnect..
   5.
   It supposed to work only for MySQL?

**Comment by WanWizard** [comment]
It's been in there for quite some time, and I can recall that at that time it solved the problem for the person reporting it.

IHMO it's a hack and shouldn't be in there (in that way). 

The PDO driver is a generic driver, and should work with whatever platform you configure it for. Therefore you're quite limited to what you can have it do.

This issue will be addressed in v2.0 where we're going to dump the old Kohana DB layer for our own, which does have platform specific drivers.

**Comment by WanWizard** [comment]
If you have the correct PDO exception messages for other RDBMS engines, let us know and and we can add them to the reconnect loop.
