### ISSUE TITLE
Standardize constants in the differents entry points

### ISSUE THREAD

**Issue by fbnfgc** [fuel/core#1421]
Today there are 3 standard entry points for a fuelphp app : 
- index.php (cgi like)
- oil (cli)
- phpunit (cli)

Each entry point defines its own constants : _DOCROOT, APPPATH, PKGPATH, COREPATH, FUEL_START_TIME, FUEL_START_MEM_...
... which are **the same**.

I think it would be a good idea to group them in a single file.

**Comment by RyanDawkins** [comment]
I agree this would be cool.

**Comment by WanWizard** [comment]
For index.php and oil, they could be moved to app/bootstrap.php. 

For phpunit, that is a bit different, since that uses an XML file for path configuration. I'll have to see if those XML file entries are really needed (for phpunit).

**Comment by WanWizard** [comment]
I spoke to soon, obviously APPPATH is required to be able to call the app bootstrap, bit of a chicken-and-egg issue...

**Comment by mrDlef** [comment]
+1

**Comment by WanWizard** [comment]
It is not at all easy, paths are defined relative to the location of the file they are in, of you move them to a separate file, you have to hardcode them all, which is not something we are prepared to do.

Pleasse send a PR with your suggested solution that doesn't include hardcoding.

**Comment by WanWizard** [comment]
This can't be addressed in the current setup.
