### ISSUE TITLE
Invalid CSS in public example

### ISSUE THREAD

**Issue by AlbinoGeek** [fuel/core#1429]
The "public" example that is distributed with Fuel has invalid CSS/HTML (missing } on the .btn .btn-primary style, therefore invalidationg the body{} style.) ; this can be seen in /fuel/app/views/welcome/\* (all three files)

**Comment by WanWizard** [comment]
has been fixed in  https://github.com/fuel/fuel/commit/c85c12f2ccd65744fce9c1ac5674256768d4d8fc
