### ISSUE TITLE
Session issue

### ISSUE THREAD

**Issue by cj** [fuel/core#143]
using memcached driver match_ua set to false and expiration_time set to 0 the site never loads, it just remains thinking.  Changing it back to 7200 the page loads just fine.

**Comment by WanWizard** [comment]
an expiration time of zero is not supported (see the config docs). If you need an expiration when the browser is closed, you should set 'expire_on_close' to true.

Having said that, I can reproduce this error, I'll have a look.

**Comment by cj** [comment]
Thank you, maybe the comments should be changed as they say you can use 0 http://screencast.com/t/vbkyccusV

**Comment by WanWizard** [comment]
no, the comments say: "anything <= 0 will be set to 2 years" (as in smaller or equal to zero). The docs also state that the value must be larger than zero.

**Comment by cj** [comment]
I understand but you said "an expiration time of zero is not supported" but it is, it just gets converted to two years (which I want) and that's when the bug happens.

**Comment by WanWizard** [comment]
Which is now fixed. 

The memcached pecl extension (the binary) chokes if you use an expiration value larger then approx. 30 days. Any larger number is supposed to be a timestamp, but looks like you've hit a bug in memcached. It now limits the memcached stored values to 30 days.
