### ISSUE TITLE
Profiler: Bad count for database queries?

### ISSUE THREAD

**Issue by AlbinoGeek** [fuel/core#1430]
FuelPHP Profiler: Never shows any database queries?  (always reports 0 queries)

**Comment by tomschlick** [comment]
You need to turn it on both in config.php and db.php on each database connection setting.

**Comment by AlbinoGeek** [comment]
In config.php:

```
     'profiling'  => true,
```

In db.php (for current env):

```
return array(
    'default' => array(
        'connection'  => array(
            'dsn'        => 'mysql:host=localhost;dbname=fuel_dev',
            'username'   => 'root',
            'password'   => '',
        ),
    ),
);
```

I'm guessing something is missing here?  If so; shouldn't this be noted in the profiler (that it's disabled / not being collected / something? ; and not just a blank page)

The default files do not appear to have a commented out setting relating to this either as would be expected.

**Comment by tomschlick** [comment]
add 'profiling' => true inside of the default array (not inside of connection)

**Comment by AlbinoGeek** [comment]
```
<?php
/**
 * The development database settings. These get merged with the global settings.
 */

return array(
    'default' => array(
        'connection'  => array(
            'dsn'        => 'mysql:host=localhost;dbname=fuel_dev',
            'username'   => 'root',
            'password'   => '',
        ),
    'profiling' => true
    ),
);
```

Still shows 0 db queries; and the tab is empty (when inserting a user, or editing a user in a oil generated crud)

**Comment by WanWizard** [comment]
This is the complete definition for a database config:

```
return array(
    'default' => array(
        'type'          => 'pdo',
        'connection'    => array(
            'dsn'        => 'mysql:host=localhost;dbname=fuel_dev',
            'hostname'   => 'localhost',
            'username'   => 'root',
            'password'   => '',
            'persistent' => false,
        ),
        'identifier'   => '`',
        'table_prefix' => '',
        'charset'      => 'utf8',
        'caching'      => false,
        'profiling'    => true,
    ),
);
```

This is copied from a working application, and profiling DB queries works fine.

I see a lot of opened issues from you. If you have bugs, by all means post them here, with an example. If you have questions about how to use it, use the forums or IRC, but don't mis-use the issue tracker.
