### ISSUE TITLE
Profiler: Bad count for session, get, post variables

### ISSUE THREAD

**Issue by AlbinoGeek** [fuel/core#1431]
Profiler: Always shows 0 for session variables, get variables and post variables (tabs empty as well)

**Comment by WanWizard** [comment]
Not here. As soon as I add "?foo=bar" to any URL, it pops up in the profiler.

**Comment by AlbinoGeek** [comment]
## 

And yet it doesn't track /user/view/1 (1 being a parameter for user action view $id); ie: routing variables, and it still doesn't seem to show me any post (but I'm guessing I'm not seeing post because of the redirects?)

**Comment by WanWizard** [comment]
That is neither a GET variable nor a POST variable, so yes, it doesn't track that. 
And if you redirect after processing the post, then yes, you won't see it.
