### ISSUE TITLE
Profiler: Bad memory usage calculation?

### ISSUE THREAD

**Issue by AlbinoGeek** [fuel/core#1432]
Profiler: "Memory Usage" is drastically different than the Memory Usage shown on the page (near the load time)

**Comment by WanWizard** [comment]
Which is pretty logical.

The profiler runs when the full application stack is still loaded and active. The information on the bottom of the welcome page (which is only there as a demo), is gathered after the framework is finished and everything is cleaned up, and will therefor show a lower value.
