### ISSUE TITLE
DBUtil generates invalid SQL with DECIMAL datatype

### ISSUE THREAD

**Issue by dudeami0** [fuel/core#1435]
Using DBUtil, I get an error related to single quotes around the constraints. Right now the code generates something like:

```
`amount` decimal('25', '2') NOT NULL,
```

which results in:

```
Uncaught exception PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''25', '2')
```

Removing the quotes around the constraints seems to fix the problem.

**Comment by frankdejonge** [comment]
@dudeami could you supply the code that generates this?

**Comment by dudeami0** [comment]
Here it is: http://pastebin.com/n1tcFbRK

**Comment by dudeami0** [comment]
Also my quick fix was to change line 319 of core/classes/dbutil.php from

```
$sql .= "('".implode("', '",$attr['CONSTRAINT'])."')";
```

to

```
$sql .= "(".implode(", ",$attr['CONSTRAINT']).")";
```

**Comment by WanWizard** [comment]
That would break ENUM's, so that's not a solution. The implode should be replaced by something that checks the type of the variable in the constraint array, and only quote strings.
