### ISSUE TITLE
Default Timezone Bug

### ISSUE THREAD

**Issue by avaluxdev** [fuel/core#144]
Hi there.

There seems to be an issue setting the default timezone in FuelPHP. From the config, I set the default timezone variable to "America/New_York", however I see no changes. In addition, no errors or exceptions are generated; the time is simply not updated correctly.

**Comment by jschreuder** [comment]
To the other Fuel devs: The timezone is set in the app bootstrap and the config value is ignored. I remember someone changed this recently but this looks wrong to me...? Would probably be better to use the config value here and UTC only by default?
