### ISSUE TITLE
ViewModel - Change view from outside

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#1441]
Found a requirement to do this. Is the following implementation worth PRing into core?

``` php
<?php
/**
 * Allows you to change the view that this renders
 *
 * @param   string  view name
 */
public function change_view($view) {
    if ($this->_view instanceof \View) {
        $this->_view->set_filename($view);
    }
    else {
        $this->_view = $view;
    }
}
```

**Comment by WanWizard** [comment]
Implemented a get_view() method in https://github.com/fuel/core/commit/2f39b15cb048e35207d4bd06a724febd0debc458 which returns the associated View object.
