### ISSUE TITLE
Response for File::download on Chrome/IE/Firefox is recognized as 404

### ISSUE THREAD

**Issue by pandamicro** [fuel/core#1452]
I'm sending a pdf file with File::download to user, it works well on safari, but on Chrome/IE/Firefox, the browser show a 404 error message.
By checking the header, in fact, the browser has received the right informations with my pdf file, but the status code is 404.

I resolved the problem by prepending the status code in the response header.
It will be better if it can be solved directly in the File class.

**Comment by WanWizard** [comment]
File::download() doesn't set any http status headers.

The only reason for a 404 to be returned is that something else, prior to starting the download, sets a 404 status header. In the entire framework, there's only one place where a 404 status header is set, which is in the default response of the HTTPNotFoundException.

This suggests you have an issue in your application design... If not, show us where the 404 is coming from, so we can fix it.

**Comment by WanWizard** [comment]
@pandamicro any update on this?

**Comment by pandamicro** [comment]
Sorry for not replying earlier.

In fact, the reason for a 404 had been returned is exactly because no status code was given. We can maybe consider this a bizarre behavior of browser, because it actually received contents and its MIME media type.

My solution was to add manually the status code 200 in my response
Here is the segment of code:

``` php
http_response_code(200);        
File::download(DOCROOT . '/voodoo/pdf/' . $filename, $filename, 'application/pdf');
```

@WanWizard Thanks for remind me this.

**Comment by WanWizard** [comment]
We have plenty of apps that use File::download(), and I've never experienced this issue. I mainly work with FF, but most clients with IE, and they don't complain it doesn't work. 

Just tried one of the apps using Chrome, but I can't reproduce it, I get a popup to save the file without any issue. According to my request logger:

```
HTTP/1.1 200 OK
Date: Wed, 05 Jun 2013 16:35:10 GMT
Server: Apache/2.4.4 (Fedora)
X-Powered-By: PHP/5.4.15
Set-Cookie: qgdsess=a%3A1%3A%7Bi%3A0%3Bs%3A32%3A%2253915579e23aa14e555c78b0f1583b2a%22%3B%7D; expires=Wed, 05-Jun-2013 18:35:11 GMT; path=/
Content-Disposition: attachment; filename="examenpakket-sessie-1.pdf"
Content-Description: File Transfer
Content-Length: 96178
content-transfer-encoding: binary
Expires: 0
Cache-Control: must-revalidate, post-check=0, pre-check=0
Keep-Alive: timeout=10, max=10
Connection: Keep-Alive
Content-Type: application/pdf
```

So I still wonder why yours would have a 404 status. Are you catching a not-found and not handling it properly (for example by downloading from a 404 method?

**Comment by pandamicro** [comment]
I have reproduced the 404 page on my Chrome with this page : 

[LINK](http://season13.com/story/download404test)

The code PHP for this action is showing below : 

``` php
public function action_download404test() {
    File::download(DOCROOT . '/voodoo/pdf/S01E01.pdf', "Voodoo Connection S01E01.pdf", 'application/pdf');
}
```

Which you can see, that I just do the download, I checked the before function of this controller, there isn't any code which send 404 neither.

By the way, I haven't noticed before, but my chrome show me a code of error : Erreur 6 (net::ERR_FILE_NOT_FOUND)

**Comment by WanWizard** [comment]
That link doesn't work here: `Firefox can't find the file at http://season13.com/story/download404test`

Also, if I go to a random link on that site, it redirects to http://season13.com/index.php/404 which doesn't look very ok to me too.

This al suggests you do have a design issue somewhere. If I try that action here, it works without problems.

**Comment by pandamicro** [comment]
That's what I met, "Firefox can't find the file", but if you look into the content firefox receive, the pdf file header is right there. Besides, on Safari, the file will be downloaded with the same link

@WanWizard Isn't it normal that a random link ( which don't exist ) leads to the 404 page? I don't understand very well the problem. I haven't much experience on development of website, I'll appreciate it if you can explain it to me, thanks!

**Comment by WanWizard** [comment]
Firefox will probably stop on the 404, and Safari will ignore it if is sees the rest of the header?

You should not have index.php in the link, as the other links on the site indicate that you rewrite to get rid of it. So somewhere your config is wrong, or you use the wrong hardcoded link.

Fact remains, that by the time you get to the File::download() line in your code, the 404 status has already been set. Fact also remains that the only line of code in the entire framework that sets a 404 header is the handler of an uncaught HttpNotFoundException. So the framework doesn't set the 404, something else does.

So, somewhere in your application something goes wrong, and a 404 is set before it gets to your download code. Or something is wrong with your rewriting which causes the 404 status to be set.

**Comment by pandamicro** [comment]
@WanWizard I will look forward into it! Thanks very much for the explication.
I think this issue can be closed, sorry for the mistaken.
I will post the reason of my 404 bug later if I found it
