### ISSUE TITLE
Enhance Session and _get_cookie() to look for session_id in a header

### ISSUE THREAD

**Issue by kaiyzen** [fuel/core#1454]
Forum thread here with some details:

http://fuelphp.com/forums/discussion/12224/how-to-remove-set-cookie-from-headers-with-rest-implementation#Item_7

Right now sessions can be loaded via native cookies and POST.  In writing REST API's sometimes use case arises where no cookie support and just hiding session_id in a header value to validate a session for each call.., kind of like a light weight oauth setup.

**Comment by WanWizard** [comment]
Implemented in https://github.com/fuel/core/commit/00478c2fc752d86e59a5ecfb869a4700989f963d
