### ISSUE TITLE
Fuelphp 1.6 zip file ships with incorrect permissions on /public/.htaccess file?

### ISSUE THREAD

**Issue by ipsod** [fuel/core#1456]
I get a "you do not have permission to access..." error when trying to access any page after manually installing fuelphp 1.6 according to the directions.  The error is resolved by running chmod 775 on the .htaccess file in the public folder, though maybe I should do a chown instead?

**Comment by WanWizard** [comment]
That depends. It doesn't have world-rights for some reason at the moment, but ideally none of your files should have world rights set, as that might be a security issue. So if you need those rights, you might have to take a look at your permissions anyway.

**Comment by kenjis** [comment]
The .htaccess file has permission `-rw-rwx---`.  It is the only file in the Zip file which others can't read.

Web server running as nobody can't read it. Why don't you set to 644?
What is the some reason?

**Comment by WanWizard** [comment]
I didn't say I wouldn't change it. :smirk: Already did, but haven't pushed it yet.

A webserver running as nobody should still be member of a group that has read access on the files. World rights are always a bad idea.

**Comment by WanWizard** [comment]
It is correct in the repo, but wrong in the zipfile for some reason.
