### ISSUE TITLE
Uri::append() to keep the existing params

### ISSUE THREAD

**Issue by huglester** [fuel/core#1458]
Hello,

We today with a friend worked a bit with orderings, and came to our attention that to keep existing get vars is to do smth like this:

 \Uri::create(\Uri::current(), array(), \Input::get() + $arr)

So we made an alias: http://bin.fuelphp.com/snippet/view/f4

so you can simlpy:

``` php
echo Uri::append(array('sex' => 'male', 'name' => 'Tony'));
```

Wht do you think about it?

Or even: http://bin.fuelphp.com/snippet/view/f5

to support smth like this:

``` php
echo Uri::append('name', 'Ted');
```

It especialy helps, you you have a working form.. and wont to re-order by date, so you do echo \Uri::append('order_by', 'date');

and you are sure all of your other params will be safe. Will make the views a lot cleaner

**Comment by WanWizard** [comment]
I would prefer a bit more generic solution, and call it update() since it's not necessarily always an append.

Also, it would be handy if there was one method that does both segment and get variables, so it can replace segment_replace(), which is something I'm not happy with anyway...

**Comment by huglester** [comment]
segment_replace() for me it names itself, like it replaces some segments(not the $_GET vars)...

Agreed, Uri::update() seems like a clearer name.

I'm not sure if merging both is a good idea, since it could complex the usage of Uri::update() 

So let's think:))
