### ISSUE TITLE
rest.auth function config not getting picked up in fuel 1.6 php 5.3.5 on windows

### ISSUE THREAD

**Issue by kaiyzen** [fuel/core#1459]
Don't know if others are experiencing this issue, running dev setup with 5.3.5 on windows 7 machine.

With setting the rest.auth='function_name' config value it is always set to null and ignored.  I had to update my code to following to get it to be picked up:

//BEGIN CUSTOMIZATION - nd
//always being set to null for some reason
        // Get the configured auth method if none is defined
        if($this->auth === null)
        {
            $this->auth = \Config::get('rest.auth');
        }
//      $this->auth === null or $this->auth = \Config::get('rest.auth');
//END CUSTOMIZATION

Havent tested on other php versions, don't know if language issue

**Comment by WanWizard** [comment]
What do you mean by "setting the rest.auth='function_name' config value"? In rest.php the configuration file? Using a Config::set() in your code?

**Comment by WanWizard** [comment]
This bug was fixed a month ago: https://github.com/fuel/core/commit/a8d9f3ae96c54149d756ad73d9af9757fa9cbbbc
