### ISSUE TITLE
Enhance session driver header session_id read to look for config param

### ISSUE THREAD

**Issue by kaiyzen** [fuel/core#1461]
The recently added session driver enhancement to look for session_id in the header is nice.  Added the following to my merged 1.6 setup:

//BEGIN CUSTOMIZATION - nd
$header_param = (isset($this->config['header_session_param'])) ? $this->config['header_session_param'] : 'Session-Id';
$cookie = \Input::headers($header_param, false);
//$cookie = \Input::headers('Session-Id', false);
//END CUSTOMIZATION

To look for header_session_param as I have pre-existing clients that have pre-defined token they are passing.  Might be nice enhancement to move this into general config

**Comment by WanWizard** [comment]
Added in https://github.com/fuel/core/commit/72f9b27b366d55bc47950ff3d5432e994eb8a610
