### ISSUE TITLE
Feature request: Multi-thread cURL

### ISSUE THREAD

**Issue by haqqi** [fuel/core#1464]
Current cURL wrapper only support single request. I think it would be good if FuelPHP has a feature of Multi-thread cURL.

The use case:
- request can handle more than 1 request in parallel.
- each request will call a callback after getting the response.
- the callback can receive custom parameter for each request, maybe we can call it like example below

``` php
$curl = Request::forge('curl');
for($i = 0; $i < 10; $i++) {
  $curl->add_request('http://a-domain.com/', 'callback', array('request-number' => $i));
}

$temp_var = array();
function some_callback($response, $param) {
  $temp_var[$param['request-number']] = $response->response(); //maybe we can use response wrapper
}
```

Several libraries i have tried, but i was not satisfied:
- https://github.com/jmathai/php-multi-curl
- https://github.com/petewarden/ParallelCurl -> quite slow
- https://github.com/stefangabos/Zebra_cURL/ -> quite fast, easy to use, but cannot add user parameter. Maybe this library can be forked.

**Comment by frankdejonge** [comment]
I suggest using Guzzle for this, it's feature-full and supports this out of the box: http://guzzlephp.org/http-client/client.html#sending-requests-in-parallel
