### ISSUE TITLE
Issue with Date ?

### ISSUE THREAD

**Issue by jhuriez** [fuel/core#1469]
Hi, I've an issue with \Date, here my example : 

``` php
$date = \Date::create_from_string('01/07/2013', 'eu');
var_dump($date->format('mysql');
```

It's output : 

```
2013-01-07 00:00:00
```

But the correct date is : 

```
2013-07-01 00:00:00
```

My date config : 

```
return array(

    /**
     * A couple of named patterns that are often used
     */
    'patterns' => array(
        'local'      => '%c',

        'mysql'      => '%Y-%m-%d %H:%M:%S',
        'mysql_date' => '%Y-%m-%d',

        'us'         => '%m/%d/%Y',
        'us_short'   => '%m/%d',
        'us_named'   => '%B %d %Y',
        'us_full'    => '%I:%M %p, %B %d %Y',
        'eu'         => '%d/%m/%Y',
        'eu_short'   => '%d/%m',
        'eu_named'   => '%d %B %Y',
        'eu_full'    => '%H:%M, %d %B %Y',

        '24h'        => '%H:%M',
        '12h'        => '%I:%M %p'
    )
);
```

**Comment by jhuriez** [comment]
For info, in \Date::create_from_string()

```
$input : 01/07/2013
$pattern_key = 'eu'
$pattern = '%d/%m/%Y'

After strptime and mktime :

date('d/m/Y', $timestamp) : 07/01/2013

```

The error is in strptime function ?

**Comment by WanWizard** [comment]
Windows? And what is your server locale (your local server date format)?

**Comment by jhuriez** [comment]
Yep it's in localhost on W7.

date_default_timezone_get() = 'Europe/Madrid'

I've try with replace '/' to '-' it's work, no other solution ?

**Comment by WanWizard** [comment]
Ok, thanks, I'll have to setup a test environment (no Windows here), and see what I can do.

**Comment by WanWizard** [comment]
Base issue is that on Windows, strptime() is emulated using strtotime(), and that function uses the format to determine the date format used, hardcoded. A dash means D-M-Y, a slash means M-D-Y. 

I have to think about how to deal with this.
