### ISSUE TITLE
Add an anchor open and close function

### ISSUE THREAD

**Issue by mrDlef** [fuel/core#1478]
I would be able to just open a link tag to be able to add some other html tags in a link.

Example :

``` php
<?php echo  Html::anchor_open('users/my_account', array('class' => 'media')); ?>
    <span class="pull-left">
        <img class="media-object" src="user.png">
    </span>
    <span class="media-body">
        <strong>Usernname</strong><br>
        <small>My account</small>
    </span>
<?php echo Html::anchor_close(); ?>
```

As you can see, My idea will be to add two new methods to the Html class but maybe there is a better way. Let me know what do you think about that...

**Comment by samuelsmal** [comment]
You can already do something like this:

```
<?php 
  $anchor_text = '<span class="pull-left">...</span>';
  echo Html::anchor('users/my_account', $anchor_text, array('class' => 'media'));
?>
```

But I can see your point.

**Comment by mrDlef** [comment]
Thanks, but I think that especially when using a template engine. And anyway it will be more elegant.

**Comment by WanWizard** [comment]
When using a template engine, you sure would use it's way of generating anchors?

**Comment by mrDlef** [comment]
For now it's just because in a Twig template I want to use the Uri::create method.
Instead of just add this method in the Twig_Fuel_Extension of Parser package I was asking myself if we can do a better thing.

**Comment by WanWizard** [comment]
The Uri methods are already available in twig templates, it's more logical to just create the anchor in the template, and use "base_url" or "current_url" to construct the anchor's href. Using Fuel code to achieve this seems like a very complex way of generating an anchor.
