### ISSUE TITLE
MongoDB class docblocks & commented out method

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#148]
My IDE noticed some bugs while I was in there for the Exceptions, I added TODO notes on those lines.

EDIT: also the docblocks aren't in line with our general standard.
EDIT 2: There's also a commented out method in there, should be either removed or finished.

**Comment by sergiigrebeniuk** [comment]
Hey guys, I believe it is fixed now

**Comment by jschreuder** [comment]
Nope, not yet. Example: https://github.com/fuel/core/blob/develop/classes/mongodb.php#L158

**Comment by tomschlick** [comment]
Judging by the commits above this should probably be closed...

**Comment by jschreuder** [comment]
Docblocks haven't been fixed yet and there's still at least one commented out function.
