### ISSUE TITLE
Input::hydrate() can corrupt base64 encoded strings

### ISSUE THREAD

**Issue by benharold** [fuel/core#1486]
A while back code was added to the Input::hydrate() method to automatically urldecode() the input data if the "www-form-urlencoded" header was detected. This has been awesome for the most part, as I have not had to manually urldecode data passed to my REST controllers via PUT requests. There is, however, one situation that I've run into where this can cause an issue. Line 513 of fuel/core/classes/input.php runs the parse_str() function on the input data right after it is urldecoded. If you're passing an image as a base64 encoded string over the wire, this will lead to all of the plusses being turned into spaces, which corrupts the image. There are obvious workarounds (encode the plusses before urlencoding and sending the request, replace spaces with plusses after receiving the request), but I though I would at least bring the issue up here, as I'm guessing this has the potential to cause problems in other circumstances.

**Comment by WanWizard** [comment]
The problem with this is that "www-form-urlencoded" implies that the data is urlencoded, which means it should be safe to decode it. From what I understand you pass data that is not encoded, and that leads to issues when decoding it.

This leads to the obvious, which is that you must encode it client-side.

**Comment by benharold** [comment]
The data is being encoded client-side. A base 64 encoded PNG has plusses in the text string. If you urlencode the text string and send it through the hydrate method (assuming you pass the "www-form-urlencoded" header) it will urldecode the string on line 511 of core/input.php (this is good), immediately followed by parse_str on line 513 (this is what ends up corrupting the image data). The parse_str method replaces all of the plusses in the text string with spaces, thereby corrupting the image data. The easiest way to workaround it is to str_replace all of the spaces in the text string with plusses after the input data has been hydrated.

**Comment by WanWizard** [comment]
I got that, my point is that the + is in there, because you haven't urlencoded the base64 value before submitting the form. You always have to urlencode stuff you put in a URL or in a form (when the content type is "www-form-urlencoded").

See http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1

**Comment by WanWizard** [comment]
Closed due to lack of feedback.

**Comment by benharold** [comment]
This issue has not been resolved. The plusses get stripped out of the data when the input is hydrated. Thus, if you're using PUT, you must:

if ( ! $image = \Input::put('image'))
{
    return false;
}

$image = str_replace(' ', '+', $image);
$image = base64_decode($image);

**Comment by WanWizard** [comment]
As I wrote earlier, this can't be solved server side. 

If you post a form as "application/x-www-form-urlencoded", you have to make sure all data in the form is urlencoded. Which means you have to urlencode the base64 string client-side, which would convert the + into %2B, which will be converted back into the + when Fuel processes the input.

**Comment by benharold** [comment]
Sorry Harro, as usual, I misheard you. I will tell the iOS guy to be sure to urlencode the base64 string client-side, that way you're not sending plusses over the wire.
