### ISSUE TITLE
Fields requiring fieldsets, or fieldsets being forced-multiton

### ISSUE THREAD

**Issue by Altreus** [fuel/core#1487]
I've been doing quite a lot with building fields recently, including setting up an arbitrary number of identical fieldsets. I've been collecting info from the user for logical rules, and so all the fieldsets for these rules are the same attribute-operator-value layout.

I've also found it useful to use a view instead of a field in some situations, and inside _that_ view, use another field to do the hard part of the rendering.

In all these situations the fact that Fieldset has to have a name has thwarted me: I've resorted to \Str::random() for the names, which logically defeats the purpose of the name in the first place. That itself is precipitated by the requirement to give a Field a Fieldset, something I'm not sure is entirely valuable.

I've not been able to use \Form::select() etc because I've needed to use a subclass of Field I wrote to facilitate all of this. These input helpers appear simply to return the HTML strings based on the input config; I can use this in some places, but not in others, and in some places it's actually useful to have a Fieldset but it is of no use to name it.

I think Fieldset would be augmented by being _optionally_ a multiton; and if no name is provided, no multiton registration happens. Alternatively, simply open the constructor for public use and allow one to be created and discarded.

As usual I may have missed something glaringly obvious so do let me know, but as it is I've had a bit of a fight trying to simply create a Field and output it.

Should I look at doing this, or is it not worth the time to spend on such a change?

**Comment by WanWizard** [comment]
Currently nobody's stopping you from using

```
$fieldset = new \Fieldset('name', $config);
```

and skip the creation of the multiton. If only the constructor would have been public.

It still requires you to pass a name, so I've made a change to the constructor to support

```
$fieldset = new \Fieldset($config);
```
