### ISSUE TITLE
Fresh checkout and the unit tests are failing

### ISSUE THREAD

**Issue by mixinmax** [fuel/core#1488]
Just did a fresh checkout and I ran the unit tests using oil:

```
$ php oil test
Tests Running...This may take a few moments.
```

Hangs like that forever. So I tried running the tests directly and skipping oil altogether:

```
$ cd fuel/core
$ phpunit
```

Same thing. With some tracking down I figure out the Agent test group was causing the hanging. So I excluded that from the test (sorry for the wall of output):

```
$ phpunit --group core --exclude-group Agent
Configuration read from D:\www\htdocs\fuel\fuel\core\phpunit.xml
```

<pre>
FFFFFFFF.....FFFF.F.F.....F....................................  63 / 347 ( 18%)
............................................................... 126 / 347 ( 36%)
...FF............F............................................. 189 / 347 ( 54%)
...................................F.....................FF.... 252 / 347 ( 72%)
FFF............................................................ 315 / 347 ( 90%)
................................

Time: 12:59, Memory: 19.75Mb

There were 24 failures:

1) Fuel\Core\Test_Agent::test_browser
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Firefox'
+'unknown'

D:\www\htdocs\fuel\fuel\core\tests\agent.php:47

2) Fuel\Core\Test_Agent::test_platform
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Linux'
+'unknown'

D:\www\htdocs\fuel\fuel\core\tests\agent.php:59

3) Fuel\Core\Test_Agent::test_version
Failed asserting that 0 is of type "float".

D:\www\htdocs\fuel\fuel\core\tests\agent.php:71

4) Fuel\Core\Test_Agent::test_property with data set #0 ('Browser', 'Firefox')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Firefox'
+'unknown'

D:\www\htdocs\fuel\fuel\core\tests\agent.php:165

5) Fuel\Core\Test_Agent::test_property with data set #1 ('Version', 3.6)
Failed asserting that 0 matches expected 3.6.

D:\www\htdocs\fuel\fuel\core\tests\agent.php:165

6) Fuel\Core\Test_Agent::test_property with data set #2 ('MajorVer', 3)
Failed asserting that 0 matches expected 3.

D:\www\htdocs\fuel\fuel\core\tests\agent.php:165

7) Fuel\Core\Test_Agent::test_property with data set #3 ('MinorVer', 6)
Failed asserting that 0 matches expected 6.

D:\www\htdocs\fuel\fuel\core\tests\agent.php:165

8) Fuel\Core\Test_Agent::test_property with data set #4 ('Platform', 'Linux')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Linux'
+'unknown'

D:\www\htdocs\fuel\fuel\core\tests\agent.php:165

9) Fuel\Core\Test_Agent::test_property with data set #10 ('Frames', true)
Failed asserting that false matches expected true.

D:\www\htdocs\fuel\fuel\core\tests\agent.php:165

10) Fuel\Core\Test_Agent::test_property with data set #11 ('IFrames', true)
Failed asserting that false matches expected true.

D:\www\htdocs\fuel\fuel\core\tests\agent.php:165

11) Fuel\Core\Test_Agent::test_property with data set #12 ('Tables', true)
Failed asserting that false matches expected true.

D:\www\htdocs\fuel\fuel\core\tests\agent.php:165

12) Fuel\Core\Test_Agent::test_property with data set #13 ('Cookies', true)
Failed asserting that false matches expected true.

D:\www\htdocs\fuel\fuel\core\tests\agent.php:165

13) Fuel\Core\Test_Agent::test_property with data set #15 ('JavaScript', true)
Failed asserting that false matches expected true.

D:\www\htdocs\fuel\fuel\core\tests\agent.php:165

14) Fuel\Core\Test_Agent::test_property with data set #17 ('JavaApplets', true)
Failed asserting that false matches expected true.

D:\www\htdocs\fuel\fuel\core\tests\agent.php:165

15) Fuel\Core\Test_Agent::test_property with data set #23 ('CssVersion', 3)
Failed asserting that 0 matches expected 3.

D:\www\htdocs\fuel\fuel\core\tests\agent.php:165

16) Fuel\Core\Test_Debug::test_debug_dump_normally
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '      &lt;script type="text/javascript"&gt;function fuel_debug_toggle(a){if(document.getElementById){if(document.getElementById(a).style.display=="none"){document.getElementById(a).style.display="block"}else{document.getElementById(a).style.display="none"}}else{if(document.layers){if(document.id.display=="none"){document.id.display="block"}else{document.id.display="none"}}else{if(document.all.id.style.display=="none"){document.all.id.style.display="block"}else{document.all.id.style.display="none"}}}};&lt;/script&gt;&lt;div class="fuelphp-dump" style="font-size: 13px;background: #EEE !important; border:1px solid #666; color: #000 !important; padding:10px;"&gt;&lt;h1 style="border-bottom: 1px solid #CCC; padding: 0 0 5px 0; margin: 0 0 5px 0; font: bold 120% sans-serif;"&gt;COREPATH/tests/debug.php @ line: 31&lt;/h1&gt;&lt;pre style="overflow:auto;font-size:100%;"&gt;&lt;strong&gt;Variable #1:&lt;/strong&gt;
 &lt;i&gt;&lt;/i&gt; &lt;strong&gt;&lt;/strong&gt; (Integer): 1

 &lt;strong&gt;Variable #2:&lt;/strong&gt;
 &lt;i&gt;&lt;/i&gt; &lt;strong&gt;&lt;/strong&gt; (Integer): 2

 &lt;strong&gt;Variable #3:&lt;/strong&gt;
 &lt;i&gt;&lt;/i&gt; &lt;strong&gt;&lt;/strong&gt; (Integer): 3

 &lt;/pre&gt;&lt;/div&gt;'

D:\www\htdocs\fuel\fuel\core\tests\debug.php:35

17) Fuel\Core\Test_Debug::test_debug_dump_by_call_user_func_array
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '&lt;div class="fuelphp-dump" style="font-size: 13px;background: #EEE !important; border:1px solid #666; color: #000 !important; padding:10px;"&gt;&lt;h1 style="border-bottom: 1px solid #CCC; padding: 0 0 5px 0; margin: 0 0 5px 0; font: bold 120% sans-serif;"&gt;COREPATH/tests/debug.php @ line: 46&lt;/h1&gt;&lt;pre style="overflow:auto;font-size:100%;"&gt;&lt;strong&gt;Variable #1:&lt;/strong&gt;
 &lt;i&gt;&lt;/i&gt; &lt;strong&gt;&lt;/strong&gt; (Integer): 1

 &lt;strong&gt;Variable #2:&lt;/strong&gt;
 &lt;i&gt;&lt;/i&gt; &lt;strong&gt;&lt;/strong&gt; (Integer): 2

 &lt;strong&gt;Variable #3:&lt;/strong&gt;
 &lt;i&gt;&lt;/i&gt; &lt;strong&gt;&lt;/strong&gt; (Integer): 3

 &lt;/pre&gt;&lt;/div&gt;'

D:\www\htdocs\fuel\fuel\core\tests\debug.php:50

18) Fuel\Core\Test_Fieldset::test_for_in_label
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'&lt;form action="welcome/index" accept-charset="utf-8" method="post"&gt;&lt;table&gt;&lt;tr&gt;&lt;td class=""&gt;&lt;/td&gt;&lt;td class=""&gt;&lt;input type="radio" value="0" id="form_gender_0" name="gender" /&gt; &lt;label for="form_gender_0"&gt;male&lt;/label&gt;&lt;br /&gt;&lt;input type="radio" value="1" id="form_gender_1" name="gender" checked="checked" /&gt; &lt;label for="form_gender_1"&gt;female&lt;/label&gt;&lt;br /&gt;&lt;span&gt;&lt;/span&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/form&gt;'
+'&lt;form action="welcome/index" accept-charset="utf-8" method="post"&gt;
+&lt;table&gt;&lt;tr&gt;&lt;td class=""&gt;&lt;/td&gt;&lt;td class=""&gt;&lt;input type="radio" value="0" id="form_gender_0" name="gender" /&gt; &lt;label for="form_gender_0"&gt;male&lt;/label&gt;&lt;br /&gt;&lt;input type="radio" value="1" id="form_gender_1" name="gender" checked="checked" /&gt; &lt;label for="form_gender_1"&gt;female&lt;/label&gt;&lt;br /&gt;&lt;span&gt;&lt;/span&gt;&lt;/td&gt;&lt;/tr&gt;
+&lt;/table&gt;&lt;/form&gt;
+'

D:\www\htdocs\fuel\fuel\core\tests\fieldset.php:91

19) Fuel\Core\Test_Model_Crud::test_get_connection
Failed asserting that null matches expected 'read'.

D:\www\htdocs\fuel\fuel\core\tests\model\crud.php:35

20) Fuel\Core\Test_Pagination::test_uri_segment_make_link_with_query_string_ending_page_number
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/welcome/index/1?foo=bar&fuel%5B0%5D=php1&fuel%5B1%5D=php2'
+'/welcome/index/1?foo=bar&amp;fuel%5B0%5D=php1&amp;fuel%5B1%5D=php2'

D:\www\htdocs\fuel\fuel\core\tests\pagination.php:375

21) Fuel\Core\Test_Pagination::test_uri_segment_make_link_with_query_string_ending_slash
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/welcome/index/1?foo=bar&fuel%5B0%5D=php1&fuel%5B1%5D=php2'
+'/welcome/index/1?foo=bar&amp;fuel%5B0%5D=php1&amp;fuel%5B1%5D=php2'

D:\www\htdocs\fuel\fuel\core\tests\pagination.php:399

22) Fuel\Core\Test_Pagination::test_query_string_make_link_by_request
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'welcome/index/?foo=bar&fuel%5B0%5D=php1&fuel%5B1%5D=php2&p=1'
+'welcome/index/?foo=bar&amp;fuel%5B0%5D=php1&amp;fuel%5B1%5D=php2&amp;p=1'

D:\www\htdocs\fuel\fuel\core\tests\pagination.php:564

23) Fuel\Core\Test_Pagination::test_query_string_make_link_by_pagination_url
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://docs.fuelphp.com/?foo=bar&fuel%5B0%5D=php1&fuel%5B1%5D=php2&p=1'
+'http://docs.fuelphp.com/?foo=bar&amp;fuel%5B0%5D=php1&amp;fuel%5B1%5D=php2&amp;p=1'

D:\www\htdocs\fuel\fuel\core\tests\pagination.php:587

24) Fuel\Core\Test_Pagination::test_query_string_make_link_by_pagination_url_include_page_number
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://docs.fuelphp.com/?foo=bar&p=1&fuel%5B0%5D=php1&fuel%5B1%5D=php2'
+'http://docs.fuelphp.com/?foo=bar&amp;p=1&amp;fuel%5B0%5D=php1&amp;fuel%5B1%5D=php2'
</pre>

The tests run, but a lot of them are failing. Has anyone encountered something similar before? Also, still having weird hanging issues with the Agent tests.

**Comment by mixinmax** [comment]
After some more careful inspection, it seems that the output I posted above is the output of the hanging process I killed (see that it says it was running for 13 minutes). The output printed to my terminal window when I wasn't looking. I can confirm this because the tests for the Agent class are in that output.

I can't explain the behaviour. Very weird.

**Comment by WanWizard** [comment]
This is probably because on first usage (and on the configured expiry) the Agent class will download the browscap file, unless you have one configured in your php.ini. This download is done using file_get_contents(), and it looks like your server couldn't get a connection, and just hung up.

**Comment by mixinmax** [comment]
I thought it could be something along those lines, so I downloaded the latest browscap file and modified by php.ini to point to it. I double checked and it seems I have the browscap setting enabled in my agent.php config. I disabled it and now the tests don't hang anymore. However, I'm still getting tons of failures. A good portion of which are from the Agent tests:

<pre>
1) Fuel\Core\Test_Agent::test_browser
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Firefox'
+'unknown'
D:\www\htdocs\fuel\fuel\core\tests\agent.php:47
2) Fuel\Core\Test_Agent::test_platform
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Linux'
+'unknown'
D:\www\htdocs\fuel\fuel\core\tests\agent.php:59
3) Fuel\Core\Test_Agent::test_version
Failed asserting that 0 is of type "float".
D:\www\htdocs\fuel\fuel\core\tests\agent.php:71
4) Fuel\Core\Test_Agent::test_property with data set #0 ('Browser', 'Firefox')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Firefox'
+'unknown'
D:\www\htdocs\fuel\fuel\core\tests\agent.php:165
5) Fuel\Core\Test_Agent::test_property with data set #1 ('Version', 3.6)
Failed asserting that 0 matches expected 3.6.
D:\www\htdocs\fuel\fuel\core\tests\agent.php:165
6) Fuel\Core\Test_Agent::test_property with data set #2 ('MajorVer', 3)
Failed asserting that 0 matches expected 3.
D:\www\htdocs\fuel\fuel\core\tests\agent.php:165
7) Fuel\Core\Test_Agent::test_property with data set #3 ('MinorVer', 6)
Failed asserting that 0 matches expected 6.
D:\www\htdocs\fuel\fuel\core\tests\agent.php:165
8) Fuel\Core\Test_Agent::test_property with data set #4 ('Platform', 'Linux')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Linux'
+'unknown'
D:\www\htdocs\fuel\fuel\core\tests\agent.php:165
9) Fuel\Core\Test_Agent::test_property with data set #10 ('Frames', true)
Failed asserting that false matches expected true.
D:\www\htdocs\fuel\fuel\core\tests\agent.php:165
10) Fuel\Core\Test_Agent::test_property with data set #11 ('IFrames', true)
Failed asserting that false matches expected true.
D:\www\htdocs\fuel\fuel\core\tests\agent.php:165
11) Fuel\Core\Test_Agent::test_property with data set #12 ('Tables', true)
Failed asserting that false matches expected true.
D:\www\htdocs\fuel\fuel\core\tests\agent.php:165
12) Fuel\Core\Test_Agent::test_property with data set #13 ('Cookies', true)
Failed asserting that false matches expected true.
D:\www\htdocs\fuel\fuel\core\tests\agent.php:165
13) Fuel\Core\Test_Agent::test_property with data set #15 ('JavaScript', true)
Failed asserting that false matches expected true.
D:\www\htdocs\fuel\fuel\core\tests\agent.php:165
14) Fuel\Core\Test_Agent::test_property with data set #17 ('JavaApplets', true)
Failed asserting that false matches expected true.
D:\www\htdocs\fuel\fuel\core\tests\agent.php:165
15) Fuel\Core\Test_Agent::test_property with data set #23 ('CssVersion', 3)
Failed asserting that 0 matches expected 3.
D:\www\htdocs\fuel\fuel\core\tests\agent.php:165
</pre>

Along with the same failures as above.

**Comment by WanWizard** [comment]
Agent parses the browscap and caches the results ot avoid having to fetch it on every request. Due to the earlier failure, you might now have an empty cache file. Delete the cache in cache/fuel/agent and try again.

**Comment by mixinmax** [comment]
Hmmm, that cache file doesn't exist. The `Agent` directory is there but nothing inside.

**Comment by WanWizard** [comment]
Just ran a full test here with a brand-new install, without any test errors. So all I can think of is that there's something wrong with your browscap installation, so Agent can't find/download/use it.

**Comment by mixinmax** [comment]
I was able to fix this by doing the following:
- Comment out the `[browscap]` entry in the php config
- Download the browscap file and put it in `fuel/app/tmp/`

For some reason I had to bring it right into Fuel for it to work.

**Comment by WanWizard** [comment]
So to recap: it doesn't work when you let PHP handle the browscap, but it does what Agent parses the browscap file itself? If that is the case, I consider that a bug that needs fixing.

**Comment by mixinmax** [comment]
Yeah that was my experience in a nutshell. This is in my environment at work so we could have some archaic part of our stack screwing it up for Fuel. I can take a look tomorrow and post some specs for our stack.
