### ISSUE TITLE
Response::redirect on URLs containing asterisks

### ISSUE THREAD

**Issue by felixgilles** [fuel/core#1490]
Hi the team !

According to the [RFC 1738 - Uniform Resource Locators (URL)](http://www.rfc-editor.org/rfc/rfc1738.txt), page 3:

> Reserved:
> 
> Many URL schemes reserve certain characters for a special meaning: their appearance in the scheme-specific part of the URL has a designated semantics. If the character corresponding to an octet is reserved in a scheme, the octet must be encoded.  The characters ";", "/", "?", ":", "@", "=" and "&" are the characters which may be reserved for special meaning within a scheme. No other characters may be reserved within a scheme.
> 
> Usually a URL has the same interpretation when an octet is represented by a character and when it encoded. However, this is not true for reserved characters: encoding a character reserved for a particular scheme may change the semantics of a URL.
> 
> Thus, only alphanumerics, the special characters "$-_.+!*'(),", and reserved characters used for their reserved purposes may be used unencoded within a URL.
> 
> On the other hand, characters that are not required to be encoded (including alphanumerics) may be encoded within the scheme-specific part of a URL, as long as they are not being used for a reserved purpose. 

We can have asterisks unencoded in URLs. But these URLs are not well redirecting when we use \Response::redirect(), the asterisks are replaced as wildcards.

The wildcard replacement should be optional, shouldn't it ?

**Comment by zoe-edwards** [comment]
Yes, or use a different wildcard?

**Comment by WanWizard** [comment]
Perhaps it should be removed from redirect() all together. If you want it, you can still call Uri::segment_replace() and feed the result into redirect().

Problem is that changing this now will break every application that uses is, so we'll have to think about it carefully.

**Comment by felixgilles** [comment]
Thank for your responses. 

In our case, we will extend Response::redirect() to work without wildcard replacement, waiting that the feature be removed from FuelPHP.

**Comment by felixgilles** [comment]
Thanks, it's perfect !
