### ISSUE TITLE
Error in config documentation

### ISSUE THREAD

**Issue by dudeami0** [fuel/core#1497]
Sorry if this is the wrong place. In the documentation, Config::save says the second argument is required, but the header says:

save($file, $config = null)

Pointing that it is not. Of course this is false, as the code clearly states its required (and the argument list in the documentation).

Minor issue, just wanted to bring it to your attention.

Url: http://fuelphp.com/docs/classes/config.html#/method_save

**Comment by WanWizard** [comment]
i'll correct it. 

Next time, please report docs issues at https://github.com/fuel/docs/issues, so we can reference the issue in the commit that fixes it.

**Comment by dmyers** [comment]
I think Wan meant https://github.com/fuel/docs/issues

**Comment by WanWizard** [comment]
Oops, corrected...
