### ISSUE TITLE
DB::last_query() race condition?

### ISSUE THREAD

**Issue by mixinmax** [fuel/core#1500]
I'm using an ORM model with CRUD methods in the controller to find my data. The problem is, I want to log all database queries ran by the CRUD calls.

The only functionality I found for this is in the DB class with the `last_query()` method. However, wouldn't this have a high risk of causing false logs due to race conditions.

If, for example, I have:

```
$data['obj'] = Model_Something::find('all');
Log::debug(DB::last_query());
```

But another user triggers another database query between my CRUD call and my call to DB. I would then me logging his query instead of mine.

Is there a way around this?

**Comment by WanWizard** [comment]
I don't really understand what you mean. What exactly is the 'race condition'?

Web applications support concurrent requests by nature, and a logfile is something sequential, so if you have concurrent users, obviously you can't predict nor control the order or sequence of entries in the log file.

This has nothing to do with a race condition (which is a bug that only surfaces at a specific sequence of events).

**Comment by mixinmax** [comment]
I'll try to explain my reasoning a little better.

Let's say I have two dashboards named A and B. Whenever I log something from dashboard A, I put a `[A]` tag in the log message so I can know which dashboard it came from. I do the same for dashboard B.

Let's say I'll only be logging MySQL statements using the `last_query` function. Something like this would appear in each dashboard:

```
// in dashboard A
$data['obj'] = Model_Something::find('all');
Log::debug("[A] " . DB::last_query()); 

// in dashboard B
$data['obj'] = Model_Something::find('first');
Log::debug("[B] " . DB::last_query()); 
```

Now let's say I have a user on dashboard A and one on dashboard B. They both trigger the above code at the same time. Wouldn't the following scenario be possible:
- `$data['obj'] = Model_Something::find('all');` on dashboard A is run
- `$data['obj'] = Model_Something::find('first');` on dashboard B is run
- `Log::debug("[A] " . DB::last_query());` runs
- `Log::debug("[B] " . DB::last_query());` runs

This would result in the following in the logs:

```
[A] query for Model_Something::find('first')
[B] query for Model_Something::find('first')
```

Whereas we would want:

```
[A] query for Model_Something::find('all')
[B] query for Model_Something::find('first')
```

The log expression in dashboard A would actually be grabbing the query run by dashboard B, even though it was expecting the query from dashboard A.

Does that make more sense?

**Comment by WanWizard** [comment]
Eh, no, that is not an issue. 

PHP is stateless, User A and User B execute are two completely different requests, they don't have anything with each other in common, and they absolutely don't share any data.

**Comment by mixinmax** [comment]
Oh okay, that makes sense. Thanks for clearing that up.
