### ISSUE TITLE
Redis Session

### ISSUE THREAD

**Issue by rafacustodio** [fuel/core#1505]
When I try to use redis to session storage I get the follow exception:

![image](https://f.cloud.github.com/assets/4119719/1021543/aa139af4-0d0c-11e3-9ba9-2d28d1c4be56.png)

**Comment by WanWizard** [comment]
You have probably installed the Redis PECL extension in your PHP installation. As that also exports a class called "Redis", it will not work together with PHP's Redis class.

**Comment by rafacustodio** [comment]
In an application I use Redis class, so when I install the Redis PECL I can't use Redis in Fuel?

**Comment by WanWizard** [comment]
Correct. Unfortunately, they choose the same class name we were already using. ;)

As a workaround, you can utilize Fuel's ability to extend core classes (see the docs for a howto). Create a new class in your app/classes somewhere, have it extend Session_Redis, 

Copy the Redis class to the app/classes folder, and rename it (to something like Fredis.

Then, in your Session_Redis extension, overload the init() method to read:

```
public function init()
{
    // generic driver initialisation
    parent::init();

    if ($this->redis === false)
    {
        // get the redis database instance
        $this->redis = \Fredis::instance($this->config['database']);
    }
}
```

That should fix your issue.

**Comment by WanWizard** [comment]
Issue dealt with in https://github.com/fuel/core/commit/03a235be4ec8dfb54eb0b55c8c7fa8f9e302c821

**Comment by rafacustodio** [comment]
Thanks
