### ISSUE TITLE
Database wont work if charset left at utf8_unicode_ci will stop sessions from working also

### ISSUE THREAD

**Issue by InsiteFX** [fuel/core#1512]
I generated tables with oil and it set the collation to utf8_general_ci, I always use utf8_unicode_ci. After looking at the DBUtil code I saw that you can set the database charset to utf8_unicode_ci and this works! but after that I always have to change it back or I start getting invalid charset errors. Can we get a collation setting added to the database configuration or fix this so that the whole database see it correct?

NOTE: If the charset is left at utf8_unicode_ci for the collation the Sessions quit to work! until you set it back to utf8

Thank you

**Comment by WanWizard** [comment]
Can you explain what you did, what you changed? We need to be able to recreate it to get it fixed.

**Comment by WanWizard** [comment]
Think I figured it out.

You've configured your db.php with `"charset" => "utf8_unicode_ci"`. For DBUtil, this will translate to `"CHARACTER SET utf8 COLLATE utf8_unicode_ci"`, which is what you're looking for. But the DB class will use the "charset" config for "SET NAMES", which fails because no charset named "utf8_unicode_ci" exists.

So actually the db.php need a config key "collation", so you can define both.

**Comment by WanWizard** [comment]
Wrong button...

**Comment by InsiteFX** [comment]
Hi,

Set the db charset = utf8_unicode_ci
Run oil to do migrations

If you leave the charset the way it is you get database charset errors and the sessions no longer work. I then have to go back in to the db config

charset = utf8

Thanks
Ray

**Comment by WanWizard** [comment]
Don't mix "charset" and "collating sequence".

You should not touch the charset, it is used in "SET NAMES", and should remain "utf8". There is a new key "collation" with you can set to "utf8_unicode_ci", and which will be used to set the collating sequence in DBUtil when you create a database.

edit: sorry, I see it's a reponse to the first question. It has already been adressed. ;-)

**Comment by InsiteFX** [comment]
Thanks.
