### ISSUE TITLE
DB Where ommit condition when value is empty array

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/core#1516]
`DB::select()->from->('t')->where('id', 'IN', array())->execute()`

This will throw an SQL syntax error near WHERE `t` IN ().

Shouldn't the builder ommit this condition? This way I shouldn't check the content of the input variable array.

**Comment by frankdejonge** [comment]
This can lead to unexpected results. For example when you delete records. If the array is ignored, all records from a table will be deleted. It's up to the dev to take this into account.
