### ISSUE TITLE
Possible bug when populating fieldset

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#1517]
Around line 525ish of fieldset::populate() is this...

``` php
$value === null and $value = \Arr::get($input, $f->basename, null);
```

I've had an issue where the basename of the field is null and thus the field gets populated with the full value of $input (a model, in this case). Presumably it should check $f->basename before using it as an array key?

Phil

**Comment by WanWizard** [comment]
How did you manage to have a null basename? The fields basename is derived from the fieldset fields' name, and that is a required field.
