### ISSUE TITLE
DBUtil::process_fields() ignore specified connection

### ISSUE THREAD

**Issue by kouhate** [fuel/core#1518]
Version 1.6 DButil::process_fields

Line 311: 

<pre>$sql .= \DB::quote_identifier($field);</pre>

DB::quote_identifier not accept $db connection, so if we have config/db.php like bellow

<pre>return array(
 'default' => array(
   'connection' => un connectable configs...
 ),
 'specified' => array(
   'connection' => connectable configs...
 ),
)
</pre>

and execute

<pre>\DBUtil::set_connection('specified');
\DBUtil::create('table', array(columns...));
</pre>

got an error like

Fuel\Core\Database_Exception [ 2054 ]: SQLSTATE[HY000] [2054] The server requested authentication method umknown to the client

Thanks

**Comment by frankdejonge** [comment]
By the looks of it this has been fixed for 1.7
