### ISSUE TITLE
DBUtil create_table CHARSET

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/core#1522]
When creating a table with DBUtil::create_table, the $charset option is setting the charset, not the collation, but in the docs it says, you can put a collation there, like 'utf8_unicode_ci'.

The processed query contains the following SQL code:
DEFAULT CHARACTER SET utf8_unicode_ci

And it should be:
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci

**Comment by WanWizard** [comment]
The docs are not correct, "utf8_unicode_ci" is not a charset.

**Comment by WanWizard** [comment]
Rereading everything: I think the idea was that if you pass "utf8_unicode_ci" as charset, it would convert this into both a charset and a collating sequence. If I understand it correctly this behaviour is now broken?

**Comment by sagikazarmark** [comment]
Quick solution :smile:
