### ISSUE TITLE
Pagination return raw array of elements

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/core#1523]
There could be an option (parameter for render()?) for rendering an array of pagination elements for templates. This way generating elements could be easy for template engines (twig, etc) and using config file templates could be ommited. This also improves the portability of themes, because there is no dependency between the app and the theme.

**Comment by WanWizard** [comment]
Can you give an example of what the possible return values should be?

**Comment by sagikazarmark** [comment]
My first idea:

```
array (
  'first' => array('title', 'url'),
  0 => array('title', 'url'),
  1 => array('title', 'url'),
  2 => array('title', 'url'),
  'current' => array('title', 'url'),
  3 => array('title', 'url'),
  'last' => array('title', 'url'),
)
```

Optional: type of pagination link (first, page, current, last, next, previous) can be stored in the array not in the key, so indexing during the rendering can be easier.
