### ISSUE TITLE
Not using native mysql driver

### ISSUE THREAD

**Issue by aswatts** [fuel/core#1526]
Error - invalid data source name in /fuel/core/classes/database/pdo/connection.php on line 94

PHP 5.5.3

ENV set to Production
Config for DB in Production
NO DB config in fuel/config

Works from other web apps with same parameters

return array(
    'production' => array(
        'type'  => 'mysql',  
        'connection'  => array(
            'hostname'   => '127.0.0.1',
            'database'   => 'eis',
            'port'       => '3306',
            'username'   => '',
            'password'   => '',
        ),
    ),
);

**Comment by WanWizard** [comment]
It doesn't seem to load it at all, issue with file rights?

**Comment by WanWizard** [comment]
Any feedback? This can not be reproduced. 

Note that the env setting maps to a directory, and is therefore (on most operating systems) case sensitive. So it must be "production" and not "Production".

**Comment by WanWizard** [comment]
Closed due to no response.
