### ISSUE TITLE
bgcolor in Image class dont work with resize()&save()

### ISSUE THREAD

**Issue by patie** [fuel/core#153]
when i resize image with $keepar=true and $pad=true and i set bgcolor to '#fff' it will work with output but when i save it - background is always black.

i think its a bug

**Comment by jschreuder** [comment]
@dudeami - could you take a look?

**Comment by dudeami0** [comment]
Sent a pull request.

**Comment by jschreuder** [comment]
@dudeami thanks for the quick reply!
