### ISSUE TITLE
Making Log class driver based

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/core#1534]
I am thinking about modifying the Log class to make it driver based.

Think about an application which needs to log user logins, special events, and the application has to be able to send emails with the log, etc. Monolog can do all this, and I don't think this is core functionality, but being able to write your own drivers is.

What do you think?

**Comment by WanWizard** [comment]
I would not put any effort in if I were you. As you said, Monolog can do this just fine, and you can access it directly via `Log::instance()` if you need to.

1.7 will be released very soon, and it is expected to be the last of the 1.x released. 2.0 will use Monolog natively.
