### ISSUE TITLE
Miss Make Link when Set Custom Pagination URL

### ISSUE THREAD

**Issue by viyancs** [fuel/core#1538]
I have Problem when I want to create some pagination with search query and custom pagination_url , The Link URL in Page Number is not active didn't have query (get params)

The result : 

current link active is correct
![screen shot 2013-10-03 at 9 15 03 pm](https://f.cloud.github.com/assets/799452/1261882/1ba9409a-2c36-11e3-9f70-d4bc602d7bed.png)

but another link is not active is incorrect, that is don't have query params in the url.
![screen shot 2013-10-03 at 9 16 18 pm](https://f.cloud.github.com/assets/799452/1261888/3624ca02-2c36-11e3-9534-75ecb18b6669.png)

```
 /**
 * set pagination
 * @param int $count
 * @return array 
 */
private function _config($count)
{
    $url = '/backend/brand';
    $url_segment = 3;
    // config Pagination
    $config = array(
        'pagination_url' => $url ,
        'uri_segment' => $url_segment,
        'num_links' => 5,
        'per_page' => 5,
        'total_items' => $count,

    );

    return $config;
}
```

**Comment by frankdejonge** [comment]
You can fix this by re-adding the get params in the paginarion_url:

``` php
'pagination_url' => Uri::create('backend/brand', array(), Input::get()),
```

**Comment by viyancs** [comment]
thanks that is work ..

sorry just little edit your code ,correct is

``` php
'pagination_url' => Uri::create('backend/brand', array(), Input::get()),
```
