### ISSUE TITLE
Input::uri() urldecode()

### ISSUE THREAD

**Issue by andrewwheal** [fuel/core#1541]
If you use a server setup (e.g. Apache) that gives you `$_SERVER['PATH_INFO']` then it comes through URL decoded, however if your server setup (e.g. Nginx) causes FuelPHP to fall back to parsing `$_SERVER['REQUEST_URI']` then what you get is still URL encoded. I am not sure what you get if `$_SERVER['ORIG_PATH_INFO']` is used.

I presume that the processing done to `$_SERVER['REQUEST_URI']` is to simulate `$_SERVER['PATH_INFO']`? If this is the case should it not also `urldecode()` the path?

**Comment by WanWizard** [comment]
Yes, your presumption is correct. 

You have urlencoded characters in a URI segment (= a URL path)? Can you give an example of such a REQUEST_URI?
