### ISSUE TITLE
Upload 'auto_rename' false removes the same name file

### ISSUE THREAD

**Issue by kenjis** [fuel/core#1544]
```
'auto_rename'  => false,
'overwrite'  => false, // default
```

It causes 'A file with the name of the uploaded file already exists' error, but also removes existing uploaded file with the same name.

**Comment by kenjis** [comment]
https://github.com/fuelphp/upload/blob/master/src/Fuel/Upload/File.php#L472
The code which removes file is needed?

**Comment by WanWizard** [comment]
If "auto_rename" is true, a temp file is created to claim the generated name, to make sure it's available if later on the uploaded file needs to be moved.

If due to an error the file isn't moved, the temp file must be deleted again. But only then offcourse.
