### ISSUE TITLE
index.php now only updates the output with profiling data if the placeholders are present in the output. 1.7 bug (possible)

### ISSUE THREAD

**Issue by leemason** [fuel/core#1546]
just updated to 1.7 and found that if i used the updated index.php file my dev went down with an ellusive error.

turns out (specifically when using the theme class) the new check in the index.php file for the memory tags was causing an issue with the partial system in the theme class.

the error message provided says "foreach expects parameter 1 to be an array" and is defined at:

https://github.com/fuel/core/blob/1.8/develop/classes/theme.php#L309

to get my site working again i changed this:

``` php
if (strpos($response->body(), '{exec_time}') !== false or strpos($response->body(), '{mem_usage}') !== false)
{
    $bm = Profiler::app_total();
    $response->body(
        str_replace(
            array('{exec_time}', '{mem_usage}'),
            array(round($bm[0], 4), round($bm[1] / pow(1024, 2), 3)),
            $response->body()
        )
    );
}
```

to this:

``` php
    $bm = Profiler::app_total();
    $response->body(
        str_replace(
            array('{exec_time}', '{mem_usage}'),
            array(round($bm[0], 4), round($bm[1] / pow(1024, 2), 3)),
            $response->body()
        )
    );
```

and it started working fine again.

**Comment by WanWizard** [comment]
Those two pieces of code don't do anything fundamentaly different. You have an error in the theme class, which is not related to your index.php. 

The error message is that $partials in that line is not an array, which is an internal Theme class issue. It sounds a bit like everything is being rendered twice, which is not supported by the Theme class, so that needs to be fixed.

**Comment by WanWizard** [comment]
render() is indeed called multiple times, I'm looking for a solution.

**Comment by WanWizard** [comment]
Fix for index.php committed: https://github.com/fuel/fuel/commit/e6237ba66444818adb2434c50b5951502baa1696

**Comment by WanWizard** [comment]
p.s. if you don't use those placeholders in your app, for performance reasons it's best to remove it completely, and only leave the `$response->send(true);`.

**Comment by leemason** [comment]
perfect, amazing fix times, definatley will be looking forward to 2.0.

was inbetween laravel and fuel but this has me definatley in the fuel camp.

im in dev right now, so yes will rember to remove the code when live.

maybe for 2.0 there should be a config setting for turning this off as well (before the replace happens) (or just use the env setting to use it).

**Comment by WanWizard** [comment]
I think that entire block should be removed. If you want stuff like that in your output, you should add it yourself. Most people remove it, it's only there because the welcome controller was created 3 years ago with this in it...

**Comment by it-can** [comment]
I see that in the public/index.php the section for VENDORPATH is missing?

```
/**
 * Path to the vendor directory.
 */
define('VENDORPATH', APPPATH . 'vendor/'.DIRECTORY_SEPARATOR);
```

**Comment by WanWizard** [comment]
Afaik it has never been present. 

It is only needed if you decide to move your composer vendor path to another location, like you do in this example (by default 'vendor' is in COREPATH, not APPPATH).

**Comment by it-can** [comment]
aah ok... ;-) Thanks
