### ISSUE TITLE
\Request::$main doesn't store first request if _404_ route

### ISSUE THREAD

**Issue by feldsam** [fuel/core#1547]
Hello, version 1.7 has problem with storing main request. So I cant get original uri. I always get rewritet uri, which is useless for handling _404_ routes.

**Comment by WanWizard** [comment]
No, it doesn't.

The 404 route is processed in your index.php, after the original request was terminated. So a 404 request is a NEW main request, not an secondary or HMVC request.

This was changed in 1.7, in previous versions it was seen as a secondary request, which is wasn't, and caused all HMVC aware controllers (that work only on secondary requests) to crash.

You can access the original Uri via `\Input::uri()`.

**Comment by feldsam** [comment]
Thanks for help
