### ISSUE TITLE
Input Params remove "+" from variable

### ISSUE THREAD

**Issue by dercoder** [fuel/core#1551]
I want to submit the date using GET method but the "+" will be removed from variable.
Example

Request:
http://www.example.com/?test=123%2B123+2

Response: var_dump(\Input::get());
array (size=1)
  'test' => string '123 123 2' (length=9)

Request:
http://www.example.com/?date=2004-02-12T15:19:21+02:00

Response: var_dump($_GET);
array (size=1)
  'date' => string '2004-02-12T15:19:21 02:00' (length=25)

I also tried to disable the filters but nothing worked

**Comment by WanWizard** [comment]
You can't put a + in the URL, you need to urlencode that. A plus in the URL will be converted to a space by the webserver, it's a reserved character: http://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters

**Comment by dercoder** [comment]
See my example:

Request:
http://www.example.com/?test=123%2B123+2

Response: var_dump(\Input::get());
array (size=1)
'test' => string '123 123 2' (length=9)

%2B is also not working

When i create a standard php file without using fuelphp i will get this result:
array (size=1)
'test' => string '123+123+2' (length=9)

**Comment by WanWizard** [comment]
Hmm... Now that's odd. What webserver are you using?

Can you dump $_SERVER at the top of your index.php, and email it to me at wanwizard<at>fuelphp.com, so I can see where it goes wrong?

**Comment by dercoder** [comment]
Sure, I am using Nginx. I will send send you all informations asap

**Comment by WanWizard** [comment]
Thanks. I have a feeling Apache doesn't decode the REQUEST_URI, and nginx does...

**Comment by WanWizard** [comment]
Gets weirder: `http://www.example.com/welcome/index/?test=123%2B123+2` works fine.

**Comment by WanWizard** [comment]
I think I found and fixed this issue. But your second result (in plain PHP) is odd though. You should get:

array (size=1)
'test' => string '123+123 2' (length=9)

because the + is a reserved character in the query string, and translates to a space. 

Reading up on it, it seems that Nginx encodes the query string if you're not careful in your rewrite rules, changing the + into a second %2B, so it turns up as a second + in PHP, instead of a space. I also find it may need "fastcgi_split_path_info" to deal with this.

I think you need to tweak your Nginx config to that a plain php test returns the result above.

**Comment by dercoder** [comment]
It worked before in FuelPHP 1.6.1 and also now in plain PHP
Here are all my informations

Nginx: 1.2.1
PHP: PHP 5.5.3
FuelPHP: 1.7

----- FUEL PHP 1.7 -----
Array
(
    [USER] => www-data
    [HOME] => /var/www
    [FCGI_ROLE] => RESPONDER
    [SCRIPT_FILENAME] => /var/www/api/public//index.php
    [FUEL_ENV] => development
    [QUERY_STRING] => date=2013-10-17T22:09:24+00:00
    [REQUEST_METHOD] => GET
    [CONTENT_TYPE] => 
    [CONTENT_LENGTH] => 
    [SCRIPT_NAME] => /index.php
    [REQUEST_URI] => /?date=2013-10-17T22%3A09%3A24%2B00%3A00
    [DOCUMENT_URI] => /index.php
    [DOCUMENT_ROOT] => /etc/nginx/html
    [SERVER_PROTOCOL] => HTTP/1.1
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_SOFTWARE] => nginx/1.2.1
    [REMOTE_ADDR] => ********
    [REMOTE_PORT] => 54466
    [SERVER_ADDR] => ********
    [SERVER_PORT] => 80
    [SERVER_NAME] => ********
    [REDIRECT_STATUS] => 200
    [HTTP_HOST] => ********
    [HTTP_CONNECTION] => keep-alive
    [HTTP_CACHE_CONTROL] => max-age=0
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.69 Safari/537.36
    [HTTP_ACCEPT_ENCODING] => gzip,deflate,sdch
    [HTTP_ACCEPT_LANGUAGE] => de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
    [HTTP_COOKIE] => connect.sid=s%3Aw%2FV7gxuUh7YNqnc2iJW0UAGS.2mbNhlw427sCySIPQR9744R6TcdoOIr342yAKy%2FXHKw
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1382047849.4647
    [REQUEST_TIME] => 1382047849
)

Request: /?date=2013-10-17T22%3A09%3A24%2B00%3A00
Response: Array ( [date] => 2013-10-17T22:09:24 00:00 )

----- PLAIN PHP -----
Array
(
    [USER] => www-data
    [HOME] => /var/www
    [FCGI_ROLE] => RESPONDER
    [SCRIPT_FILENAME] => /var/www/api/public//test.php
    [FUEL_ENV] => development
    [QUERY_STRING] => date=2013-10-17T22%3A09%3A24%2B00%3A00
    [REQUEST_METHOD] => GET
    [CONTENT_TYPE] => 
    [CONTENT_LENGTH] => 
    [SCRIPT_NAME] => /test.php
    [REQUEST_URI] => /test.php?date=2013-10-17T22%3A09%3A24%2B00%3A00
    [DOCUMENT_URI] => /test.php
    [DOCUMENT_ROOT] => /etc/nginx/html
    [SERVER_PROTOCOL] => HTTP/1.1
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_SOFTWARE] => nginx/1.2.1
    [REMOTE_ADDR] => ********
    [REMOTE_PORT] => 54493
    [SERVER_ADDR] => ********
    [SERVER_PORT] => 80
    [SERVER_NAME] => ********
    [REDIRECT_STATUS] => 200
    [HTTP_HOST] => ********
    [HTTP_CONNECTION] => keep-alive
    [HTTP_CACHE_CONTROL] => max-age=0
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.69 Safari/537.36
    [HTTP_ACCEPT_ENCODING] => gzip,deflate,sdch
    [HTTP_ACCEPT_LANGUAGE] => de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
    [HTTP_COOKIE] => connect.sid=s%3Aw%2FV7gxuUh7YNqnc2iJW0UAGS.2mbNhlw427sCySIPQR9744R6TcdoOIr342yAKy%2FXHKw
    [PHP_SELF] => /test.php
    [REQUEST_TIME_FLOAT] => 1382047994.2925
    [REQUEST_TIME] => 1382047994
)

Request: test.php?date=2013-10-17T22%3A09%3A24%2B00%3A00
Array ( [date] => 2013-10-17T22:09:24+00:00 )

**Comment by dercoder** [comment]
In FuelPHP i have tried $_GET and Input::get(). Its always the same result

**Comment by dercoder** [comment]
I see that FuelPHP convert the QUERY_STRING

FUELPHP: [QUERY_STRING] => date=2013-10-17T22:09:24+00:00
PLAINPHP: [QUERY_STRING] => date=2013-10-17T22%3A09%3A24%2B00%3A00

**Comment by dercoder** [comment]
Your commit (https://github.com/fuel/core/commit/43705ba1402327dcaa5e8420a0c5331008a22007) works fine

**Comment by WanWizard** [comment]
Ok, thanks for the feedback.

**Comment by it-can** [comment]
this seems to cause some issues for me...

using nginx and I rewrite a url like this, it will throw a 404 error, seems to work correct in 37fd6789e6abb55f6affc801e0d82339c119ef0c

```
	location = /test.php
	{
	    set $request_url /test$is_args$args;
	    try_files $uri $uri/ /index.php$is_args$args;
	}

	location ~ ^/index.php$
	{
	    fastcgi_param REQUEST_URI $request_url;
	    fastcgi_param FUEL_ENV production;
	    fastcgi_pass php;
	}
```

**Comment by WanWizard** [comment]
Can you dump QUERY_STRING, REQUEST_URI, SCRIPT_NAME and PATH_INFO from $_SERVER at the start of your index.php for me, so I can check what goes wrong?

I remember this QS jugling was added for nginx, but I don't have it handy to test at the moment.

**Comment by it-can** [comment]
Ok this is weird, tested now and it seems to work again with the latest version... I was getting a 404 error, but now a 200... Will keep an eye out

**Comment by it-can** [comment]
It seems to be a problem with non-encoded slashes...

I have values in my GET parameter like this:

```
date=2017/04/11&time=11:24:03
```

It works on an older version of FuelPHP but not on the latest, and I have no way to encode the parameters (signal comes from a external device)

**Comment by JefferyHus** [comment]
Just in case guys you are coming alongside such a pain issue, try to base64 what cause you a problme then inside your controller you decode it, this way you will overcome this problem till @WanWizard fixes it or someone else.

**Comment by WanWizard** [comment]
I can't test it until I have a reply on my question from yesterday.

@it-can can you get me the $_SERVER variables from a request that goes wrong?

**Comment by it-can** [comment]
@WanWizard here you go

````
["REQUEST_URI"]=> string(210) "/test?date=2017/04/11&time=10:21:50"

["QUERY_STRING"]=> string(204) "date=2017/04/11&time=10:21:50"

["SCRIPT_NAME"]=> string(10) "/index.php"

["PATH_INFO"]=> string(0) ""
````

on the latest version this will trigger a 404, on older versions a 200

**Comment by WanWizard** [comment]
@it-can Thanks. This should fix your issue while keeping the other cases fixed too.

**Comment by it-can** [comment]
@WanWizard will test asap

**Comment by it-can** [comment]
@WanWizard seems to work as far as I can test...

**Comment by WanWizard** [comment]
Cool, thanks for the feedback!
