### ISSUE TITLE
POST with Controller_Rest

### ISSUE THREAD

**Issue by ahanden** [fuel/core#1552]
Whenever I have a form that sends data via POST to a rest controller, nothing is returned: no errors, no text, nothing.

This is beyond simply not getting anything when I try to use Input::post('foo');. Any rest controller, whether it uses POST data or not, will not reply if I send it anything by POST.

**Comment by WanWizard** [comment]
What kind of reply are you expecting? What code have you written that produces that reply?

**Comment by WanWizard** [comment]
Closed due to no response. 

Please re-open if you have details we can use to reproduce your problem.
