### ISSUE TITLE
Upload class with strange behavoir

### ISSUE THREAD

**Issue by MeySolution** [fuel/core#1554]
Good evening folks,

Today i've noticed a strange behavoir in the Upload-Class.

I use 4 Upload fields in the same page, all created by Form::file().

When proccessing these files Upload::get_files() return 8 entrys.
Two for each file i've uploaded.

To make it way more strange:
The access by Upload::get_files($key) works only with the last occurens of every file.
Saving only with the first.

I'm strugeling with this for hours without finding anything.

Any ideas?

**Comment by kenjis** [comment]
How about this?

> Caution: if you intend to call Upload::process() manually, make sure auto_process is set to false. If not, the uploaded files will be processed twice with duplicate file entries as a result.
> http://fuelphp.com/docs/classes/upload/config.html

**Comment by MeySolution** [comment]
Shame on me....
I'll check this later and - if it works - close this issue
