### ISSUE TITLE
image driver : scope and call_fuel_func_array()

### ISSUE THREAD

**Issue by emarguin** [fuel/core#1556]
It seems that there is a bug when using image manipulation in Fuel 1.7
Indeed the run_queue calls call_fuel_func_array (contained in base.php) to run every operations (example : _crop_resize).
But theses functions are protected -> problem with scope, base.php don't inherit from imagedriver...
We get then the following error : 

ErrorException [ Fatal Error ]:
Call to protected method Fuel\Core\Image_Driver::_crop_resize() from context ''

**Comment by WanWizard** [comment]
This has already been fixed in 1.8/develop, and will be part of the 1.7.1 maintenance release. If you can't wait for that, backport the file from the 1.8/develop repository.
