### ISSUE TITLE
Undefined Offset Exception in call_fuel_func_array() When Calling Request::execute() Associative Array Params

### ISSUE THREAD

**Issue by johnatron** [fuel/core#1562]
On 1.7/master

Receive ‘Undefined offset’ exception when calling the execute() method on a Request object with an associative array as the method parameters. (Making HMVC request to Hybrid controller). From the docs:

Request::forge('mymodule/mycontroller/mymethod/parms', false)->execute(array('tree'=>'apple'));

It looks like it chokes in core/base.php in call_fuel_func_array().

For example, in call_fuel_func_array(), ~ Line 431:

return $instance->$method($args[0]);

expects and indexed array not an associative array.  To get the example above to work the call has to be:

Request::forge('mymodule/mycontroller/mymethod/parms', false)->execute(array('apple'));

**Comment by WanWizard** [comment]
Can you give a stack trace? There is nu call_fuel_func_array() in Request::execute().

I tried to reproduce it in an existing application, but no errors here.

**Comment by johnatron** [comment]
Stack trace screenshot attached.  Sample code below.  Thank you.

class Controller_Test extends Controller_Hybrid
{
    public function action_index()
    {
        $this->template->content = Request::forge('test/test', false)->execute(array('name' => 'World'));
    }

```
public function action_test($name = null)
{
    if (!Request::is_hmvc()) {
        throw new \HttpNotFoundException();
    }

    return Response::forge("<p>Hello, $name</p>");
}
```

}

![issue_1562_stacktrace](https://f.cloud.github.com/assets/2894032/1466270/b43327c6-456e-11e3-89d1-b819d16e5550.png)
