### ISSUE TITLE
Database alias is prefixed bug

### ISSUE THREAD

**Issue by byazrail** [fuel/core#1567]
Click for details relevant to the subject;

http://fuelphp.com/forums/discussion/comment/15936

**Comment by WanWizard** [comment]
I've looked into it, but although it might solve your particular problem, this doesn't solve THE problem. It creates one.

Issue is that if in quote_identifier() you get a string "this.that", can you tell that "this" is a table name (which should be prefixed) or an alias (which should not be prefixed)? Problem is, you can't, so the solution that was implemented is to prefix both.

**Comment by sjamaan** [comment]
Like I mentioned elsewhere, I think quoteIdentifier is overly complex, because it is trying to do too many things at once. Simplifying it should also reduce the number of weird edge cases.
