### ISSUE TITLE
Form::select() $values ignores 0 and '0'

### ISSUE THREAD

**Issue by dercoder** [fuel/core#1578]
The selected value will be ignored when 0 (Integer) or "0" (String) in FuelPHP 1.7

Example 1:
echo Form::select('status', 1, array(1 => 'Active',0 => 'Inactive'));

< select name="status" id="form_status">
    < option value="1" selected="selected">Active< /option >
    < option value="0">Inactive< /option >
< /select >

Example 2:
echo Form::select('status', 0, array(1 => 'Active',0 => 'Inactive'));

< select name="status" id="form_status">
    < option value="1">Active< /option >
    < option value="0">Inactive< /option >
< /select >

**Comment by WanWizard** [comment]
Please check the current development code before opening a new issue.

This has been fixed here: https://github.com/fuel/core/commit/7335a61b51ffab93d8cedec96bb642d92e5552a2.
