### ISSUE TITLE
Asset favicon support

### ISSUE THREAD

**Issue by dercoder** [fuel/core#1579]
It would be nice to set a favicon path for automatic html rendering.

when i use Asset::css('favicon.ico', array('rel' => 'shortcut icon'));

< link rel="shortcut icon" type="text/css" href="/themes/default/assets/css/favicon.ico?1372950621" / >

It's not possoble to remove or change the "type". Also when i want use other favicon types: png, jpeg, gif

See: http://www.kevinleary.net/cross-browser-favicons/

**Comment by WanWizard** [comment]
doesn't

```
Asset::css('favicon.png', array('type' => 'image/png', 'rel' => 'icon'));
```

work?

**Comment by WanWizard** [comment]
now it should ;)

**Comment by dercoder** [comment]
Returns: < link type="text/css" rel="icon" href="favicon.ico" / >

**Comment by WanWizard** [comment]
just fixed that ;)

**Comment by dercoder** [comment]
Thx :) It's working now
