### ISSUE TITLE
Config::load() with $reload = true fails with OpCache (PHP 5.5)

### ISSUE THREAD

**Issue by Savageman** [fuel/core#1580]
Because the file is cached by the OpCache native extension, loading it multiple times in a single execution won't reflect the config modifications done using Config::save().

**Comment by WanWizard** [comment]
Hmm... 

So Opcache suffers from the same problem as APC: it doesn't check for changed files. Which also means never to use it in development, because like with APC, PHP will crash on a changed class ?

**Comment by Savageman** [comment]
It does check for changed files, but not in the same request. Or maybe it does, but the mtime() is the same (the script runs in under a second).

I have no idea about the crash on a changed file.

This is how we fixed it for now: https://github.com/novius-os/core/blob/1932a32ad3fd25f2d4d23b6034b958f7cc7b0c4c/framework/classes/fuel/config/php.php

**Comment by WanWizard** [comment]
APC does sometimes, not so much experience with Opcache yet.

Why invalidate if it hasn't changed? I personally would invalidate in save(), so that you only flush the cache if it really has been changed.

**Comment by WanWizard** [comment]
Just a question, why the reload? If you have saved the config in a request, the changes will be in memory (Fuel v1 has a global config), so I don't see a need to force a reload of something you already have?

**Comment by Savageman** [comment]
We extended load_file() because save() was much harder to extend, since we need to recompute the file name manually :/ 
The reload is here to ensure fresh data because the content of our file has changed. Config::save() would do the job just the same, but was just harder to extend.
We know about Config::set() but we use it in a generic code which can read / write the file several times, we're not going to change it.

**Comment by Savageman** [comment]
Meh. We had to extend Config_Php::save() eventually, because several request in the same time frame also had the problem.

Process 1 loads config.php and Opcache stores it into the cache.
Process 1 overwrites config.php (without clearing the opcache).
Process 2 then loads config.php and we get the old content...

By modifying save() the cache is properly cleared and we get the correct value in Process 2.

**Comment by sagikazarmark** [comment]
Any update on this? Can this be part of the core or I have to extend the config class?

**Comment by Savageman** [comment]
If you want to extend the config class, you copy this file:

https://github.com/novius-os/core/blob/16ccb2eb54f146d93b44868e59e524dec9331e88/framework/classes/fuel/config/php.php
