### ISSUE TITLE
DB reconnect and $attempts = 3

### ISSUE THREAD

**Issue by huglester** [fuel/core#1583]
Hello,

This is a nice feature to have, that DB automatically tries to reconnect, but what if we want this limit to be something like 99999? 

What I am talking about is here: 
https://github.com/fuel/core/blob/14b625c758dd5b66945e2e39738c8534081021a4/classes/database/pdo/connection.php#L208-L237

we tried something like:

``` php
Database_Connection::instance()->connect();
$query->execute();
Database_Connection::instance()->disconnect();
```

but we still hit the limit, when importing 10k images + resizing them.

it would be nice to have some way to reset this counter

Thank you

**Comment by frankdejonge** [comment]
@huglester apart from this issue ... it might be worth wile to check why your database server is so unstable?

**Comment by huglester** [comment]
well everythign is ok with db. but some configurations have smth like: 

disconnect user from sql server when idle for 10 minutes.

What if my php process is running for 30minutes or so?

Maybe there is at least some way to 'reconnect' manually? 

so I do foreach and reconnect() before each DB communication

Thank you

**Comment by WanWizard** [comment]
This is caused by the DB connect() method wiping the username and password after connect, which causes all reconnect attempts to fail. I don't see an immediate reason for removing the password from the config property, I'll remove the unset(), which should fix this issue.
