### ISSUE TITLE
Bug in Model_Crud::__isset on 1.8/develop.

### ISSUE THREAD

**Issue by yuya-miyake** [fuel/core#1593]
```
 public function __isset($property)
 {
     return isset($this->_data[$data]);
 }
```

should be

```
 public function __isset($property)
 {
     return isset($this->_data[$property]);
 }
```

**Comment by frankdejonge** [comment]
@yuya-miyake thanks, by mad :-1:

**Comment by it-can** [comment]
I get this error when testing

PHP Fatal error:  Namespace declaration statement has to be the very first statement in the script in /fuel/core/classes/model/crud.php on line 14

Fatal error: Namespace declaration statement has to be the very first statement in the script in /fuel/core/classes/model/crud.php on line 14
Compile Error - Namespace declaration statement has to be the very first statement in the script in COREPATH/classes/model/crud.php on line 14

**Comment by frankdejonge** [comment]
@IT-Can corrected, thanks!

**Comment by it-can** [comment]
No problem ;-)
