### ISSUE TITLE
Format class issue

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#1594]
The commit ff3acd7e711f08e13fab6ade085167d29fe7188c introduced an issue because the old config values are being used as defaults to the new config values, even though the new config values are specified in the core config.

This should have worked the other way around.

It's probably not so much of an issue as it's been in there for a while, though we've just noticed because an old site was just upgraded.

**Comment by WanWizard** [comment]
You do have a point, for a proper fallback it should be the other way around.
