### ISSUE TITLE
Error with a float value on Image::resize()

### ISSUE THREAD

**Issue by SRWieZ** [fuel/core#1599]
When I try to resize a image with this line :

``` php
Image::load($path)->resize($size[0], null, false)->save_pa('', $sizedname);
```

I got this error :

Notice - A non well formed numeric value encountered in [...]/fuel/core/classes/image/gd.php on line 438

I temporary corrected the problem by adding intval() on image/driver.php in lines 267 and 271 :

``` php
$sizes = $this->sizes();
if ($height == null and $width != null)
{
    $height = intval($width * ($sizes->height / $sizes->width));
}
elseif ($height != null and $width == null)
{
    $width = intval($height * ($sizes->width / $sizes->height));
}
else
{
    throw new \InvalidArgumentException("Width and height cannot be null.");
}
```

But i'm sure you have a better solution to this problem.

**Comment by WanWizard** [comment]
On all fields that should be an integer convert_number() is called, for width and height at #L280. So I think you need to figure out why that doesn't do it's job in your case. 

You are on the latest version (1.7.1+)?

**Comment by SRWieZ** [comment]
I just updated and it seems to be resolved.
Sorry, i close this issue.
