### ISSUE TITLE
Request CURL on custom "Accept" header auto_format is not working

### ISSUE THREAD

**Issue by dercoder** [fuel/core#1600]
When i set the custom "Accept" Header for a Curl Request the auto_format function will not work and return an string instead of array

Example:

```
$curl = \Request::forge('http://example.com/test.json', 'curl');
$curl->set_method('get');
$curl->set_mime_type('json');
$curl->set_auto_format(true);
$curl->set_option(CURLOPT_HEADER, 1);
$curl->set_header('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8');
$curl->execute();

print_r($curl->response());
```

Response should be 

```
Fuel\Core\Response::__set_state(array(
   'status' => 200,
   'headers' =>
  array (
    'Server' => 'nginx',
    'Date' => 'Thu, 12 Dec 2013 13:45:09 GMT',
    'Content-Type' => 'application/json',
    'Transfer-Encoding' => 'chunked',
    'Connection' => 'keep-alive',
    'Vary' => 'Accept-Encoding',
    'X-Powered-By' => 'PHP/5.5.6-1~dotdeb.1',
    'Access-Control-Allow-Origin' => '*',
    'Access-Control-Allow-Methods' => 'POST, GET, PUT, DELETE',
    'Access-Control-Allow-Headers' => 'x-prototype-version, x-requested-with',
    'X-UA-Compatible' => 'IE=Edge,chrome=1',
  ),
   'body' =>
  array (
    'success' => true,
    'result' => 'json',
  ),
))
```

But it returns

```
Fuel\Core\Response::__set_state(array(
   'status' => 200,
   'headers' =>
  array (
    'Server' => 'nginx',
    'Date' => 'Thu, 12 Dec 2013 13:45:21 GMT',
    'Content-Type' => 'application/json',
    'Transfer-Encoding' => 'chunked',
    'Connection' => 'keep-alive',
    'Vary' => 'Accept-Encoding',
    'X-Powered-By' => 'PHP/5.5.6-1~dotdeb.1',
    'Access-Control-Allow-Origin' => '*',
    'Access-Control-Allow-Methods' => 'POST, GET, PUT, DELETE',
    'Access-Control-Allow-Headers' => 'x-prototype-version, x-requested-with',
    'X-UA-Compatible' => 'IE=Edge,chrome=1',
  ),
   'body' => '{"success":true,"result":"json"}',
))
```

In Request\Curl::execute() i have found this:

```
$mime = isset($this->headers['Accept']) ? $this->headers['Accept'] : $this->response_info('content_type', 'text/plain');
```

It's using the "Accept" header but thats not correct

**Comment by WanWizard** [comment]
Your code clearly states in the Accept that you want "text/html" returned, which is a string. And you're getting a string back. So what is the problem?

If you specify your accept header as "application/json", you'll see you will get your array returned. Or do not specify an Accept header, in which case the returned content-type will determine the type of the return value.

**Comment by dercoder** [comment]
I need for an external API to set the "Accept" headers of the current browser.

```
$curl->set_header('Accept', \Input::server('HTTP_ACCEPT'));
```

So auto_format will not work

**Comment by WanWizard** [comment]
In that case you'll have to do a manual json_decode() on the string returned, or use

```
$json = Format::forge($yourbody, 'json')->to_array();
```

**Comment by dercoder** [comment]
Ok, but i think that it makes sense to support W3 specifictions
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

The media type quality factor associated with a given type is determined by finding the media range with the highest precedence which matches that type. For example,

```
   Accept: text/*;q=0.3, text/html;q=0.7, text/html;level=1,
           text/html;level=2;q=0.4, */*;q=0.5
```

would cause the following values to be associated:

```
   text/html;level=1         = 1
   text/html                 = 0.7
   text/plain                = 0.3
   image/jpeg                = 0.5
   text/html;level=2         = 0.4
   text/html;level=3         = 0.7
  Note: A user agent might be provided with a default set of quality
  values for certain media ranges. However, unless the user agent is
  a closed system which cannot interact with other rendering agents,
  this default set ought to be configurable by the user.
```

**Comment by WanWizard** [comment]
You have a point there, but that doesn't solve your problem, since application/json is not in that list.

**Comment by dercoder** [comment]
Thats right. I will use your workaround now and maybe you will add the W3 specification sometimes :)

**Comment by WanWizard** [comment]
Then we should leave this issue open. ;)

**Comment by WanWizard** [comment]
@DerCoder, I've been looking at this again, but I'm not sure what it is exactly what you want, and why you want it.

You're passing the accept header of the current request (i.e. browser -> application) to th cURL request (application -> REST endpoint). I can sort of understand this (if your client want json you want to tell the REST endpoint you want json too),  but what is the relation to the W3 spec?

**Comment by dercoder** [comment]
For example if i want to use FuelPHP as an proxy service. 
Client sends request to Server (FuelPHP) and will submit this Information to an other API and then all the way back. So the Client can decide how he wants the data back (json, xml, ...)

**Comment by WanWizard** [comment]
I understand that use case.

I looked into the code. What it does, is:
- if you have defined an accept header for the request, it will use the mime type defined
- if you haven't, it will use the mime type of the response returned

If you have enabled "auto format", this mime type will be used to format the response, if a valid mime time can be found.

Problem here is that the accept header you set contains an entire list of mime types, causing the match to fail, and the response not to be formatted. Even if you had added "application/json" to the list, it would not have worked. How do you suggest to address this?

**Comment by dercoder** [comment]
I think it should work like this

Example:
Request text/xml;q=0.0, application/json:g=0.7

If auto format is enabled and server supports json
it will return a json string
else if auto format is enabled and server supports xml
it will return a xml string
else if auto format is enabled and server supports nothing of both and maybe return text/html
an exception should be throwed

**Comment by WanWizard** [comment]
That is not how it works. If that is the request header going to your code and passed on to the REST service, the return value could be text/xml or application/json. Or something else.

The problem is, the return value from the cURL call is always a string. If auto format is on, how would the code know what it represents? If the REST service if free to decide what to return?

**Comment by dercoder** [comment]
The same how it works now: 
"I looked into the code. What it does, is: if you haven't, it will use the mime type of the response returned"

**Comment by WanWizard** [comment]
That is not possible, because you have potentionally an entire list of mime types. 

It would have to explode the accept header; loop over all of them in order of priority; try a format of the received body; check if that went ok; if not try the next one...

That would make it quite slow, and a result is not guaranteed, unless you do real deep validation.

**Comment by dercoder** [comment]
But you will receive the Content-Type from cURL response 

```
$mime = isset($this->headers['Accept']) ? $this->headers['Accept'] : $this->response_info('content_type', 'text/plain');
```

so you only have to use always the response Content-Type and 
maybe you should throw an exception if auto format is on and mime is not supported

```
if ($this->auto_format and array_key_exists($mime, static::$auto_detect_formats))
{
     $body = \Format::forge($body, static::$auto_detect_formats[$mime])->to_array();
}
```

**Comment by WanWizard** [comment]
Not if an accept header is set, that is the point. That code will only fetch the content-type from the response if NO accept header was set. 

The assumption here was that you would set a single accept header, to force the REST service to return that content-type. You set an entire list of acceptable mime types.

Perhaps change that code to only use the Accept header if it contains a single mime type?

**Comment by dercoder** [comment]
Yes, currently the code will only fetch the Content-Type if Accept header was not set. Thats why i told you this part must be changed.

This "Perhaps change that code to only use the Accept header if it contains a single mime type?" will work but why do you dont use **always** the response Content-Type? 
Do you think the Server will send a json string but a **wrong** Content-Type?

**Comment by WanWizard** [comment]
Technically, if you would say "I accept text/xml" and the server returns "application/json", the response should be discarded.

so:
- always fetch the returned content-type into the mime type
- check if auto format is enabled, if not, do nothing
- if enabled, check if there was an accept header
- if not, use the content-type to auto format
- if present, check if the content-type returned is in the accepted list
- if not, throw an exception
- it so, auto format the response

Is this the correct flow?

**Comment by dercoder** [comment]
Yes correct

**Comment by WanWizard** [comment]
Ok, cool, I'll have a look at it.

**Comment by WanWizard** [comment]
Slightly modified the flow. I think that if an accept header is specified, the returned content type must ALWAYS be validated against the accept header. Whether you're auto formatting or not.

Can you check if this works for you?

**Comment by dercoder** [comment]
The code looks good for me. I will test it later ;)

**Comment by WanWizard** [comment]
To late, it's now part of 1.7.2. Still appreciate your feedback though, if it doesn't work it needs to be fixed.

**Comment by dercoder** [comment]
OK

**Comment by WanWizard** [comment]
Closed because of no further response.
