### ISSUE TITLE
Cannot load current language file in autoload when changed current language by use Config::set();.

### ISSUE THREAD

**Issue by ve3** [fuel/core#1604]
In **/fuel/app/config/config.php** file
Default language : 'en'
Fallback language : 'en'

Autoload language file is 'fslang'

``` php
'always_load'  => array(
    'language'  => array('fslang' => 'fslang'),
),
```

By default, in the controller when i use `echo \Lang::get('fslang.fslang_test');` it returns 'test' message in english.

``` php
public function action_index() 
{
    echo \Lang::get('fslang.fslang_test'); // return test.
}
```

But when i change language using `\Config::set('language', 'th');` before call the language. (Thai language) it returns **nothing**. Thai translation was exists and has language array already.

``` php
public function action_index() 
{
    \Config::set('language', 'th');
    echo \Lang::get('fslang.fslang_test'); // return empty nothing.
}
```

If i changed language and load 'fslang' again everything works fine.

``` php
public function action_index() 
{
    \Config::set('language', 'th');
    \Lang::load('fslang', 'fslang');
    echo \Lang::get('fslang.fslang_test'); // return ทดสอบ.
}
```

**Comment by WanWizard** [comment]
Which is "as designed". 

Language files are only loaded for the current active language. There is no mechanism to automatically reload language files when you switch languages.
