### ISSUE TITLE
REST controller DIGEST auth doesn't accept string parameters containing commas

### ISSUE THREAD

**Issue by okhayat** [fuel/core#1607]
I setup a REST with config/rest.php:

``` php
return array(
    'default_format' => 'json',
    'xml_basenode' => 'xml',
    'realm' => 'MY API',
    'auth' => 'digest',
    'valid_logins' => array('login' => 'pass'),
    'ignore_http_accept' => true,
);
```

Everything works fine on my local setup (PHP 5.5.3 and Apache 2.4)

Moving the code to another server (PHP 5.3.8 and Apache 2.2) I face two issues:
1. When passing a parameter like (ids=1,2,3,4) authentication fails. Basic auth works fine. Also, using encoded string works fine with digest auth.
2. Digest auth doesn't work! It doesn't accept the username/password. Though changing it to 'basic' works fine

**Comment by WanWizard** [comment]
Odd that you have a working environment somewhere. The code contains a regex to split the digest response that simply terminates on the first comma detected, so it should fail on all platforms.

**Comment by okhayat** [comment]
Sorry, I must have mixed up the issues.
DIGEST Auth doesn't work at all when tested on PHP 5.3.8, though BASIC works
The comma issue is on all platforms

**Comment by WanWizard** [comment]
Thought so. ;) Fixed.

**Comment by okhayat** [comment]
Ok.. the comma issue is fixed ;)
But DIGEST still fails on 5.3.8
Need me to open a new issue?

**Comment by WanWizard** [comment]
Yes please. 

But there might be some local debugging needed, as I don't have 5.3.8 here, and I can't reproduce it.
