### ISSUE TITLE
Pagination querystring not valid html.

### ISSUE THREAD

**Issue by ve3** [fuel/core#1608]
I have current URL like this..
1. `http://localhost/public/view-logins?orders=login_ua&sort=ASC&q=find%E0%B9%84%E0%B8%97%E0%B8%A2&filter=aaa`
2. `http://localhost/public/view-logins?orders=login_ua&amp;sort=ASC&amp;q=find%E0%B9%84%E0%B8%97%E0%B8%A2&amp;filter=aaa`

One is raw ampersand (&) 
Two is html valid ampersand (`&amp;`)

I generate pagination with this code.

``` php
$config['pagination_url'] = \Uri::main() . \Uri::getCurrentQuerystrings(true, false);
$config['total_items'] = $list_logins['total'];
$config['per_page'] = $option['limit'];
$config['uri_segment'] = 'page';

$pagination = \Pagination::forge('viewlogins_pagination', $config);
```

---

If i generate pagination with **1st** choice URL. It will become like this...

```
http://localhost/public/view-logins?orders=login_ua&sort=ASC&q=find%E0%B9%84%E0%B8%97%E0%B8%A2&filter=aaa&page=2
```

It is not valid html escape. (`&` should be `&amp;`)
validated from w3 validator

---

If i generate with **2nd** choice URL. It will become like this...

```
http://localhost/public/view-logins?orders=login_ua&amp%3Bsort=ASC&amp%3Bq=find%E0%B9%84%E0%B8%97%E0%B8%A2&amp%3Bfilter=aaa&page=2
```

It is not valid html too. (`&amp%3B` should be `&amp;`)

**Comment by WanWizard** [comment]
Using &amp; in a URL is invalid, since the & has special meaning. 
If you really want HTML in the URL, you need to urlencode it.

Pagination uses parse_url() and http_build_query(), which gets hopelessly confused if you feed it an invalid URL.

See http://www.htmlhelp.com/tools/validator/problems.html#amp

```
When writing the same URL in a plain text email message or in the location bar of your browser,
you would use "&" and not "&amp;". With HTML, the browser translates "&amp;" to "&" so the
Web server would only see "&" and not "&amp;" in the query string of the request.
```

**Comment by ve3** [comment]
I need to use querystring in the URL.
My URL is like this.. http://localhost/public/view-logins?orders=login_ua&sort=ASC&q=find%E0%B9%84%E0%B8%97%E0%B8%A2&filter=aaa

This is the URL in web browser address.
**I want pagination after those querystring.**

My code is...

``` php
$config['pagination_url'] = 'http://localhost/public/view-logins?orders=login_ua&sort=ASC&q=find%E0%B9%84%E0%B8%97%E0%B8%A2&filter=aaa';
$config['total_items'] = $list_logins['total'];
$config['per_page'] = $option['limit'];
$config['uri_segment'] = 'page';

$pagination = \Pagination::forge('viewlogins_pagination', $config);
```

I really don't see the way FuelPHP generate correct URL in pagination links. 
As i said in the topic 
If i set pagination_url to choice 1 or choice 2 FuelPHP **never** generate valid pagination html links.

Please don't close, there still is a problem about this and can not be solved.

---

### Please try both of these code in your controller.

``` php
echo '<!DOCTYPE html>';

$config['pagination_url'] = 'http://localhost/public/view-logins?orders=login_ua&sort=ASC&q=find%E0%B9%84%E0%B8%97%E0%B8%A2&filter=aaa';
$config['total_items'] = 100;
$config['per_page'] = 10;
$config['uri_segment'] = 'page';

$pagination = \Pagination::forge('viewlogins_pagination', $config);
echo $pagination->render();

echo '<br><br>';

$config['pagination_url'] = 'http://localhost/public/view-logins?orders=login_ua&amp;sort=ASC&amp;q=find%E0%B9%84%E0%B8%97%E0%B8%A2&amp;filter=aaa';
$config['total_items'] = 100;
$config['per_page'] = 10;
$config['uri_segment'] = 'page';

$pagination = \Pagination::forge('viewlogins_pagination2', $config);
echo $pagination->render();
```

Now you got generated pagination.
Copy the source code and validate html with w3 validator (http://validator.w3.org/#validate_by_input)

![fuelphp-pagination-failed](https://f.cloud.github.com/assets/1568262/1861249/aa79cbda-77bf-11e3-9b90-3e17bf0824f8.jpg)

**Comment by kenjis** [comment]
Pagination::render() returns HTML Markup for page number links. So it should return valid HTML.
If URL has `?orders=login_ua&sort=ASC`, it should return `?orders=login_ua&amp;sort=ASC`.

It seems simply forgetting HTML escaping of `href` value.

**Comment by kenjis** [comment]
@ve3 @WanWizard 
How about my fix above?

If Ok, I'll send Pull Request.

**Comment by ve3** [comment]
@kenjis 
Perfect!!

**Comment by WanWizard** [comment]
Resultwise, yes. Implementation, unfortunately not. It also has side-effects, as it encodes the entire link, which might not be desirable.

Problem is http_build_query(), which if you don't specify a separator will use the &.

**Comment by kenjis** [comment]
@WanWizard 
What's  side-effects?

Your fix returns URL with `&amp;` if we want raw data with `render(true)`. Is it Okay?

**Comment by WanWizard** [comment]
htmlentities() does a lot more than only deal with the ampersand. So potentionally you encode more than you need to (or even want to). 

Also, raw-data is about returning the pagination info in an array, so you can build something custom. In that case you also need the ampersand encoded.
