### ISSUE TITLE
Php config-> export format () modifies the content values

### ISSUE THREAD

**Issue by felixgilles** [fuel/core#1612]
This line:
https://github.com/fuel/core/blob/1.8/develop/classes/config/php.php#L35

In the `str_replace`, the two first strings to replaced are applied also on values content, not only on leading spaces (for the first case) or on array declaration (for the second).

Those two replacing are only here for styling. But this is Fuel styling. I suggest to remove those two replacing. If you're OK, I make a PR.

**Comment by WanWizard** [comment]
Perhaps it can be made more precise, so it matches only what it should match? 

For example using 'array ('.PHP_EOL ?

If there is no easy solution, the first two can go, as you said they are cosmetic only.

**Comment by WanWizard** [comment]
Fix was merged.
