### ISSUE TITLE
date::time_ago return NULL value

### ISSUE THREAD

**Issue by giangywork** [fuel/core#1619]
Hi, i have find a probabil bug on time_ago method, that return empty or NULL value on correct data input, please can verify?

**Comment by tominon** [comment]
Can you provide specific example of your input?

**Comment by giangywork** [comment]
SORRY, i have finded a "problem", if have set different language of default, and not have language file in directory, return NULL!.. sorry and escuse me for bad english, i am Italian..

**Comment by giangywork** [comment]
WOW, FuelPHP si the BEST framework in the world, and have people  that respond in a fee time.. wonderfull!
