### ISSUE TITLE
URL change of Browser Capabilities Project

### ISSUE THREAD

**Issue by wate** [fuel/core#1620]
Get URL to lite_php_browscap.ini that is currently set is out of date

old
http://tempdownloads.browserscap.com/stream.asp?Lite_PHP_BrowsCapINI

new
http://browscap.org/stream?q=Lite_PHP_BrowsCapINI

**Comment by kenjis** [comment]
The old URL stopped.
https://groups.google.com/forum/#!topic/browscap/dIc8C6GnFN4

We need new release of Fuel with updated URL.

**Comment by sjamaan** [comment]
This fix is incorrect, IMO: See #1686 for more details

**Comment by kenjis** [comment]
This fix is absolutely right. Reverting the fix makes Agent class useless.  :-)

**Comment by sjamaan** [comment]
I wasn't suggesting reverting it, but using a custom file and shipping that with the framework instead of just updating the URI and waiting for it to break yet another time.
See #1686

**Comment by kenjis** [comment]
But if upstream will change the URL, Agent class will be useless again.
If Agent class does not work, it is reasonable that the tests fails.

**Comment by sjamaan** [comment]
It will only start failing if the cached copy isn't available, and the class isn't necessarily useless: you can also use the class with a file override through a config in your application. If you're doing that, I believe the tests will still fail regardless of whether the app is broken or not.

This is a _unit test_, which should strictly be only testing the methods of the class. That's why unit tests often use a mocking framework in order to stub out network APIs or storage backends.

**Comment by kenjis** [comment]
The tests are for Fuel core, not your application. So it should fail if the function does not work, I think.

**Comment by sjamaan** [comment]
It depends on what exactly it's supposed to be testing. The functionality offered by this class is to parse a browscap file and the user-agent header, matching them up. I'd say that's what it should be testing, ideally with various differently constructed browscap files with valid and invalid syntax and various examples of user-agent headers.

The fetching of a browscap file is functionality that's really unrelated to the functioning of the class. Neither is the testing against _only that_ browscap file enough to verify correct functioning of the parser.

If you configure it to use a local browscap file, the app will work fine even without a network connection. The database tests don't run against the live database either, so why should the agent tests run against a live server? Besides, if you configure Fuel to use a browscap file from a different network resource, a successful run of the tests (which will still use the same hardcoded location) is not an indication that the real application will work, either.
