### ISSUE TITLE
File class suggestions

### ISSUE THREAD

**Issue by dercoder** [fuel/core#1621]
I think 2 Features would be nice:

1.) \File::exists() method
You have created \File::delete() so i think it would be also nice to have \File::exists()

2.) \File::download() delete argument
The file download method will exit the php request and it would be nice to set this delete parameter for temporary download files. \File::delete() is after \File::download() not possible in the same request

**Comment by WanWizard** [comment]
File::exists() I need to think about. Any reason why you want to use that instead of file_exists() or is_file()?

**Comment by dercoder** [comment]
Because this part (example delete method)
$path = rtrim(static::instance($area)->get_path($path), '\/');
