### ISSUE TITLE
[request] Theme for mobile, tablet.

### ISSUE THREAD

**Issue by ve3** [fuel/core#1624]
You already have theme, theme for modules.
Now you should have theme for mobile and tablet.

The folder structure i suggest is...
`themes/<theme_name>/<mobile> OR <tablet>/`
and there might be a folder for modules in mobile/tablet view
example 
`themes/<theme_name>/<mobile>/modules` OR
`themes/<theme_name>/<modules>/<module_name>/<mobile> OR <tablet>/`

modules inside mobile or mobile inside modules, whatever, up to you.

Some application does not fit for responsive design. It should have design for mobile or tablet access device.
This is why i ask you to have theme for mobile/tablet.

Thank you.

**Comment by WanWizard** [comment]
The descision what theme to use is application specific, it is the application that decides, based on requirements and detected environment which theme is loaded. This logic has no place in the core.
