### ISSUE TITLE
Format XML to Array

### ISSUE THREAD

**Issue by dercoder** [fuel/core#1625]
I am trying to convert this string into an array

**XML**

```
<root>
    <id>123456</id>
    <name>TestUser</name>
    <description></description>
</root>
```

**Result**

```
object(Fuel\Core\Format)#120 (1) {
  ["_data":protected]=>
  array(3) {
    ["id"]=>
    string(6) "123456"
    ["name"]=>
    string(8) "TestUser"
    ["description"]=>
    array(0) {
    }
  }
}
```

I think "description" should be "null" or an empty string instead of an empty array

**Comment by SRWieZ** [comment]
When I use REST Controller (using Array to XML) with something null, I have something like that: 

``` xml
<root>
    <id>123456</id>
    <name>TestUser</name>
    </description>
</root>
```

If you try with this string, may be you will have "description" == null

**Comment by dercoder** [comment]
I have tried 

```
$string = '<root><id>123456</id><name>TestUser</name><description></description></root>';
var_dump(\Format::forge($string, 'xml'));
```

and

```
$string = '<root><id>123456</id><name>TestUser</name><description/></root>';
var_dump(\Format::forge($string, 'xml'));
```

Both return the same result (description is an empty array)

**Comment by SRWieZ** [comment]
Too bad.

Anyway, I'm agree with you, it should be null or an empty string.
