### ISSUE TITLE
DB Builder Insert, multiple inserts 

### ISSUE THREAD

**Issue by ghost** [fuel/core#1626]
Hello.

Im on Fuel 1.7.1 stable.

what are you trying to do?  ->
Build a query inserting multiple rows in one query.

what were you expecting?
That the query was build and inserted

what are you getting instead?
A query being build wrong.

This is due to the builder function adding too many parentheses, which breaks the query.

I tracked the problem to this file: 
/fuel/core/classes/database/query/builder/insert.php, 

My workaround:
![image](https://f.cloud.github.com/assets/6609831/2104451/a738b9e4-8f7b-11e3-8ab0-0008b28366e6.png)
Current code in first square, modified code in second square.
###### 

   $groups[] = '('.implode(', ', array_map($quote, $group)).')'; - Old, broken..

.. Above is under certain curcumstances broken.. Below code mitigates this:

```
            if (isset($this->_values[0][0][0])) {
                $groups[] = '' . implode(', ', array_map($quote, $group)) . ''; //Improved

            } else
                $groups[] = '(' . implode(', ', array_map($quote, $group)) . ')'; //Default
        }
```
###### 

Running the following query fails:

$result = \DB::insert()
                    ->table('testtable')
                    ->columns(array('row1', 'row2'))
                    ->values(array(array('test' => 1, 'test2' =>2),array('test' => 3, 'test2' =>4)))
                    ->execute();

My fix is maybe not the best way to go about it :-)

Kind Regards
TwinA

**Comment by WanWizard** [comment]
Multiple inserts are not supported in the current codebase, so yes, the query will not be generated the way you want it.

**Comment by ghost** [comment]
Thank you WanWizard. I managed to fix it though, but i will keep out for any other problems in that category. Are there plans to add multi insert? If not i would like to propose it. This specifik scenario reduced the time used from 400 ms to 25, when the 37 inserts was reduced to one. And in the final solution, the code may handle as much as 2000 inserts, in one query..

**Comment by Art4** [comment]
@TwinA :+1:

**Comment by WanWizard** [comment]
No plans, most of our time goes into the v2 codebase at the moment. But feel free to send a PR.

**Comment by sjamaan** [comment]
Maybe I'm misunderstanding what you're trying to do here (I can't see any full code), but it looks like you're using a prepared statement.

Have you tried using positional inserts, like the code below?

``` php
$insert = \DB::insert('mytable', array('field1', 'field2', 'field3'));
foreach($items as $item) {
  $insert->values($item['field1'], $item['field2'], $item['field3']);
}
$insert->execute();
```

This works fine for me. We're using it at a few places in our codebase at work without problems.

**Comment by it-can** [comment]
It seems that this fix is not working for multiple inserts in 1 query.  The query fails with error "Operand should contain 1 column(s)". I use MariaDB btw.

``` sql
INSERT INTO `test` (`user_id`, `test_id`, `month`, `year`) VALUES (('5', '0', '01', '2014'), ('6', '0', '01', '2014'), ('7', '0', '01', '2014'), ('8', '7174', '01', '2014'), ('9', '220', '01', '2014'), ('10', '817', '01', '2014'), ('11', '978', '01', '2014'), ('12', '7415', '01', '2014'), ('13', '3190', '01', '2014'), ('14', '5541', '01', '2014'), ('15', '294', '01', '2014'), ('16', '108', '01', '2014'), ('17', '413', '01', '2014'), ('18', '2281', '01', '2014'), ('19', '9291', '01', '2014'), ('20', '5', '01', '2014'), ('21', '411', '01', '2014'), ('22', '9579', '01', '2014'), ('23', '9496', '01', '2014'), ('24', '12', '01', '2014'), ('25', '2099', '01', '2014'));
```

There is a double `((` that is the problem I think

**Comment by it-can** [comment]
Mmm seems I am still working with the "old" version... I'll try with the latest 1.8/develop

**Comment by it-can** [comment]
latest 1.8/develop works correct
