### ISSUE TITLE
Redis configuration parameter "database" not used

### ISSUE THREAD

**Issue by heremit** [fuel/core#1629]
"Database" parameter is mentioned in documentation http://fuelphp.com/docs/classes/redis.html but this parameter is unused in fuel/core/classes/redis/db.php
I just fixed for myself by adding code at end of __construct() function:

```
        if (!empty($config['database']) && is_numeric($config['database'])){
            $this->select($config['database']);
        }
```

**Comment by WanWizard** [comment]
It is used, here: https://github.com/fuel/core/blob/1.8/develop/classes/redis/db.php#L110
