### ISSUE TITLE
Uri::main() execution problem on HMVC request

### ISSUE THREAD

**Issue by mitsu7788** [fuel/core#1641]
\Uri::main() returns the active URI on HMVC context when main request URI is an empty string (i.e. http://mydomain/)

**Comment by codeChap** [comment]
Try: http://fuelphp.com/docs/classes/uri.html#/method_current

**Comment by WanWizard** [comment]
@mitsu7788,

Is it fixed if you change L#155 to `is_null($uri) and $uri = static::string();` ?

**Comment by mitsu7788** [comment]
@codeChap 

Thank you for your suggestion.

@WanWizard  

Yes, my problem has been resolved.

**Comment by mitsu7788** [comment]
Sorry, I found one side effect.

If form action is empty string, Form::open() doesn't generate current url.

my workaround:  form/instance.php

109 > if( ! array_key_exists('action', $attributes) or $attributes['action'] === null)

to

109> if( ! array_key_exists('action', $attributes) or $attributes['action'] === null or $attributes['action'] === '')
