### ISSUE TITLE
Form::open() : Why Uri::string() ?

### ISSUE THREAD

**Issue by jhuriez** [fuel/core#1647]
Hi,

If i do \Form::open(). By default the "action" attribute is Uri::string(), why not Uri::main() ?

I've an issue with Uri::string, for example my uri is : /backend/user/add. 

By default with Uri::string(), the action attribute will be action="backend/user/add".
If i submit my form, the uri will be : /backend/user/add/backend/user/add

**Comment by frankdejonge** [comment]
This is because the default action is to go to the same page, it's the same as no action. With uri main all the actions would go to the homepage by default, which makes no sense at all. The uri string should be prefixed with a / though. I'll fix that.

**Comment by frankdejonge** [comment]
Wait, main does that... that's confusing. I'll correct this.

**Comment by jhuriez** [comment]
Thanks :-)

**Comment by WanWizard** [comment]
My fault. Fixed.
