### ISSUE TITLE
Format from_csv function()

### ISSUE THREAD

**Issue by jhuriez** [fuel/core#1650]
Hi,

Since the commit [fixed incorrect csv parsing and generation](https://github.com/fuel/core/commit/9e36af0080048f8cffc9a8b06d80c89279edb822#diff-ffc0d74dc3c3d28d2281a4f569dc8d46)

With function preg_split instead of explode, the function doesn't get rows if the regex_newline is "\n".

With function explode, it's work fine.

```
-       $rows = explode(\Config::get('format.csv.regex_newline', "\n"), trim($string));
 +      $rows = preg_split('/(?<=[0-9'.preg_quote(\Config::get('format.csv.enclosure', \Config::get('format.csv.import.enclosure', '"'))).'])'.\Config::get('format.csv.regex_newline', "\n").'/', trim($string));
```

**Comment by jhuriez** [comment]
I've make the test with : 

CSV :

```
"prenom";"nom"
"julien";"huriez"
```

Config : 

``` php
    'csv' => array(
        'delimiter' => ';',
        'enclosure' => '"',
        'newline'   => "\n",
        'regex_newline'   => "\n",
        'escape'    => '\\',
    ),
```

**Comment by WanWizard** [comment]
Just tried that here, and I don't see a problem.

``` php
$csv = '"prenom";"nom"'."\n".'"julien";"huriez"'."\n";
\Debug::dump(\Format::forge($csv, 'csv')->to_array());
```

produces

```
Variable #1:
  (Array, 1 element) ↵
     0 (Array, 2 elements) ↵
         prenom (String): "julien" (6 characters)
         nom (String): "huriez" (6 characters)
```

which looks fine to me?

**Comment by jhuriez** [comment]
```
"prenom";"nom"
"julien";"huriez"
```

Is in a file .csv, and i load the it with file_content. I will try csv inline string (your example) monday.

**Comment by WanWizard** [comment]
``` php
$csv = file_get_contents(APPPATH.'tmp/csv.txt');
\Debug::dump(\Format::forge($csv, 'csv')->to_array());
```

returns exactly the same. Are you sure your file has \n line endings?

**Comment by jhuriez** [comment]
Yes because its work with the explode fonction. Maybe because im on windows ? I will make more tests monday

**Comment by WanWizard** [comment]
Then that might be your problem. Windows by default doesn't use \n line endings, it uses \r\n (CR+LF). 

Which explodes just fine (but leaves a \r at the end of each line). The regex however doesn't match, because it looks for "\n (enclosure + regex_newline), and that doesn't match when you have \r\n line-endings (because your lines end with "\r\n instead).

explode() is not an option, as it doesn't take enclosure into account, so it will break multi-line strings in the csv (like "A\nB\nC").

**Comment by jhuriez** [comment]
Ok thanks. You're right, it's work when i set "\r\n" in regex_newline.

I will set "\r\n" in development env, and "\n" in production env. Thanks !

**Comment by jhuriez** [comment]
Hi,

i re-open the issue.
By default, Microsoft Excel don't use enclosure for save in csv format. 

Like that : 

```
nom;prenom
HURIEZ;Julien
```

But that don't work with the Format class.
Config : 

``` php
    'csv' => array(
        'delimiter' => ';',
        'enclosure' => '',
        'newline'   => "\r\n",
        'regex_newline'   => "\r\n",
        'escape'    => '\\',
    ),
```

Any idea ?
