### ISSUE TITLE
Add a new constant for public directory

### ISSUE THREAD

**Issue by mrDlef** [fuel/core#1654]
Today like said in #1421 we have `oil` and the public `index.php` defining each the required constants.

But we have a different path for the `DOCROOT` constant. So, when using `oil`, we can't know where is the public directory.

It would be cool to have a `WEBROOT` or `PUBLICROOT` constant pointing to the public directory.

What do you think ?

**Comment by WanWizard** [comment]
This is not needed, you can just change the DOCROOT definition in the oil script as you need it.

The reason for it to point to the current directory is pretty simple. There is no way to determine the path to the public root (the directory that contains your index.php) from the oil script.
