### ISSUE TITLE
Add a value_in rule for validation

### ISSUE THREAD

**Issue by mrDlef** [fuel/core#1655]
To be able to easily test if a value is allowed by the application, we can add a rule like this `_validation_value_in($val, $values)` which test if `$val` is in `$values`.

**Comment by WanWizard** [comment]
You can create it, and send a pull request? Also remember that validation rules can be defined as string as well, so you will have to think about how to pass the list of valid values in that case.

If you do send a PR, don't forget a PR for the documentation.

**Comment by mrDlef** [comment]
OK I will propose something.
