### ISSUE TITLE
Asset render show disk path

### ISSUE THREAD

**Issue by jhuriez** [fuel/core#1656]
Hi,

On 1.8 branch, when i use <?= \Theme::instance()->asset->render('css'); ?> the output is : 

``` php
<link type="text/css" rel="stylesheet" href="http://fuelphp.localhost/C:/wamp/www/fuelphp/public/themes/default/css/bootstrap.css?1395070509">
```

But it's work find on 1.7/master branch.

If i use the function $asset->find_file() from 1.7, it's work.

**Comment by WanWizard** [comment]
Can you dump DOCROOT? What is it set to in your case?

I find it fully that it shows a Windows path, but uses forward slashes...

**Comment by jhuriez** [comment]
DOCROOT dump : C:\wamp\www\fuelphp\public\

**Comment by WanWizard** [comment]
To be clear, this in a view fails?

``` php
    <?php
        Asset::css('bootstrap.css', array(), 'css', false);
        echo Asset::render('css');
    ?>
```

It works in Linux, so it must be something Windows. Not looking forward to firing that up... :cry:
