### ISSUE TITLE
phpseclib - encryption of RSA keys with a password

### ISSUE THREAD

**Issue by gperrudin** [fuel/core#1657]
When I want to generate RSA keys when a password is set, I got an exception coming from TripleDES.php.
## 

Use of undefined constant CRYPT_DES_MODE_CBC - assumed 'CRYPT_DES_MODE_CBC'
COREPATH/vendor/phpseclib/Crypt/TripleDES.php @ line 71
line 71 : define('CRYPT_DES_MODE_CBC3', CRYPT_DES_MODE_CBC);

It does the same exception when I just want to encrypt a string with TripleRSA.

(topic on the forum : http://fuelphp.com/forums/discussion/12970/phpseclib-creating-rsa-encrypted-key#Item_1)

**Comment by WanWizard** [comment]
No longer needed (see the same topic), fixed in https://github.com/fuel/core/commit/b55d66d610da1f3e752db550f603d34ee24159d8
