### ISSUE TITLE
Adding :format param to route doesn't do anything

### ISSUE THREAD

**Issue by jpudney** [fuel/core#1662]
I believe I've found a bug when adding a `:format` param to a route.

The following is the route in `fuel/app/config/routes.php`

``` php
':format/numbers/all' => 'numbers/all'
```

The following is my rest controller, `fuel/app/controller/numbers.php`

``` php
<?php
class Controller_Numbers extends \Controller_Rest
{
    public function get_all()
    {
        return $this->response(range(1,6));
    }
}
```

I make the following request using cURL:

```
curl -i -XGET http://localhost/json/numbers/all
```

And I get the following response

```
HTTP/1.1 200 OK
Date: Sun, 23 Mar 2014 18:50:31 GMT
Server: Apache/2.2.26 (Unix) DAV/2 PHP/5.4.23 mod_ssl/2.2.26 OpenSSL/0.9.8y
X-Powered-By: PHP/5.4.23
Content-Length: 135
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8"?>
<xml><item>1</item><item>2</item><item>3</item><item>4</item><item>5</item><item>6</item></xml>
```

I'd expect the format to be picked up from the route as per (format_determination)[http://fuelphp.com/docs/general/controllers/rest.html#/format_determination], however this doesn't seem to be the case.

On further investigation the rest controller uses \Input::param('format'), so on checking myself this value appears to be `null`. I've checked for the value using the controller method param (`$this->param('format')`) and I do indeed get back the format I'm expecting ('json').

I added some logging to config:

``` php
// controller method:
public function get_all()
{
    \Log::info("Debugging format issue.", __METHOD__);
    \Log::debug(\Input::param('format'), __METHOD__);
    \Log::debug($this->param('format'), __METHOD__);
    \Log::info("End of debug", __METHOD__);

    return $this->response(range(1,6));
}
// log file:
INFO - 2014-03-23 18:56:06 --> Controller_Numbers::get_all - Debugging format issue.
DEBUG - 2014-03-23 18:56:06 --> Controller_Numbers::get_all - 
DEBUG - 2014-03-23 18:56:06 --> Controller_Numbers::get_all - json
INFO - 2014-03-23 18:56:06 --> Controller_Numbers::get_all - End of debug
```

Any info would be greatly appreciated.

**Comment by WanWizard** [comment]
Interesting.

:format in the route is just a named parameter, it does not have any relation to the "format" as used in the REST controller. Which explains why you have to use `$this->param()`.

The current code is correct, it checks `Input::param()` because it supports URL's like "/this/that?format=json". It simply doesn't check the route parameter at all. Didn't even know that was supported...
