### ISSUE TITLE
Hybrid controller router not being called when I think it should

### ISSUE THREAD

**Issue by jpudney** [fuel/core#1667]
I believe that the is_restful() method in the hybrid controller doesn't return a correct result for some restful requests.

I've created a simple hybrid controller:

``` php
<?php
class Controller_Test extends \Controller_Hybrid
{
    public function get_outcome()
    {
        return $this->response(range(1,5));
    }
}
```

When executing the following curl request:

```
curl -i -XGET http://127.0.0.1/test/outcome
```

I get the following response

``` http
HTTP/1.1 200 OK
Date: Sun, 23 Mar 2014 21:52:19 GMT
Server: Apache/2.2.26 (Unix) DAV/2 PHP/5.4.23 mod_ssl/2.2.26 OpenSSL/0.9.8y
X-Powered-By: PHP/5.4.23
Content-Length: 78
Content-Type: text/html

The requested REST method returned an array:<br /><br />[
    1,
    2,
    3,
    4,
    5
]
```

Here I would have expected to see xml in the response as this is the default format to return when using the rest controller element of the hybrid controller. From my findings I've deduced that the is_restful is returning false, which leads to the rest controllers router not being called, which in turn means that the response does not get formatted correctly.

Within the is_restful function is simply calls is_ajax which checks for a particular header being set in the request. I don't think that a request being sent using ajax makes a request restful.

**Comment by it-can** [comment]
what happens when you call:

curl -i -XGET http://127.0.0.1/test/outcome.xml

**Comment by jpudney** [comment]
@it-can exactly the same:

```
curl -i -XGET http://127.0.0.1/test/outcome.xml
HTTP/1.1 200 OK
Date: Mon, 24 Mar 2014 17:13:01 GMT
Server: Apache/2.2.26 (Unix) DAV/2 PHP/5.4.23 mod_ssl/2.2.26 OpenSSL/0.9.8y
X-Powered-By: PHP/5.4.23
Content-Length: 78
Content-Type: text/html

The requested REST method returned an array:<br /><br />[
    1,
    2,
    3,
    4,
    5
]
```

**Comment by it-can** [comment]
Does json work?

**Comment by WanWizard** [comment]
I don't agree with this. 

A cURL request is a request like any other, just with a different client. It is not an ajax call, so is_restful() returns false, as it should. This is how the Hybrid class was designed.

If you want to do something about it, it will no longer be hybrid. How can it distinguish between a GET from a browser which needs an HTML response, and a GET from some other tool, which requires (for example) a JSON response?

Do you have any suggestion on how to solve this dilemma? Without breaking the existing functionality?

**Comment by jpudney** [comment]
@it-can nope :smile:

@WanWizard I agree that a cURL request is a request like any other, however what we're trying to determine with `is_restful` is whether that request can be considered restful or not, and on this occasion I believe the request is restful. 

Currently the `is_restful` method merely checks for the value of the `HTTP_X_REQUESTED_WITH` header in the request to see if it's equal to `xmlhttprequest`, and if it is, then the request is being made over ajax. I don't think that whether a request is made over ajax should determine whether a request is restful or not.

As for a suggestion I think that the `is_restful` method should be modified to check the accept header instead. If the output is going to a web browser then `text/html` should be present in the accept header and the rest controller router should correctly determine that this is html and select the appropriate output format for the response. If the preferred output is anything else that this can be formatted as necessary.

I notice that the rest controller router doesn't pick up `text/xhtml` as html format so if we're going to employ this it might need to be added to the [supported formats array](https://github.com/fuel/core/blob/1.8/develop/classes/controller/rest.php#L51) so that browsers with a preference for xhtml(!) don't get xml back.

What do you think?

**Comment by WanWizard** [comment]
I might agree with you if you say that is_restful() should have been called is_ajax(), which is probably more correct. 

And perhaps from a theoretical point of view your reasoning is correct too (and definitely something we need to look at for v2!).

The point is that an accept header of "text/html" doesn't say anything about the remote client. It could be a browser, an ajax call, curl or a wget. Who knows. Changing this will break BC big time.

I can guarantee all our applications will tumble over at some point, because they currently have methods that return different output (but both HTML) based on the result of is_restful().

So I'd say "not in v1, definitely to be looked at for v2".

**Comment by jpudney** [comment]
> The point is that an accept header of "text/html" doesn't say anything about the remote client. It could be a browser, an ajax call, curl or a wget. Who knows.

Really I think this is the point. The purpose of the hybrid controller in my mind is a marriage of the template controller and the rest controller, which allows you to have methods for both types in a single controller, without separating the functionality over multiple controllers. Within the controller you don't care what's making the request as long as you're able to generate a response in a format that it _accepts_, which I believe is what the whole Accept Header is all about.

At the end of the day it's not really about determining whether a request is restful or not, but whether we can deduce what controller functionality is required for what response is needed – if it's a request from a browser then the format is more likely going to be needed in HTML, and if it's over ajax, curl, wget, et. al. then the response maybe better served in json, xml or whatever. It's up to the requesting client to make that decision, and for the controller to format the requested information in an acceptable format.

> Changing this will break BC big time.

I agree and, unfortunately, perhaps it's best to leave this until v2.0 and leave v1 without. But definitely worth thinking about :+1:

**Comment by WanWizard** [comment]
I agree.  Let's move to v2 asap. :runner:
