### ISSUE TITLE
Autoloader issue

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#1669]
I have no idea how this was a thing, but it was. A typo was made in an ORM model relation definition where the related model was said to be \BkCms\Section\List rather than \BkCms\Section_List. This caused the autoload to be handled by an app specific autoloader because the Fuel one did not find this class. This included the file fuel/app/modules/bkcms/section/list.php which contained the class \BkCms\Section_List.

A method_exists call for \BkCms\Section_List::run triggered the Fuel autoloader. This re-included the file and triggered a class already exists error. This is the bit I'm not sure of... sounds like a PHP bug but I can't replicate it in a compact enough way to report it.

Anyway... the long and short of it is that I think the Fuel autoloader should use include_once and require_once instead of the non-suffixed equivalents because this was a royal ball bag to diagnose.

PHP-FPM v5.4.25

**Comment by WanWizard** [comment]
Perhaps better: in all cases, init_class() is called after the file is loaded. If could do a class_exist(), and barf out an "file X does not contain class Y" exception? 

So you can fix it instead of hide the problem?

**Comment by WanWizard** [comment]
I've made a change to the autoloader that it now always uses include (which is by far the fastest and less memory consuming), and it will throw this exception when you make a classname error:

```
Exception [ Error ]:
File "APPPATH/../modules/test/classes/model/test.php" does not contain class "Test\Model_Test"
```

when you load Test\Model_Test instead of Test\Model\Test.
