### ISSUE TITLE
Where is the version 2.0 repository?

### ISSUE THREAD

**Issue by RyanDawkins** [fuel/core#1670]
I'm looking to contribute to the FuelPHP project, but I can't find the 2.0 repo.

I did find this however... https://github.com/fuelphp/fuelphp (which says it's 2.0)

**Comment by Art4** [comment]
https://github.com/fuelphp/ is the 2.0 repo.

See also: http://fuelphp.com/blogs/2012/07/first-fuelphp-2-0-alphabeta-releases

**Comment by moakdesigns** [comment]
RyanDawkins - You landed in the right place. :)

**Comment by WanWizard** [comment]
Fuel v2 uses composer. Clone the fuelphp/fuelphp repo, and run composer on it to install all dependencies.
