### ISSUE TITLE
How to implement "comet" in fuelphp?

### ISSUE THREAD

**Issue by chriskoo** [fuel/core#1681]
I want to use "comet" in fuelphp envirorment. (Loop in server)

I try to write below code in controller:
      set_time_limit(0);
        $i=0;
        while(1) {
            $i++;
            echo 'Time:'.time();
            ob_flush();
            flush(); // used to send the echoed data to the client
            sleep(1); // a little break to unload the server CPU
        }

When I try to use browser to access the page, the browser is keep in loading, for about 1mins, the nginx show error.
I've also to move the code from controller to a view , it's the same.

I've already tested the code in a single php file outside fuelphp enviorment, it's work.

How to solve the problem? help

**Comment by WanWizard** [comment]
Fuel does output buffering, which is required to be able to make header modifications in the request shutdown, for example to set cookies. So this kind of code doesn't work, you need to deal with the buffering, and depending on your config, also disable gzip of the output (which requires buffering).

Other than taking these precautions, there is nothing in Fuel that would abort an HTTP request, so I would check your nginx setup instead, it looks like it has a request timeout and no keep-alive support to allow long-running requests.

If I add this to the controller, it works fine in my Apache setup (that is configured for long-running requests). You will get errors when you use cookies (for example when you use sessions).

```
// disable output buffering
ob_end_flush();

set_time_limit(0);
$i=0;
while($i<600) {
    $i++;
    echo 'Time ',$i,':'.time(), '<br />';
    ob_flush();
    flush(); // used to send the echoed data to the client
    sleep(1); // a little break to unload the server CPU
}

// restart up output buffering
ob_start(\Config::get('ob_callback'));
```
