### ISSUE TITLE
XCache Support

### ISSUE THREAD

**Issue by dercoder** [fuel/core#1683]
Is it possible to create a XCache Storage for Fuel\Cache?
http://xcache.lighttpd.net/

**Comment by WanWizard** [comment]
I don't see why not.

**Comment by dercoder** [comment]
Ok cool. So you added it to your todo list?

**Comment by WanWizard** [comment]
Experimental driver committed, would you mind testing it?

**Comment by dercoder** [comment]
Thx, i will test it this weekend :)

**Comment by dercoder** [comment]
Its working fine. I have testet it on my development project and also all functions

**Comment by WanWizard** [comment]
Cool, thanks for the confirmation. I'll update the docs.
