### ISSUE TITLE
Unit tests should not require network connection to run

### ISSUE THREAD

**Issue by sjamaan** [fuel/core#1686]
It is a _really_ bad idea to require a live network connection for running the tests. This is currently needed only for the "Agent" class tests, see #1620 . 

Also, these files might change "upstream" at any time (as we've already seen in #1620 ), which would cause unit tests to fail randomly. Because Fuel also caches these downloaded files, you might not notice until the moment you try to run the tests on a new machine. This wreaks havoc when you're enforcing a clean test run as part of your deployment process (as we're doing): things might just fail seemingly at random moments, which is extremely hard to debug. It took me an strace(1) call to figure out why the tests worked on one machine and not on another.

It also hampers developer testing on temporarily disconnected machines (laptops, for instance).  It also completely breaks in locked down configurations where `allow_url_fopen` is `Off` for security reasons. Curl might not be available either.

All in all, I recommend constructing a custom minimal browscap file just for the tests and shipping that along with the system.

**Comment by kenjis** [comment]
How do we know the issue like #1620 ?

**Comment by sjamaan** [comment]
Perhaps by putting it in a functional or integration test, or (I don't know if this is possible) by putting it in a group which isn't run by default.

**Comment by sjamaan** [comment]
Also note that I didn't notice the fact it was wrong until this week when the tests started failing out of the blue. I didn't notice before due to the annoying caching behaviour, even though it's apparently been broken for at least a month (at least according to github's presentation of your first comment's date).

**Comment by kenjis** [comment]
Why don't you run tests except group=Core ?

**Comment by sjamaan** [comment]
I'd want to check that my setup is correct in its entirety. If I upgrade Fuel, I would want to get failed tests when the server is running an outdated PHP which doesn't have features used by the new Fuel, for example. The application might not (yet) be using those features, but the app as a whole might not work as a result.

**Comment by WanWizard** [comment]
Agent tests no longer need a network connection, it will also no longer use the existing browscap cache (if present).
