### ISSUE TITLE
No tests found in class "Fuel\Core\TestCase".

### ISSUE THREAD

**Issue by takahc9** [fuel/core#1694]
When I execute unit test with wildcard(*) to pick testcase (as default), The warning No tests found in class "Fuel\Core\TestCase" occured.

I can avoid the warning if the filename of testcase exact match with containing class name(CASE SENSITIVE!). or I can avoid it if the test case class extends \PHPUnit_Framework_TestCase directory (because Fuel\Core\TestCase is empty).

A better way, Fuel\Core\TestCase class should be abstract class. 

Thank you.

**Comment by WanWizard** [comment]
Can you explain what exact command you use to execute that unit test?

**Comment by takahc9** [comment]
I just run the unit test with oil command as bellow.

<pre>
# FUEL_ENV=test php oil test
Tests Running...This may take a few moments.
PHPUnit 3.7.37 by Sebastian Bergmann.
Configuration read from /Applications/eclipse/4.3/workspace/fueldev/build/site/fuel/app/phpunit.xml
F............
Time: 1.6 seconds, Memory: 13.00Mb
There was 1 failure:
1) Warning
No tests found in class "Fuel\Core\TestCase".
</pre>

I wrote the test for some modules as bellow.

<pre>
namespace Realm\Model;
class TestGroup extends \TestCase
{
......
}
</pre>

I retrieve phpunit by composer. and I adjust the path for my own directory structures.

<pre>
config/test/oil.php
return array(
    'phpunit' => array(
        'autoload_path' => DOCROOT . '../../vendor/autoload.php' ,
        'binary_path' => DOCROOT . '../../vendor/bin/phpunit' ,
    ),
);
</pre>

**Comment by kenjis** [comment]
I got the same error before. And when I google `No tests found in class "Fuel\Core\TestCase"`, I see some blog articles about the same error. So I sent PR.

**Comment by WanWizard** [comment]
PR was merged (although I have never seen the error here).
