### ISSUE TITLE
Default expiration time for cookies is not used

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#170]
In the cookie class there is a public variable $expiration that is not used. In the public function set(), if the local parameter $expiration is not set, expiration time will be set to a hard coded value of 86500. I'd suggest that instead of:

$expiration = time() + 86500;

it should be:

$expiration = time() + static::$expiration

Also, now that I've seen a lot of the Fuel code, it seems that the public variables: $expiration, $path, $domain, $secure, and $http_only should be set in a config file which would be similar to other classes.

One other thought is that for completeness, perhaps the function set() should also take $secure = null and $http_only = null as passed parameters.

**Comment by jschreuder** [comment]
It's probably some left-over code from when the class was ported from Kohana. Those static class properties shouldn't be there, they should all be values from main config.

I think those global default settings should be set in the main app/config/config.php (defaults for cookies are global app concerns). If you've been in there already feel free to go ahead and pull-request a proposal...

**Comment by Mitchell64** [comment]
I would agree that they're a good candidate for the global config file. I'm pretty clueless regarding how to use GitHub to contribute code. I'm not trying to get out of helping, but I also don't want to screw anything up. I checked out a few help pages regarding forking, branching, pull-request, etc., and frankly I'm confused. The help shows what looks like Linux command line commands, and I'm using a Windows machine. If you could guide me to any "GitHub for Dummies" pages or walk me though the process, I'll try to make changes to the config.php and cookies.php files.

**Comment by jschreuder** [comment]
tbh I'm pretty much a Git-noob myself (I leave the hard stuff for Dan & Phil ;) )

On Windows I'm using TurtoiseGit as a Git GUI, should help you get started without the scary command line. But you can also use git from the commandprompt, just like on Linux in the commandline.
On Git in general, sadly I haven't saved the tutorials I read but there's a couple of good ones easily googled or found on questions on stackoverflow from others who wanted to learn it. Believe me, once you've tried it you wont go back.

And don't be scared to screw anything up, we check all pull-requests before accepting them of course.

**Comment by ShonM** [comment]
I recommend gitextensions for windows, and git tower for Mac

**Comment by Mitchell64** [comment]
I did a little googling, and it looks like TortoiseGit and GitExtensions are the main Windows interface software. I used TortoiseSVN a little in the past, so I may try Tortoise. Jelmer, did you also have to install Msysgit - Git For Windows in addition to TortoiseGit?

**Comment by jschreuder** [comment]
Yeah, I think TurtoiseGit even requires it to work - it only offers a GUI for git, it's not an alternative implementation.

**Comment by Mitchell64** [comment]
I'm leaving tomorrow for a few days, so I didn't have time to install TortoiseGit, however I did fork and make changes to config.php and cookie.php. Not sure if I did the fork, etc. correctly, so you probably want to take a look.

Let me know if you see anything that doesn't look correct or if you have any suggestions. Thanks.

**Comment by Mitchell64** [comment]
I'm probably missing something, but in the function set(), if $expiration === null, then $expiration will be taken from either the default values in the $config array or it will be taken from the app/config/config.php file. If $expiration is taken from config.php, doesn't it still need to be added to time() unless the value of $expiration == 0?

**Comment by WanWizard** [comment]
yes, you're absolutely right. Must have missed that.

**Comment by Mitchell64** [comment]
Glad I could be of help.
