### ISSUE TITLE
Default theme path

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/core#1717]
IMO the default theme path is not a lucky choice. First of all it should be considered to be bad security to have the theme files (not only the assets) in the DOCROOT. It means anyone can have access to those files.

Secondly, when using oil generate the DOCROOT is something else, so it becomes inconsistent. (I have to admit, that IMO the DOCROOT constant itself is a bit confusing).

APPPATH/themes or APPPATH/../themes would be a much better choice. Docs also refers to APPPATH/../themes as a default path, composer/installers package also tries to install fuel-theme packages there.

**Comment by WanWizard** [comment]
I didn't even know there were fuel-theme packages...

Changing the default theme path should be done with care, all applications dependent on the default will break if you change it.

**Comment by sagikazarmark** [comment]
Actually I implemented it based on the docs. Then I saw that the default config is something else.

**Comment by WanWizard** [comment]
Most of Themes is open source donation from our app framework. And we use a different file structure, which is were the APPPATH/../themes comes from I guess (which in the default would get you in the fuel folder, which is a bad idea). 

So I guess both need some updating, and APPPATH/themes seems the most sensible option. Perhaps we should even create it by default (we do that for other empty folders too).

**Comment by sagikazarmark** [comment]
I am open to any ideas which makes the default out of DOCROOT. If you make the change in fuel, I will open a PR in composer installers package.

**Comment by WanWizard** [comment]
The docs mention APPPATH.'themes', which looks to me like the logical location. I'll update the package and the core config accordingly.

**Comment by sagikazarmark** [comment]
@WanWizard ok. Will open PR referencing this issue in composer installers
repo.
