### ISSUE TITLE
Add fuel/fuel to packagist

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/core#1726]
Since fuel packages are now installed with composer, the only thing is needed to be able to do this:
`composer create-project fuel/fuel:dev-1.8/develop`

is adding fuel/fuel to packagist. It doesn't matter there are no tags in v1.

**Comment by kenjis** [comment]
It' nice!

**Comment by WanWizard** [comment]
Just a matter of adding the repo as-is, no further action needed?

**Comment by sagikazarmark** [comment]
IMO yes.

**Comment by WanWizard** [comment]
ok, done.

**Comment by kenjis** [comment]
I could install via Composer.

```
$ composer create-project fuel/fuel:dev-1.8/develop --prefer-source
```

and all tests passed.

```
OK (375 tests, 447 assertions)
```

**Comment by Art4** [comment]
Yeah :+1:

**Comment by WanWizard** [comment]
Thanks for confirming that!

**Comment by WanWizard** [comment]
How would that work for master?

```
composer create-project fuel/fuel:dev-1.7/master
```

(assuming 1.7.2 would have been released?)

I would like to update the docs with this, but obviously can't test it yet.

**Comment by kenjis** [comment]
We can't test.

By the way, current composer.json is not valid.

```
$ composer validate 
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See http://getcomposer.org/doc/04-schema.md for details on the schema
description : is missing and it is required
```

**Comment by WanWizard** [comment]
I have added a description
