### ISSUE TITLE
Problem with phpseclib

### ISSUE THREAD

**Issue by it-can** [fuel/core#1728]
After updating to the latest 1.8/develop I now get this error when I use auth...

```
Fuel\Core\PhpErrorException [ Notice ]:
Use of undefined constant CRYPT_MODE_CTR - assumed 'CRYPT_MODE_CTR'

COREPATH/vendor/phpseclib/Crypt/AES.php @ line 79
```

**Comment by WanWizard** [comment]
Is being looked at.

**Comment by WanWizard** [comment]
Is your code up to date? In my version of AES.php, line 79 is a comment line... Auth runs fine here.

**Comment by it-can** [comment]
I just updated to the latest 1.8/develop... I don't use the phpseclib stuff, only use Auth...

I see this is merged this morning... https://github.com/fuel/core/pull/1723/files#diff-1bbef995184bae951923685616d9d731R79

**Comment by WanWizard** [comment]
That is the version I have working, yes.

**Comment by it-can** [comment]
It seems I am calling \Auth::check() ...

**Comment by mikepmtl** [comment]
So is the issue resolved?  Can I do a pull.  Right now I just commented all the defines out and it seems to be working.

**Comment by it-can** [comment]
It is not working for me...

**Comment by mikepmtl** [comment]
Did you try just commenting out all the defines in:
COREPATH/vendor/phpseclib/Crypt/AES.php

I tried giving them their integer values, but it said they were already defined in another file.

**Comment by it-can** [comment]
jup, commenting out all defines in AES.php solved the issue...

**Comment by kenjis** [comment]
I got the same error:

```
INFO - 2014-07-10 22:32:54 --> Fuel\Core\Request::__construct - Creating a new main Request with URI = ""
INFO - 2014-07-10 22:32:54 --> Fuel\Core\Request::execute - Called
INFO - 2014-07-10 22:32:54 --> Fuel\Core\Request::execute - Setting main Request
ERROR - 2014-07-10 22:32:54 --> shutdown - Use of undefined constant CRYPT_MODE_CTR - assumed 'CRYPT_MODE_CTR' in .../fuel/core/vendor/phpseclib/Crypt/AES.php on 79
```

**Comment by kenjis** [comment]
The constant defined in Crypt/Base.php, but it is not autoloaded.

**Comment by WanWizard** [comment]
Bug in PHPSecLib, just fixed.
