### ISSUE TITLE
Global namespaces

### ISSUE THREAD

**Issue by it-can** [fuel/core#1733]
There are no global namespaces defined here:

https://github.com/fuel/core/blob/1.8/develop/classes/database/query.php#L272
DB::SELECT >> \DB::SELECT

https://github.com/fuel/core/blob/1.8/develop/classes/database/query.php#L280
Database_Result_Cached >> \Database_Result_Cached

https://github.com/fuel/core/blob/1.8/develop/classes/database/query.php#L282
CacheNotFoundException >> \CacheNotFoundException

https://github.com/fuel/core/blob/1.8/develop/classes/dbutil.php#L473
InvalidArgumentException >> \InvalidArgumentException

https://github.com/fuel/core/blob/1.8/develop/classes/migrate.php#L453
FuelException >> \FuelException

https://github.com/fuel/core/blob/1.8/develop/classes/migrate.php#L459
FuelException >> \FuelException

https://github.com/fuel/core/blob/1.8/develop/classes/migrate.php#L466
FuelException >> \FuelException

https://github.com/fuel/core/blob/1.8/develop/classes/profiler.php#L22
PhpQuickProfiler >> \PhpQuickProfiler

https://github.com/fuel/core/blob/1.8/develop/classes/router.php#L209 (fixed in PR: https://github.com/fuel/core/pull/1732)
Route >> \Route

https://github.com/fuel/core/blob/1.8/develop/classes/module.php#L88
ModuleNotFoundException >> \ModuleNotFoundException

**Comment by emlynwest** [comment]
Pull requests are welcome ;)

**Comment by it-can** [comment]
haha ok... ;-)

**Comment by it-can** [comment]
@stevewest see #1734
