### ISSUE TITLE
[REST API] Decoding of multipart-data input

### ISSUE THREAD

**Issue by ghost** [fuel/core#1735]
Hello,

I want to upload a file in a PUT HTTP request, using multipart-data.

In a POST request, PHP do the decoding of the input, but in a PUT request, the framework has to do it, and currently it does only support www-form-urlencoded, and no multipart-data.

**Comment by emlynwest** [comment]
Please raise this issue on http://github.com/fuelphp/upload

**Comment by WanWizard** [comment]
Technically, this is more about Input then Upload. The problem is that on a HTTP POST, PHP will parse the input data, and split it into $_POST and $_FILES. It doesn't do that for PUT, and they seem to refuse to do so: https://bugs.php.net/bug.php?id=55815

**Comment by ghost** [comment]
So, in a REST API, it's not posible to upload a file editing a resource ?

**Comment by WanWizard** [comment]
Note that if you do this manually (http://stackoverflow.com/questions/9464935/php-multipart-form-data-put-request has some pointers), stuff like `is_uploaded_file()` and `move_uploaded_file()` will not work, so even this workaround might only work partially.

**Comment by WanWizard** [comment]
@akimad The short answer is: not that the moment, no. I agree it should, but it might be too complex to "quickly fix".

**Comment by ghost** [comment]
Ok, thank you very much for your help.

I think that for the moment, I will use POST request to achieve this.

**Comment by WanWizard** [comment]
http://codereview.stackexchange.com/questions/69882/parsing-multipart-form-data-in-php-for-put-requests has a decent code example, but needs quite a bit of test work. Need to find the time for it.

**Comment by WanWizard** [comment]
Implemented: https://github.com/fuel/core/commit/39fd019c3325a32db87a3e921cb7dac181f3c37a
