### ISSUE TITLE
Better MongoDB Support

### ISSUE THREAD

**Issue by dercoder** [fuel/core#1738]
There are a lot of MongoDB functions which are not supported now by FuelPHP Mongo_Db Class. 

1st example is the $set and $unset (and some more) parameter in update function
http://docs.mongodb.org/manual/reference/operator/update/set/

2nd example is the aggregate function
http://php.net/manual/en/mongocollection.aggregate.php
http://docs.mongodb.org/manual/core/aggregation-introduction/

**Comment by WanWizard** [comment]
Send a PR. ;-)

Nobody of the team uses it (we've switched to Monga some time ago), and Monga will also be the Fuel v2 Mongo interface.

**Comment by dercoder** [comment]
Whats PR?
Thanks for info, i will try Monga

**Comment by emlynwest** [comment]
Pull request. And I think this issue can be closed. If people want better mongo support they can use Monga.

**Comment by dercoder** [comment]
Ah ok, thx.
1 more question before you can close this issue. 
Have you tested other MongDB classes? Is Monga the best solution?

**Comment by emlynwest** [comment]
Personally I have not. I have not had a chance to use Mongo in a project yet.

**Comment by dercoder** [comment]
Mhm, ok. I will try some of this libs

**Comment by WanWizard** [comment]
You may want to ask @FrenkyNet, he's the author of Monga.

**Comment by frankdejonge** [comment]
@DerCoder Monga is probably a better thing to go with for a simple MongoDB abstraction. I'm no longer maintaining it, the project is looking for a new lead, but the code there works like a charm. Other options would be to use the doctrine odm package. Haven't used that myself but hear great things!

**Comment by dercoder** [comment]
Ok, thx for this information. I dont want to use Doctrine. I will check some other libs from this
http://docs.mongodb.org/ecosystem/drivers/php-libraries/
