### ISSUE TITLE
Error in session/file.php

### ISSUE THREAD

**Issue by it-can** [fuel/core#1744]
I now get this error:

Warning - is_file() expects parameter 1 to be a valid path, string given in /fuel/core/classes/session/file.php on line 280 (https://github.com/fuel/core/blob/1.8/develop/classes/session/file.php#L280)

It seems this has happend when these changes were made... 848e3a648063167348da4f74bbc794659ab60116

**Comment by WanWizard** [comment]
Where you encrypting the cookie? If so, you might have had corrupt data stored (data that can't be encoded now), causing the constructed filename to be rubbish?

**Comment by it-can** [comment]
Isn't this the change to the \Crypt:encode() and \Crypt::decode() functions recently?

**Comment by WanWizard** [comment]
Those are only used to encode/decode the cookie. If you had a cookie encoded before the fix, and you try to decode that after the fix, null is returned, which might cause the constructed filename to be invalid. 

Other than this, encode/decode isn't used in Session.

**Comment by it-can** [comment]
I'll do some logging...
