### ISSUE TITLE
Delete routes for unloaded module

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/core#1746]
When a module is unloaded, all the routes added to the router are deleted [here](https://github.com/fuel/core/blob/1.8/develop/classes/module.php#L113). IMO it is bad, since the routes are deleted with the same name, not the added routes. So if I add a route with the same name, it will be deleted. I admit it is a weird scenario. But the delete is not the inverse of the add. Not sure if it is right.

Also, I don't want to make anyone to mess with v1, just wanted to make a note and make sure the same is not done in v2.

**Comment by WanWizard** [comment]
Correct, but there is no way to determine which routes were loaded by which module.

In v2, every component has it's own Router instance, so routes aren't merged.

**Comment by WanWizard** [comment]
Going to assume no two modules (or the app) define the same route prefix, so just deleting the routes that were added when the module was loaded (by name) should do.
