### ISSUE TITLE
Return value for Module::load and Package::load

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/core#1747]
Both methods return a false negative value (false) when an array is passed.

It should be either a boolean value calculated by the success of all load methods (and nulls should be treated as true, since it is already loaded) or an array of return values should be returned.

**Comment by sagikazarmark** [comment]
Maybe I am wrong and false does not have a negative meaning?

**Comment by sagikazarmark** [comment]
It seems that false value was indicating that an array was passed, so it will possibly break BC, but this implementation is more consistent.

**Comment by WanWizard** [comment]
That would be odd, given the fact that the docblock states "returns true on success".

**Comment by sagikazarmark** [comment]
Which was obviously false until now.

**Comment by WanWizard** [comment]
Correct, so I thought the best way was to correct it, so it's behaviour is now as documented.
