### ISSUE TITLE
Router automatically loads module

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/core#1749]
If a request uri starts with a module name, the router always loads the module. What's the purpose of module loading then? (if the requested module is always loaded). This stands for request as well: it checks if the module exists and loads the routes, even if it isn't loaded.

If you agree, I open a PR for that.

**Comment by WanWizard** [comment]
The module is loaded to be able to switch the framework to the "module context". If that is not done, certain module specific things won't work.

**Comment by sagikazarmark** [comment]
What I dont understand, why is it possible or should be a module loaded if it is automatically loaded by the request.

It is also a bit weird that the context (routes) is added by the request. I checked the v2 component model maybe the module loading should add the routes to the router.

**Comment by WanWizard** [comment]
Sorry, I don't understand what you mean here.

**Comment by sagikazarmark** [comment]
In router if a module EXISTS then the router LOADs it. It does not matter if it is loaded by user or added to always load.

In request if a module EXISTS then a the routes.php (if exists) is loaded (instead of doing this in module load).

**Comment by WanWizard** [comment]
So it's loaded twice you mean?

**Comment by sagikazarmark** [comment]
1. It is loaded twice.
2. It is loaded by the request/rouer, no matter if the user did not load it. (Meaning a user cannot keep a module disabled, it will be loaded if the first segment is the same as one of existing module names)
3. The routes are not added when the module is loaded, but when the request is forged. Imo this means that multiple requests add the routes multiple times.

**Comment by WanWizard** [comment]
1. Ok
2. You can not keep it disabled. If the URL points to a module controller, it MUST be loaded otherwise it won't work.
3. You have a point.

I'll have an in-depth look tonight, busy atm. ;-)

**Comment by sagikazarmark** [comment]
1. This is the point. If it is not loaded, 404 should be thrown. Why is it obvious, that a module should always been loaded?

**Comment by WanWizard** [comment]
If that was the case, you would have to always_load ALL your routeable modules. Otherwise requesting something like `/modulename/controller/method` will never work, as `modulename` needs to be loaded for that to work. Therefore it's dynamically loaded if requested. 

Calling load() multiple times is not a problem, the method will return immediately if the module is already loaded. And I think that it may be faster than having to figure out if it is loaded first.

**Comment by sagikazarmark** [comment]
I accept that.

It would also be nice if autoloading and routing could be loaded in separate functions in Module class (like in case of v3 components) to be able to override easily. (Like custom routing rules and namespaces, etc)

**Comment by WanWizard** [comment]
Module routing is a bit of a pain at the moment, it has a lot of limitations. In the past we've decided a refactoring of that code wasn't worthwhile, because it is a lot of work to do it right, and it should be addressed in v2.

**Comment by sagikazarmark** [comment]
I am talking about some minor changes to make things at least hackable.

This does not affect the way modules are loaded but makes it possible the default rules.

I have some sort of implementation, can send a PR if you are curious.

**Comment by WanWizard** [comment]
Always interested in improvements... ;-)

**Comment by sagikazarmark** [comment]
I decided to implement it for myself, then you can take a look. Actually it might be a bit big change, might break BC, so not sure if it can be part of the core. But I am stucked now, because of some change in Finder. Can't replace core Module class. See #1750.

**Comment by WanWizard** [comment]
That issue isn't related to this one, the Finder is used long before routing comes into play.

**Comment by sagikazarmark** [comment]
@WanWizard [here](https://github.com/indigophp/fuel-module) is the extension.

**Comment by WanWizard** [comment]
And what do I do with that?

p.s. as for version 2, components are defined and not discovered, and for every component, you can define whether or not it is routeable. Components that are not defined are not known, v2 doesn't do dynamic autoloading. So v2 doesn't have this issue.

**Comment by sagikazarmark** [comment]
If you are interested in it, you can merge it in the core. (I can open a pull request) As I said it might break BC, but I am not sure. I implemented it in a different package, so if it does not fit in the core it still can be used.

**Comment by WanWizard** [comment]
breaking BC is a bad idea, so I have to see in detail what it does before anything can be merged.

**Comment by sagikazarmark** [comment]
This is why I wanted to show this before ;)

**Comment by WanWizard** [comment]
Don't think we'll have this change in v1. v2 already works this way.
