### ISSUE TITLE
Adding core namespaces multiple times is permitted

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/core#1753]
In case of adding a core namespace multiple times (eg. using the same namespace in two different packages) the core namespace stack is not filtered, so (in theory) the autoloader could search for a class in the same namespace several times.

You could say "use different namespaces", but I think this belongs to the autoloader to make sure the core namespace stack's elements are unique.

It is still an open question how to decide the correct order of multiple added namespaces.

**Comment by WanWizard** [comment]
This is by design, it allows for exactly that. Obviously, if both packages define the same class name, the first one found will be used.

**Comment by sagikazarmark** [comment]
Well, it isn't about classes, but namespaces. Core namespace is not mapped to a file path, so it does not depend on order of packages.

IMO defining the SAME core namespace is pointless, or is it about the order? Adding the same namespce several times assumes a different order of namespaces. If it is not about order then the class won't be found in the same namespace several times, so checking the same namespace several times is pointless.

**Comment by WanWizard** [comment]
add_core_namespace() allows you to define the namespace before or after the already defined namespace, so yes, the order is relevant.

**Comment by sagikazarmark** [comment]
Ok, thanks.
