### ISSUE TITLE
Official 1.7.2 Zip file permission

### ISSUE THREAD

**Issue by kenjis** [fuel/core#1755]
Some folders and files in 1.7.2 Zip file have too little permissions.

Examples:

```
$ ls -l fuel/
合計 16
drwxrwxr-x 15 kenji kenji 4096  7月 13 22:02 app
drwx------  9 kenji kenji 4096  7月 22 18:22 core
drwxrwxr-x  7 kenji kenji 4096  7月 13 22:27 packages
drwxrwxr-x  7 kenji kenji 4096  7月 13 22:27 vendor

$ ls -l fuel/vendor/
合計 24
-rw------- 1 kenji kenji  183  7月 22 18:25 autoload.php
drwx------ 3 kenji kenji 4096  7月 22 18:23 composer
drwx------ 3 kenji kenji 4096  7月 22 18:24 fuelphp
drwx------ 3 kenji kenji 4096  7月 22 18:24 michelf
drwx------ 3 kenji kenji 4096  7月 22 18:24 monolog
drwx------ 3 kenji kenji 4096  7月 22 18:25 psr
```

**Comment by WanWizard** [comment]
Didn't even know a zipfile contained linux permissions.

I checked the zip, and I don't see any permission info. And in the source tree from with the zip is created, those folders have 775. 

Are you sure you haven't run anything yourself, or a result ot the way you unpacked it?

**Comment by kenjis** [comment]
Zip file has permissions.

```
$ unzip -Z fuelphp-1.7.2.zip | grep /fuel/vendor/[a-z]*/$ | grep ^d
drwx------  3.0 unx        0 bx stor 22-Jul-14 18:23 fuelphp-1.7.2/fuel/vendor/composer/
drwx------  3.0 unx        0 bx stor 22-Jul-14 18:24 fuelphp-1.7.2/fuel/vendor/fuelphp/
drwx------  3.0 unx        0 bx stor 22-Jul-14 18:24 fuelphp-1.7.2/fuel/vendor/michelf/
drwx------  3.0 unx        0 bx stor 22-Jul-14 18:24 fuelphp-1.7.2/fuel/vendor/monolog/
drwx------  3.0 unx        0 bx stor 22-Jul-14 18:25 fuelphp-1.7.2/fuel/vendor/psr/
```

**Comment by ghost** [comment]
confirm the same issue

**Comment by WanWizard** [comment]
Very odd. I've created a new zip, can you check this before I change the one on the site?

http://s000.tinyupload.com/?file_id=71219201322714930279

(both the rights, and the composer update run please)

**Comment by kenjis** [comment]
The permission seems okey. All files have `-rw-rw-r--`, and all folders have `drwxrwxr-x`.

```
$ unzip -Z fuelphp-1.7.2.zip | grep '^\-' | cut -f 1 -d ' ' | uniq
-rw-rw-r--
$ unzip -Z fuelphp-1.7.2.zip | grep '^\d' | cut -f 1 -d ' ' | uniq
drwxrwxr-x
```

But if I run `composer update`, required packages are removed.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing michelf/php-markdown (1.4.0)
Deleting fuel/packages/parser/ - deleted
Deleting fuel/packages/orm/ - deleted
Deleting fuel/packages/oil/ - deleted
Deleting fuel/packages/email/ - deleted
Deleting fuel/packages/auth/ - deleted
  - Removing psr/log (dev-master)
  - Removing fuelphp/upload (2.0.1)
  - Removing monolog/monolog (1.5.0)
  - Updating composer/installers dev-master (020fa19 => 74fb0a7)
    Checking out 74fb0a7a1a23696d9c8cc2fba5903f6711cdd067

Writing lock file
Generating autoload files
```

And it has `./fuel/vendor/composer/installers/.git` folder.

**Comment by WanWizard** [comment]
Ah, I probably have to update the lock file too. 

I left the installers .git folder in there (and the corresponding entry in the composer.json) to allow you to have the composer installers updated on a `composer update`.

**Comment by WanWizard** [comment]
Fixed, zipfile updated, and put online.

**Comment by kenjis** [comment]
If we run `composer update`, autoloader can't find `Monolog\Logger`.

```
$ oil test
Tests Running...This may take a few moments.
PHPUnit 4.1.3 by Sebastian Bergmann.

Configuration read from /home/kenji/Downloads/fuelphp-1.7.2/fuel/core/phpunit.xml

...............................................................  63 / 375 ( 16%)
............................................................... 126 / 375 ( 33%)
............................................................... 189 / 375 ( 50%)
....................................................F.......... 252 / 375 ( 67%)
............................................................... 315 / 375 ( 84%)
............................................................

Time: 748 ms, Memory: 20.75Mb

There was 1 failure:

1) Fuel\Core\Test_Model_Crud::test_get_connection
Failed asserting that null matches expected 'read'.

/home/kenji/Downloads/fuelphp-1.7.2/fuel/core/tests/model/crud.php:35

FAILURES!                                
Tests: 375, Assertions: 446, Failures: 1.
```

We missed to fix the test failure before 1.7.2 release?

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating composer/installers dev-master (020fa19 => 74fb0a7)
    Checking out 74fb0a7a1a23696d9c8cc2fba5903f6711cdd067

Writing lock file
Generating autoload files
```

```
$ oil test
PHP Fatal error:  Class 'Monolog\Logger' not found in /home/kenji/Downloads/fuelphp-1.7.2/fuel/core/classes/log.php on line 100
PHP Fatal error:  Class 'Monolog\Logger' not found in /home/kenji/Downloads/fuelphp-1.7.2/fuel/core/classes/log.php on line 100

Fatal error: Class 'Monolog\Logger' not found in /home/kenji/Downloads/fuelphp-1.7.2/fuel/core/classes/log.php on line 100

Fatal error: Class 'Monolog\Logger' not found in /home/kenji/Downloads/fuelphp-1.7.2/fuel/core/classes/log.php on line 100
```

**Comment by WanWizard** [comment]
That means that composer removes the existing entries in it's autoloader files when it runs the update, which in turn means we have an unsolvable catch-22 situation.

So either there is composer support, and then we go back to our original plan with only fuel/fuel in the zip (so you have to run composer to install the rest), or have a complete zip that works out of the box, but has no composer support at all. 

I don't see another solution, but I'm up for suggestions. I don't want to include repo's in the zip, if you want to use local clones, you can clone fuel/fuel directly. In that case there is no point using the zip, the zip is meant for beginners that don't know any VCS, but just want to download and give Fuel a go...

**Comment by kenjis** [comment]
Solution is to change `minimum-stability` to `stable`.
There is no reason to set it `dev` for released version.

**Comment by WanWizard** [comment]
And that doesn't remove the existing packages from the autoloader? Even if you would add a new package to the json (and a `composer update` regenerates the autoloader class files)?

**Comment by kenjis** [comment]
Yes.

I feel wired that Composer installs dev-master of psr/log and composer/installer, but it seems specification of Composer. And the reason Composer does not install them from zip is `minimum-stability:dev`. If minimum-stability is stable (default of Composer), Composer installs them from zip.

So all composer packages are installed from zip, and we don't have to remove .git folders or edit composer.json/composer.lock.

**Comment by WanWizard** [comment]
Ok, so you opt to go back to our original plan, only include the fuel/fuel repo, and install all dependencies from "stable" to pull the zips in? 

Could you prepare a PR on the fuel/fuel 1.7/master repo with the correct composer.json? I'm out of time for the rest of the day, then I will prepare another update of the zip tonight.

**Comment by kenjis** [comment]
> Ok, so you opt to go back to our original plan, only include the fuel/fuel repo, and install all dependencies from "stable" to pull the zips in? 

No.

I hope Zip file with all composer packages, to create zip file after running `composer update`.

**Comment by kenjis** [comment]
The latest Zip file, only composer.lock has little permission.

```
-rw-------  3.0 unx     3394 tx defN 19-Aug-14 18:17 fuelphp-1.7.2/composer.lock
```

I don't know why permission is changed. Maybe your editor chages it?

**Comment by kenjis** [comment]
I sent PR.

And tested.

```
$ git clone git@github.com:kenjis/fuel-fuel.git --branch fix_minimum-stability
$ cd fuel-fuel
$ composer update
$ oil test

Tests Running...This may take a few moments.
PHPUnit 4.1.3 by Sebastian Bergmann.

Configuration read from /home/kenji/tmp/fuel-fuel/fuel/core/phpunit.xml

...............................................................  63 / 375 ( 16%)
............................................................... 126 / 375 ( 33%)
............................................................... 189 / 375 ( 50%)
....................................................F.......... 252 / 375 ( 67%)
............................................................... 315 / 375 ( 84%)
............................................................

Time: 527 ms, Memory: 21.00Mb

There was 1 failure:

1) Fuel\Core\Test_Model_Crud::test_get_connection
Failed asserting that null matches expected 'read'.

/home/kenji/tmp/fuel-fuel/fuel/core/tests/model/crud.php:35

FAILURES!                                
Tests: 375, Assertions: 446, Failures: 1.

$ composer require "twig/twig:*"
$ oil test

Tests Running...This may take a few moments.
PHPUnit 4.1.3 by Sebastian Bergmann.

Configuration read from /home/kenji/tmp/fuel-fuel/fuel/core/phpunit.xml

...............................................................  63 / 375 ( 16%)
............................................................... 126 / 375 ( 33%)
............................................................... 189 / 375 ( 50%)
....................................................F.......... 252 / 375 ( 67%)
............................................................... 315 / 375 ( 84%)
............................................................

Time: 525 ms, Memory: 21.00Mb

There was 1 failure:

1) Fuel\Core\Test_Model_Crud::test_get_connection
Failed asserting that null matches expected 'read'.

/home/kenji/tmp/fuel-fuel/fuel/core/tests/model/crud.php:35

FAILURES!                                
Tests: 375, Assertions: 446, Failures: 1.

$ find . -name .git
./.git
```

You can create Zip file after removing .git for fuel/fuel.

**Comment by WanWizard** [comment]
I can't find a .git folder in the zip.

**Comment by kenjis** [comment]
What do you mean?

The .git folder is for fuel/fuel. You remove it and create zip file. So there is no .git folder in the zip.
