### ISSUE TITLE
Migrate class cannot rollback 1st migration

### ISSUE THREAD

**Issue by mubashariqbal** [fuel/core#176]
When you're at version 1 of your database schema, doing a:

`php oil r migrate:down`

Generates:
`Error: You are already on the first migration.`

You should be allowed to rollback your first migration.

**Comment by WanWizard** [comment]
Afaik this has been fixed in develop some time ago, what version of Fuel are you using?

**Comment by mubashariqbal** [comment]
I'm running RC.2.1.

I checked the code I have with what's in Core, and they appear to be the same.
https://github.com/fuel/core/blob/master/tasks/migrate.php

**Comment by WanWizard** [comment]
don't compare with master, compare with develop.

**Comment by mubashariqbal** [comment]
I tried with the code from the develop branch (just that one file) and got the same results.  Looks like an easy fix, I'll see if I can update the code and do a pull request.

**Comment by crynobone** [comment]
I guess the problem is that `php oil r migrate --version=0` work but `php oil r migrate:down` when version currently at 1 doesn't
