### ISSUE TITLE
DB Connection Ignored

### ISSUE THREAD

**Issue by joshbrw** [fuel/core#1760]
When you do `->set_connection($name)` and run `->execute()` it seems to ignore the connection and runs on the default.

**Comment by emlynwest** [comment]
A little more info would be good. What does your config look like? Do you have any test code? And I assume this is with the DB class?

**Comment by joshbrw** [comment]
Config is set correctly as doing `->execute($connection_name)` works perfectly fine, yet doing `->set_connection($connection_name)->execute()` seems to go back to the default connection. I have no example code, and I believe the problem is inside the `Query` class.

**Comment by emlynwest** [comment]
Looking at the code it seems that `->execute()` ignores the connection set with `->set_connection()`. https://github.com/fuel/core/blob/1.8/develop/classes/database/query.php#L251

I'll have a look at a fix in an hour or so once I am home.

**Comment by andrewwheal** [comment]
@stevewest the logic at the start of both `Database_Query::compile()` and `Database::execute()` is incorrect whereby no parameter being passed doesn't use the `$connection` property if it has been set

**Comment by emlynwest** [comment]
I'll double check as a quick look at the code seems to show that it would obey `set_connection()`

https://github.com/fuel/core/blob/1.8/develop/classes/database/query.php#L222

I'll check both however, thanks for pointing that out. I have to test it but this should be a rather quick fix.

**Comment by andrewwheal** [comment]
You are correct, but passing an instance name when a connection hasn't been set would not work.

**Comment by emlynwest** [comment]
The commit above should solve both issues. Could you please test then we can close the issue.

**Comment by joshbrw** [comment]
+1

**Comment by emlynwest** [comment]
@joshbrw Do the latest commits solve your issue then?

**Comment by WanWizard** [comment]
Closed due to no response.
