### ISSUE TITLE
Escaping Table Names

### ISSUE THREAD

**Issue by joshbrw** [fuel/core#1762]
Using the ORM/Query Builder Fuel doesn't seem to wrap backticks around table names, causing table names that are already used by MySQL (e.g. `group`) to cause errors.

**Comment by emlynwest** [comment]
I have not noticed any issues. What version of fuel are you using?

**Comment by WanWizard** [comment]
If you're using the PDO driver, you need to define the identifier separator in your db.php config. Like so: https://github.com/fuel/core/blob/1.8/develop/config/db.php#L39
