### ISSUE TITLE
Why some methods in DbUtil do not pass database connection?

### ISSUE THREAD

**Issue by kanonji** [fuel/core#1767]
## Question

Do you not need to pass database connection as arguments to call methods of DB class in DbUtil?
I guess database connection is required to call mehods of DB class in DbUtil.

For example: 
- https://github.com/fuel/core/blob/1.7/master/classes/dbutil.php#L61
- https://github.com/fuel/core/blob/1.7/master/classes/dbutil.php#L120
- https://github.com/fuel/core/blob/1.7/master/classes/dbutil.php#L399

But I find some methos are not passed database connection.

For example:
- https://github.com/fuel/core/blob/1.7/master/classes/dbutil.php#L345
- https://github.com/fuel/core/blob/1.7/master/classes/dbutil.php#L375
- https://github.com/fuel/core/blob/1.7/master/classes/dbutil.php#L481
- https://github.com/fuel/core/blob/1.7/master/classes/dbutil.php#L497
- https://github.com/fuel/core/blob/1.7/master/classes/dbutil.php#L533-L542
## What I did. What error I got

```
$ php oil r migrate --packages=auth
Uncaught exception Fuel\Core\Database_Exception: invalid data source name
Callstack:
#0 /path/to/fuel/core/classes/database/pdo/connection.php(460): Fuel\Core\Database_PDO_Connection->connect()
#1 /path/to/fuel/core/classes/database/connection.php(523): Fuel\Core\Database_PDO_Connection->escape('')
#2 /path/to/fuel/core/classes/db.php(192): Fuel\Core\Database_Connection->quote('')
#3 /path/to/fuel/core/classes/dbutil.php(375): Fuel\Core\DB::quote('')
#4 /path/to/fuel/core/classes/dbutil.php(121): Fuel\Core\DBUtil::process_fields(Array)
#5 /path/to/fuel/core/classes/migrate.php(599): Fuel\Core\DBUtil::create_table('migration', Array)
#6 /path/to/fuel/core/classes/migrate.php(74): Fuel\Core\Migrate::table_version_check()
#7 [internal function]: Fuel\Core\Migrate::_init()
#8 /path/to/fuel/core/classes/autoloader.php(375): call_user_func('Migrate::_init')
#9 /path/to/fuel/core/classes/autoloader.php(249): Fuel\Core\Autoloader::init_class('Migrate')
#10 [internal function]: Fuel\Core\Autoloader::load('Migrate')
#11 /path/to/fuel/core/tasks/migrate.php(223): spl_autoload_call('Migrate')
#12 /path/to/fuel/core/tasks/migrate.php(179): Fuel\Tasks\Migrate::_run('auth', 'package')
#13 /path/to/fuel/core/base.php(457): Fuel\Tasks\Migrate->__call('run', Array)
#14 /path/to/fuel/core/base.php(457): Fuel\Tasks\Migrate->run()
#15 /path/to/fuel/packages/oil/classes/refine.php(108): call_fuel_func_array(Array, Array)
#16 [internal function]: Oil\Refine::run('migrate', Array)
#17 /path/to/fuel/packages/oil/classes/command.php(126): call_user_func('Oil\\Refine::run', 'migrate', Array)
#18 /path/to/oil(61): Oil\Command::init(Array)
#19 {main}
```

I started to think about this incident after I got this error.
## My env

|  | version |
| --- | --- |
| php | 5.5.14 |
| FuelPHP | 1.7.2 |

There is no `default` database connection in my `fuel/app/config/db.php` and `fuel/app/config/development/db.php`. My project has several databases because of vertical partitioning.
I use mysqli driver for all.

I'm new to FuelPHP. using less than a week yet.

**Comment by emlynwest** [comment]
Ideally the functions that don't have the DB instance passed through should be updated so that they do. PRs are always welcome ;)

**Comment by kanonji** [comment]
Thank you replying.
I thought it's a string of database connection name such as `default`, `master`.
Should it be instance of DB class?

**Comment by emlynwest** [comment]
It can be either. You can just pass through whatever the calling function is using.

**Comment by kanonji** [comment]
I see.

I am going to add `, $db ? $db : static::$connection` at least errors coming up with stack trace of `php oil r migrate --packages=auth`.
I will send PR when I have done fixing.
But for my project, I can not wait to FuelPHP updated.

```
$ cp fuel/core/classes/dbutil.php fuel/app/classes/
$ vi fuel/app/classes/dbutil.php # fixing some lines to pass database connection
$ php oil r migrate --packages=auth
```

I did this but got same stack trace.
It seams `fuel/app/classes/dbutil.php` is not loaded.
`fuel/app/classes/dbutil.php` is still loaded.

Is this workaround not possible?
Are there any other workaround?

**Comment by emlynwest** [comment]
You can easily extend core classes using the autoloader. http://fuelphp.com/docs/general/extending_core.html

**Comment by kanonji** [comment]
Thanks.

Now I can run `php oil r migrate --packages=auth` after only a line https://github.com/fuel/core/blob/1.7/master/classes/dbutil.php#L375 fixed.

I will send PR later in outside of business hours.

**Comment by emlynwest** [comment]
Thanks! Let me know if you are not able, this is a small fix and I can get it in place if you can't.

**Comment by kanonji** [comment]
@stevewest How about my PR?
If there are any problems, it is okay to discard my PR and fix with your commit.

**Comment by emlynwest** [comment]
Ah, sorry. Had somehow totally forgotten about this. Merging it in now,

**Comment by kanonji** [comment]
Thanks!
