### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by xrobau** [fuel/core#1770]
https://github.com/fuel/core/blob/1.8/develop/classes/request.php#L410

The code above says that when you define a router, it gets handed the request and any params to it. But the documentation says it will be handed the METHOD and then an array of params.

http://fuelphp.com/docs/general/controllers/base.html#/router

Probably a good idea to update the documentation to say use \Input::method() to get the actual method used.

**Comment by WanWizard** [comment]
Those are two different things.

When talking about creating a request, the "method" passed to forge() and to the constructor means "the HTTP method method".

When talking about the controller router() method, "method" means "the controller action method being called".
