### ISSUE TITLE
phpseclib as external dependency

### ISSUE THREAD

**Issue by michael-lefebvre** [fuel/core#1775]
Hi All,

would it be better that phpseclib was no longer included in the core framework, but instead treated as a dependency, loaded by Composer.

For example, I'm using thephpleague/flysystem as abstraction layer who depends of phpseclib too. It result  conflicts with the defined constants used in the Crypt classes. 

I dirtily fixed it in Fuelphp v1.5, but it's a real headache in 1.7.2 due to poor phpseclib's namespaces. 

thanks for your feedbacks.

**Comment by it-can** [comment]
+1

**Comment by WanWizard** [comment]
The main reason this hasn't been done, is that we use a modified version. So if we go for the stock package, we need to start overloading, and have a possible dependency hell on our hands.

**Comment by emlynwest** [comment]
I agree with @WanWizard on this. But that said I have been using flysystem with no problems with fuel `1.7.2`/`1.8/develop`

**Comment by WanWizard** [comment]
Our PHPSecLib classes live in the PHPSecLib namespace, so it can live besides the original package without problems. I just checked all classes, but none define constants in the global namespace.

**Comment by WanWizard** [comment]
Checked again. Currently the php5 branch is still under development, there is no stable version available and the dev version requires all sorts we don't know. So let's park this for now.

**Comment by WanWizard** [comment]
Implemented in https://github.com/fuel/core/commit/8f4c2804d4ba36048a22d92254b337a886f6acb2

**Comment by kenjis** [comment]
@WanWizard You added `phpseclib/phpseclib` to `fuel/fuel`. It means all existing FuelPHP 1.7.3 projects must update their `composer.json` manually. If you just run `composer update` after releasing 1.7.4, you would get the fatal error.

Why don't you move the dependency to `fuel/core`?
Is there any problem?

**Comment by WanWizard** [comment]
No, not a problem, sounds like a good idea. I'll test and update it.

**Comment by WanWizard** [comment]
Done.
