### ISSUE TITLE
Core / Validation::_validation_valid_string() -- A bug to be fixed

### ISSUE THREAD

**Issue by vmhnrj** [fuel/core#1783]
Fuel Core / validation.php file, _validation_valid_string() method has a bug.
It does not validate "newlines". I have changed this line
$pattern .= in_array('newlines', $flags) ? "\n" : '';
to
$pattern .= in_array('newlines', $flags) ? '\r\n' : '';

changes are:
1. added \r
2. and use '(single quote) instead of "(double quote)

Hope this will be fixed in next release

**Comment by emlynwest** [comment]
The new line character differs based on operating system so this would not be a valid fix.

**Comment by kenjis** [comment]
It might depend on Web browser.
You might be better to standardize new line characters to "¥n" before validation.

**Comment by WanWizard** [comment]
According to http://www.w3.org/MarkUp/html-spec/html-spec_8.html#SEC8.2.1 a newline in a multiline value must be defined as CR+LF, so this indeed seems wrong. 

A quick test on Linux, with Firefox for Linux and a local app seems to confirm this.
