### ISSUE TITLE
Validation "valid_string" alpha is not working with special chars

### ISSUE THREAD

**Issue by dercoder** [fuel/core#1784]
I am trying to validate customers last and first name so i tried this code

```
$validation->add('name', 'Name')->add_rule('valid_string', 'alpha');
```

will generate this

```
preg_match('/^([a-zA-Z])+$/u', $string);
```

But this will not work for German names like "Maierhöfer"

This Example is not working

```
if (preg_match('/^([a-zA-Z])+$/u', 'Maierhöfer')) {
    echo 'Valid';
}
```

This Example is working

```
if (preg_match('/^[[:alpha:]]+$/u', 'Maierhöfer')) {
    echo 'Valid';
}
```

**Comment by emlynwest** [comment]
Valid string's `alpha` rule only includes `a-zA-Z` you would have to add extra characters as a regex as part of the valid string's conditions.

**Comment by dercoder** [comment]
Ok but why is "('valid_string', 'alpha')" = "a-zA-Z" and not "[[:alpha:]]"?

**Comment by emlynwest** [comment]
My guess would be that the original author did not know about such a thing. Both do the same job so I don't see the issue.

**Comment by dercoder** [comment]
Its not the same because in "a-zA-Z" such letters like "äöüß" are not allowed but in "[[:alpha:]]" they are

**Comment by emlynwest** [comment]
According to the little documentation I can find after a quick google `[[:alpha:]]` only includes `a-zA-Z`. But that is not the issue, changing the behaviour of this would break backwards compatibility, it would be better if a new rule was added that includes `a-zA-Z` and accented characters.

**Comment by dercoder** [comment]
All english sites describes that `[[:alpha:]]` only includes `a-zA-Z` but on german sites they describe that it also includes other special letters like `äöü`. 

Some if them describes that this depends on setlocales but thats not true. I have installed and uninstalled many locales on my test server to detect if there is some problem when you change the locales but its working fine. So locales has no effect on this.

Its also working with arabic and turkish words like  `ستخدم` and `şifre`

I can understand backwards compatibility must be given but it would be nice to have a new rule

**Comment by emlynwest** [comment]
Ah curious, that's good to know. Thank you for the info.

A new rule would be good, I'll reopen this issue then and either yourself or someone else can implement it. It should just be a case of adding the extra handling into the validation class. https://github.com/fuel/core/blob/1.8/develop/classes/validation.php#L892

**Comment by dercoder** [comment]
I have testet this code in some PHP Versions here: http://sandbox.onlinephpfunctions.com/

`[[:alpha:]]` is working since 5.3.10

But this code is working since 5.0.5

```
if (preg_match('/^[\pL\pM]+$/u', 'Mayerhöfer')) {
    echo 'Valid';
} else {
    echo 'Invalid';
}
```

I have found this code in Laravel Framework but i dont understand this Regexp Rules
https://github.com/laravel/framework/blob/75b1dff27778354e44511556171cf6ae466c8b59/src/Illuminate/Validation/Validator.php

```
protected function validateAlpha($attribute, $value)
{
    return preg_match('/^[\pL\pM]+$/u', $value);
}

protected function validateAlphaNum($attribute, $value)
{
    return preg_match('/^[\pL\pM\pN]+$/u', $value);
}

protected function validateAlphaDash($attribute, $value)
{
    return preg_match('/^[\pL\pM\pN_-]+$/u', $value);
}
```

Maybe we should use this instead of [[:alpha:]]. What do you think?
I have also found this: http://stackoverflow.com/questions/6493954/how-to-properly-write-regex-for-unicode-first-name-in-java

**Comment by emlynwest** [comment]
Seeing that fuelPHP v1 supports only 5.3 or higher, and that 5.3 is EOL I don't see this as a problem.

**Comment by dercoder** [comment]
Yes but i think `\pL\pM` will be strict and maybe `[[:alpha:]]` can be changed in future.

**Comment by emlynwest** [comment]
I don't believe that `[:alpha:]` will be changed without good reason.

**Comment by dercoder** [comment]
But they have changed it between 5.3.3 and 5.3.10 and i have not found anything in the php changelog
Its your decision ;)

**Comment by emlynwest** [comment]
I'd say it's fine.

**Comment by dercoder** [comment]
I think it would be nice in FuelPHP v2 to use this as default for alpha and use utf8 flag to support specials chars because in the current version "alpha" will add "utf8" flag but utf8 is not supported

**Comment by emlynwest** [comment]
v2 does not actually have a "valid string" rule, it has a "regex" rule and comes with a regex builder class.
