### ISSUE TITLE
\View->set_filename() extension bug

### ISSUE THREAD

**Issue by dakorpar** [fuel/core#1787]
If I have
$this->view = View::forge();
and later I try to set filename like
$this->view->set_filename("template.twig"); it will search for template.twig.php,
but if I have
$this->view = View::forge("dummy.twig");
later I can do
$this->view->set_filename("template"); //notice that there's no .twig extension
and everything will work as expected.
I find this behavior littlebig strange.

**Comment by WanWizard** [comment]
Could you re-open it here: https://github.com/fuel/parser ?

It's not an issue with the core class, the View class in the parser package overloads the forge() method, but not the set_filename() method.
