### ISSUE TITLE
Date::time_ago() is not working out very well

### ISSUE THREAD

**Issue by goosys** [fuel/core#1795]
I think `Date::time_ago()` is not working out very well.

See the verification as I did.
https://gist.github.com/goosys/3cd14d840d5096d64c29

It has several problems like this.

>  -11 days  =  2 weeks ago
>  -18 days  =  3 weeks ago

If it is not working, I have several ideas for improving.

**Comment by WanWizard** [comment]
What exactly is the problem? That it rounds? Or that it rounds down?

**Comment by goosys** [comment]
`floor()` is better than `round()`.

> $now='2014-03-02'
> 2014-03-01      -  1 days      = 1 day ago
> 2014-02-24      -  6 days      = 6 days ago
> 2014-02-23      -  7 days      = 1 week ago
> 2014-02-17      - 13 days      = 1 week ago
> 2014-02-16      - 14 days      = 2 weeks ago
> 2014-02-10      - 20 days      = 2 weeks ago
> 2014-02-09      - 21 days      = 3 weeks ago
> 2014-02-03      - 27 days      = 3 weeks ago
> 2014-02-02      - 28 days      = 4 weeks ago
> 2014-02-01      - 29 days      = 4 weeks ago
> 2014-01-31      - 30 days      = 4 weeks ago
> 2014-01-30      - 31 days      = 1 month ago

but I think time stamp difference can not calculate month difference because number of days in month(or year) is not constant.

If it can use PHP>=5.3.0
I want to use `DateTime::diff()` for calculating month(or year) difference.

```
$datetime1 = new DateTime('2014-03-02');
$datetime2 = new DateTime('2014-02-01');
$datetime3 = new DateTime('2014-02-02');
$datetime4 = new DateTime('2014-02-03');
$interval = $datetime1->diff($datetime2);
echo $interval->format('%m month');
>> 1 month, 29 total days

$interval = $datetime1->diff($datetime3);
echo $interval->format('%m month, %a total days');
>> 1 month, 28 total days

$interval = $datetime1->diff($datetime3);
echo $interval->format('%m month, %a total days');
>> 0 month, 27 total days
```

What do you think?

**Comment by WanWizard** [comment]
It is not intended to do this, to be this specific. It's purpose is to give an indication, like for example github does on the commit date. There are indeed native PHP solutions for that, but as said, both service different purposes.
