### ISSUE TITLE
Official fuelphp-1.7.2.zip is still broken

### ISSUE THREAD

**Issue by kenjis** [fuel/core#1797]
If you download the official fuelphp-1.7.2 zip file, and if you use Composer, then Fuel won't work.
### How to reproduce

```
$ unzip fuelphp-1.7.2.zip
$ cd fuelphp-1.7.2
$ php composer.phar self-update
$ php composer.phar update
```

```
$ vi fuel/app/config/config.php
```

Change `log_threshold`.

```
'log_threshold'    => Fuel::L_ALL,

```

```
$ oil server
```

Access to `http://localhost:8000/`.

> ( ! ) Fatal error: Class 'Monolog\Logger' not found in .../fuelphp-1.7.2/fuel/core/classes/log.php on line 100
### Solution
1. Change `minimum-stability` in `composer.json` to `stable` on branch `1.7/master`. See https://github.com/fuel/fuel/pull/303
2. Clone `fuel/fuel` and run `composer install`.
3. Remove `.git` folder.
4. Make sure all file permissions are right. See https://github.com/fuel/core/issues/1755
5. Create Zip file.

`1.` makes Composer install all dependencies via Zip not via Git. So there will be no `.git` folders under `vendor` directory.
### Reference
- http://fuelphp.com/forums/discussion/13310/update-fuel-1-7-2-zip-link#Item_2
- http://qiita.com/cs_sonar/items/16948a105f03b3c3ed92

**Comment by okhayat** [comment]
I just downloaded the .zip for 1.7.2 from the site and facing this issue.
Should I just use the installer instead?

**Comment by WanWizard** [comment]
You can download the zip directly from github (https://github.com/fuel/fuel/archive/1.7/master.zip), unpack it, and run composer installer to install it's dependencies. There is a 1.7.3 on the way where this issue will be addressed.

**Comment by okhayat** [comment]
Thanks @WanWizard I just used the installer and it's working fine for now.

**Comment by WanWizard** [comment]
And in thee meantime the zip is fixed too.
