### ISSUE TITLE
Trying to set a config in app using Session::get() throws error.

### ISSUE THREAD

**Issue by tevfik6** [fuel/core#1798]
It seems like, if you try to set a config settings using Session:get(), it throws following error;

```
Fuel\Core\FuelException [ Error ]:
There is no security.output_filter defined in your application config file
```

Although, security.output_filter set in your config.

I've tested this issue in latest version(1.8/develop) as well. To reproduce the issue, all you need to do; go to `app/config.php` and change language to

``` php
'language' => Session::get('language', 'en'),
```

There are two possibilities, either intended behaviour or a bug.

**Comment by sagikazarmark** [comment]
I don't think it is intended behaviour, but I wouldn't say it is a bug. Application heavily depends on your configuration. Think about this line in `APPPATH/bootstrap.php`:
`Fuel::init('config.php');`

So I would say having code like that in the config file is not the best idea. In v2 you won't be able to do such hacks as there is no application context before loading that file, so the session is not loaded.

**Comment by WanWizard** [comment]
It's indeed neither of them. You're running into a recursion problem.

Config is loaded quite early in the framework bootstrap process, for obvious reasons. If you start using framework components in your config file that require a loaded configuration, you've got your loop.

All our apps use an 'application.php' config file, which is always loaded, and contains all custom application configuration. In there you can do things like

``` php
// languages this application supports
$supported_languages = array('nl', 'fr', 'de', 'en');

// language cookie available? And valid?
if ($language = \Cookie::get('exlang', false) and in_array($language, $supported_languages))
{
    \Config::set('language', $language);
}

// if not, perform browser language autodetection
else
{
    foreach ($supported_languages as $supported_language)
    {
        if (\Agent::accepts_language($supported_language))
        {
            \Config::set('language', $supported_language);
            break;
        }
    }
}
```
