### ISSUE TITLE
Table maintenance on InnoDB tables

### ISSUE THREAD

**Issue by RCarpac** [fuel/core#1800]
Doing a DBUtil::optimize_table on an InnoDB table gives the following error : 

<code>
Fuel\Core\FuelException [ Error ]: Invalid level "Note" passed to logger()
</code>

Her is the dump of the Database_Query object result of the function 

<code>table_maintenance($operation, $table, $db = null) in 
COREPATH/classes/dbutil.php @ line 597

Fuel\Core\Database_Result_Cached Object
(
    [_query:protected] => OPTIMIZE TABLE `mp_dummy`
    [_result:protected] => Array
(
[0] => Array
                (
                    [Table] => db.mp_dummy
                    [Op] => optimize
                    [Msg_type] => note
                    [Msg_text] => Table does not support optimize, doing recreate + analyze instead
                )

[1] => Array
                (
                    [Table] => db.mp_dummy
                    [Op] => optimize
                    [Msg_type] => status
                    [Msg_text] => OK
                )
        )
    [_total_rows:protected] => 2
    [_current_row:protected] => 0
    [_as_object:protected] => 
)
</code>

Thanks.

**Comment by WanWizard** [comment]
Hmm, interesting. The MySQL manual says:

> The Msg_type column displays one of the following values: status, error, info, or warning.

Which doesn't seen to be correct. I'll map "note" to "info", as it seems to be an informal message.
