### ISSUE TITLE
Documentation error: Namespaced REST controllers require protected $response

### ISSUE THREAD

**Issue by rickmacgillis** [fuel/core#1807]
When you use namespaced controllers, Controller_Rest does not recognize the $this->response property as valid as it's apparently out of scope when calling it from \Modulename\Controller\Classname. To solve this issue, you must define your namespaced controller a bit differently than what's in the documentation at http://fuelphp.com/docs/general/controllers/rest.html

First create a protected property named $response.

`protected $response = null;`

Now, in your before() method, set:

`$this->response = new \Response;`

You can now use the namespaced REST controller normally without the E_NOTICE and other errors.

**Comment by WanWizard** [comment]
Isn't the issue here that `if ( ! $response instanceof Response)` should be `if ( ! $response instanceof \Response)` ?
