### ISSUE TITLE
Want a way to disable automatic CSRF protection on specific pages

### ISSUE THREAD

**Issue by kenjis** [fuel/core#1808]
If I set `security.csrf_autoload` true, Fuel checks CSRF token on all post, put, delete requests.
But sometimes I don't want to check on a few specific pages.

There is no way to disable auto protection in specific pages.

I want a way to do it.

**Comment by WanWizard** [comment]
Personally I never have it set to `true`, because it will trigger very early in the framework, and you don't have a lot of control over it. Instead, we check it in the before() of our base controller, where it's also possible to define exceptions.

I think it will be very complex to implement something like this in the Security class, since it will be quite application dependent.

**Comment by kenjis** [comment]
Thanks for your comment.

I think a framework must have:
1. automatic CSRF protection to every POST/PUT/DELETE request
2. how to add exceptions

Because there are too many web applications which have no CSRF protection or missing it.
Or a lot of web developers who don't know CSRF?

This is the same approach as output filtering (default HTML escaping).

Fuel has 1. but no way to add exceptions.

**Comment by WanWizard** [comment]
Any suggestions?

Because any solution I can think of is application specific, and can therefore not be implemented in the framework. How would you explode a single form (it's POST values), without having something client-side?

**Comment by kenjis** [comment]
CSRF protection protects an action, not a form. So it is enough we can specify actions.

**Comment by kenjis** [comment]
In fact, I don't need this feature in real web applications. If any, I could work aroud using GET requests in stead of POST.

But logically it is needed, and v1 design of auto CSRF protection is not good (it will trigger too earlier in the framework). So I hope only v2 will be improved.

**Comment by emlynwest** [comment]
I would say that this issue can be closed and a feature request opened for v2.

**Comment by WanWizard** [comment]
Agreed, addressing this properly calls for a complete redesign of this functionality, which is not for v1 anymore.
