### ISSUE TITLE
The problem of DB insatace in transaction

### ISSUE THREAD

**Issue by keech** [fuel/core#1811]
## Problem

DB instance in transaction are different from the db instance made when the transaction starts.
## Details

```
$db = \Database_Connection::instance("db_id"));
$db->start_transaction();
try{
    \Model\User::regist($params);
    \Model\Rank::regist($params);

    $db->commit_transaction();

}catch(\Exception $e){
    $db->rollback_transaction();
    throw $e;
}
```

When I create database connection like below, 

```
$db = \Database_Connection::instance("db_id");
```

$db is instance of below.

```
\Config::get("db.db_id");
```

But,

```
\Model\User::regist($params);
\Model\Rank::regist($params);
```

will be used 

```
\Config::get('db.active');
```

now.
## My thinking

We should be able to use the same DB instance both DB instances in transaction and DB instance made when the transaction starts if argument of DB name is not provided.

**Comment by emlynwest** [comment]
This is not a terribly easy thing to solve with the current architecture and arguably this is an ORM issue, not a core issue. To work around this you could add a static method to your models that allows you to set their connection, thereby gaining the functionality you desire.

**Comment by keech** [comment]
Sorry for reporting in Core issue.
I'll take this issue to ORM issue.

And thank you for your advice.
I'll correspond to this issue by it.
