### ISSUE TITLE
[il8n] False positive: Test_Validation's test_error_message()

### ISSUE THREAD

**Issue by rickmacgillis** [fuel/core#1816]
Test_Validation's test_error_message() method performs tests to see if the error messages occur for the dummy post data. When someone changes the default language file, the test data is no longer valid.

**Steps to reproduce**
1. Run php oil test and get the following error:

Fuel\Core\Test_Validation::test_error_message
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'The field Title is required and must contain a value.'
+'The field Title is required.'
/fuel/core/tests/validation.php:829

**Proposed fix**

Instead of checking for the exact text, consider the following. The error_message() of \Validation checks if there's a key on the array of error messages for the field name passed to it as the first parameter. If that doesn't exist, it spits out a default value. If the error message key is in the array, it asks get_message() for the error message. If there isn't an error message attached to the key, then it returns false.

Therefore, if you pass boolean false as the default, then assert that the error message is not boolean false when it should contain the error message's text, then the assertion is no longer language file dependent and it serves the same purpose.

NOTE: Back in 2012 when version 1.5 was in development, billmn also had this issue. See: https://github.com/fuel/core/pull/1212

**Comment by WanWizard** [comment]
I can not reproduce this here. 

The current tests don't have a validation check at L#829, are you checking an old version of Fuel?

**Comment by rickmacgillis** [comment]
In 1.8 the same error message now occurs on L#900.

**Comment by kenjis** [comment]
> When someone changes the default language file,

Why do you change it? You should not change when testing.

**Comment by rickmacgillis** [comment]
The sentence is redundant, so I cleaned it up. It could conflict when people translate their websites, but for now I'm not going to translate this one.

**Comment by WanWizard** [comment]
As Kenjis said, you should not run core tests on an application install, since that will load all kinds of custom data in, specific to your application. Which causes tests to fail.
