### ISSUE TITLE
[CLI] Partial error message for Redis output

### ISSUE THREAD

**Issue by rickmacgillis** [fuel/core#1817]
In Redis_Db, readResponse() contains a switch case for all possible delimiters at the 0 place of the response string. For error messages (starting with a -), the script throws an error containing the error response starting from position 4 of the string.

`throw new \RedisException(trim(substr($reply, 4)));`

That should show the full error message without the delimiter.

`throw new \RedisException(trim(substr($reply, 1)));`

Now people will see
"Error: NOAUTH Authentication required. in /fuel/core/classes/redis/db.php on 250"
instead of
Error: "UTH Authentication required. in /fuel/core/classes/redis/db.php on 250"

I'm still working out why that message shown despite the fact that I've added a password to the config and it works perfectly even with the error message. I've debugged it a bit and I've found that some +OK responses are being returned from Redis during the php oil test. If this is a bug, I'll repot that, too.

**Comment by WanWizard** [comment]
I think initially, when the class was written, the error messages were all prefixed with "-ERR", so the code was meant to beautify the message. As this is no longer the case, I agree it has to be fixed.
