### ISSUE TITLE
\Form::select() is not UTF-8 ready

### ISSUE THREAD

**Issue by rickmacgillis** [fuel/core#1821]
**Problem**
When using foreign characters in the content of a select option tag, the tag contents are removed.

**Steps to reproduce**
1. Run:
`\Form::select('myname', null, array('AX' => 'Åland Islands'));`
2. Display its output and it's contents will be empty.

**Comment by emlynwest** [comment]
Have you seen this elsewhere in the framework? Everything uses the HTML class to build any html so if this has an issue it would be seen elsewhere too.

**Comment by rickmacgillis** [comment]
I haven't tested it elsewhere.

**Comment by WanWizard** [comment]
I can not reproduce it here, works fine here.  I generates:

``` html
<select name="myname" id="form_myname">
    <option value="AX">&Aring;land Islands</option>
</select>
```

**Comment by rickmacgillis** [comment]
My mistake. The file it resided in was not marked as UTF-8. I'm using Eclipse and the default for every project was set to UTF-8. I'm not sure how that came undone, but I reset it and everything works fine now.

**Comment by emlynwest** [comment]
Glad to hear you got your issue sorted.
