### ISSUE TITLE
DB::count_last_query errors when using on queries with subqueries

### ISSUE THREAD

**Issue by bernhardh** [fuel/core#1826]
ORM is generating the following query:

```
SELECT `t0`.`id` AS `t0_c0`, ...
FROM (
        SELECT ...
        FROM `bookmarkgroup` AS `t0` 
        WHERE `t0`.`user_id` = 1 AND `t0`.`status` = 1 ORDER BY `t0`.`name` ASC LIMIT 5
    ) AS `t0` 
LEFT JOIN `bookmark` AS `t1` ON (`t0`.`id` = `t1`.`bookmarkgroup_id`
    ) ORDER BY `t0`.`name` ASC
```

If I now afterwards run `\Db::count_last_query()´ I get a sql error since the query looks like:

```
SELECT COUNT(*) AS `total_rows` 
FROM (
    SELECT ...
    FROM (
        SELECT ...
        FROM `bookmarkgroup` AS `t0` 
        WHERE `t0`.`user_id` = 1 AND `t0`.`status` = 1 
        ORDER BY `t0`.`name` ASC AS `t0` 
    LEFT JOIN `bookmark` AS `t1` ON (`t0`.`id` = `t1`.`bookmarkgroup_id`) 
    ORDER BY `t0`.`name` ASC
) AS `counted_results`
```

The problem is, the missing ")" after "LEFT JOIN `bookmark` AS `t1`".

**Comment by bernhardh** [comment]
I am not sure, how to make a pull request, but basically the fix would be to change the file classes/database/connection.php

on line number 245 from

```
 $sql = preg_replace('/\sLIMIT\s+[^a-z]+/i', ' ', $sql);
```

to

```
 $sql = preg_replace('/\sLIMIT\s+[^a-z\)]+/i', ' ', $sql);
```

**Comment by WanWizard** [comment]
Fork the repository to your own account, edit the file (you can do that online these days), commit your change, send the commit back as a PR. :+1: 

See http://yangsu.github.io/pull-request-tutorial/ for a decent tutorial.

**Comment by emlynwest** [comment]
Github's own help pages explain it all pretty well too.

**Comment by bernhardh** [comment]
Ah, ok.. Sorry. I have just created one.
Thanks for your help.

**Comment by WanWizard** [comment]
You missed the last step, send the commit upstream as a pull request, so we can merge it.

**Comment by bernhardh** [comment]
? But you already merged it:

WanWizard   Merge pull request #1828 from bernhardh/1.8/develop …  7183871

**Comment by emlynwest** [comment]
This seems to have been committed and merged correctly.

**Comment by WanWizard** [comment]
Sorry, missed that.
