### ISSUE TITLE
Memory exhausted crypt.php

### ISSUE THREAD

**Issue by it-can** [fuel/core#1829]
@WanWizard After updating to the latest version I get this error:

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /fuel/core/classes/crypt.php on line 93
```

**Comment by it-can** [comment]
I think this line needs the have a `return` ?

https://github.com/fuel/core/blob/1.8/develop/classes/crypt.php#L93

**Comment by WanWizard** [comment]
The return is directly below it?

**Comment by WanWizard** [comment]
fixed in https://github.com/fuel/core/commit/5ba01c190dca26431f9fded825b93f37a7cb1996

**Comment by it-can** [comment]
thanks for the quick fix! Looked over the return haha
