### ISSUE TITLE
Using Crypt when crypt config is not set yet.

### ISSUE THREAD

**Issue by julesjanssen** [fuel/core#1830]
If no `config/crypt.php` file is present, this_init method will fail because `static::instance()` is called before the config values are set and therefore the constructor will fail.

**Comment by WanWizard** [comment]
Should be fixed in https://github.com/fuel/core/commit/7acd50eed79f3acdba6e599a83311bfed26ce306

**Comment by julesjanssen** [comment]
Thank you.
