### ISSUE TITLE
Credentials in memory

### ISSUE THREAD

**Issue by rickmacgillis** [fuel/core#1831]
When a database connection occurs, login data is extracted from the configuration data, but the variables created by extract() that contain the credentials are left in memory until PHP runs it's garbage collection. Consider setting every extracted variable to NULL (don't use unset()) to wipe them from memory immediately.

Why is this practice important? If someone compromises the server, they could possibly run a memory dump, then search the dump for strings, and finally have a perfectly easy to use dictionary attack for any connected infrastructure.

EDIT: Just for clarification: While someone who has access to raw memory data could probably grab all of the PHP files, consider that some people might have compiled the PHP code, while using tactics to hide credential strings. (For instance storing the passwords as ASCII numbers, and translating them to characters later.) While the credentials aren't impossible to find in the compiled code, it makes things much more inconvenient for the attacker, so they might eventually give up.

**Comment by WanWizard** [comment]
It's in the config (both in Config as in the database connection driver config), so it will remain in memory there. If you remove it from the config, you can not reconnect again. 

Don't you think that if your hacker has enough access to your server so it can do what you describe, you have worse problems then a possible memory dump decompilation?

**Comment by rickmacgillis** [comment]
It's just good practice to remove confidential information from unnecessary locations after you've finished with it. You only need the handle for the resource until the shutdown function is called, but the credentials are no longer necessary once you've established the connection.

FWIW, I admit that my example wasn't all that great, but it's not the only way someone could use that to their advantage.

**Comment by kenjis** [comment]
If an attacker could read memory of PHP, he/she can read the file which stores database credentials?

**Comment by emlynwest** [comment]
as @kenjis said, if they can get into your memory you have much bigger problems. I think this issue should be closed.

**Comment by WanWizard** [comment]
Agreed.
