### ISSUE TITLE
[Asset] Broken get_file function

### ISSUE THREAD

**Issue by kRen0** [fuel/core#1832]
After updating the framework, the function "get_file" begin to return the wrong URL's.
Sample code
`\Asset::add_path(DOCROOT.'assets/uploads/books/8231', 'doc');`
`echo \Asset::get_file('oktoih.pdf.rar', 'doc');`

Before:
http://azbyka.ru/otechnik/assets/uploads/books/8231/oktoih.pdf.rar
Now:
http://azbyka.ru/otechnik//home/azbyka_otechnik/www/azbyka.ru/otechnik/assets/uploads/books/8231/oktoih.pdf.rar

Likely to use the parameter "raw", code
`$file = str_replace(str_replace(DS, '/', DOCROOT), '', $file);`
was taken out from the "find_file" and moved to the function "render".
However, the "find_file" is invoked even in "get_file." And now it returns the URL of the site + absolute path to the file, which in most cases does not make any sense.
I think a good idea to leave the code clear the path of to "find_file" and add an additional parameter of the function to use it.

P.S. Sorry for my bad English.

**Comment by emlynwest** [comment]
Just came across this with something else and have been pulling my hair out over it. Thanks for the fix @WanWizard
