### ISSUE TITLE
Add support for dot-notation to View::set()

### ISSUE THREAD

**Issue by Art4** [fuel/core#1835]
I've seen this commit 76742eedbcf29fe020cb88115289dc401f425e61 with support for dot-notation in View::get(). Is it possible to add it to View::set() too?

**Comment by WanWizard** [comment]
Forgot to reference this issue. Implemented here: https://github.com/fuel/core/commit/239fe31fd2d6fbf49cafa4d53b41fa317375b588

**Comment by Art4** [comment]
Great. Thank you
