### ISSUE TITLE
[BEST PRACTICES] CSRF failures should issue a 400 code, not 500.

### ISSUE THREAD

**Issue by rickmacgillis** [fuel/core#1836]
CSRF validation fails due to the client sending the wrong CSRF cookie, or not sending one at all. Therefore the error occurs on the client side, not the server-side. As the server is doing what it should be (denying crap requests), consider sending a 400 Bad Request instead of a 500 Server Error.

**Comment by WanWizard** [comment]
400 is not a defined exception at the moment, so this requires quite a bit of changes, with BC consequences, so although you might have a point, I think this should be postponed and moved to v2.

**Comment by rickmacgillis** [comment]
Alright. For anyone who comes across this thread, and wants to implement this functionality with 1.7.2, you can always extend \HttpException, then write in custom HTTP status code based errors to throw. You'll need to make a wrapper for the \Security::check_token() to throw your custom error. Write your error exceptions like that of core/classes/httpexceptions.php.
