### ISSUE TITLE
Language fallback not set

### ISSUE THREAD

**Issue by it-can** [fuel/core#1839]
I have to following code in my before() function in a controller:

```
public function before()
{
    parent::before();

    // Set language
    \Config::set('language', 'it');
    \Config::set('language_fallback', 'nl');

    \Lang::load('Terms');
}
```

When I do some `print_r` in `Lang::load()` function it seems that the fallback value will always be what I entered in the config.php file...

If I call it this way it seems to work though..

```
public function before()
{
    parent::before();

    // Set language
    \Config::set('language', 'it');
    \Config::set('language_fallback', 'nl');

    \Lang::_init();
    \Lang::load('Terms');
}
```

**Comment by WanWizard** [comment]
Your fallback is your fallback, it is the main language of your application, the one that is (probably) native to you, and for which all language files are known to be present and 100% correct. You set the fallback in your config, and it should be fixed for your application.

The language is there to be changed. If you want more then one (for example use `nl_BE` as first language, `nl_NL` as second, and `en` as fallback.

**Comment by it-can** [comment]
mmm yeah makes sense... thanks
