### ISSUE TITLE
namespace in module has problem

### ISSUE THREAD

**Issue by chriskoo** [fuel/core#1844]
Hello everyone, the fuelphp is a greate framework for web development.

I've try to make a module name "bank" , write some classes with namespace "Bank" ,  everything are working fine.

When I try to modify the namespace  from "Bank" to "Company\Bank" , and also modify the code which is depency on the "bank" module, the fuelphp is show the error message , said "Class \Company\Bank" not found.

My fuelphp version is 1.7.1 , and php version is 5.6.

**Comment by WanWizard** [comment]
This is not really the place to ask questions, you should use  the forum for that.

But to answer it, you can't. A module only has a root namespace, and that must be equal to the module folder name. You can not nest modules. You can create a module called "company", and in there have a class called "Bank" (creating \Company\Bank). You can also create roles starting with "company/bank" that are mapped to the "bank" module.

**Comment by chriskoo** [comment]
thanks for your answer! :+1:
