### ISSUE TITLE
oil tasks does not output in real time

### ISSUE THREAD

**Issue by kento-furui** [fuel/core#1847]
Oil task is supposed to output in real time since 1.7 but it doesn't.
It buffers the output until the task is completely finished and flushes it all at once at the end.

**Comment by emlynwest** [comment]
Can you check against 1.8/develop? I am sure I remember seeing this being fixed at some point.

**Comment by kenjis** [comment]
This should be reported to https://github.com/fuel/oil

**Comment by kento-furui** [comment]
Tried the same script in 1.8/develop and it's fixed.
Oil task CLI outputs result line by line.

Thanks for the help.

**Comment by emlynwest** [comment]
@kento-furui It's always best to check the latest develop branch before reporting an issue.

**Comment by kento-furui** [comment]
@stevewest Yeah, but I was directed to post this here by Harro Verton himself. He thought this had been fixed on 1.7 too.

**Comment by WanWizard** [comment]
1.7.2 is older than I thought. 

It was merged in 13/7/2014, the issue was fixed on 20/8/2014. We need to get 1.7.3. out the door soon!
