### ISSUE TITLE
Validation when setting and saving nested models

### ISSUE THREAD

**Issue by MattijsKneppers** [fuel/core#1853]
In reference to [this](http://fuelphp.com/forums/discussion/comment/19185) thread:

Currently in ORM 1.8, when saving a model after setting it with an array with child arrays, saving works fine, but the validation seems to return the erroneous fields of _only one_ of either a child or the parent model that has been changed.

It would be ideal if the `get_fieldset()` method of the caught exception would contain a nested array that contains all the fields, in the base model or any of its children, that did not pass validation.

**Example**

I have two models:

```
class Model_User extends \Orm\Model
{
    protected static $_observers = array('Orm\\Observer_Validation' => array(
        'events' => array('before_save')
    ));  

    protected static $_properties = array(
        'id', 
        'username', 
        'password',
        'group',
        'email' => [
            'validation' => ['required', 'valid_email', 'max_length' => [255]]
        ]
    );

    protected static $_has_one = array('contact');   
```

and 

```
class Model_Contact extends \Orm\Model
{
    protected static $_observers = array('Orm\\Observer_Validation' => array(
        'events' => array('before_save')
    ));

    protected static $_properties = array(
        'id',
        'title',
        'user_id',
        'locale',
        'street',
        'house_number',
        'zipcode',
        'city',
        'country',
        'telephone' => [
            'validation' => ['min_length' => [10]]
        ],
        'mobile',
        'email' => [
            'validation' => ['required', 'valid_email', 'max_length' => [255]]
        ]
    );

    protected static $_belongs_to = array('user');
```

I have the following put handler:

```
        $query = Model_User::query()
            ->where('id', \Input::json('id'))
            ->related('contact');
        $user = $query->get_one();

        $user->set(\Input::json()); // Now works due to recent fix in 1.8 version of ORM!

        try {
            $user->save();
        } catch (Orm\ValidationFailed $e) {
            foreach ($e->get_fieldset()->validation()->error() as $field => $error) {
                echo "Error: " . $error->__toString() . " ";
            }
        }
```

When I PUT the following payload:

```
{"id":"2","username":"leo","group":"2","email":"foo","contact":{"title":"Leo Leeghte","street":"Westersingel","housenumber":"","city":"Rotterdam","zipcode":"3011 BG","country":"Nederland","telephone":"123","mobile":"0612345678","email":"bar","locale":"en_US"}}
```

(note that there is invalid info in the email field in the user model but also in the email field in the contact model, and additionally there is invalid info in the telephone field in the contact model)

I get only the following echo:

```
Error: The field email must contain a valid email address.
```

When all info for the user model would be valid, I would get the following echo's:

```
Error: The field telephone has to contain at least 10 characters. 
Error: The field email must contain a valid email address.
```

But I never get the errors for both the parent model _and_ the nested model.

It would be great if there was a way to get validation errors for all invalid fields at once.

**Comment by WanWizard** [comment]
Looking at this again, I think the reason behind this is, it is an exeception.

Once it is thrown, all execution (in this case validation) stops, so as long as you have validation errors in your primary model object, nothing else is being validated.

**Comment by WanWizard** [comment]
I've looked at this again, but it can't be addressed in the current architecture. Model validation happens inside the model object,  completely self-contained, and it runs separately, when each indivudual object is processed. The set of parent and children is not treated as a single entity, it's recursion into related objects.

It is perhaps something to mention at https://github.com/fuelphp/orm/issues (perhaps link back this issue), so it might be addressed in the new ORM.
