### ISSUE TITLE
[BUG] Array key names are not encoded in \Debug::dump()

### ISSUE THREAD

**Issue by rickmacgillis** [fuel/core#1856]
**The problem**
As I'm parsing Yaml documents, I chose to make my variables in the document use angle brackets so they don't interfere with the Yaml structure. Sometimes those variables are used as array keys, and they fail to show in the debug output for obvious reasons.

**Proposed solution**
Wrap the variable name for arrays with htmlentities() on [L#169 of \Debug](https://github.com/fuel/core/blob/1.8/develop/classes/debug.php#L169).

**Comment by rickmacgillis** [comment]
However, I hadn't tested that code. The referenced line in the OP is the incorrect placement for the htmlentities(). It should go on the is_string() branch at [L#204](https://github.com/fuel/core/blob/1.8/develop/classes/debug.php#L204). So, the following code is tested and working correctly.

```
$return .= "<i>{$scope}</i> <strong>".htmlentities($name)."</strong> (String): <span style=\"color:#E00000;\">\"".\Security::htmlentities($var)."\"</span> (".strlen($var)." characters)\n";
```

**Comment by WanWizard** [comment]
shouldn't it go on all branches then? If only for just-in-case?

**Comment by rickmacgillis** [comment]
Yeah, I doubt it could cause any issues. In that case, it's probably best to just place it at the top instead of each branch to keep things simple.

**Comment by WanWizard** [comment]
I prefer to do it in the branches, if only to make it clear it's encoded. Just pushed.
