### ISSUE TITLE
Unable to use multipart/form-data

### ISSUE THREAD

**Issue by rickmacgillis** [fuel/core#1857]
**The Problem**
[POST, PUT, and DELETE requests](https://github.com/fuel/core/blob/1.8/develop/classes/request/curl.php#L254) through \Request_Curl only use supported formatting types or they [default to x-www-form-urlencoded](https://github.com/fuel/core/blob/1.8/develop/classes/request/curl.php#L347) which is [terrible for longer request types](http://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data).

There currently isn't any way (that I know of) to force an array to CURLOPT_POSTFIELDS to allow for multipart/form-data requests, though every other format is possible.

**Proposed Solution**
To allow an array to be directly set to CURLOPT_POSTFIELDS, create a method to set a property flag to true when the functionality is needed. Developers can call that method when they wish to allow for such functionality.

**Comment by emlynwest** [comment]
http://fuelphp.com/dev-docs/classes/request/curl.html#/method_set_option ?

**Comment by rickmacgillis** [comment]
I saw that, but the execute function overwrites that value.

**Comment by emlynwest** [comment]
Indeed it does. It seems like the Curl request functionality does not support multi-part requests at this time. I am sure there is a good reason for this and I think it has come up before. Possibly @WanWizard can shed some light on this.

**Comment by rickmacgillis** [comment]
Perhaps @WanWizard doesn't get notified when his name is mentioned?

**Comment by WanWizard** [comment]
Yup, I do, but busy elsewhere. ;)

I assume you've tested this PR?

**Comment by rickmacgillis** [comment]
Yes I have. Use an array with the key 'array' and the desired param array as its value, and it works just fine.

**Comment by WanWizard** [comment]
Ok. I'll try to make some time later to have a look at it.
