### ISSUE TITLE
DBUtil: transactions have no effect 

### ISSUE THREAD

**Issue by MattijsKneppers** [fuel/core#1862]
It looks like DBUtil operations are not buffered within the `start_transaction()/commit_transaction()/rollback_transaction()` logic within a `try/catch`, like the DB methods are, but are committed immediately regardless of whether an error occurred.

It would be ideal if transactions could be used to prevent DBUtil actions from resulting in a halfheartedly filled database.

**Comment by WanWizard** [comment]
Can you give a code example of what you mean by operations being buffered?

As far as I can see, the DBUtil methods all run a single DB::query() with some custom generated SQL. So as far as I can see, it doesn't really matter if you run a DB or a DBUtil method, neither explicitly do anything with transactions.

**Comment by WanWizard** [comment]
@MattijsKneppers ping?

**Comment by MattijsKneppers** [comment]
Sorry for not getting back earlier. 

If neither DB or DBUtil do anything with transactions, I wonder what the purpose of transactions is. I assumed they buffer the DB and DBUtil operations in order to enable rollback when an operation fails. But perhaps I misunderstood transactions.

Unfortunately it looks like I will not have time in the near future to look into this much further.

Thanks for looking into it.

**Comment by WanWizard** [comment]
If you don't know what the purpose of transactions is, you shouldn't be using them. But I assume you mean something different.

The transaction methods in the DB class are there for you as a developer, so you can manually, start, commit or rollback a transaction in your code. And that includes DBUtil operations in your migrations. The operation itself is seldom atomic, so DBUtil itself doesn't encapsulate the SQL into a transaction. It is also rather pointless, since it's in most cases a single SQL statement, and that succeeds or fails, no transaction needed.

It would not be a bad idea to wrap the entire up() or down() migration into a DB transaction, for an automatic rollback on failure. I have to think about that.

**Comment by MattijsKneppers** [comment]
Aah, then I may have misunderstood the current implementation. Looking at [this](http://fuelphp.com/docs/classes/database/db.html#/transaction) documentation, I assumed that it would be possible to queue multiple queries and rollback when any of them failed with the caught Exception. 

When it appeared that the rollback didn't occur after errors in my migration code (and I ended up with a corrupt database after all) I assumed this was because I was using DBUtil operations, but didn't actually test whether it works as I expected with only DB operations. 

When I have more time I'll have to give this another close look, thanks for taking the time to reply.

**Comment by WanWizard** [comment]
Yes, that is correct. I didn't write anything different did I?

If you want to use this in migrations, you have to start your up() and down() method with a "start transaction", do whatever DBUtil calls you have to do, and end it with a "commit". MySQL will do an automatic rollback if the script aborts in the middle of a transaction. 

The migration engine itself doesn't wrap the up() and down() method in a transaction automatically, you have to do that yourself (but doing it automatically is maybe not a bad idea).

**Comment by MattijsKneppers** [comment]
Hehe, ok, it's getting confusing now. 

What you describe is exactly what didn't work for me. Let me first do some tests and get back to you with example code. Perhaps I simply made a mistake in the code.

Thanks again,
Mattijs

**Comment by emlynwest** [comment]
I think possibly the key point here is that fuel will not automatically roll back the transaction should a query fail. From what I understand it has to be done manually by the developer.

**Comment by WanWizard** [comment]
It might not be a bad idea to implement this for the migrate class, to wrap calls to up() or down() into a transaction. It would solve the problem of crashing migrations leaving your db in limbo...

**Comment by WanWizard** [comment]
Since a lot of databases (notably MySQL) can't wrap DDL statements in a transaction, I feel that this will give developers a "false" sense of security. So I'm not sure we should build this in as standard. People using PostgreSQL can always wrap their migrations in a transaction themselfs. @stevewest ?

**Comment by emlynwest** [comment]
Agreed, I don't think this should be built in to fuel's migrations. Perhaps we could add a `before()` and `after()` to migrations to allow generic logic wrappers when running migrations? If we do this it would be useful to be able to abort the migration from the new methods.

**Comment by WanWizard** [comment]
Aborting from `before()` seems useful, but how do you see aborting an `after()`?

**Comment by emlynwest** [comment]
Not 100% sure on the use case there but seeing that migrations are not just for the database it might be useful to have some kind of validation in there at some point or the like and it also makes its behaviour consistent with the `before()` method.

**Comment by WanWizard** [comment]
Ok. 

And what is your definition of "abort"? Currently there's only an option to return false in `up()`, which skips that migration (you may call that abort) but it is retried later. This is pretty easy to implement. Really aborting a complete migration run will be more complex.

Also, if you abort in `after()`, the `up()` migration has already run, so what do you want to do with that? Revert on abort?

**Comment by emlynwest** [comment]
Given that migrations are only re-run a limited number of times I think that the same behaviour as returning `false` on `up()` would work fine.

**Comment by WanWizard** [comment]
You can do that on `before()` without a problem, but you can't do that on `after()` without calling `down()` to revert the migration, since `up()` has already processed the migration when you get to the after method...

**Comment by emlynwest** [comment]
Good point, should be simple enough to just run the `down()` of that migration in that case.

**Comment by WanWizard** [comment]
ok
