### ISSUE TITLE
A controller namespacing issue in router.php

### ISSUE THREAD

**Issue by wolftotem4** [fuel/core#1901]
In file /fuel/core/classes/router.php (Line 276 to 296):

``` php
// determine which classes to check. First, all underscores, or all namespaced
$classes = array(
    $namespace.$prefix.\Inflector::words_to_upper(implode(substr($prefix, -1, 1), $temp_segments), substr($prefix, -1, 1)),
);

// if we're namespacing, check a hybrid version too
$classes[] = $namespace.$prefix.\Inflector::words_to_upper(implode('_', $temp_segments));

array_pop($temp_segments);

foreach ($classes as $class)
{
    if (static::check_class($class))
    {
        return array(
            'controller'    => $class,
            'action'        => isset($segments[$key + 1]) ? $segments[$key + 1] : null,
            'method_params' => array_slice($segments, $key + 2),
        );
    }
}
```

As you can see, it allows two different routes to access controller:

``` php
// determine which classes to check. First, all underscores, or all namespaced
$classes = array(
    $namespace.$prefix.\Inflector::words_to_upper(implode(substr($prefix, -1, 1), $temp_segments), substr($prefix, -1, 1)),
);
```

``` php
// if we're namespacing, check a hybrid version too
$classes[] = $namespace.$prefix.\Inflector::words_to_upper(implode('_', $temp_segments));
```

But the second one never works due to throwing error in line 288:

``` php
// It never return false if the file exists and fail to match the name of the first one.
if (static::check_class($class))
```

**Comment by WanWizard** [comment]
What  exactly is the problem? What do you want to do, why  doesn't it work, what error do you get?

**Comment by wolftotem4** [comment]
The problem is that the hybird version mentioned in comments doesn't work.

For example, if I have a controller like this.

``` php
namespace Controller;

class Admin_Login extends \Controller {
...
```

Then I will get the error:

```
"......./login.php" does not contain class "Controller\Admin\Node".
```

I guess I have to choose between "Controller\Admin\Login" and "Controller_Admin_Login",
but it means the codes in "router.php" for hybrid version never runs properly.

**Comment by WanWizard** [comment]
I can't really map this, the controller example you give does not contain the class mentioned in that error, so it's obvious you get this error?

You mean you want to use the "Controller" root namespace, and have underscored controllers, like `\Controller\Admin_Login` in `./app/classes/controller/admin/login.php`?

**Comment by wolftotem4** [comment]
Yes, `/Controller/Admin_Login` in `./app/classes/controller/admin/login.php`.  I found I should be able to do this because of commenting codes (in router.php)

``` php
// if we're namespacing, check a hybrid version too
$classes[] = $namespace.$prefix.\Inflector::words_to_upper(implode('_', $temp_segments));
```

(File: ./core/classes/router.php, Line: 281)

**Comment by WanWizard** [comment]
Ok, clear, that should indeed work.
