### ISSUE TITLE
Image class not permitting use of Imagemagick

### ISSUE THREAD

**Issue by simonberube** [fuel/core#192]
In the core image configuration, the `driver` _is_ set to `imagemagick`. Calling a method that doesn't exist in the Image class will show that the gd driver is in use. The error is: `Call to undefined method Fuel\Core\Image_Gd::blablabla()`. It should be stating that method is undefined in `Image_Imagemagick`.

I manually adjust line 51 of image.php to `$protocol = 'Imagemagick';`, I cause a 500 on my host just by trying to load and output the JPEG as in following code. However, it works with gd, just not with Imagemagick. I'm pulling a valid image and the temp file location is correct.

```
        Image::load(DOCROOT.'assets/img/myimage.jpg")
            ->output("jpeg");
```

I would recommend having a look at the core config for the image class and possibly changing the imagemagick dir and temp dir. Temp dir should definitely be `'temp_dir' => APPPATH.'tmp/',` and I would think C:\Wamp location wouldnt be good for the core config.

**Comment by jschreuder** [comment]
This should be solved once #199 is merged.
