### ISSUE TITLE
Migration changes break 5.3 compatibility.

### ISSUE THREAD

**Issue by jpudney** [fuel/core#1927]
This change ([https://github.com/fuel/core/commit/4a01393a16cf3bf8dd6b9464ee7c05759f6c9b0e]) that uses `[]` as defaults for configuration breaks support for 5.3.

Should I create a pull request to maintain compatibility with 5.3?

**Comment by emlynwest** [comment]
Good spot. A PR would be appreciated.

**Comment by WanWizard** [comment]
Indeed. So used to 5.5+ atm, really need to pay more attention to stuff like this.

**Comment by emlynwest** [comment]
Closed with #1928
