### ISSUE TITLE
SQL error with create table making index key too long

### ISSUE THREAD

**Issue by MacTwister** [fuel/core#1943]
I have a migration that used to work but after upgrading now dose not work. Below is the function that creates a SQL error `Syntax error or access violation: 1059 Identifier name __ is too long with query:`

```
\DBUtil::create_table(
    'product_types',
    array(
        'product_id' => array('constraint' => 11, 'type' => 'int', 'unsigned' => true),
        'type' => array('constraint' => 10, 'type' => 'varchar'),
        'related_product_id' => array('constraint' => 11, 'type' => 'int', 'unsigned' => true)
    ),
    array('product_id', 'type', 'related_product_id'),
    false,
    'InnoDB'
);
```

the primary key generated (notice the double key name):

```
PRIMARY KEY `product_id_type_related_product_id``product_id_type_related_product_id` (`product_id`, `type`, `related_product_id`) 
```

Commit: adf0b912d76f8b59207d078d51226cacb3f75c03 ($key_name is added twice)

**Comment by WanWizard** [comment]
I'm not sure this is the fix. For other RDBMS engines a double name is also not allowed.

I think this bug has been there for quite some time, and not discovered because most people use MySQL and that will silently ignore a name for a primary key...

**Comment by MacTwister** [comment]
I use MYSQL. I was on 1.7.2 a long time and recently updated to 1.7.3 and so now when I re-ran the migrations I get this SQL error. Or some reason not silently ignoring the primary key name.

I have a 3 column primary key, so it makes a really long name which then gets doubled makes more than 64 char long key name.

I think on line 136  /classes/dbutil.php#L136 if we remove appending the $key_name variable again resolves it, but yes I don't know the consequences.

Or anything else I can do?
