### ISSUE TITLE
Parse error: syntax error, unexpected '.' in /fuel/core/base.php on line 454

### ISSUE THREAD

**Issue by mikepmtl** [fuel/core#1952]
With new update I am getting the following error for 1.8.

Parse error: syntax error, unexpected '.' in /fuel/core/base.php on line 454

// If php is 5.6 or higher then use variadic
if (PHP_VERSION_ID >= 50600)
{
    return $instance->{$method}(...$args);
}

**Comment by WanWizard** [comment]
Guess you're on PHP < 5.6 then? Which in turn means this is not going to work...

**Comment by kenjis** [comment]
PHP 5.5 or before can't parse `...`, so the `if` can't avoid fatal error.

```
$ php base.php 

Parse error: syntax error, unexpected '.' in /path/fuel/core/base.php on line 454
```

The fix works fine.

```
$ php base.php 
$ 
```

**Comment by WanWizard** [comment]
It's time we lift the minimum version. PHP 5.4 is already end of life, and 5.5 is already in phase-out.

**Comment by kenjis** [comment]
RedHat supports PHP 5.3 until 2020. Because RHEL6 has 5.3.

**Comment by mikepmtl** [comment]
Using Ubuntu 14.04 LT for production and it's 5.5.9 by default. Keep thinking about moving to a 5.6.x package but worried about getting into any dependency issues in the future.

**Comment by WanWizard** [comment]
@kenjis what a disaster. I never use RHEL's PHP version, just because of that. I understand long-term support, but 6+ years is rediculous.
