### ISSUE TITLE
Database_Query_Builder_Insert::set() cannot call twice

### ISSUE THREAD

**Issue by nyunkrim** [fuel/core#1954]
The sample code for pre_save() (below) In the document for Model_Crud not work well.

protected function pre_save(&$query)
{
    // change the query
    $query->set(array('field' => 'value'));
}

Database_Query_Builder_Insert::set() calls column() and values().
The method column() add field names to the insert-column-list.
But the method vlaues() add data to VALUES as new record, quoting by ().
It cause SQL Syntax Error.

**Comment by WanWizard** [comment]
Correct, currently no method exist to change data already added.

This is not something that can easily addressed, as there is only one list of columns, but there could be multiple sets of values (so you can insert multiple rows are once).

If you have this use-case, it's better to assemble the record in a protected class array property, modify that in the pre_save(), and the call set() with that property to set it all in one go.

I agree the example is not correct, I will try to come up with a better one.
