### ISSUE TITLE
Repository Size

### ISSUE THREAD

**Issue by ghost** [fuel/core#1958]
This repository takes a couple lifetimes to clone. Does it make sense to put each version into a separate repository?

A person could always make their own, I suppose...

**Comment by emlynwest** [comment]
Cloning for me is a matter of a few seconds. It could be either your machine or internet connection are slow. If you want to speed things up you could use the `--depth` flag when cloning the repo.

Having each version in its own repository would make updating a nightmare as you would always be having to change your remote or composer.json.

**Comment by ghost** [comment]
Anyhow, other repositories don't take 7 minutes for me to clone, so there is something here worth investigating. I had noticed FuelPHP 2 has its own repository and thought, why not every version?

Although I don't think it would be as inconvenient as you suggest... Thanks for the confirmation.

**Comment by kenjis** [comment]
> Anyhow, other repositories don't take 7 minutes for me to clone, so there is something here worth investigating.

It takes about 40 sec for me. Is your network connection slow?

```
$ time git clone git@github.com:fuel/core.git
Cloning into 'core'...
remote: Counting objects: 31653, done.
remote: Total 31653 (delta 0), reused 0 (delta 0), pack-reused 31653
Receiving objects: 100% (31653/31653), 11.04 MiB | 292.00 KiB/s, done.
Resolving deltas: 100% (15653/15653), done.
Checking connectivity... done.

real    0m40.694s
user    0m2.616s
sys 0m0.836s
```

@stevewest 

> Cloning for me is a matter of a few seconds.

Incredible! Too fast. What is your Internet connection like?

**Comment by emlynwest** [comment]
@kenjis ![speed test](http://www.speedtest.net/result/4886130389.png)

But even on other connections I've not had to wait more than 15 seconds or so.

@wdch-nseeley The reason that v2 is in its own set of repos is that it's a total rewrite from the ground up and we've changed the way that we deal with visioning to better work with composer.

**Comment by kenjis** [comment]
@stevewest Thank you!
Your internet connection seems to be much faster than mine. Actually, my network connection is not so fast.

I tested on my server which has faster connection than my place:

```
$ time git clone https://github.com/fuel/core.git
Initialized empty Git repository in /home/foo/core/.git/
remote: Counting objects: 31653, done.
remote: Total 31653 (delta 0), reused 0 (delta 0), pack-reused 31653
Receiving objects: 100% (31653/31653), 11.04 MiB | 2.55 MiB/s, done.
Resolving deltas: 100% (15653/15653), done.

real    0m6.857s
user    0m1.520s
sys 0m0.586s
```

It took only 7 sec.

**Comment by emlynwest** [comment]
The v1 repos have a lot of history in them, if you are on a slow connection then it's best to use the `--depth` flag when doing the initial clone, this makes git exclude the history so you only get the latest version of the code, so should download quicker.

**Comment by ghost** [comment]
Composer does not work with --depth, unfortunately.
I'm looking into the problem on our end. It should not be an oauth issue, but I'll check from home this weekend.

Thanks for the help.

**Comment by kenjis** [comment]
@wdch-nseeley If you just want to install Fuel, the fastest way is to download the offical Zip file.

If you really want to install Fuel via Composer, even though you don't need to clone the repos normally when you just use Fuel.

```
$ composer create-project fuel/fuel:dev-1.7/master --prefer-dist
```
