### ISSUE TITLE
Input::post() does't provide data under certain circumstances

### ISSUE THREAD

**Issue by Art4** [fuel/core#1965]
I'm building a [JSON API](http://jsonapi.org/) server and the specification writes that [a client MUST send all requests](http://jsonapi.org/format/#content-negotiation-clients) with the header `Content-Type: application/vnd.api+json`. The `Input` class works well with this for the methods PUT, PATCH and DELETE and provide access to the data. But there is a problem with `Input::post()`.

In a POST request [PHP wraps the body to the superglobal $_POST](https://stackoverflow.com/a/8893792) only if the data is
- `application/x-www-form-urlencoded` (standard content type for simple form-posts) or
- `multipart/form-data-encoded` (mostly used for file uploads)

Because of the Content-Type `application/vnd.api+json` the data isn't wrap to $_POST, so in a POST AJAX request with a special Content-Type `Input::post()` doesn't return anything.

I've build a workaround for this extending `Input`:

``` diff
<?php

/**
 * Input class
 */
class Input extends \Fuel\Core\Input
{
    /**
     * Fetch an item from the POST array
     *
     * @param   string  The index key
     * @param   mixed   The default value
     * @return  string|array
     */
    public static function post($index = null, $default = null)
    {
-       return (func_num_args() === 0) ? $_POST : \Arr::get($_POST, $index, $default);
+       if ( ! empty($_POST) )
+       {
+           return (func_num_args() === 0) ? $_POST : \Arr::get($_POST, $index, $default);
+       }
+
+       static::$put_patch_delete === null and static::hydrate();
+       return (func_num_args() === 0) ? static::$put_patch_delete : \Arr::get(static::$put_patch_delete, $index, $default);
    }

    /**
     * Hydrates the input array
     *
     * @return  void
     */
    protected static function hydrate()
    {
        static::$input = array_merge($_GET, $_POST);
-       if (static::method() == 'PUT' or static::method() == 'PATCH' or static::method() == 'DELETE')
+       if (static::method() == 'POST' or static::method() == 'PUT' or static::method() == 'PATCH' or static::method() == 'DELETE')
        {
            static::$php_input === null and static::$php_input = file_get_contents('php://input');
            if (strpos(static::headers('Content-Type'), 'www-form-urlencoded') > 0 and \Config::get('security.form-double-urlencoded', false))
            {
                static::$php_input = urldecode(static::$php_input);
            }
            parse_str(static::$php_input, static::$put_patch_delete);
            static::$input = array_merge(static::$input, static::$put_patch_delete);
        }
        else
        {
            static::$put_patch_delete = array();
        }
    }
}
```

I wonder if there is a better way to workaround this problem and it would be nice if FuelPHP would take care of this situation.

**Comment by WanWizard** [comment]
Isn't it more logical to use `Input::json()` if your input is json?

**Comment by Art4** [comment]
You're right. I played around with `Input::json()` and realized the POST data was accidentally urlencoded. I solved this issue and can now work with `Input::json()`. Thanks. :+1:
