### ISSUE TITLE
Image::load('path/to/img.png') returns Image_Gd instance everytime.

### ISSUE THREAD

**Issue by johnnyfreeman** [fuel/core#197]
I have copied the image.php config file to my app folder. I have also set the driver (in the config) to use Imagemagick. Yet, when a run this in a controller:

``` php
var_dump( Image::load('path/to/img.png') ); die();
```

it returns an instance of Image_Gd instead of Image_Imagemagick.

I have tracked down the issue to the factory() method in the Image class. What's happening is, it should be getting the config defaults from the image.php config file.

Between lines 49 and 50 add this to fix this issue:

``` php
if (empty($config)) {
    Config::load('image', 'image');
    $config = Config::get('image');
}
```

I'll be submitting a pull request for this.

**Comment by johnnyfreeman** [comment]
Sorry, I didn't realize the pull request would automatically create a new issue. First time making a pull request on Github. :)

**Comment by jschreuder** [comment]
Closing this for #199
