### ISSUE TITLE
migration doesn't work!!

### ISSUE THREAD

**Issue by shucream0117** [fuel/core#1972]
In my environment(centos7.1, PHP7, MariaDB10.1.9), `php oil r migrate` doesn't work with following error.

```
Uncaught exception Fuel\Core\Database_Exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS ``)
)DEFAULT CHARACTER SET utf8' at line 13 [ CREATE TABLE IF NOT EXISTS `users` (
        `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT
        // some columns
        PRIMARY KEY (`id` AS ``)
)DEFAULT CHARACTER SET utf8; ]
```

PRIMARY KEY (`id` AS ``)...??????

I think it is caused by some recent commits about database(for example, like this https://github.com/fuel/core/commit/9f8d384e13480d48178da3480c3cab58bc16ef2f ).
At least, it works correctly on `af548c9ffc7dabeebdeced56e6e4a41a894cd3b8` of fuel-core.

**Comment by WanWizard** [comment]
Looks like a typo, just a sec...
