### ISSUE TITLE
Sanitizaion should be on only during View output

### ISSUE THREAD

**Issue by kenjis** [fuel/core#1973]
If we pass an instance which implements Sanitizaion to a view, the View object (output encoding) turns on sanitization automatically.

But it does not turns it off. So after rendering, sanitization of the instance is still enabled.

The below code shows how it works:

``` php
        // Orm\Model implements Sanitization interface
        $user = new Model_User();
        $user->id = 1;
        $user->username = '<s>abc</s>';
        $user->group = 1;

        // Not escaped
        var_dump($user->username);

        $data['user'] = $user;
        $view = View::forge('sanitization/index', $data);

        // Output filter htmlentities automatically turns on sanitization
        echo $view;

        // Escaped because sanitization is still on
        var_dump($user->username);

        // If we want true value, we have to turn off sanitization manually
        $user->unsanitize();
        // Not escaped
        var_dump($user->username);
```

If we save the instance in Session, we get the instance with sanitizaion enabled when next request.
Then if you get `$user->username`, you get HTML-escaped value.

The behaviour is difficult to understand. So I think we should turn off sanitization after view rendering.

**Comment by WanWizard** [comment]
The View calls `Security::clean()` on all it's variables, which in turn cleans the variables and enables sanitation.  Which means that it will require quite a bit of processing to disable sanitation. 

Given the fact that I think your use case is quite limited, as for most people the View is the end of the request, I don't want to do this by default (which would also break BC).

I'll have to give this some thought. @stevewest, what is your opinion?

**Comment by emlynwest** [comment]
If we can I think that we should turn off the sanitization after the view has been rendered. In quite a few of my projects I've constructed views in some "controller/helper" code and passed that through to a parent view, going on to reuse objects for other things later on.

**Comment by WanWizard** [comment]
I'll see if I can come up with something. I would like to control it through config, so you can enable this when needed, both to not break BC, and to avoid a performance impact for those who don't need this.

**Comment by WanWizard** [comment]
BTW, I now see that `Security::clean()` is not recursive, so if you pass a multi-dimensional array structure, it will only get a surface clean, not a deep clean. That doesn't seem to be correct?

**Comment by WanWizard** [comment]
Changing the View behavior might have side-effects. Data is being cleaned in the `get_data()` method, which by default is protected and only called before rendering the view. But in case of overloading, `get_data()` could be called without rendering the view. 

So calling unsanitize() after rendering wouldn't have the desired effect in these circumstances.

**Comment by WanWizard** [comment]
Pushed a fix. 

Can you let me know if this has any significant performance impact? If so, I would like to make it configurable. Please let me know if it works as desired, so I can modify all parser classes too...
