### ISSUE TITLE
Request_Curl throws RequestStatusException too liberally.

### ISSUE THREAD

**Issue by ghost** [fuel/core#1978]
This is perhaps an opinion, but not an unreasonable one, I hope.

Request_Curl will throw a RequestStatusException for any status code >= 400.

A perfectly normal JSON API will return all kinds of 4xx status codes with a response body. The 4xx status codes do not automatically indicate that the server exploded (that would be 5xx). Regrettably, I don't see a way to switch it off, either.

The impact is that Request->set_auto_format(true) becomes completely unusable when trying to retrieve the body of a 4xx response (the response is object is lost). As a result, I am motivated to abandon that feature entirely and handle everything by hand.

I'm not sure what the motivation was to throw on 4xx status codes. The only code comment simply says "Request failed", which ignores half the story (the body, specifically).

**Comment by ghost** [comment]
Loosing the response object is also bad if you are looking for something in the response header. Luckily I am not.

**Comment by ghost** [comment]
Erm, its the body isn't lost. The request still holds the response which holds the body. Seeing the body in the exception just confused me. Still, I would prefer not to have that exception...

**Comment by WanWizard** [comment]
HTTP responses >= 400 are not supposed to carry a response body, they are error codes. For REST purposes, the response body is still accesable using `$request->response_info('response', '');`
