### ISSUE TITLE
DB::select() doesn't return extended Database_Query_Builder_Select class

### ISSUE THREAD

**Issue by ysshir** [fuel/core#1982]
DB::select() doesn't return extended Database_Query_Builder_Select class

I'm using 1.8-dev and I have "extended Database_Query_Builder_Select" class, which is register to autoloader in bootstrap.php.
There was no problem to use until update.

DB::select() doesn't return "extended Database_Query_Builder_Select".
it returns Fuel\Core\Database_Query_Builder_Select class.

**Comment by codeChap** [comment]
If you want to extend the DB class you need to extend core/db.php and not core/database/query/builder/select.php

**Comment by ysshir** [comment]
thank you for the reply.

I actually want to extend Database_Query_Builder_Select class.
I want to use my extended Database_Query_Builder_Select class everywhere.
and it worked fine.

It looks Database_Query_Builder_Select class is created by only DB::select().
So it will be fine to extend db class and return my extend  Database_Query_Builder_Select class.

But I wonder if extending Database_Query_Builder_Select  class is bad way or not.

**Comment by codeChap** [comment]
If you want to change how the you select data from the database then yes you should be able to extend and modify the select builder class. I would assume you then use the DB class as normal. Is that what you are trying to do?

**Comment by Art4** [comment]
I think the problem is in https://github.com/fuel/core/blob/1.8/develop/classes/database/connection.php#L248

It should call the `Database_Query_Builder_Select` from the global namespace.

``` diff
    public function select(array $args = null)
    {
-       return new Database_Query_Builder_Select($args);
+       return new \Database_Query_Builder_Select($args);
    }
```

There should be the same problem with `Database_Query_Builder_Insert`, `Database_Query_Builder_Update` and `Database_Query_Builder_Delete`.

**Comment by WanWizard** [comment]
My bad, good catch!
