### ISSUE TITLE
Switching Language

### ISSUE THREAD

**Issue by tjapro** [fuel/core#1986]
Hello!
I've tried many times and I got the same problem.

Description:
I've the following configuration for language: `language = pt; language_fallback = en;`
When I forge a view in pt language, all its ok.
But when the language is "en", the following code doesn't change the `\Lang::$loaded_files`:

```
$language = 'en';
\Config::set('language', $language);
\Lang::get("title.{$this->page}", array(), 'nothing!!', $language));
```

I got "nothing!!".

Please, what I'm doing wrong?

Note: I've tried with "pt" see the `$loaded_files` and nothing is show. This only works with "en" and loaded the pt files. Why?

**Comment by WanWizard** [comment]
Fuel doesn't autoload files, so if you need multiple languages, you need to make sure they are loaded.

**Comment by tjapro** [comment]
But the "pt" default language files autoload (I added these files in config file)!
So, if I change the language, I must call the load function to reload all the files? I think this isn't explained in documentation page...

**Comment by WanWizard** [comment]
exactly, and this is why it works. Because you set the language to "pt", and you have configured some language files to autoload, these files will load for the "pt" language. And that language only. 

It will not load the language file for all available languages, since most people only want to display a page in "the users" language, and have no need for multiple languages.

1.8 has a new method, `Lang::set_lang()`, which will allow you to switch languages, and has the option to reload all loaded language files in this new language. The release of 1.8 is due in a few weeks, but you can switch to 1.8/develop now if you want.

**Comment by Art4** [comment]
>  The release of 1.8 is due in a few weeks

Nice! \o/

**Comment by kenjis** [comment]
1.8? It is 1.7.4, isn't it?

**Comment by tjapro** [comment]
Ok, I understand now. And this `Lang::set_lang()` function will be very usefull. An example: I'm in a Portuguese homepage, but I like the backoffice in English; the framework can change the language automatically.
Very thanks!
But another question: how can I update to 1.8/production (when complete) using git pull without destroy my website files?

**Comment by WanWizard** [comment]
@kenjis It will probably be 1.8.

@Art4 timing isn't fixed yet, the rewrite of the database layer needs to be finished first.

@TJProgrammer if you have git repo's locally, you need to do a "git checkout 1.8/develop" for fuel/core and all fuel packages, and you need to check the oil script and your index.php (both in fuel/fuel) for updates.

**Comment by tjapro** [comment]
Very Thank you!

**Comment by tjapro** [comment]
Hello again!
@WanWizard : I noticed `Validation` code displays the correct labels in correct language. Does this class have the missing code for `Validation` class? It's only a suggestion...

**Comment by WanWizard** [comment]
I can't comment if I don't know exactly what you did.

If you run a validation after you switched the language, the validation language strings are loaded with that switched language (which is now the current language), so it's quite logical. 

Again, Fuel doesn't automatically reload language files when you switch a language, unless you use set_lang() and instruct it to do so.

**Comment by tjapro** [comment]
Ok, thank you.
I'm waiting for the release of new version.
