### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by it-can** [fuel/core#1989]
After updating to the latest 1.9/develop (commit 3120979) I suddenly get these errors:

```
Fatal error: Call to undefined method Error::error_handler() in /fuel/core/bootstrap.php on line 103

Fatal error: Call to undefined method Error::shutdown_handler() in /fuel/core/bootstrap.php on line 71
```

using PHP 5.6.2 (it worked before on commit 24b18cd)

It seems that when I switch branches to 1.8/develop I am getting the same errors..

**Comment by emlynwest** [comment]
Make sure you check the change log. The `Error` class has been renamed for PHP7 compatibility.

**Comment by it-can** [comment]
The problem seems to be here: https://github.com/fuel/core/blob/1.9/develop/classes/fuel.php#L211

when I comment that line out, it works on php 5.6...

I also do not extend the \Error class in my app...

**Comment by emlynwest** [comment]
I've not had any reports of anyone else having issues with 5.6, are all your fuel packages and the like up to date too?

**Comment by it-can** [comment]
Yeah it is weird, have 3 projects, all of them worked yesterday and today after updating to the latest 1.9/develop give this error (also Oil and when I visit in browser)...

_UPDATE_
aah the problem is as follows:

I have this package in my composer.json

```
"phpseclib/phpseclib": "^2.0",
```

this installs `phpseclib/phpseclib 2.0.x-dev b3171cc` and `paragonie/random_compat (v2.0.2)`

when I change my composer.json file to `"phpseclib/phpseclib": "2.0.0"` it works!
