### ISSUE TITLE
View files whose name contains two dots cause a problem.

### ISSUE THREAD

**Issue by sdebacker** [fuel/core#1992]
Hello Harro,

I discovered that on FuelPHP 1.7+, in certain cases, a view file can not contain two dots in its name.
Example: If we have a file named **page.header.php**, calling `set_filename('page.header')`  will throw an exception because `pathinfo()` will consider that **header** is the extension.

Do you see a simple fix for that?

**Comment by WanWizard** [comment]
Do you have the parser package loaded?

If so, upgrade to 1.8 will fix it (has been adressed in February).

**Comment by sdebacker** [comment]
On 1.8, I have the problem even with `'parser'` set in `always_load['packages']`. Probably because we manually call the `set_filename()`method in our app.

**Comment by WanWizard** [comment]
Just as in the example above? I'll have a look.

**Comment by sdebacker** [comment]
Yes, just as the example above. Did you see the bug ?

**Comment by sdebacker** [comment]
Thank you. Would it not be useful to create a 1.8.1 version ?

**Comment by WanWizard** [comment]
Will happen in a few weeks, currently not in a position to do that.
