### ISSUE TITLE
Error with Database_PDO_Connection::set_savepoint in 1.8.0

### ISSUE THREAD

**Issue by tenda-chi** [fuel/core#1994]
1.7.2
    protected function set_savepoint($name) {
        $result = $this->_connection->exec('SAVEPOINT LEVEL'.$name);
        return $result !== false;
    }

1.8.0
    protected function set_savepoint($name)
    {
        $result = $this->_connection->exec('SAVEPOINT '.$name);
        return $result !== false;
    }

if i call DB::start_transaction twice, i got syntax error from database.

  42000 - SQLSTATE[42000]: Syntax error or access violation: 1064 You have an
  error in your SQL syntax; check the manual that corresponds to your MariaDB
  server version for the right syntax to use near '1' at line 1 in
  fuel/core/classes/database/pdo/connection.php
  on line 530

**Comment by WanWizard** [comment]
Hmm, that seems like a regression bug, I'll have to check that...

**Comment by WanWizard** [comment]
Yup: https://github.com/fuel/core/commit/b862e486a4db2dae99fbea34e3ab2d3d773ea6c1
