### ISSUE TITLE
how make multi modular in fuelphp? 

### ISSUE THREAD

**Issue by khanhnam99** [fuel/core#2000]
how make multi modular in fuelphp? 
pls ,send me a base project
i'm a new member,
Email : khanhnam99@gmail.com
thanks you!

**Comment by emlynwest** [comment]
This kind of question is best asked on the [forums](http://fuelphp.com/forums/).

As for modules there's plenty in the [documentation](http://fuelphp.com/docs/general/modules.html) and although out of date the [depot repo](https://github.com/fuel/depot/tree/1.0/develop/fuel/modules) can serve as an example of how modules might be used.

**Comment by khanhnam99** [comment]
Thanks you!
