### ISSUE TITLE
Dots in parameters

### ISSUE THREAD

**Issue by Eredrim** [fuel/core#2002]
When I pass parameters with dots (GET), the last substring is removed when I get back the variable in my controller function.

For example, if I pass the email address hello.sir@gmail.com as a parameter => controller/function/hello.sir@gmail.com, I just receive the string 'hello.sir@gmail' in my function.

**Comment by emlynwest** [comment]
Extension stripping can be disabled by setting the `routing.strip_extension` config value to `false` https://github.com/fuel/core/blob/1.9/develop/config/config.php#L307

**Comment by axelitus** [comment]
Hey @stevewest! Is this a new feature just for 1.9 version? Or does this work in previous versions also?

**Comment by emlynwest** [comment]
This feature has been around for longer than I can remember, so that's at least from 1.4 upwards. A quick look at the history shows the last change to that config item in the config file was made in 2012, so I think it's safe to say you'll be able to use it.

**Comment by WanWizard** [comment]
There is also a discussion about this here: http://fuelphp.com/forums/discussion/13750/uri-parameter-containing-dots

**Comment by WanWizard** [comment]
Maybe we should introduce this config format:

```
routing.strip_extension = array('.html', '.php'),
```

so a list of known extensions that need to be stripped.

**Comment by Eredrim** [comment]
I think the config format suggested by WanWizard is a good idea especially as I don't understand why this option is enabled by default.

**Comment by WanWizard** [comment]
It is enabled by default because that was the default behavior before this option was introduced, and we never break backward compatibility without a very good reason.

**Comment by axelitus** [comment]
Personally I've never used dots in my uris, but @WanWizard's suggestion seems right.

```
// do not strip anything
routing.strip_extension = false // or array()

// strip this extensions
routing.strip_extension = array('.html', '.php')
```

**Comment by WanWizard** [comment]
@Eredrim can you test if this solves your problem?

**Comment by Eredrim** [comment]
I tested today, it works. Thank you. I think it would be well to add the following comment above the parameter `routing.strip_extension` : 

> Set to false if you want to pass parameters containing dots to the controller.

**Comment by WanWizard** [comment]
Ok, thanks.
