### ISSUE TITLE
FuelPHP and PHP7.

### ISSUE THREAD

**Issue by iammichiel** [fuel/core#2003]
Hi all, 

I am currently trying to upgrade an application from 1.7 to 1.8. However, as the upgrade includes the PHP7 `Error` class, I cannot finish the procedure. 

Let me explain, we are using a lot of differents components in our app and one of them pulls in the `symfony/polyfill7` package. That package aims to introduce the feature of PHP7 to prior PHP7 projects. It also includes an `Error` class. The problem is that Fuel aliases the `ErrorHandler` class to the `Error` class if the class is defined. 

The following code does that in `fuel/core/classes/fuel.php` : 

``` php
        // BC FIX FOR PHP < 7.0 to make the error class available
        if (PHP_VERSION_ID < 70000)
        {
            // alias the error class to the new errorhandler
            class_alias('\Fuel\Core\Errorhandler', '\Fuel\Core\Error');

            // does the app have an overloaded Error class?
            if (class_exists('Error'))
            {
                // then alias that too
                class_alias('Error', 'Errorhandler');
            }
        }
```

As the autoloading is managed by composer, the `Error` class that is being registered as `Errorhandler` is the symfony polyfill class. Meaning that when trying to call the `Errorhandler::shutdown_handler` function this fails. 

In my opinion, this was a mistake. Assuming the user defined a `Error` class extending the existing Error class and acting on that assumption makes it very dangerous code. Reflection would have been a much better choice here. Or at least check if the class has the `shutdown_handler` function before aliasing it.

**Comment by iammichiel** [comment]
Hello,

Thanks for the correction. Indeed, your solution seems better. However, I don't understand why the issue cannot be ported to the 1.8 branch. The bug was introduced in the 1.8 version. It should be backported for users still using the 1.8 version.

**Comment by WanWizard** [comment]
I didn't say the solution can't be ported, I said we don't accept PR's on master branches. :smile: 

I'm merge it into 1.8/master and release a 1.8.0.2 hotfix over the weekend.

**Comment by iammichiel** [comment]
Hi again. Did you manage to create a hotfix version?

**Comment by WanWizard** [comment]
Just did: https://github.com/fuel/core/releases/tag/1.8.0.2

If you have a 1.8 composer.json, an `composer update` will install it automatically.

**Comment by iammichiel** [comment]
Great ! Thanks a lot !
