### ISSUE TITLE
Bug: Validation min_length doesn't catch empty value

### ISSUE THREAD

**Issue by glOOmyART** [fuel/core#2005]
Version 1.8 and 1.7.3 don't catch empty fields when validating against min_length which it should because empty value is defnitely below min_length.

core/classes/validation.php
(line 796 for 1.7.3 and line 806 for 1.8)

public function _validation_min_length($val, $length)
{
    return $this->_empty($val) || \Str::length($val) >= $length;
}

should be

public function _validation_min_length($val, $length)
{
    return ! $this->_empty($val) || \Str::length($val) >= $length;
}

to catch empty value

i changed it in the 1.8 version i'm currently using and it catches empty values too now...

**Comment by emlynwest** [comment]
"Empty" values should be checked for with the `required` rule. You should add both `min_length` and `required` to the field to get the functionality that you want.

**Comment by glOOmyART** [comment]
ok... i thought it would be better to call only one function instead of two since it's impossible to meet the min_length with an empty value, so min_length makes it required by default...
i'll put it in my extended validation class then...
thanks for clearing it up...

**Comment by emlynwest** [comment]
The overhead of the second function all is pretty much nothing in the grand scheme of things. While I understand your use case there are a couple of issues with changing the rule, first off this would break backwards compatibility and it also makes validation much less flexible as it would be impossible for a min_length field optional. (you might want the field optional but have a minimum length if a value is entered)

**Comment by glOOmyART** [comment]
you're right... i also noticed that the validation is checked one by one, so if i put required first and the value is empty, the min_length function is never called...
i was a little off the grid yesterday and 5 minutes after i posted my answer i ran into trouble :D because of the OR, as soon as the value isn't empty, the min_length is never checked...
i think i'll have to run partial validation to skip the required fields of orm models when they are not needed in a form...
sorry for trashing the tracker and thanks for your answers

**Comment by emlynwest** [comment]
No worries, happy to be of help.
