### ISSUE TITLE
Getting error after fastcgi_finish_request

### ISSUE THREAD

**Issue by Somebi** [fuel/core#2006]
Session::write();
fastcgi_finish_request();

ERROR - 2016-07-07 11:01:12 --> shutdown - Cannot modify header information - headers already sent in fuel/core/classes/cookie.php on 100

There should be some flag, which indicates, that cookie have been sent and to avoid sending it second time on script end.

**Comment by WanWizard** [comment]
Why would you call that? That would effectively terminate all further Fuel processing, which is why you get this error, you close and flush the output stream before all output is send.

**Comment by WanWizard** [comment]
If you need this to execute some server-side processes, schedule a shutdown event, and in the event method, finish the request and do your processing.
