### ISSUE TITLE
Latest commit causes Fuel 1.8 to no longer work in PHP 5.3

### ISSUE THREAD

**Issue by willpoorman** [fuel/core#2008]
Commit e8f2345 adds in syntax that does not work in PHP 5.3. 
I.e. in the COREPATH/classes/database/connection.php on line 248:
`return (new \Database_Query_Builder_Select($args))->set_connection($this);`
is not valid PHP 5.3 syntax.

Specifically, you cannot call a method from an object that was created in the same line.
See: [http://stackoverflow.com/questions/13388541/php-parse-error-syntax-error-unexpected-t-object-operator](url)

This works in PHP 5.4, but not in 5.3.

I can see that this is part of 1.9 development, but it got merged into 1.8 master and broke an app that was just created on a server running PHP 5.3. When attempting to run a migrate, this error appeared: 
![screen shot 2016-07-20 at 1 37 59 pm](https://cloud.githubusercontent.com/assets/14079950/16998542/7db9db46-4e7f-11e6-8b4c-834236402a5d.png)

**Comment by emlynwest** [comment]
Given that PHP5.3 has not been supported for a long while I think the
advice here is to upgrade to a newer php version.

It's worth updating for the speed improvements alone, not to mention the
security fixes.

**Comment by willpoorman** [comment]
I understand that and am working on it. But your website does claim fuel 1.8 works with PHP 5.3 and that is no longer true, if you get what I am saying.

**Comment by emlynwest** [comment]
Personally I would prefer to drop support for non-maintained language
versions but I suppose this is up to @WanWizard

**Comment by willpoorman** [comment]
By all means, do so. But could you please do so with update 1.9 instead of modifying 1.8 after it has been released.

**Comment by emlynwest** [comment]
Good point, I'll get a fix pushed up tomorrow morning for this.

**Comment by willpoorman** [comment]
Thank you very much Steve! Glad to see that there is progress being made on Fuel and hope the update to 1.9 and eventually 2.0 and beyond goes well
