### ISSUE TITLE
When using PDO, select result integer becomes string

### ISSUE THREAD

**Issue by watanabeyu** [fuel/core#2014]
I'm using pdo as db driver,but select result integer becomes string.

example below.

```
desc hoge;
+----+-----------+
| id | name      |
+----+-----------+
|  1 | username   |
+----+-----------+

$result = DB::select()->from(hoge)->execute()->as_array();
var_dump($result);

array(1) { [0]=> array(2) { ["id"]=> string(1) "1" ["name"]=> string(8) "username" } }
```

To fix, I rewrote core/classes/database/pdo/connection.php.

```
// Force PDO to use exceptions for all errors
$this->_config['attrs'] = array(
  \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
  \PDO::ATTR_EMULATE_PREPARES => false
);

array(1) { [0]=> array(2) { ["id"]=> int(1) ["name"]=> string(8) "username" } }
```

These methods are correct?

**Comment by WanWizard** [comment]
We can't accept that, as it will break backward compatibility. If you want that behavior, you need to pass it via your db config.

This does however expose a bug: the current code seems to overwrite any attrs you set in your db config. https://github.com/fuel/core/commit/c9743407168175520a46cde2d4d031deb8930b7a will fix that.
