### ISSUE TITLE
Model find_one_by, find_by_*, find_one_by_* return wrong results

### ISSUE THREAD

**Issue by huuphuc2401** [fuel/core#2018]
My environment is: fuelphp 1.8.0, centos 7, apache 2, php 5.4
I got some problems:
find_one_by : `display warning`, expected return `single object`
find_by_\* : return `single object` expected `array`
find_one_by_\* : return `null` expected `single object`

**Comment by WanWizard** [comment]
There are no methods called `find_one_*`, so it is logical that these don't work. `find_by_*` is an alias for find first record, so it returns an object, not an array. If you want all matches, you need to use `find_all_by_*` which does return an array.

**Comment by WanWizard** [comment]
The ORM will now throw an exception when an incorrect find method is used: https://github.com/fuel/orm/commit/284feff83ed9e7cdb6a1e898b61936d4a4dbec96
