### ISSUE TITLE
oil refine fromdb:scaffold not work with unix_socket

### ISSUE THREAD

**Issue by fdjean** [fuel/core#2029]
with

``` php
'dsn' => 'unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock;dbname=fueltest',

(I have /var/mysql/mysql.sock -> /Applications/MAMP/tmp/mysql/mysql.sock)
```

``` bash
$ set FUEL_ENV=developpement && oil refine fromdb:scaffold users
$ invalid data source name
```

work with

``` php
'dsn' => 'mysql:host=127.0.0.1;dbname=fueltest',
```

**Comment by WanWizard** [comment]
I don't think that this is limted to oil, I think the database driver doesn't support unix_socket at all, I'll have to look at it.

**Comment by WanWizard** [comment]
Just tried it here

```
    'dsn'   => 'mysql:dbname=DEV_FuelTest;unix_socket=/var/lib/mysql/mysql.sock',
```

and this works without problems. I seem to recall there was some issue with order of the fields in the DSN with certain PHP versions?

**Comment by WanWizard** [comment]
Since this is about MAMP: it's special case is documented: http://fuelphp.com/docs/installation/troubleshooting.html#oil_db_error
