### ISSUE TITLE
Missing hotfix 3 changelog in wiki

### ISSUE THREAD

**Issue by Daijobou** [fuel/core#2030]
I read here https://twitter.com/fuelphp that here is a hotfix 1.8.0.3. So I have two questions.

That changelog for hotfix 3 is in wiki still missing. Its only exists a changelog for hotfix 2
https://github.com/fuel/core/wiki/Changelog-v1.8.0-hotfix-2

Is this hotfix part of "Download v1.8.0 now!" download-package after 20.july or I must doing a update with composer?

**Comment by WanWizard** [comment]
Woops, totally forgotten. I've added it.

No, hotfixes are not part of the zip files. If you use the composer.json file supplied, it will update to the latest 1.8.x version when you run an update. If you install using composer, or clone from github, you do get the latest release.
