### ISSUE TITLE
white page on xampp with php 7.0.8

### ISSUE THREAD

**Issue by oneill78** [fuel/core#2036]
Hello,
Sorry for my english !
i have a white page after installation fuelphp 1.8 on xampp with php 7.0.8.
The same installation on my webserver show the welcome page as documentation.
I don't know the reason.
thank you for your help.

**Comment by WanWizard** [comment]
Did you check your logfiles for error messages? And run in the development environment, so error messages are displayed.

**Comment by oneill78** [comment]
Thank you for your answer,
I have 2 errors in logs :
[Thu Nov 17 00:25:40.284800 2016] [mpm_winnt:notice] [pid 9812:tid 576] AH00418: Parent: Created child process 9476
[Thu Nov 17 00:25:41.417196 2016] [mpm_winnt:notice] [pid 9476:tid 588] AH00354: Child: Starting 150 worker threads.

I have the bootstrap file on mode development but i have only a blank page without errors.

**Comment by WanWizard** [comment]
Those are standard Apache messages. Anything in Fuel's own logfiles? Make sure you have configured logging in your config.php to `Fuel::L_ALL`.

**Comment by WanWizard** [comment]
And what exactly have you installed? The zip? A git clone? Did you run composer to make sure you are updated to the latest 1.8 release (currently 1.8.0.3)?

**Comment by oneill78** [comment]
Thank you for your response.
After consult log in fuelphp (and not in apache), there isn't error. 
I have installed fuelphp with composer and zip with the same result : blank page.
To finish i have unistall xampp and install easyphp and all is right. the welcome page is displayed.
Thank you
