### ISSUE TITLE
phpunit with php 7 exits with status code 0 on fatal exceptions

### ISSUE THREAD

**Issue by iturgeon** [fuel/core#2037]
After upgrading to php7 and fuelphp 1.8, we noticed our CI builds were passing despite a unit test throwing an exception and exiting the unit tests.

Looking at the new exception handling code, it looks like nothing is explicitly exiting with a failure code in CLI mode on uncaught fatal exceptions.

My best guess points to `Fuel/Core/Errorhandler` line 237: https://github.com/fuel/core/blob/1.9/develop/classes/errorhandler.php#L237

I'm more than happy to put the PR together, but looking for advice about the best place to make sure the error code is returned.

Here's my proposal, it's solved our current problem.

```php
		# https://github.com/fuel/core/blob/1.9/develop/classes/errorhandler.php#L229
		if (\Fuel::$is_cli)
		{
			\Cli::write(\Cli::color($data['severity'].' - '.$data['message'].' in '.\Fuel::clean_path($data['filepath']).' on line '.$data['error_line'], 'red'));
			if (\Config::get('cli_backtrace'))
			{
				\Cli::write('Stack trace:');
				\Cli::write(\Debug::backtrace($e->getTrace()));
			}

			# NEW - if the error is fatal, exit with an error status
			if ($fatal)
			{
				exit(1);
			}
			return;
		}
```

**Comment by WanWizard** [comment]
Afaik a non-zero exit code was never used. I wouild personally reverse it:
```
			if ( ! $fatal)
			{
				return;
			}
			exit(1);
````
but I can't really tell you why... ;)
