### ISSUE TITLE
Windows check in sqlsrv (and other?) drivers incorrect

### ISSUE THREAD

**Issue by willpower232** [fuel/core#2039]
Newbie to fuel here, trying to make use of the sqlsrv driver in WampServer.

There is a check in the constructor of the driver class where `php_uname('s')` is checked to be equal to the string "Windows".

In my WampServer, it returns "Windows NT" so fails the check despite being the appropriate OS.

Not sure what the best way to proceed is here. I can comment it out in my copy but obviously that isn't appropriate long term.

**Comment by WanWizard** [comment]
Does this work?
````php
if (strpos(php_uname('s'), 'Windows') === false)
````

**Comment by WanWizard** [comment]
Or probably even better:
````php
if ( ! \Cli::is_winwdows())
````

**Comment by willpower232** [comment]
Thanks for that, yes the `strpos `works nicely and I'll give the `cli` a whirl next week.

We have identified other issues when making use of sqlsrv so will sort this as part of a bigger effort and probably a pull request later.

Thanks again for your help.

**Comment by WanWizard** [comment]
Much appreciated, I don't have a Windows system here and my MSSQL knowledge is ancient.

If you're going to improve the driver, know that with 1.9-dev the DButil class is also abstracted, so you can make a driver specific schema class.
