### ISSUE TITLE
Security::js_fetch_token() and Security::js_set_token() in a Twig template

### ISSUE THREAD

**Issue by notakaos** [fuel/core#2041]
I'm trying to call `Security::js_fetch_token()` and `Security::js_set_token()` in a Twig template.

in a Twig template:

```html
<!DOCTYPE html>
<html>
<head>
<!-- ... -->
</head>
<body>
<!-- ... -->
{{ Security::js_fetch_token() }}
{{ Security::js_set_token() }}
</body>
</html>
```

then

```
Twig_Error_Syntax [ Error ]:
Unexpected token "punctuation" of value ":" ("end of print statement" expected) in "welcome.twig" at line 30.
```

The error occurred.

in a Twig template:
```
{{ js_fetch_token() }}
{{ js_set_token() }}
{{ security_js_fetch_token() }}
{{ security_js_set_token() }}
{{ form_csrf() }}
```

An error occurred in either case.

I found `getFunctions()` from `Twig_Fuel_Extension` class in fuel/parser package.

https://github.com/fuel/parser/blob/1.9/develop/classes/twig/fuel/extension.php#L43-L102

It doesn't define CSRF related functions.

So, how do I call `Security::js_fetch_token()` and `Security::js_set_token()` in a Twig template?

**My Environment**:
* CentOS 6.8 on VirtualBox
* PHP 5.6.28
* FuelPHP 1.8
  * fuel/core 1.8.0.3
  * fuel/parser 1.8.0
* twig/twig v1.28.2

**Comment by Art4** [comment]
Just use `{{ form_csrf() }}` in a form. This will create a hidden field with the csrf token.

**Comment by WanWizard** [comment]
I'll add them when I have a moment, or do it yourself and send us a pull request.

**Comment by WanWizard** [comment]
https://github.com/fuel/parser/commit/7fc3807833350f5328334bf86939f67e015278f9

Please post your issues in the correct repository next time.
