### ISSUE TITLE
Excluding classes and methods from autoloading

### ISSUE THREAD

**Issue by hemor** [fuel/core#2043]
Any class inside app/classes gets auto loaded by default which is a very nice feature to have (and one of the things that made me start learning Fuel yesterday) but I needed to have some classes and methods which shouldn't be auto-loaded because I don't want them to be available globally but I couldn't get a way to do that.

What I ended up doing is to create a folder outside app/classes to save my classes which don't need to be auto-loaded and anywhere I need them, I used php require to import the file but I had to call my _init() function in all static methods cause they are no longer called by default. Thanks to tolja on irc.

IMHO, it will be nice if there is a way to easily exclude classes (and probably methods too) from being auto-loaded e.g prefixing the class or method name with exclude_ then anywhere it's needed there should be an easy way to load the class (or make the method available) ONLY within the scope of where it is needed and NOT globally.

Another option could be to have them auto-loaded but not available globally. I think this one will be faster as everything will already be loaded.

Thank you for providing this nice framework.

**Comment by WanWizard** [comment]
Imho, when you use a class in your code, you want it loaded. There is no such thing as a "non-global" class in PHP, so I'm a bit clueless as to your specific use case.

But if you want to, you can place those classes in packages (and load those only when needed), you can manually define a class to the autoloader, so you can place it outside classes and still use the autoloader (when you define the class manually), and you can place the classes in the vendor folder and use the import() function (but then be careful when you update your core).

So I think there are enough options, and I haven't seen a use case to convince me there is a valid reason not to want to autoload a class.

**Comment by hemor** [comment]
I just noticed I didn't have to call _init() from all static methods. That's nice.

**Comment by hemor** [comment]
@WanWizard  I have a config.json file which stores some basic configurations which doesn't need database tables like site name, upload folder e.t.c. A template can get the values of some of those configs (not all) but cannot edit it, all editing must be done specifically from the admin side. In order to avoid having to repeat myself doing similar things like json_decode e.t.c and to make it easier to use, I decided to create classes for parts of those json file e.g Site::name() will give you the site name while Site::set_name('new name') will change the site name inside the config file e.t.c but Site::new_name('dffhfh') shouldn't be available inside the template. Normally if the class is inside app/classes it will be available anywhere that's why I needed to restrict that by stopping autoload from loading it by default.

I like all my files grouped inside a common folder like app/classes does already, having all classes inside that folder, so I didn't want to create any class outside that folder until someone suggested it on irc I think that's probably my only option. It does what I want perfectly.


BTW this is my first php project, my boss told me to use php else I would have used python or nodejs. Even though I don't like php, I like fuel php framework and I'll most likely use it for other projects.

**Comment by WanWizard** [comment]
Still don't understand the use-case. 

What is the problem of "the class being available anywhere"? What possible "mis-use" are you afraid of?

If you have templates made my third parties that you don't trust, do not use PHP for your templates, but use a template engine, as you would do with other languages (like cheetah for Python). If you use PHP, what is stopping these untrusted parties to include your class and use still it?

Fuel supports a substantial list of template engines through the parser package, and using it doesn't require any changes to your code (the template engine used is transparent for your interaction with the View class).

**Comment by hemor** [comment]
The project is a light weight e-commerce website which we want to use for clients who just need a small e-commerce setup on their website. Using Magento or wordpress + woocommerce will add a lot of redundant functionalities on the website making it too big.

Part of the config file will include credentials for payment gateway provider and since the clients can choose to tell anyone (it might not be us) to help them design a template if they later want different design, if all functions are available globally and the template designer somehow knows the function to call to view those private credentials that would be bad, that's why I have to make sure it will only be edited from the admin side or editing the config.json manually. If the client isn't reckless then his private credentials should remain private. He might even mistakenly call the function which changes the upload folder path which then breaks the whole website. These are the kind of things I'm trying to avoid 'cos prevention is better than cure.

**Comment by WanWizard** [comment]
You may assume that a "template designer" that can write PHP templates knows at least a reasonable amount of PHP. 

So it's security by obscurity, even if the client shields all access to the application, it is peanuts to write a bit of PHP to get those credentials. Or anything else from the the filesystem, the databases, and anything else that server and the webserver user has access to.

You can only fix this by not giving the designer access to the filesystem at all, and use a template engine. That way the designer only has access to the variables your application passes on to the template, and the command syntax of that template engine. Which you can restrict if needed. 

Take for example Dwoo (http://dwoo.org/documentation/dwoo-for-designers.html) or Twig (http://twig.sensiolabs.org/doc/2.x/templates.html), two popular ones.

**Comment by hemor** [comment]
@WanWizard The template designer doesn't need access to the file system but I think using template engine will be better, thanks a lot for the suggestion.

**Comment by WanWizard** [comment]
Good luck, and give a shout when you need more help. You should also have forum access now.

**Comment by hemor** [comment]
@WanWizard Thanks.

**Comment by hemor** [comment]
@WanWizard I just noticed you're one of the core developers so I would like to say my only frustration with Fuel php (so far), the documentation isn't detailed and robust enough.

Thanks you and everyone for making everybody's life easier.

**Comment by WanWizard** [comment]
Was sort of intentional of the founder, it was his way of "deterring" novices. And we never got the manpower to really do something about that.

**Comment by JefferyHus** [comment]
@hemor Hi friend :), I just want to give my view about the fuelphp docs it is really easy and good for beginners to start using fuel as their starter, as an advanced programmer I believe you can read the core codes and understand the framework better.

**Comment by hemor** [comment]
@WanWizard oh I see. I believe Fuel php is beginner friendly because I'm a php beginner and I already understand the basics of fuel php. Though fieldset still confuses me but the good thing is I don't even have to use it.

**Comment by hemor** [comment]
@JefferyHus I'm a php beginner so I probably won't understand the advanced codes they use but when my php skills become better (if I decide to stick around), I'll try reading it to get a better understanding. I might even be able to help add 1 or 2 things.

**Comment by WanWizard** [comment]
@hemor lol, Fieldset probably is a complex part that needs getting used to. But for discussions about that, the forum is a lot better suited than an issue ticket.

**Comment by JefferyHus** [comment]
@hemor just keep on with php mate, and use the forum it is helpfull. Have a great journey on fuelphp

**Comment by hemor** [comment]
@WanWizard @JefferyHus Thanks. I will post any question I have on the forum.
