### ISSUE TITLE
Why not using Str::tr() for normal strings?

### ISSUE THREAD

**Issue by JefferyHus** [fuel/core#2045]
Hi in the core of `Str` class the function ```tr()``` accepts two arguments the first is the string that we will be translating using the second argument, my question is why this function is only used for SQL parameters such as ':param', while we could specify if we are going to use it for both sql query or just a normal string, in my case I have this string "This country has more population than !mc" so in this case if I use Str::tr():

```php
Str::tr($string, array('!mc' => $country)); // the result will be: " This country has more population than :$country "
```
I don't want to see ':', my suggestion is to add another argument such as:
```php
public function tr($string, $array = array(), $sql = false){}
// now you can check if we are transforming an sql statment string or just a normal string
```

**Comment by WanWizard** [comment]
What do you mean by "a SQL string"?

`Str::tr()` is used as a more user friendly alternative for `sprintf()`, with the option to pass an assoc array with variable->value mappings. You are just using it wrong, it is supposed to be used like so:
````php
$country = "France";
$string = "This country has more population than :mc";

// This country has more population than France
echo Str::tr($string, array('mc' => $country));  
`````
In which case it will work as advertized.

**Comment by JefferyHus** [comment]
yeah sorry I haven't read the documentation about Str class and how it should be used, though it was designed just for bindParam parameters to be translated later and replaced by values...shame!!!

**Comment by WanWizard** [comment]
No problem! ;)
