### ISSUE TITLE
Fuel v1 isn't compatible with PHP 7.1

### ISSUE THREAD

**Issue by WanWizard** [fuel/core#2051]
https://fuelphp.com/forums/discussion/14013/oil-scaffold-admin-fatal-error

**Comment by craftpip** [comment]
I got it too, 
```
Fuel\Core\PhpErrorException [ Warning ]:
A non-numeric value encountered
```
in `fuel/core/classes/date.php @ line 314`
this is for php 7.1

**Comment by WanWizard** [comment]
What is your configuration for `\Config::get('server_gmt_offset', 0);` ?

Checked the config, "server_gmt_offset" is defined as a numeric value in seconds, so it can't be a non-numeric value.

**Comment by craftpip** [comment]
```
    'server_gmt_offset' => 'UTC+5:30',
    'default_timezone'  => 'Asia/Calcutta',
```
This is my config, It worked on php 7.0.15
i have been defining 'server_gmt_offset' as a UTC offset value for my projects.

**Comment by WanWizard** [comment]
It worked because the error wasn't raised by earlier PHP version. It was just silently converted to zero.

See https://fuelphp.com/docs/general/configuration.html, "server_gmt_offset" is defined as an `int`, "The offset in seconds the server offset from gmt timestamp when time() is used.".

Luckily for you, most servers are configured correctly, and don't need an offset, so zero worked fine for you.

**Comment by craftpip** [comment]
Oh yes i get it now, sorry for my little negligence there. 👍  
Thanks for the great help and quick response!

**Comment by WanWizard** [comment]
@craftpip are you able to test if these changes fix the issue?

**Comment by craftpip** [comment]
@WanWizard As you said, the problem was with the type of the variable, should be int instead of string
```
  'server_gmt_offset' => 0,
  'default_timezone'  => null,
```
this worked for me.
