### ISSUE TITLE
Allow URI::create() to return relative URLs to work with Load Balancers

### ISSUE THREAD

**Issue by allella** [fuel/core#2055]
We're running an older version of Fuel but the problem we ran into is the same in all version so I thought to share and make a potential feature suggestion.

Our site is behind an AWS load balancer (ELB) and uses [SSL offloading](http://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html) where the SSL cert is installed at the load balancer instead of on every web server. As such, communication between the load balancer and Fuel is over http:// while traffic to/from the web browser is all https://.

We use the URI::create() function with form actions and various other places, but this method forces everything to absolute URLs by design.

Hence all our form actions are rendering http:// when we really needed it to be https:// (or relative) to avoid mixed content warnings (in Chrome) and any subsequent 301 redirects. 

More ideally, the URI::create() could allow for returning relative URLs, which should eliminate protocol confusion when you're behind a load balancer.

Would it make sense for URI:create() to have an optional parameter to request that return values be URL relative?  If there's a reason everything is forced to absolute URLs then is there a simple alternative?

Thanks,
Jim

**Comment by WanWizard** [comment]
If your webserver is behind an SSL offloader, the offloader usually passes this information on in HTTP request headers, so your application can act upon it. Amazon does this too: http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html

Fuel honours these headers, if you have enabled it in your config (key "allow_x_headers" in the "security" section), and if you didn't hardcode your "base_url" in the config. This feature was added in 2013, so if your version is not too old, it should just work.

All our web applications are behind loadbalancers as well, some http only, some with ssl offloading, and it works without problems.

**Comment by allella** [comment]
Thanks.

Embarrassed to say that we're on v1.0, but it looks like 1.6 docs added the security.allow_x_headers so we'll need to get the client to give us time to upgrade to 1.9.

Out of curiosity, is there a design reason for absolute URLs for the application's native domain name?

**Comment by WanWizard** [comment]
The only thing I can think of is that it is much easier to generate FQDN's when the app isn't installed in the document root, but somewhere deeper, so you need to generate relative paths with a prefix.

**Comment by WanWizard** [comment]
p.s. upgrading from 1.0 to 1.8 is not going to be completely painless, so make sure you to through all change logs before you start converting. If you need help, give a shout in the forums.
