### ISSUE TITLE
\File cant create dir

### ISSUE THREAD

**Issue by craftpip** [fuel/core#2056]
on windows, creating directories fails.
for example: 
```php
DOCROOT // E:\www\htdocs\fuel_path\
$s = File::create_dir(DOCROOT, $folder); // returns false.
```

The File class tries to create the directory `\E:` @ classes/file.php:206
```php
foreach (explode(DS, $new_dir) as $dir)
{
	// some security checking
	if ($dir == '.' or $dir == '..')
	{
		throw new \FileAccessException('Directory to be created contains illegal segments.');
	}
	$path .= DS.$dir;
	if ( ! is_dir($path))
	{
		try
		{
			if ( ! mkdir($path)) // this throws exception "mkdir(): Invalid argument" $path is "\E:" here
			{
				return false;
			}
			chmod($path, $chmod);
		}
		catch (\PHPErrorException $e)
		{
			// exception is caught and jumps out of the foreach
			return false;
		}
	}
}
```
Is there anything i've missed ?

Thanks

**Comment by craftpip** [comment]
I'm using Fuel version 1.8 and php 7.0.15

**Comment by WanWizard** [comment]
Should be addressed in https://github.com/fuel/core/commit/c642e6cbfb8f91b044c9965e5d22b2fecb66f098,  could you try https://github.com/fuel/core/blob/1.9/develop/classes/file.php and see if it fixes your issue?

**Comment by craftpip** [comment]
Tested it on 1.9/develop, and it fixes the issue

**Comment by WanWizard** [comment]
Cool, thanks for the feedback.
