### ISSUE TITLE
Possible bug when submiting form post data

### ISSUE THREAD

**Issue by glOOmyART** [fuel/core#2059]
I don't know if it's really a bug in fuelphp, my programming or the inspector but i noticed something strange by coincidence.  
Whenever i try to submit data from a form with csrf token enabled (don't know if that matters), which, in the process, leads to a Response::redirect_back() and i have the inspector open (chrome and firefox), it leads directly to the core 404 page and not to the app 404 page.  
As soon as i close the inspector, everything works as expected.  
  
Edit: i'm on FuelPHP 1.8.0  
  
Edit 2: i just checked it and Response::redirect() doesn't work either

**Comment by WanWizard** [comment]
You mean Ctrl-Shift-I in Chrome(ium)?

I can't reproduce it, every form in our apps contain and a csrf_token, and a redirect after succesful submission of the form.

**Comment by glOOmyART** [comment]
yes, ctrl+shift+i... chrome and firefox...  
really very strange thing...

i'm developing a barebone package with stuff i need for several of my projects like login and acl so i can be as modular as possible...  
it contains its own bootstrap.php and routes.php with \_404\_ and \_home\_ so i can develope the actual apps on top of it without writing or copying the same stuff over and over again...  
i have left the app's routes.php with an empty array and the package is listed on the always load packages in the app's config.php and since it works without the inspector (form submit, 404 and all other routes), i assume this setup is correct...

the strange thing is, that it redirects to the core 404 and not the 404 set in the package routes.php...

in the meantime, i put the sole \_404\_ in the app's routes.php and suddenly, i can submit forms even with the inspector on :O

so i did some testing and removed the app's routes.php alltogether, and it still works with the inspector on...

so it looks like somehow the inspector prevents fuelphp from mergin the package's routes.php with the app's routes.php if the app's routes.php is an empty array and therefor can't redirect to the correct route nor the correct 404 and instead loads the core's 404

so, i'm still not sure if it's a bug on my end, the inspector or fuelphp.

since this is a really rare occasion and not critical, i wouldn't mind if you consider this false positive (dammit, my second submitted issue, my second false positive, sorry :P )

**Comment by WanWizard** [comment]
That would be weird, I can't think of anything client-side that we have an influence on whether or not a package is loaded.

You have to keep the order of overload into account (true for code, config, views, etc), which is:
- core
- packages
- app
- module

So something in a package would override something in the core, something in the app would override both the package and the core definition. 

Whether or not a package is loaded is easy to debug: add a logger() call to the package bootstrap.

**Comment by glOOmyART** [comment]
so, i put in a few logger calls...

calling _https://domain.com_ without inspector:  
> INFO - 2017-04-09 12:54:54 --> package\bootstrap.php - Package bootstrap start  
INFO - 2017-04-09 12:54:54 --> package\bootstrap.php - Package bootstrap end  
INFO - 2017-04-09 12:54:54 --> package\config\routes.php - Package routes  
INFO - 2017-04-09 12:54:54 --> app\config\routes.php - App routes  
INFO - 2017-04-09 12:54:54 --> app\bootstrap.php - After Fuel::init  
INFO - 2017-04-09 12:54:54 --> Fuel\Core\Request::__construct - Creating a new main Request with URI = ""  
INFO - 2017-04-09 12:54:54 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:54:54 --> Fuel\Core\Request::execute - Setting main Request  
INFO - 2017-04-09 12:54:54 --> package\classes\controller\base.php - Package Base: before() start  
INFO - 2017-04-09 12:54:54 --> Fuel\Core\Request::__construct - Creating a new HMVC Request with URI = "nav"  
INFO - 2017-04-09 12:54:54 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:54:54 --> Fuel\Core\Request::__construct - Creating a new HMVC Request with URI = "system/widgets/switch"  
INFO - 2017-04-09 12:54:54 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:54:54 --> Fuel\Core\Request::__construct - Creating a new HMVC Request with URI = "acl/widgets/login"  
INFO - 2017-04-09 12:54:54 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:54:54 --> before end - Base  
INFO - 2017-04-09 12:54:54 --> package\bootstrap.php - Package bootstrap start  
INFO - 2017-04-09 12:54:54 --> package\bootstrap.php - Package bootstrap end  
INFO - 2017-04-09 12:54:54 --> package\config\routes.php - Package routes  
INFO - 2017-04-09 12:54:54 --> app\config\routes.php - App routes  
INFO - 2017-04-09 12:54:54 --> app\bootstrap.php - After Fuel::init  
INFO - 2017-04-09 12:54:54 --> Fuel\Core\Request::__construct - Creating a new main Request with URI = "assets/minijs"  
INFO - 2017-04-09 12:54:54 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:54:54 --> Fuel\Core\Request::execute - Setting main Request  
INFO - 2017-04-09 12:54:54 --> assets construction - minijs  
INFO - 2017-04-09 12:54:55 --> package\bootstrap.php - Package bootstrap start  
INFO - 2017-04-09 12:54:55 --> package\bootstrap.php - Package bootstrap end  
INFO - 2017-04-09 12:54:55 --> package\config\routes.php - Package routes  
INFO - 2017-04-09 12:54:55 --> app\config\routes.php - App routes  
INFO - 2017-04-09 12:54:55 --> app\bootstrap.php - After Fuel::init  
INFO - 2017-04-09 12:54:55 --> Fuel\Core\Request::__construct - Creating a new main Request with URI = "assets/minicss"  
INFO - 2017-04-09 12:54:55 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:54:55 --> Fuel\Core\Request::execute - Setting main Request  
INFO - 2017-04-09 12:54:55 --> assets construction - minicss

the exact same call _https://domain.com_ with inspector:  
> INFO - 2017-04-09 12:58:56 --> package\bootstrap.php - Package bootstrap start  
INFO - 2017-04-09 12:58:56 --> package\bootstrap.php - Package bootstrap end  
INFO - 2017-04-09 12:58:56 --> package\config\routes.php - Package routes  
INFO - 2017-04-09 12:58:56 --> app\config\routes.php - App routes  
INFO - 2017-04-09 12:58:56 --> app\bootstrap.php - After Fuel::init  
INFO - 2017-04-09 12:58:56 --> Fuel\Core\Request::__construct - Creating a new main Request with URI = "assets/minicss"  
INFO - 2017-04-09 12:58:56 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:58:56 --> Fuel\Core\Request::execute - Setting main Request  
INFO - 2017-04-09 12:58:56 --> assets construction - minicss  
INFO - 2017-04-09 12:58:56 --> package\bootstrap.php - Package bootstrap start  
INFO - 2017-04-09 12:58:56 --> package\bootstrap.php - Package bootstrap end  
INFO - 2017-04-09 12:58:56 --> package\config\routes.php - Package routes  
INFO - 2017-04-09 12:58:56 --> app\config\routes.php - App routes  
INFO - 2017-04-09 12:58:56 --> app\bootstrap.php - After Fuel::init  
INFO - 2017-04-09 12:58:56 --> Fuel\Core\Request::__construct - Creating a new main Request with URI = "assets/bootstrap-theme.min.css"  
INFO - 2017-04-09 12:58:56 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:58:56 --> Fuel\Core\Request::execute - Setting main Request  
INFO - 2017-04-09 12:58:56 --> Fuel\Core\Request::__construct - Creating a new main Request with URI = "welcome/404"  
ERROR - 2017-04-09 12:58:56 --> Compile Error - Cannot declare class Controller_Welcome, because the name is already in use in /srv/www/vhost/cms.pmj.rocks/PMJ/app/classes/controller/welcome.php on line 57  
INFO - 2017-04-09 12:59:00 --> package\bootstrap.php - Package bootstrap start  
INFO - 2017-04-09 12:59:00 --> package\bootstrap.php - Package bootstrap end  
INFO - 2017-04-09 12:59:00 --> package\config\routes.php - Package routes  
INFO - 2017-04-09 12:59:00 --> app\config\routes.php - App routes  
INFO - 2017-04-09 12:59:00 --> app\bootstrap.php - After Fuel::init  
INFO - 2017-04-09 12:59:00 --> Fuel\Core\Request::__construct - Creating a new main Request with URI = ""  
INFO - 2017-04-09 12:59:00 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:59:00 --> Fuel\Core\Request::execute - Setting main Request  
INFO - 2017-04-09 12:59:00 --> package\classes\controller\base.php - Package Base: before() start  
INFO - 2017-04-09 12:59:00 --> Fuel\Core\Request::__construct - Creating a new HMVC Request with URI = "nav"  
INFO - 2017-04-09 12:59:00 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:59:00 --> Fuel\Core\Request::__construct - Creating a new HMVC Request with URI = "system/widgets/switch"  
INFO - 2017-04-09 12:59:00 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:59:00 --> Fuel\Core\Request::__construct - Creating a new HMVC Request with URI = "acl/widgets/login"  
INFO - 2017-04-09 12:59:00 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:59:00 --> before end - Base  
INFO - 2017-04-09 12:59:00 --> package\bootstrap.php - Package bootstrap start  
INFO - 2017-04-09 12:59:00 --> package\bootstrap.php - Package bootstrap end  
INFO - 2017-04-09 12:59:00 --> package\config\routes.php - Package routes  
INFO - 2017-04-09 12:59:00 --> app\config\routes.php - App routes  
INFO - 2017-04-09 12:59:00 --> app\bootstrap.php - After Fuel::init  
INFO - 2017-04-09 12:59:00 --> Fuel\Core\Request::__construct - Creating a new main Request with URI = "assets/minijs"  
INFO - 2017-04-09 12:59:00 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:59:00 --> Fuel\Core\Request::execute - Setting main Request  
INFO - 2017-04-09 12:59:00 --> assets construction - minijs  
INFO - 2017-04-09 12:59:01 --> package\bootstrap.php - Package bootstrap start  
INFO - 2017-04-09 12:59:01 --> package\bootstrap.php - Package bootstrap end  
INFO - 2017-04-09 12:59:01 --> package\config\routes.php - Package routes  
INFO - 2017-04-09 12:59:01 --> app\config\routes.php - App routes  
INFO - 2017-04-09 12:59:01 --> app\bootstrap.php - After Fuel::init  
INFO - 2017-04-09 12:59:01 --> Fuel\Core\Request::__construct - Creating a new main Request with URI = "assets/minicss"  
INFO - 2017-04-09 12:59:01 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:59:01 --> Fuel\Core\Request::execute - Setting main Request  
INFO - 2017-04-09 12:59:01 --> assets construction - minicss  
INFO - 2017-04-09 12:59:06 --> package\bootstrap.php - Package bootstrap start  
INFO - 2017-04-09 12:59:06 --> package\bootstrap.php - Package bootstrap end  
INFO - 2017-04-09 12:59:06 --> package\config\routes.php - Package routes  
INFO - 2017-04-09 12:59:06 --> app\config\routes.php - App routes  
INFO - 2017-04-09 12:59:06 --> app\bootstrap.php - After Fuel::init  
INFO - 2017-04-09 12:59:06 --> Fuel\Core\Request::__construct - Creating a new main Request with URI = "assets/bootstrap-theme.min.css"  
INFO - 2017-04-09 12:59:06 --> Fuel\Core\Request::execute - Called  
INFO - 2017-04-09 12:59:06 --> Fuel\Core\Request::execute - Setting main Request  
INFO - 2017-04-09 12:59:06 --> Fuel\Core\Request::__construct - Creating a new main Request with URI = "welcome/404"  
ERROR - 2017-04-09 12:59:06 --> Compile Error - Cannot declare class Controller_Welcome, because the name is already in use in /srv/www/vhost/cms.pmj.rocks/PMJ/app/classes/controller/welcome.php on line 57

it makes absolutely no sense to me why the two calls should be different...  
also the line `Fuel\Core\Request::__construct - Creating a new main Request with URI = "assets/bootstrap-theme.min.css"` doesn't make any sense...  
i did a `grep -r -l "bootstrap-theme.min.css" .` on the whole vhost document directory it only occured in the log files, obviously, in a file where it is directly called from the bootstrap CDN and in the file with the list of all css files to unify...

so, for the time being, i stick with the deletion of the app's routes.php to solve this, well, let's say "anomaly"...

if you say you never had problems with this and noone else seems to have, it has to be a problem on my part...

you may close this issue... if i get any more information or proper solution for this, i'll report it back...

thanks anyway...

**Comment by WanWizard** [comment]
If you see a request for an asset, it means that the asset does not exist, and your rewrite rules will therefore rewrite the request to index.php. It should come from somewhere.

No clue where "Cannot declare class Controller_Welcome" comes from. You don't develop on Windows do you, and have some case issues (for example Welcome.php instead of welcome.php)?

**Comment by glOOmyART** [comment]
nope, i'm on linux and the welcome.php is the default coming with fuel, didn' touch it at all...

i'm fully aware if the asset or any other public directory call is not found it redirects to the index.php... i just don't know where that call comes from...

at first, i actually had the controller to unify all css/js files into one call each named assets (namespace Controller, class Assets extends \Controller, \\Controller\\Assets => pkgpath."/path/to/assets.php" in the package's bootstrap.php) so i thought this may be responsible for some conflict and renamed it unify -> still the same problem but it now tries to call unify/bootstrap-theme.min.css... wtf?!?
nowhere in my code i call a css file directly and i don't pass them to the controller over a url, they are all directly processed in the unify controller which has 2 actions, action_minicss and action_minijs and is loaded in the template with  
`<script type="text/javascript" src="https://domain.com/unify/minijs"></script>`  
and  
`<link type="text/css" rel="stylesheet" href="https://domain.com/unify/minicss" />`

2 reasons:  
1. reduce the amount of calls  
2. keep the files in the package folder for edits and hence everything in one repo (the fonts and images are copied to the public/assets folder and all paths are adapted to this layout)

i just don't understand why the inspector makes such a huge difference...

**Comment by WanWizard** [comment]
If the network tab of the inspector doesn't tell you what is requested, you can also look into something like wireshark. 

It must come from somewhere, I use these tools on a daily basis, but this behavior is new to me.

**Comment by glOOmyART** [comment]
thx for all the assistance ;)  
i was so fed up with this thing, i needed a break...

didn't understand wireshark, it was way to complicated for my problem...

but i found the solution: somehow the commented url(bootstrap-theme.min.css.map) in the bootstrap-theme.min.css got parsed and therefor produced the 404... don't know why, and actually don't care anymore...  
just deleted it and now everything works...

so it was definitely a bug on my end ;)

**Comment by WanWizard** [comment]
Good you've got it sorted!
