### ISSUE TITLE
Cached Model_Crud cannot keep is_new, is_frozen status.

### ISSUE THREAD

**Issue by ysshir** [fuel/core#2061]
Test code

    $model = Model_Crud::forge();
    $model->is_new(false);
    $model->frozen(true);

    Cache::delete('test');

    Cache::set('test', $model);
    $model2 = Cache::get('test');

    echo $model->is_new() . ' / ' . $model2->is_new() . "\n"; // different
    echo $model->frozen() . ' / ' . $model2->frozen() . "\n"; // different

I think serialize/unserialize function shoud be something like below.

    /**
     * Serializable implementation: serialize
     *
     * @return  array  model data
     */
    public function serialize() {
        $data = [
            'props' => [
                '_is_new'    => $this->_is_new,
                '_is_frozen' => $this->_is_frozen,
            ],
            'data'  => $this->_data,
        ];
        return serialize($data);
    }

    /**
     * Serializable implementation: unserialize
     *
     * @param   string  $data
     * @return  array   model data
     */
    public function unserialize($data) {
        $data = unserialize($data);

        foreach ($data['props'] as $key => $value) {
            $this->{$key} = $value;
        }
        $this->_data = $data['data'];
    }

I'm not sure why official unserialize function is setting data through __set method..
If there is reason, I would like to know.
thanks.

**Comment by WanWizard** [comment]
It isn't logical to use `__set()`. If it is overloaded in your model, model data might be pre-treated or modified twice.
