### ISSUE TITLE
To create a driver logs and unify with oil

### ISSUE THREAD

**Issue by polmartinez** [fuel/core#2066]
The management of logs is very closed in the core, we need to be able to manage from a configuration or overload, and also both oil and the log class and the function are unified.
I use https://metricsmine.com/ to handle the exceptions and I have to touch the core to be able to cover all the app errors.
Thanks

**Comment by WanWizard** [comment]
Can you explain a little bit more about what exactly you want to be able to do?

**Comment by polmartinez** [comment]
I want to use bugsnag o metricsmine to replace the system of logs to disk and also be able to trace more things like backtrace and other variables.

The problem is that the Log class is independent of the logger method (it only uses it to call the monolog instance) both on Core and finally it is impossible to do the same thing by running oil.

I can override the Log class (copy to app / classes and extend from Core/ Log) and manage the instance my way, but what I can't do yet is to capture the oil logs without modifying the print_exception method of Command class.

**Comment by WanWizard** [comment]
The current version uses Monolog to create and write logs, and the Log class has been written in such a way that you can overload Log::initialize() method to create your own monolog instance.

There is a third-party monolog handler for bugsnag (see https://github.com/Seldaek/monolog/wiki/Third-Party-Packages), perhaps there is also one for metricsmine, and if not, one of the existing ones can probably be modified to use it, as it's a matter of the correct REST API calls.

Some of our apps mainly use newRelic this way, some have a customized logger to talk to the clients internal systems (most of our apps aren't public).

I have merged your PR against oil, errors should be logged there as well.

**Comment by polmartinez** [comment]
Yes, I did an overload of Log::initialize() and I was still to solve the CLI issue, but with the modification of the PR I think it is already complete.
```

class Log extends \Fuel\Core\Log {

    public static function initialize() {

        $client = Bugsnag\Client::make("xxxx");

        $client
            ->setReleaseStage(\Fuel::$env)
            ->setBatchSending(false)
            ->setSendCode(true)
            ->setAppType(\Config::get('name'))
            ->setHostname(gethostname());

        $handler = new \MeadSteve\MonoSnag\BugsnagHandler($client);

        static::$monolog->pushHandler($handler);
    }

}

```

Thank you Harro

**Comment by WanWizard** [comment]
Ok, so you're happy now? Feel free to issue more PR's on oil if needed.
