### ISSUE TITLE
Crypt Class: fixed IV (initialization vector) is used 

### ISSUE THREAD

**Issue by arekkusu** [fuel/core#2070]
Hi,
I am no expert in cryptography but I could not help notice in the Crypt class that the IV is a fixed value. ("crypto_iv"). I don't understand why a random IV is not used.

My understanding is that a random IV should be used every time a message is encrypted with the same key. If the same key and IV are (re)used, they encrypting the same cleartext message with result in the same encrypted message which is a big issue in cryptography. I suspect this might depend somewhat on the exact cipher used.

Bellow are a few link discussing this. I also remember Bruce Schneier book "Cryptography Engineering" mentioning this.

http://www.cryptofails.com/post/70059609995/crypto-noobs-1-initialization-vectors
https://www.schneier.com/blog/archives/2005/01/microsoft_rc4_f.html
https://stackoverflow.com/questions/5108607/encryption-use-of-initialization-vector-vs-key

Also here is an example from phpseclib which shows using a random IV.

http://phpseclib.sourceforge.net/crypt/examples.html

I want to point out that I am unsure of the exact use of crypto in FuelPHP. My understanding is that it is used to encrypt cookie. I don't know how critical that that is to overall security.

Please let me know if I am missing something, there is good reason to use a fixed IV here. My cryptography related reading tells me this is bad practice.

**Comment by WanWizard** [comment]
It does use a random IV, but it doesn't use a random IV per message. I'm afraid it won't be that easy to implement that  without breaking BC, this needs a proper think...

**Comment by WanWizard** [comment]
Has been adressed by replacing the crypto methods by Sodium encryption: https://github.com/fuel/core/commit/59112c96d0a6f2b0ead6a57edd8ac465678bdcb0
