### ISSUE TITLE
File::open_file() valid lock pattern is wrong

### ISSUE THREAD

**Issue by RyutaKojima** [fuel/core#2074]
I think the value passed to `flock` is incorrect.

### Expected pattern
- LOCK_SH
- LOCK_EX
- LOCK_SH | LOCK_NB
- LOCK_EX | LOCK_NB

### Current valid pattern
- LOCK_SH
- LOCK_EX
- LOCK_NB

`LOCK_NB` can't be used alone.

`File::open_file('example.txt', LOCK_NB);`
**Fuel\Core\PhpErrorException: flock(): Illegal operation argument**

thanks.

**Comment by WanWizard** [comment]
Works fine here?
```
$ oil console
Fuel 1.9-dev - PHP 7.1.9 (cli) (Sep  6 2017 11:45:02) [Linux]
>>> touch('/tmp/test.tst');
true
>>> $x = File::open_file('/tmp/test.tst', LOCK_NB);
>>> var_dump($x);
/data/dev/fuelphp/1.9/develop/fuel/packages/oil/classes/console.php(116) : eval()'d code:1:
resource(42) of type (stream)
>>> fclose($x);
true
>>> 
````
What platform are you using? There are issues with LOCK_NB on certain Windows versions.

**Comment by RyutaKojima** [comment]
Sorry. Infomation was insufficient.

$ php oil console
> Fuel 1.9-dev - PHP 7.1.10 (cli) (Sep 27 2017 07:12:42) [Linux]

It seems that you need a configuration file to enable locking.
Add file `fuel/app/config/file.php`.
```php
<?php
return array(
    'base_config' => array(
        'use_locks' => 1,
    ),
);
```
run
```php
var_dump( touch('/tmp/test.tst') );
//>>> (true)

$x = \File::open_file('/tmp/test.tst', LOCK_NB);
//>>> Uncaught exception Fuel\Core\PhpErrorException: flock(): Illegal operation argument

var_dump($x);
```

**Comment by WanWizard** [comment]
Darn, you're right. Good find!
