### ISSUE TITLE
filetype(): Lstat failed

### ISSUE THREAD

**Issue by cinemaforay** [fuel/core#2076]
Please refer to the following discussion.
https://fuelphp.com/forums/discussion/comment/11037
The issue is five years old, but it has not been resolved yet.

I am not sure how this can be reliably reproduced.  For that, I will try to talk to my colleague who is more familiar with this issue.

**Comment by WanWizard** [comment]
Ok, I'll wait for the response. Could you also ask:
- what platform (OS, webserver) and what PHP version?
- which Fuel version is in use?
- whether or not open_basedir is in use?
- for the exact error message?

**Comment by cinemaforay** [comment]
Thank you.  I have passed those questions on to my colleague.

**Comment by cinemaforay** [comment]
- what platform (OS, webserver) and what PHP version?
[root@redacted-prod-main ~]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[root@redacted-prod-main ~]# php -v
PHP 7.0.6 (cli) (built: Apr 28 2016 22:26:18) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
[root@redacted-prod-main ~]# httpd -v
Server version: Apache/2.4.6 (CentOS)
Server built:   Nov 19 2015 21:43:13

- which Fuel version is in use?
1.8

- whether or not open_basedir is in use?
open_basedir is not in use.

- for the exact error message?
ERROR - 2017-10-29 21:09:25 --> shutdown - filetype(): Lstat failed for /tmp/fuelfid_0b3553636f1f5375c50881176b07044e in /var/www/redacted/production/fuel/core/classes/session/file.php on 231

**Comment by WanWizard** [comment]
Can you ask to check, when this happens, whether or not that file (/tmp/fuelfid_0b3553636f1f5375c50881176b07044e) really exists?

Also, /tmp isn't a very secure place to store session files...

**Comment by cinemaforay** [comment]
Thank you for your feedback.  I've asked my colleague about that, and I'll try to get back to you when he replies.

**Comment by cinemaforay** [comment]
It might take a while to reproduce the error because it seems to happen only under specific circumstances.

**Comment by WanWizard** [comment]
No worries, I'll just leave this issue open for the moment.

**Comment by cinemaforay** [comment]
The issue has reappeared and now occurs every few hours.
The issue is intermittent and hard to reproduce reliably.
We have restarted Apache and the instance, and the issue did not go away.
Do you have any pointers?

**Comment by WanWizard** [comment]
It looks like this is about server side session files? The error means the file no longer exists, do you have some process that cleans out /tmp, or otherwise deletes those files outside of the application?

It's probably not a good idea to write session files to /tmp anyway, given the fact it's volatile storage, and uses memory.

**Comment by cinemaforay** [comment]
Files like `/tmp/fuelfid_0b3553636f1f5375c50881176b07044e` did not exist when they were checked within a few hours of an incident.

**Comment by WanWizard** [comment]
So what deletes them?

The code does:
````
				while (($file = readdir($handle)) !== false)
				{
					if (filetype($this->config['path'] . $file) == 'file' and
						strpos($file, $this->config['cookie_name'].'_') === 0 and
						filemtime($this->config['path'] . $file) < $expire)
					{
						@unlink($this->config['path'] . $file);
					}
				}

				closedir($handle);
````
so something deletes the file between the moment the directory is scanned and the moment the loop starts processing the file.

Does your application have lots of requests perhaps, and you do have a high gc probablility configured? I can imagine a race condition where multiple requests decide, at the same time, to do a garbage cleanup.

It's probably easiest to mitigate by using
````
if (file_exists($this->config['path'] . $file) and filetype($this->config['path'] . $file) == 'file' and
````

**Comment by cinemaforay** [comment]
>The error means the file no longer exists, do you have some process that cleans out /tmp, or otherwise deletes those files outside of the application?
I will check this with my colleagues.

Are you also suggesting that we should change the path parameter to somewhere other than `/tmp`? The default is `/tmp`.
https://fuelphp.com/docs/classes/session/config.html

Thank you for your help.

**Comment by WanWizard** [comment]
It is up to you, and depends on your situation and use case. 

Using /tmp means you loose all session data when you restart the server (as /tmp is volatile in CentOS), and as a tmpfs is used for /tmp, files are effectively stored in memory. Not an issue with a few MB of files, could be a big issue if you start to have GB's in session files...

We had to pick a default, and /tmp always exists. :smirk:

**Comment by cinemaforay** [comment]
>Does your application have lots of requests perhaps, and you do have a high gc probablility configured?

We have about a few thousand simultaneous users at peak hours. I am checking gc probability.

**Comment by WanWizard** [comment]
A few thousand an hour, or a few thousand concurrent? 

gc is defined as a probability percentage, so even at 1, it means it runs at 1% of the requests, which with a few thousand concurrent is still every second.

If that is the case, it might be better to set gc_probability to 0, and do a cleanup ourside of the app, for example using a nightly task via cron.

**Comment by cinemaforay** [comment]
I am sorry about my previous ambiguous statement.
To be more specific, I meant a few thousand concurrent users reported under the real-time report in Google Analytics.

**Comment by WanWizard** [comment]
With that many concurrent users, I would disable gc in the app, and create a batch process to remove stale session files.

**Comment by cinemaforay** [comment]
`gc_probability` was set at 1 in `php.ini`.

**Comment by WanWizard** [comment]
You need to look in your application session config: https://github.com/fuel/core/blob/1.9/develop/config/session.php#L286

**Comment by cinemaforay** [comment]
Thank you for pointing out my mistake.
gc_probability was set at 5 at /var/www/redacted/production/fuel/core/config

```
                'gc_probability'        =>      5,                                              // probability % (between 0 and 100) for garbage collection
```

**Comment by cinemaforay** [comment]
>as a tmpfs is used for /tmp

In our case, `/dev/vda3` is used for `/tmp`.

**Comment by WanWizard** [comment]
> > as a tmpfs is used for /tmp
> 
> In our case, `/dev/vda3` is used for `/tmp`.

Ok, then the issues don't apply.

**Comment by cinemaforay** [comment]
The errors went away after setting `gc_probability` to 0.
Do you accept a donation via PayPal or other means?
I want to thank you personally!

**Comment by WanWizard** [comment]
You're welcome.

I don't take money personally, but the project does: https://fuelphp.com/contribute/donate

**Comment by cinemaforay** [comment]
I made a payment to `paypal<at>fuelphp.com`.
Thank you!

**Comment by WanWizard** [comment]
Thanks very much, much appreciated!

And don't forget to create some form of garbage collection, otherwise your tmp will continue to grow with stale session files.

Best is probably to create something using the code in https://github.com/fuel/core/issues/2076#issuecomment-550563696 as the basis, and delete files that have a modified time older than time() - your session expiration time (meaning those files contain an expired session and can safely be deleted).
