### ISSUE TITLE
Using DB::query($query, DB::SELECT)->cached(360) causes error

### ISSUE THREAD

**Issue by ghost** [fuel/core#2088]
Fuel version 1.8.1

As soon as I use DB::query($query, DB::SELECT)->cached($int)->execute(), I get the following error message.  If I omit the ->cached(), the query runs normally.

Tracing it with xdebug shows that it is indeed an array of the query values and not a PDOStatement object.
```
Error [ Error ]:
Call to a member function fetchAll() on array

COREPATH//classes/database/pdo/cached.php @ line 31
```

**Comment by WanWizard** [comment]
What do you think that method does?

Hint: it has nothing to do with caching something for a specific time...

**Comment by WanWizard** [comment]
Interesting, something looks seriously broken here. This code has been active and used in 1.9/dev in since December, and nobody bumped into it.
