### ISSUE TITLE
Using Session driver redis causes error

### ISSUE THREAD

**Issue by cs-sonar** [fuel/core#2089]
Fuel version 1.8.1

when using Session with Session_Redis got a error.

session config(Excerpt)

```
	'auto_initialize'	=> true,
	'auto_start'		=> true,
	'driver'			=> 'redis',
```

redis config(Excerpt)

```
    'redis' => array(
        'default' => array(
            'hostname' => 'xxxxxxxxxx',
            'port' => 6379,
            'timeout' => null,
        ),
    ),
```

examples 

```
Session::set('aaaa','aaaaa');
```

got a error

```
Error [ Error ]:
Call to a member function get() on boolean

COREPATH/classes/session/redis.php @ line 229
```

when I inserted `$this->init();` Session_Redis construct method , this error was fixed.
https://github.com/fuel/core/blob/1.9/develop/classes/session/redis.php#L41

**Comment by WanWizard** [comment]
Thanks for your report. You can do a "composer update" to install the hotfix.
