### ISSUE TITLE
PHP function "hash_equals" only exist in versions >= 5.6.0, but Fuel currently states to work with >= 5.4.0

### ISSUE THREAD

**Issue by willpoorman** [fuel/core#2090]
https://github.com/fuel/core/blob/53a457aeb4c779b0ac636b3b2d2f28c3cc35af2a/classes/crypt.php#L376

Hi Team,

The function used on line 376 of classes/crypt.php, "hash_equals", was added to PHP in 5.6. Currently on Fuel's website, it states that it works for 5.4+, yet now it can't because it uses that function.

I know 5.4 is old and there isn't much support for it left, but some people still have to use it for one reason or another and if Fuel states it works with 5.4, at least in 1.8, then it makes sense to make sure to keep that compatibility.

Source on creation of hash_equals in 5.6.0: http://php.net/manual/en/function.hash-equals.php

**Comment by WanWizard** [comment]
Tagged 1.8.1.3, will be installed automatically on a `composer update`.

**Comment by willpoorman** [comment]
Impressively quick! Thanks WanWizard!
