### ISSUE TITLE
strpos(): Offset not contained in string

### ISSUE THREAD

**Issue by it-can** [fuel/core#2093]
Sometimes I see this error in my logs...

```
strpos(): Offset not contained in string
```

https://github.com/fuel/core/blob/1.9/develop/base.php#L380

**Comment by WanWizard** [comment]
I assume this happens when the path is an empty string, but I have to test to be sure.

**Comment by it-can** [comment]
Happens when path is empty...

**Comment by WanWizard** [comment]
Should be fixed now then.
