### ISSUE TITLE
Using Mysqli driver count causes error

### ISSUE THREAD

**Issue by ghost** [fuel/core#2097]
Fuel version 1.8.1.4

when using Mysqli Deiver got a error in php7.2.

```
Fuel\Core\PhpErrorException [ Warning ]:
count(): Parameter must be an array or an object that implements Countable
```

I think the following is correct.

https://github.com/fuel/core/blob/cd46fc6e4904354ecd2ab32ea6e2aaee15ab5027/classes/database/mysqli/cached.php#L63

```diff
- $this->_total_rows = count($this->_result);
+ $this->_total_rows = count($this->_results);
```

https://github.com/fuel/core/commit/0a7931b9acd9b6cbb7abca393c5044b04668f596
Fuel version 1.9 is already fixed.

**Comment by WanWizard** [comment]
I'll push it as a 1.8.1.5 hotfix later. Thanks for reminding me.

**Comment by WanWizard** [comment]
Done.
