### ISSUE TITLE
Encountered an error with Pagination:_recalculate() 

### ISSUE THREAD

**Issue by kawakattsun** [fuel/core#2103]
I encountered an error with pagination.

```
Notice - A non well formed numeric value encountered
```

I think the cause is in the following line.
https://github.com/fuel/core/blob/1.8/master/classes/pagination.php#L513
https://github.com/fuel/core/blob/1.9/develop/classes/pagination.php#L513

```php
$this->config['calculated_page'] = \Input::get($this->config['uri_segment'], null);
```

For example, in the case of this parameter, E_NOTICE is generated from php 7.1.
( https://secure.php.net/manual/en/migration71.other-changes.php
```php
$this->config['calculated_page'] = '1a'
```
https://github.com/fuel/core/blob/1.9/develop/classes/pagination.php#L549

I think that it is desirable to modify it for the following.
```diff
- $this->config['calculated_page'] = \Input::get($this->config['uri_segment'], null);
+ $this->config['calculated_page'] = (int) \Input::get($this->config['uri_segment'], null);
```

Is there any other way to avoid errors?

**Comment by WanWizard** [comment]
The obvious solution to this is make sure your page numbers are numeric?

I prefer to log an error and revert to page one when it's not numeric, instead of casting to int and hope for the best.

**Comment by kawakattsun** [comment]
I see.
But why is this are you casting to int?

https://github.com/fuel/core/blob/1.8/master/classes/pagination.php#L517

```php
$this->config['calculated_page'] = (int) \Request::main()->uri->get_segment($this->config['uri_segment'], null);
```

**Comment by WanWizard** [comment]
Hmm, I'm a bit clueless here:
````php
			if ( ! ctype_digit((string) $this->config['uri_segment']))
			{
				$this->config['calculated_page'] = \Input::get($this->config['uri_segment'], null);
			}
			else
			{
				$this->config['calculated_page'] = (int) \Request::main()->uri->get_segment($this->config['uri_segment'], null);
			}
````
why would you NOT want the page number to be numeric? There is an explicit test for it? 

I need to dive into the history of this, it sounds very odd...

**Comment by seeds-kawakatsu** [comment]
> I prefer to log an error and revert to page one when it's not numeric, instead of casting to int and hope for the best.

I agree with this opinion, too,
I simply wondered why one casted to an int, why the other was not casting.

I found that it is possible to rewrite the values ​​that can be acquired with \ Input :: get ().
Check it in advance and overwrite it if it is illegal.

Thank you very much.

**Comment by kawakattsun** [comment]
> I prefer to log an error and revert to page one when it's not numeric, instead of casting to int and hope for the best.

I agree with this opinion, too,
I simply wondered why one casted to an int, why the other was not casting.

I found that it is possible to rewrite the values ​​that can be acquired with \ Input :: get ().
Check it in advance and overwrite it if it is illegal.

Thank you very much.
