### ISSUE TITLE
Upload class uses finfo PECL to get MIME which is not available on all systems

### ISSUE THREAD

**Issue by theycallmeswift** [fuel/core#213]
We currently do this: (lines 291-3 in upload.php)

```
 $handle = finfo_open(FILEINFO_MIME_TYPE);
 $files[$key]['mimetype'] = finfo_file($handle, $value['file']);
 finfo_close($handle);
```

The problem is that not some shared hosts don't come with the finfo PECL installed and make it difficult to actually install anything (_cough_ ...Dreamhost... _cough_).  So perhaps a workaround would be something along these lines:

```
private static function get_mime_type($filename) {

    $mime_types = array(

        'txt' => 'text/plain',
        'htm' => 'text/html',
        'html' => 'text/html',
        'php' => 'text/html',
        'css' => 'text/css',
        'js' => 'application/javascript',
        'json' => 'application/json',
        'xml' => 'application/xml',
        'swf' => 'application/x-shockwave-flash',
        'flv' => 'video/x-flv',

        // images
        'png' => 'image/png',
        'jpe' => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'jpg' => 'image/jpeg',
        'gif' => 'image/gif',
        'bmp' => 'image/bmp',
        'ico' => 'image/vnd.microsoft.icon',
        'tiff' => 'image/tiff',
        'tif' => 'image/tiff',
        'svg' => 'image/svg+xml',
        'svgz' => 'image/svg+xml',

        // archives
        'zip' => 'application/zip',
        'rar' => 'application/x-rar-compressed',
        'exe' => 'application/x-msdownload',
        'msi' => 'application/x-msdownload',
        'cab' => 'application/vnd.ms-cab-compressed',

        // audio/video
        'mp3' => 'audio/mpeg',
        'qt' => 'video/quicktime',
        'mov' => 'video/quicktime',

        // adobe
        'pdf' => 'application/pdf',
        'psd' => 'image/vnd.adobe.photoshop',
        'ai' => 'application/postscript',
        'eps' => 'application/postscript',
        'ps' => 'application/postscript',

        // ms office
        'doc' => 'application/msword',
        'rtf' => 'application/rtf',
        'xls' => 'application/vnd.ms-excel',
        'ppt' => 'application/vnd.ms-powerpoint',

        // open office
        'odt' => 'application/vnd.oasis.opendocument.text',
        'ods' => 'application/vnd.oasis.opendocument.spreadsheet',
    );

    $ext = strtolower(array_pop(explode('.',$filename)));
    if (array_key_exists($ext, $mime_types)) {
        return $mime_types[$ext];
    }
    elseif (function_exists('finfo_open')) {
        $finfo = finfo_open(FILEINFO_MIME);
        $mimetype = finfo_file($finfo, $filename);
        finfo_close($finfo);
        return $mimetype;
    }
    else {
        return 'application/octet-stream';
    }
}
```

Thoughts?

**Comment by jschreuder** [comment]
It's part of PHP5.3 according to this page: http://nl.php.net/manual/en/fileinfo.installation.php
As it's far more reliable than other methods we do prefer to use it.

I'll leave anything further to @WanWizard (he wrote the Upload class) but I think we are open to pull-requests for a fallback option.

**Comment by WanWizard** [comment]
I'm not sure we should do anything here.

fileinfo is included in your PHP installation by default (as @jschreuder already mentioned). If you have a PHP 5.3+ installation without it, it means it's a custom compilation. I feel we can (or should) not accomodate custom installations with our code, if we start to do that, where will it end?

It is only in PECL for pre 5.3 installations, but as Fuel requires 5.3+, that is not an issue here.

If you're on a Windows platform, you might have to enable the fileinfo DLL in your php.ini. We should add this remark to the documentation, probably in the requirements section.

**Comment by theycallmeswift** [comment]
When I encountered it I figured it would be a problem for any users with shared hosting. But according to what you guys are saying, it really shouldn't be. I'm not sure why my install doesn't support it out of the box. (I'm definitely running on 5.3+). 

Anyways, I'm considering this closed. I'll make a post somewhere on the forums with the workaround instructions for Dreamhost users.  

Thanks for your help,
Mike

**Comment by WanWizard** [comment]
This might help you: http://wiki.dreamhost.com/Fileinfo

**Comment by miklschmidt** [comment]
(from: http://nl.php.net/manual/en/fileinfo.installation.php) Windows users must include the bundled php_fileinfo.dll DLL file in php.ini to enable this extension. 

So per default every windows user will get an error when trying to use it.

May i suggest a check and a descriptive error message or something?
