### ISSUE TITLE
Database_Connection improperly quotes array as not being a string

### ISSUE THREAD

**Issue by PeterTillema** [fuel/core#2139]
After lots of debugging, it turns out that when the default for any key in a model is set to an array, the update query is wrong. FuelPHP uses `Database_Connection::quote($value)` to quote values to be used in the database, but the result is wrong for arrays. The return value is something like `'(' . implode(', ', <array>) . ')'` but it isn't surrounded by quotes, resulting in a wrong query, i.e. something like `UPDATE db SET x = () WHERE y` rather than `UPDATE db SET x = '()' WHERE y`.

See https://github.com/fuel/auth/issues/120 for reference.

**Comment by WanWizard** [comment]
The question I think is whether or not an array() as input should be accepted where a string is expected. 

Passing an array is meant for collections, like `UPDATE db set x = 'y' WHERE id IN ('a', 'b', 'c')` which does not require quotes.

Which imho means that passing an empty array in the code is wrong. It should be NULL or "" or something.

**Comment by PeterTillema** [comment]
Right, that makes sense. Thanks for the explanation!
