### ISSUE TITLE
No Email::reply_to() [or something similar]

### ISSUE THREAD

**Issue by bencorlett** [fuel/core#214]
No Email::reply_to() [or something similar].

I've got no  idea how PHP sends emails so no use me having a go at writing this method in the drivers...

Kudos to whoever can though :)

**Comment by jschreuder** [comment]
As we're planning on removing the current Email class I don't think it's fair to encourage anyone to do any work on it.

(parts of it are from CI and we can't release 1.0 with CI licensed stuff in it that is incompatible with our MIT license)

**Comment by bencorlett** [comment]
It is getting replaced, right?

**Comment by jschreuder** [comment]
Yeah it is, but until it is we shouldn't have open issues that encourage people to waste time on writing something that will be discarded.
