### ISSUE TITLE
PhpMarkdown dependencie issue on PHP 7.4.4

### ISSUE THREAD

**Issue by AdamSGit** [fuel/core#2141]
Hey guys. When updating Fuel app to PHP 7.4.4, the following issue happend : 

PhpMarkdown 1.7 generate the following notice :
```
8192 - Array and string offset access syntax with curly braces is deprecated in vendor/michelf/php-markdown/Michelf/MarkdownExtra.php on line 209
```

When trying to update PhpMarkdown dependencie to 1.9 in composer, which should correct the issue, it trigger the following error : 
```
fuel/core 1.8.2 requires michelf/php-markdown 1.7.0 -> satisfiable by michelf/php-markdown[1.7.0] but these conflict with your requirements or minimum-stability.
```
Also, don't take it the wrong way, but isn't this markdown wrapper completely useless ? Given the fact that it bring nothing except normalizing syntax with fuel guidelines, and may cause compatibility issue. It would be more convenient to let people choose the php markdown library they wanna use, if any.

**Comment by WanWizard** [comment]
How did you try to upgrade?

It looks like you added it in the main composer.json, while every Fuel package has it's own composer.json file and dependencies: https://github.com/fuel/core/blob/1.9/develop/composer.json#L18

**Comment by AdamSGit** [comment]
How did I miss that ? Amazing.
