### ISSUE TITLE
In SecurityException, set_token is always called with true.

### ISSUE THREAD

**Issue by uron802** [fuel/core#2146]
In SecurityException, set_token is always called with true.
```
static::set_token(true);
```
Token generation is always done.
```
public static function set_token($rotate = true)
{
	// re-use old token when found (= not expired) and expiration is used (otherwise always reset)
	if ($rotate === false and static::$csrf_old_token !== false)
	{
		static::$csrf_token = static::$csrf_old_token;
	}
	// set new token for next session when necessary
	else
	{
		static::$csrf_token = static::generate_token();

		$expiration = \Config::get('security.csrf_expiration', 0);
		\Cookie::set(static::$csrf_token_key, static::$csrf_token, $expiration);
	}
}
```
I think it should be called according to the setting of config.
```
static::set_token(\Config::get('security.csrf_rotate', true));
```

**Comment by WanWizard** [comment]
Which
````
static::set_token(true);
````
do you exactly mean? Class and line please?

**Comment by uron802** [comment]
Class: [SecurityException](https://github.com/fuel/core/blob/1.9/develop/classes/security.php)
Line: 310 and 292

**Comment by uron802** [comment]
I can not explain this. sorry..

**Comment by WanWizard** [comment]
310 is only called when there is no token loaded, so at that moment you MUST generate a new one.

And in 292, rotation is controlled by the `security.csrf_rotate` config value, it is checked in the "if" clause.

**Comment by uron802** [comment]
Thank you.
