### ISSUE TITLE
URL segments error

### ISSUE THREAD

**Issue by davidarendsen** [fuel/core#215]
When typing the plus sign in the url I get the following error:

ErrorException [ Notice ]: Undefined offset: 0

COREPATH/classes/router.php @ line 110:

**Comment by WanWizard** [comment]
what code base are you using? I have a line of comments @ line 110.

I don't see an error using the develop branch when using a + in the URL, and I haven't seen a major change of the router class recently either...

**Comment by davidarendsen** [comment]
I downloaded it from the site a week ago.

**Comment by WanWizard** [comment]
Do you have an example of a URL that fails in your case, so I have something to test with?

**Comment by davidarendsen** [comment]
Just downloaded it again and now I got it working.
