### ISSUE TITLE
How do you guys do php8 compatibility checks ?

### ISSUE THREAD

**Issue by Nao000** [fuel/core#2155]
How do you check the compatibility of PHP8 with FuelPHP?

I've set up a docker environment with PHP8 and displayed a welcome page.

Do you call each method of the core file and check the behavior?

**Comment by WanWizard** [comment]
Well, that's the challenge... ;)

I know the Pro version of PHPStan can do it, but that is buyware.

For now, we're in the process of updating our internal develop- and staging environment to PHP8, as we need to check our apps too, and hopefully any issues that may be present will pop up in testing. The most obvious have already been fixed.

**Comment by Nao000** [comment]
oh i see...

I'll try and if there's a problem, I'll report back.

thanks !
