### ISSUE TITLE
update PDO methods pls

### ISSUE THREAD

**Issue by hotlabs** [fuel/core#2156]
public function list_tables($like = null)
	{
	    $this->_connection or $this->connect();
	
		if (is_string($like))
		{
			// Search for table names
			$q = $this->_connection->query("SHOW TABLES LIKE ".$this->quote($like));
		}
		else
		{
			// Find all table names		
			$q = $this->_connection->query("SHOW TABLES");
		}     
		$q->execute();
		$result  = $q->fetchAll();
		$tables = array();
		foreach ($result as $row)
		{
			$tables[] = reset($row);
		}
		
		return $tables;
	}

public function list_indexes($table, $like = null)
	{
		// Quote the table name
		$table = $this->quote_table($table);

		if (is_string($like))
		{
			// Search for index names
			$q = $this->_connection->query('SHOW INDEX FROM '.$table.' WHERE '.$this->quote_identifier('Key_name').' LIKE '.$this->quote($like), false);
		}
		else
		{
			// Find all index names
			$q = $this->_connection->query('SHOW INDEX FROM '.$table, false);
		}
        $q->execute();
        $result  = $q->fetchAll();	
	
		// unify the result
		$indexes = array();
		foreach ($result as $row)
		{
			$index = array(
				'name' => $row['Key_name'],
				'column' => $row['Column_name'],
				'order' => $row['Seq_in_index'],
				'type' => $row['Index_type'],
				'primary' => $row['Key_name'] == 'PRIMARY' ? true : false,
				'unique' => $row['Non_unique'] == 0 ? true : false,
				'null' => $row['Null'] == 'YES' ? true : false,
				'ascending' => $row['Collation'] == 'A' ? true : false,
			);

			$indexes[] = $index;
		}

		return $indexes;
	}

**Comment by WanWizard** [comment]
No. The PDO driver is the generic parent for all platform specific drivers, and should not be used directly.
