### ISSUE TITLE
DB: MySQL connection.php does not have a port number option, though docs say it does

### ISSUE THREAD

**Issue by markbao** [fuel/core#216]
Database: MySQL connection.php doesn't have a port number option, even though the docs say they do.

Doc page:
http://fuelphp.com/docs/classes/database/introduction.html

I am looking here:
https://github.com/crynobone/fuelphp/blob/master/fuel/core/classes/database/mysql/connection.php

@ commit 205309f478628ada3603

Temporary workaround is to set the hostname to "hostname:port" like "localhost:3306".

I'll try to submit a patch if I have a chance.

**Comment by WanWizard** [comment]
Bug has been fixed for both the MySQL and  MySQLi drivers
