### ISSUE TITLE
How do I update my markdown class

### ISSUE THREAD

**Issue by Nao000** [fuel/core#2162]
PHP Version 8.0.6
FuelPHP 1.8.2

fuel uses "michelf/php-markdown": "1.7.0". but this markdown module version is old.

this version access array with curly braces. Example: `$array{0}`

So, this code will be error.
```php
$string = '# About Markdown';

echo Markdown::parse($string);
```
> Compile Error!
> ErrorException [ Compile Error ]:
> Array and string offset access syntax with curly braces is no longer supported

I don't know what to do.

**Comment by WanWizard** [comment]
Current version of php-markdown is 1.9.0, have you tried upgradeing it?

If that doesn't fix it, we probably have to switch to another library, like league/commonmark.

**Comment by Nao000** [comment]
Thanks, I manual upgrade 1.9.0 and it works. I download php-markdown v1.9.0, and copy and paste to `fuel\vendor\michelf`.

Fuelphp is requires `michelf/php-markdown: 1.7.0` so I couldn't upgrade with composer.

**Comment by WanWizard** [comment]
Thanks for testing, I've updated the composer.json to require 1.9.0.
