### ISSUE TITLE
Form / Fieldset, 'auto_id' and <label for="...">

### ISSUE THREAD

**Issue by snrp** [fuel/core#218]
The id is missing from the label (eg: `<label for="id">`) for fields rendered with the Fieldset. You can easily see this by examining the outputed form in Firebug, OR simpler, by clicking on the label of any form item, and see that it does not bring focus to the coresponding input.

Note that for field type radio / checkbox **with options**, the 'sublabel' of each radio / chb **does** have the id in the `label for`

If it helps to trace the problem down, this hack I made to the Core\Form class seems to fix it:

```
    // I added this above the switch statement in Core\Form::build_field()
    if (empty($field->attributes['id']) && $this->get_config('auto_id', false) == true)
    {
        $field->set_attribute('id',$this->get_config('auto_id_prefix', '').$field->name);
    }

    switch($field->type)
    ...
```

Then further down this:

```
                    if (empty($attributes['id']) && $this->get_config('auto_id', false) == true)
                    {
                        $attributes['id'] = $this->get_config('auto_id_prefix', '').$field->name.'_'.$i;
                    }
                    elseif( ! empty($attributes['id']))
                    {
                        $attributes['id'] .= '_'.$i;
                    }
                    else
                    {
                        $attributes['id'] = null;
                    }
```

remove the first `if` statement:

```
                    if( ! empty($attributes['id']))
                    {
                        $attributes['id'] .= '_'.$i;
                    }
                    else
                    {
                        $attributes['id'] = null;
                    }
```

**Comment by Mitchell64** [comment]
I've been playing around quite a bit with fieldsets and displaying forms, and I don't think I see the problem you're describing. I'm setting the form fields using add_model() and set_form_fields() and explicitly setting the id for each form field, so I don't know if that makes a difference.

One problem I am seeing is that for radio buttons and checkboxes the <label for="id"> should not be applied to the main label. For example, if the main label is "Pick a color" and the options are "red" and "green," the <label for="id"> should be applied to the options "red" and "green," but not the label "Pick a color."

Here's an example output: The first label tag should not be there.

```
<label for="checkbox-test">Checkbox Test</label>

<input type="checkbox" value="3" id="checkbox-test_0" name="checkbox_id[0]" >
<label for="checkbox-test_0">Three</label>          

<input type="checkbox" value="4" id="checkbox-test_1" name="checkbox_id[1]" >
<label for="checkbox-test_1">Four</label>
```

**Comment by jschreuder** [comment]
@snrp
Can you give some code examples of the HTML, I did some quick tests and it works as expected for me.

@Mitchell64
I won't get around to your bugreport now, can you make a separate issue out of that? It's never a good idea to report a bug in another bugreport unless you're a 100% sure they're related (and these aren't).

**Comment by Mitchell64** [comment]
Didn't mean to hijack this issue, but the issues looked pretty similar to me. Anyway, I'll open a new issue.

**Comment by jschreuder** [comment]
@snrp as you didn't provide any additional details and I couldn't replicate the issue I'm going to assume this is invalid.
