### ISSUE TITLE
PHP 8.3 Problem with View Class : COREPATH/classes/view.php @ line 586

### ISSUE THREAD

**Issue by fledoux** [fuel/core#2207]
Fuel\Core\PhpErrorException [ Runtime Deprecated code usage ]: Automatic conversion of false to array is deprecated

if (strpos($key, '.') === false)
{
    $this->data[$key] = $value;
}

I replace by this, it works:

if (strpos($key, '.') === false) {
    if (isset($this->data) && !is_array($this->data)) {
        $this->data = array();
    }
    $this->data[$key] = $value;
}

**Comment by WanWizard** [comment]
How did you manage to make `$this->data` `false`?

I think this is not the actual problem, the problem is in the constructor, which should only accept objects or arrays, but doesn't do a very good job validating the input, as it allows `false` to fall through.
