### ISSUE TITLE
1.9-dev Fatal Error in Uploads.php

### ISSUE THREAD

**Issue by glOOmyART** [fuel/core#2215]
FuelPHP 1.9-dev (latest from ```composer update```)
PHP 8.2.22

When in "DEVELOPEMENT" mode, i get the following error when trying to use the upload class

```
Fatal error:  During inheritance of ArrayAccess: Uncaught Fuel\Core\PhpErrorException: Return type of Fuel\Upload\Upload::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in fuel/vendor/fuelphp/upload/src/Upload.php:503
Stack trace:
#0 ./fuel/core/bootstrap.php(112): Fuel\Core\Errorhandler::error_handler()
#1 ./fuel/vendor/fuelphp/upload/src/Upload.php(16): {closure}()
#2 ./fuel/vendor/composer/ClassLoader.php(582): include('...')
#3 ./fuel/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#5 ./fuel/core/classes/upload.php(87): class_exists()
#6 [internal function]: Fuel\Core\Upload::_init()
#7 ./fuel/core/classes/autoloader.php(377): call_user_func()
#8 ./fuel/core/classes/autoloader.php(249): Fuel\Core\Autoloader::init_class()
#9 ./fuel/app/modules/music/classes/controller/admin/companies.php(434): Fuel\Core\Autoloader::load()
#10 [internal function]: Music\Controller\Admin\Companies->action_edit()
#11 ./fuel/core/classes/request.php(483): ReflectionMethod->invokeArgs()
#12 ./public_html/index.php(133): Fuel\Core\Request->execute()
#13 ./public_html/index.php(172): {closure}()
#14 {main} in ./fuel/vendor/fuelphp/upload/src/Upload.php on line 16
```

The line for ```#9``` in my script is
```if ((\Upload::is_valid() or empty($_FILES['image']['name'])) and $company and $save = $company->save())```

When i switch to "PRODUCTION", the error does not occur

Tell me if you need more information

**Comment by WanWizard** [comment]
Can you check which version of FuelPHP/Upload is defined in your composer.json ?

This issue should be addressed in the latest, 2.0.7.

**Comment by WanWizard** [comment]
Was updated 3 days ago: https://github.com/fuel/fuel/commit/76ef377ea69a38ea7e5a4a11126f29e014a2fb95

**Comment by glOOmyART** [comment]
> Can you check which version of FuelPHP/Upload is defined in your composer.json ?
> 
> This issue should be addressed in the latest, 2.0.7.

yep, it is set to 2.0.6
do i need to manually update the composer.json?
i did ```composer update``` and thought everything is going to be updated (i'm not very familiar with the mechanics of composer)

**Comment by WanWizard** [comment]
It depends on how you constructed your app, whether or not you can pull upstream changes in, or rebase with upstream. 

Most people heavily modify the structure and the default files, making it impossible without a lot of merge issues. In which case it will be easier to update your composer.json, and run a `composer update`.

**Comment by WanWizard** [comment]
> i did `composer update` and thought everything is going to be updated (i'm not very familiar with the mechanics of composer)

That will update everything but the main ( fuel/fuel ) repo itself.

**Comment by glOOmyART** [comment]
thx

i did a ```composer require fuelphp/upload``` which updates the specific package to the latest version number

**Comment by WanWizard** [comment]
That works too... :grin:
