### ISSUE TITLE
Uploaded files array "key" field is reserved word in MySQL

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#223]
When using the Upload class, the uploaded files array contains a number of fields, one of which is the field "key." Unfortunately, "key" is a reserved word in MySQL, so one cannot do a one-to-one mapping of the uploaded files array to a MySQL table. It sure would be nice to change the "key" index to something else that does not conflict.

**Comment by WanWizard** [comment]
What's the point of storing the entire array into a database? There are only a few fields worth keeping...

**Comment by Mitchell64** [comment]
Not being totally familiar with all the fields, my first attempt was to store all of them. In fact, I'm not really sure what the "key" field is, however trying to save it results in a MySQL error unless it's renamed to something else, since "key" is a reserved word in MySQL. I found this out the hard way, scratching my head why the insert query kept returning an error.

**Comment by WanWizard** [comment]
This is why you need to quote fieldnames in your queries. Afaik both the query builder and the ORM package do that, exactly because of errors like this. If you construct your own query, you'll have to take care of this yourself.

The 'key' field is just an internal reference, only valid for that particular upload. No point saving it.

**Comment by jschreuder** [comment]
I'll be the bad guy here: this is nonsense. If you want to put something in the database format it right, and even if you don't this won't be a problem if you quote your identifiers. Marking this as invalid and closing.

Names in array should be logical and easily understood for their goal, not for the of-change someone might want to put it into a DB without quoting his identifiers.

**Comment by Mitchell64** [comment]
You're both quite right. I forgot to quote the field names in my query. I was experimenting with a somewhat complex query that used DB::expr. My apologies for the waste of time.
