### ISSUE TITLE
Download Class

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#230]
It would be nice to have a Download Class that handles most of the setting of headers, etc. to download or display a file. This would be particularly useful when files are stored above the public directory and cannot be downloaded using a simple link.

**Comment by jschreuder** [comment]
I'm not sure this needs to be a class, I think a method in the File class would do.

**Comment by Mitchell64** [comment]
Yes, a method in the File class would certainly work. In fact, before I read through the all File class documentation, I was hoping there was already a method that would download a file.
