### ISSUE TITLE
Support multiple errors in the Upload class

### ISSUE THREAD

**Issue by WanWizard** [fuel/core#241]
The current process() and save() methods of the Upload class stop at the first error detected, and only return that error (both code and message).

Especially for validation, all detected errors should be returned.

See http://fuelphp.com/forums/topics/view/2603

**Comment by WanWizard** [comment]
Moved to v1.1, as this will change the behaviour of the Upload class.

**Comment by frankdejonge** [comment]
@WanWizard: Hasn't this issue been worked out? Looking at the class it seems it does.

**Comment by WanWizard** [comment]
No, it hasn't. The point here was that an upload of a single file could cause more than one error. 

Currently the file array contains only one error code and error message, this should be an array.
