### ISSUE TITLE
Add image width and height to Upload class files array

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#243]
If the file uploaded is an image, add width and height to files array.

**Comment by nerdsrescueme** [comment]
Not sure if it will make it into core, but this little snippet could help you out for now. If anyone wants I can add support into the Upload class for this, but it requires the gd library... and I'm not sure if you want to rely on it to be there... Could always check for it first...

``` php
list($width, $height, $type, $attr)= getimagesize('path/to/image.img');

echo 'Width: ' . $width;
echo 'Height: ' . $height;
```

**Comment by Mitchell64** [comment]
Since getimagesize() doesn't require the GD library, what about using getimagesize() to get the width and height and add it to the upload file array so that all the file info is in one place?

**Comment by nerdsrescueme** [comment]
It was under the GD image function list so I assumed it required the library... but you are correct it does not. I can add it in if anyone decides it's fit for core.

http://php.net/manual/en/function.getimagesize.php

**Comment by Mitchell64** [comment]
Ok, we'll wait for the keepers of the core to make a judgement.

**Comment by WanWizard** [comment]
I'm not in favor for it. The Upload class should be agnostic to the type of file being uploaded.

Either do additional processing after the upload itself has been processed, or, if your processing determines whether or not to accept the uploaded file, though a validation callback.

**Comment by Mitchell64** [comment]
Ok, I can certainly get the width and height if it's an image. It's some extra code that I'll have to add whenever I store image files in the database. The Upload class seemed to me like a good place to do it since it's filling in all the other file information. I was thinking something similar to CodeIgniter where if it's not an image, the width and height and a few other fields are empty. If I remember correctly, CI has an "is_image" field.

**Comment by nerdsrescueme** [comment]
Could this suggestion possibly be better suited within the Image class? It seems to me that the image class is currently used for manipulating images only, but couldn't it also at the same time gather data about the images you've loaded and save them to the instance?

Could make the class useful in more ways, and wouldn't really change how it works. You'd just add a method or two to retrieve the data collected with you call factory on the image?

Maybe on the factory method you could have an argument (boolean) added so you don't have to load the image until you decide to do so? That way you don't have all the overhead if you're not altering the image, but you'll still get all of the information that is loaded about the image in the factory call?

Just an idea.

**Comment by Mitchell64** [comment]
I see your point about expanding the Image class, but to me it still makes sense that the order would be:
1. File is uploaded and Upload class provides info about the uploaded file
2. File info is saved in a database
3. When the file is to be displayed or manipulated, the file info is pulled from the database and passed to the Image class.

**Comment by tomschlick** [comment]
@Mitchell64 i see your point (because i just did that myself) but most people would be editing an image upon upload anyways. and if you were not its not too much of a hassle to do Image::load('image.jpg')->metadata() or something of that sorts.

**Comment by Mitchell64** [comment]
Ok, I think you guys have convinced me. It would be nice to enhance the Image class to get some of the image info. I guess I was somewhat biased coming from CodeIgniter where the upload array had all the image info in it.

**Comment by nerdsrescueme** [comment]
If someone agrees that this should be in core i'll program it this weekend.

**Comment by tomschlick** [comment]
i dont think a metadata (doesn't have to be that name) method would be rejected as it doesn't change any existing functionality and only adds to the ease of use of the class.

**Comment by nerdsrescueme** [comment]
I see your point, i'll code it this weekend and send a pull request. If it's rejected i'll just post it up as a class extension and people can use it as they see fit.

**Comment by Mitchell64** [comment]
Sounds good to me. Thanks.

**Comment by jschreuder** [comment]
Ok, this looks closed. We'll wait for a new pull-request to judge that as a new issue.
