### ISSUE TITLE
Add magic get method to classes

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#254]
I realize this is going to be a controversial request, but I'm going to throw it out anyway. A number of the core classes use the magic get method to allow read access to class variables. It would be nice if more/most of the classes had this.

For example, I'm trying to email the error trace for production code. This is really valuable to see and fix errors. The problem is that when the error trace references a class object, only those variables that are public can be accessed.

**Comment by jschreuder** [comment]
Values are often protected/private for a reason and many times having everything available might give the wrong impression. We've used __get() where it was logical to make certain values available. If you feel it is logical for some class or another pull-request to that specific class and explain why you feel the properties should be available outside.
