### ISSUE TITLE
add_csrf() generates a Warning when validation fails

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#256]
Using add_csrf() function as below:

$form->form()->add_csrf();

If this validation fails, a warning is generated as below. In this case, $callback[0] = 'Security' and $callback[1] = 'check_token'

Warning!
ErrorException [ Warning ]: get_class() expects parameter 1 to be object, string given
COREPATH/classes/validation/error.php @ line 73:

72: ? str_replace('::', ':', $callback)
73: : preg_replace('#^([a-z_]_\\)_#i', '', get_class($callback[0])).':'.$callback[1];
74: }

**Comment by WanWizard** [comment]
I haven't used the form class myself, so I can't test it quickly, but I thing line 800 should read

```
->add_rule('Security::check_token');
```

since it's a static method. Could you try that?

**Comment by Mitchell64** [comment]
I'm trying to test it, but suddenly getting weird mcrypt errors: "mcrypt_generic_init(): 46 is not a valid MCrypt resource"

If I can get past these errors, I'll test the csrf rule.

**Comment by WanWizard** [comment]
Complete error message please, including filename and line number.

**Comment by Mitchell64** [comment]
I can't reproduce the mcrypt error message. Not sure what happened, but once I got that error, I couldn't get rid of it. Here are entries from the log file. It would generate a number of errors so that the max number of errors was hit. Another odd thing was that no error message would display. Not sure if that's a result of hitting the error number limit.

Error - 2011-07-04 14:38:37 --> 2 - mcrypt_generic_init(): 45 is not a valid MCrypt resource in M:\xampp\htdocs_Fuel-v1.0-rc3\core\vendor\phpseclib\Crypt\AES.php on line 361
Error - 2011-07-04 14:38:37 --> 2 - mcrypt_generic_init(): 46 is not a valid MCrypt resource in M:\xampp\htdocs_Fuel-v1.0-rc3\core\vendor\phpseclib\Crypt\AES.php on line 362
Error - 2011-07-04 14:38:37 --> 2 - mdecrypt_generic(): 45 is not a valid MCrypt resource in M:\xampp\htdocs_Fuel-v1.0-rc3\core\vendor\phpseclib\Crypt\AES.php on line 300
Error - 2011-07-04 14:38:37 --> 2 - mcrypt_generic_init(): 45 is not a valid MCrypt resource in M:\xampp\htdocs_Fuel-v1.0-rc3\core\vendor\phpseclib\Crypt\AES.php on line 361
Error - 2011-07-04 14:38:37 --> 2 - mcrypt_generic_init(): 46 is not a valid MCrypt resource in M:\xampp\htdocs_Fuel-v1.0-rc3\core\vendor\phpseclib\Crypt\AES.php on line 362
Error - 2011-07-04 14:38:37 --> 2 - mcrypt_generic(): 46 is not a valid MCrypt resource in M:\xampp\htdocs_Fuel-v1.0-rc3\core\vendor\phpseclib\Crypt\AES.php on line 257
Error - 2011-07-04 14:38:37 --> 2 - mcrypt_generic_init(): 45 is not a valid MCrypt resource in M:\xampp\htdocs_Fuel-v1.0-rc3\core\vendor\phpseclib\Crypt\AES.php on line 361
Error - 2011-07-04 14:38:37 --> 2 - mcrypt_generic_init(): 46 is not a valid MCrypt resource in M:\xampp\htdocs_Fuel-v1.0-rc3\core\vendor\phpseclib\Crypt\AES.php on line 362
Error - 2011-07-04 14:38:37 --> 2 - mcrypt_generic(): 46 is not a valid MCrypt resource in M:\xampp\htdocs_Fuel-v1.0-rc3\core\vendor\phpseclib\Crypt\AES.php on line 257
Error - 2011-07-04 14:38:37 --> 2 - mcrypt_generic_init(): 45 is not a valid MCrypt resource in M:\xampp\htdocs_Fuel-v1.0-rc3\core\vendor\phpseclib\Crypt\AES.php on line 361
Error - 2011-07-04 14:38:37 --> 2 - mcrypt_generic_init(): 46 is not a valid MCrypt resource in M:\xampp\htdocs_Fuel-v1.0-rc3\core\vendor\phpseclib\Crypt\AES.php on line 362

It occurred in: 

File: core/vendor/phpseclib/Crypt/Aes.php
Lines: 361 and 362
mcrypt_generic_init($this->demcrypt, $this->key, $this->iv);
mcrypt_generic_init($this->enmcrypt, $this->key, $this->iv);

What was weird was that tracing through the code, the previous if statement on line 353: if (!isset($this0>enmcrypt)) was always false, so the code on lines 354 - 359 was not executed. If I set $this->enmcrypt to null on line 353, so the statements were executed, the code would not generate any errors.

**Comment by Mitchell64** [comment]
Back to the original issue of add_csrf() and check_token(), you're fix worked. As usual, thanks.

**Comment by WanWizard** [comment]
The only reason for these errors is if mcrypt_module_open() returns false. Which would normally only happen when you use an invalid cipher or cipher mode, which I don't think is the case here. I find some references to this issue, but no solutions.

$this->demcrypt and $this->enmcrypt are only assigned in that if, so how a case can exist where that isset() is false, but these properties are not a resource, is beyond me.

Are you sure you're mcrypt installation is correct (looks like a Windows platform you're using, on which you'll have to install it manually).

**Comment by Mitchell64** [comment]
I don't know what was going on. This was on a Linux server, and I had no errors before, and I'm having no errors now. While this was happening, I tried deleting the crypt config file to let it be rewritten and also tried copying a crypt config file from another project. For now, it's just one of those mysteries of the universe.
