### ISSUE TITLE
Validation error, model could not be converted to string

### ISSUE THREAD

**Issue by Arjeno** [fuel/core#262]
I'm passing a few additional parameters (including a model) to the add_rule function in a field for validation. Looks like when validation fails it tries to stringify the given arguments to put together a validation error message. But my model is an object which can't be converted to a string, thus this error:

ErrorException [ 4096 ]: Object of class Model_User could not be converted to string

COREPATH/classes/validation/error.php @ line 124

**Comment by jschreuder** [comment]
This is a note to myself as I don't have the time to fix it right now:  
Caused by str_replace() of the additional args for the validation method, those need some way of being turned into strings.
