### ISSUE TITLE
Notice with core/classes/security.php htmlentities()

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#263]
I just downloaded the latest core code from the development branch, and code that I've been using for a while just generated the following Notice. I'm not sure yet what's triggering the notice, but I thought I'd post this in case the developer who is familiar with this code may know. I can do more investigating if necessary.

Notice!

ErrorException [ Notice ]: Object of class stdClass could not be converted to int

COREPATH/classes/security.php @ line 170:

169:    // Prevent looping & encoding twice
170:    if (in_array($value, $already_cleaned))
171:    {

**Comment by jschreuder** [comment]
This is an incredibly weird error, there's no casting to int there... the first var $value is accepted as mixed and does no casting and the second var is always an array as expected.

**Comment by WanWizard** [comment]
You'll get this notice if $already_cleaned is an object instead of an array. 
But I don't see how it could become an object though...

**Comment by huglester** [comment]
Hello,
I must join this conversation, because I think I've met some problems with similar issue.
Until yesterday, before update (I was updating around week ago or so), so security.php also updated, and I started to get infinite loops, logs were showing this: Error - 2011-07-11 08:22:15 --> Error - Maximum function nesting level of '100' reached, aborting! in /var/www/vhosts/vibe/fuel/core/classes/database/connection.php on line 526

Later I have found, that infinite loop occurs here:

``` php
public static function dropdown()
    {
        $results = static::find('all');

        //Lets generate array now
        $return = array(0 => 'Select country');
        foreach ($results as $item)
        {
            $return[$item->id] = e($item->name);
        }

        return $return;
    }
```

As I've said, this method was working fine, until update, so later I've spotted, that doing:
$return[$item->id] = $item->name; // without escaping - solved my problem, webpage starts to load.

after going further I'm stuck now, because some insane things happen:

``` php
$return[$item->id] = e($item->name); // NOT working
$return[$item->id] = \Security::htmlentities($item->name, ENT_COMPAT, \Fuel::$encoding, false); // NOT working
$return[$item->id] = htmlentities($item->name, ENT_COMPAT, \Fuel::$encoding, false); // WORKS
$return[$item->id] = $item->name; // WORKS
```

for these tests, I'm sure I was passing the 'string' from the database

**Comment by jschreuder** [comment]
@huglester I'm having a feeling there's something else going on here, the Security::htmlentities() method would never invoke the usage of the Database_Connection class. I just tested this and didn't have any problems with the e() function.

Also: next time open your own issue and leave it up to us whether to merge them. Only add to an issue if you're a 100% sure it really is the same issue. Even a related issue is often better of in its own entry as it might have unexpected unrelated bits as well which would make it impossible to handle both at the same time and keep the issue readable.

**Comment by jschreuder** [comment]
@WanWizard even under those conditions it still wouldn't give a "stdClass could not be converted to **int**" warning would it? It would give an error about not being an array or auto-convert the stdClass to an array.

**Comment by WanWizard** [comment]
No, the point here is that in PHP 5+, objects are stored internally as integer pointers. This is what triggers this (imho incorrect) warning.

It doesn't give the error on the needle, it gives the error if the haystack is an object: in_array($value, $object). No matter what the value is...

**Comment by jschreuder** [comment]
@WanWizard ahh, didn't know that. Stupid bit of error reporting. Still, as you said earlier: there seems to be no way that $already_cleaned could turn into a stdObject.

**Comment by Mitchell64** [comment]
Ok, I had some time to track down what's causing the error. The following line of code in a controller was causing the problem. In this situation, the '2' was a long, not a string.

```
$view->set('random_client_index', 2);
```

Of course, once I changed it to the following, everything works fine. Not sure why it worked before but throws an error with the newest code.

```
$view->set('random_client_index', 2, false);
```

**Comment by WanWizard** [comment]
That's weird, since Security::htmlentities() only deals with strings and objects, and returns all other types untouched.

**Comment by Mitchell64** [comment]
I did a little more digging and found the comment below in the PHP manual for in_array(). In my example, the parameter $value for function htmlentities() was a long, however the array $already_cleaned was:

```
$already_cleaned: array = 
    0:object(stdClass) =
        client_id: string = '12'
        company: string = 'Pendulum, LLC'
        thumbnail: string = '/images/hp_pendulum_tn.jpg'
```

This function will generate a PHP_NOTICE if you are looking for data of type A in an array containing data of type B if casting A to B would generate a PHP_NOTICE.  This may not be obvious.  For example:

<?php
$o = new stdClass;
$a = array(1, 2, $o);
in_array(5, $a);
?>

The output here is:

Notice: Object of class stdClass could not be converted to int in /some/script.php on line 5

**Comment by WanWizard** [comment]
That's what I wrote earlier.

**Comment by andrewwheal** [comment]
I have come across the same issue. Mitchell64 pretty much nailed it in his last comment.

The $already_cleaned variable in Security::htmlentities() is always an array (contrary to what WanWizard has said), but at times it can contain objects, as per Mitchell64's comment.

The issue then arises when you try to do in_array() and it attempts to compare and integer with an object. When comparing a string, the object is converted to a string but objects can not be converted to integers hence the error that is thrown.

This was the underlying issue to a problem I had similar to huglesters where I got the error message -  Error - Maximum function nesting level of '100' reached, aborting!

WanWizard mentions that "Security::htmlentities() only deals with strings and objects, and returns all other types untouched" so it might be a good idea to check if the value passed to the method is a string/object/array before the in_array() and return the raw value. Patch to this effect submitted: https://github.com/fuel/core/pull/270

Hopefully this will make sense to people.

**Comment by Mitchell64** [comment]
Just tested. Looks good. Thanks.
