### ISSUE TITLE
Asset type declarations

### ISSUE THREAD

**Issue by ghost** [fuel/core#272]
I think it would be worthwhile to remove the type="text/javascript" and type="text/css" from the Asset::js/css respectively. This is completely valid HTML5, and although not valid, working HTML4. The types are defaulted by the browser, and eliminate additional bytes being sent to the document, thus saving file/cache size, and making the site faster overall. Plus, it's one less thing we'd need inside of the class, making the class even render it faster.

All in all, faster, and better.

Thoughts?

Edit: I'd be happy to make the modification and send a pull request if the community feels this is a good way of going about things. Otherwise I'll just continue using my own :P

**Comment by philsturgeon** [comment]
I see no benefit to removing them and one minor annoyance will be created. So... no.

**Comment by ghost** [comment]
The benefit would be to save additional file size (html), as well as a relatively unnoticeable (but still existing) amount of execution time (php). What annoyance do you see?

**Comment by ghost** [comment]
Another alternative would be perhaps making it toggle-able from the asset configuration? Then people have the option to do so.

**Comment by philsturgeon** [comment]
The annoyance is it works for less browsers, all to improve page-load by basically nothing. If you have so many script tags on your page that reducing this would make a noticeable difference then you'll probably find the page is still loading insanely slowly because you have so many script includes!

Use the grouping feature to reduce the number of actual script includes you are outputting, which would make this change utterly pointless.

**Comment by ghost** [comment]
It doesn't work in less browsers? It works completely fine down to IE6, it's just not considered valid HTML4. And I realize that it's not a significant impact, but who doesn't want to save a few bytes where they can?

**Comment by philsturgeon** [comment]
If you are that hot on saving bytes we could probably remove all the quotation marks from output HTML too...

It saves 22 bytes from a page and breaks IE6... what is the point? Im not the first to complain about something working in IE6 or not, but I get an email for every issue and comment that comes in. If we merge this I will get a lot more emails and I'd like to avoid that, especially over 22 bytes.

**Comment by ghost** [comment]
Understandable. Just trying to help make Fuel as standard compliant and optimal as I possibly can.

Just as a note: It does work in IE6, I mean't it doesn't work in anything less than IE6.
