### ISSUE TITLE
MediaTemple and Routes

### ISSUE THREAD

**Issue by ghost** [fuel/core#274]
I recently have been migrating over to MediaTemple, and I've found that apparently nothing routes correctly. An example, is I have the following addition to the welcome controller:

http://pastecode.com/926

On my local environment, when I go to the base url of my application, I get the following, as expected:

http://pastecode.com/929

On MT, I get this:

http://pastecode.com/930

Not exactly sure what's going on here.  Nothing within my application is out of the ordinary. The only thing I did, is change the Welcome controller to extend Controller_Template, and I've been working on views, nothing else. Then of course I added the route() method to see what was going on :P. But other than those few things, there's no reason my configuration should be the issue here..

**Comment by jschreuder** [comment]
This looks more like a support request than a bugreport, as there's currently no information in here that describes a bug (more likely a config problem). Try the forums and make sure before posting a bug, the issue tracker should only contain stuff we can actually give feedback on.

**Comment by ghost** [comment]
My apologies. I pushed it to the issue tracker, as I thought it might be something within the uri parsing that takes place on some apache servers. But I'll move it to the forums.

**Comment by WanWizard** [comment]
This is related to issue #233, MT also passes the script in ORIG_PATH_INFO, instead of the path.
