### ISSUE TITLE
CSRF ajax token check should not generate a new token

### ISSUE THREAD

**Issue by bperin** [fuel/core#277]
If you have multiple forms on a page and one of them is ajax, if an ajax request is sent first the csrf cookie will be regenerated once a check is done rendering the static forms (non ajax) invalid. If you add a simple boolean in the conditional statement in /core/classes/security to only overwrite if the controller was NOT accessed with ajax then the static forms will still pass the input check if submitted.

```
public static function check_token($value = null)
{
    $value = $value ?: \Input::post(static::$csrf_token_key, 'fail');

    // always reset token once it's been checked and still the same
    if (static::fetch_token() == static::$csrf_old_token and ! empty($value) and !Input::is_ajax())
    {
        static::set_token(true);
    }

    return $value === static::$csrf_old_token;
}
```

**Comment by jschreuder** [comment]
If you're using Ajax you should grab the key from the cookie, we provide a JS method for that very goals with Security::js_fetch_token().

Don't reuse tokens, that's just unsafe.

**Comment by bperin** [comment]
Yes, I do do that. That wasn't my point, if you have mixed forms on a page, 1 ajax, 1 standard, and the ajax form is submitted first then once the key is checked a new one will be generated, thus rendering the csrf key in the standard form invalid.

**Comment by jschreuder** [comment]
Then also use the javascript function there...
