### ISSUE TITLE
REST client feature request

### ISSUE THREAD

**Issue by billmn** [fuel/core#280]
Hi guys,
What do you think about a REST Client implementation for external webservices requests??

I've talked about that with WanWizard ... See this topic :
http://www.fuelphp.com/forums/topics/view/1728

Cheers

**Comment by ghost** [comment]
So this would more or less be a curl class?

**Comment by billmn** [comment]
Mmmm, something like CI REST Client library created by Phil :
https://github.com/philsturgeon/codeigniter-restclient

But, in topic discussion ( http://www.fuelphp.com/forums/topics/view/1728 ), Phil would a more awesome library, not a simple porting.

**Comment by ghost** [comment]
I'm currently in the process of creating a socket-level browser emulation, which will also support other protocols (ftp, sftp, ssh, etc..). That package could probably be utilized the same way? But if they would prefer this as a core feature, then that's also understandable.

The socket "browser" will also have other configurations you can attach to it that you cannot currently do within curl.

**Comment by billmn** [comment]
Personally I think is a good idea to add a REST Client into the "Request" class ...

But I don't know what it wants to make the staff

**Comment by huglester** [comment]
in case you missed, first version of it is in develop branch:
https://github.com/fuel/core/tree/develop/classes/rest

**Comment by jschreuder** [comment]
This is in development but not exactly as described here, closing this as the issue doesn't serve a purpose to keep open.
