### ISSUE TITLE
Refactor Unzip class to match Fuel style?

### ISSUE THREAD

**Issue by nerdsrescueme** [fuel/core#287]
Just throwing this out there for the devs to make a decision. I'm willing to refactor the Unzip class to make it follow more along the lines of how other classes are used in Fuel.

Possible improvements... use the File class to add a bit more functionality and ease of use to the class.

It is also possible to add a hook into the File class so that Unzip could be used within File... kind of like Form, Validation, and Input are used within Fieldset.

Just a though, no big deal if not... I'll just develop my own class for personal use. Just thought the community could benefit.

**Comment by philsturgeon** [comment]
Absolutely. This Unzip class was bunged in to help get packages working but
they'll be changing pretty soon anyway. If you refactor the class make sure
you update the oil package, or poke me so I can do it. It should be pretty
simple to do just grep -R "Unzip" ./fuel/packages/oil

**Comment by nerdsrescueme** [comment]
Will do. It'll take me a week or so with some of the other stuff I'm working on now. But I'll get to work.

**Comment by philsturgeon** [comment]
No rush. It'll probably have to go in a branch and wait for 1.1 anyhow.

**Comment by tomschlick** [comment]
I think this should be part of the archive class we were just talking about. Basically you would do

```
Archive::factory('filename.zip')->extract('path/to/extract');
```

it would work with zip, tar, gzip, etc via a driver system

**Comment by philsturgeon** [comment]
Will it check a file exists, then assume you are in "create mode"? If 
you try to extract when in "create mode" it'll throw an exception saying 
"WHUT - file does not exist"?

Throw in add_file() add_folder() etc. Also, I think extract(foo, 2nd) 
should be an array of allowed file extensions.

Let me know if im pointing out  the obvious or you dont agree.

**Comment by tomschlick** [comment]
Yeah thats what I was thinking. Basically to create an archive you would do

```
Archive::factory()
    ->add_file("xyz.doc", $xyz_file_contents)
    ->add_folder('subfolder')
    ->add_file('subfolder/test.txt', $test_file_contents)
    ->save('archive.bz2', 'bzip2');
```

**Comment by philsturgeon** [comment]
Create vrs add? Or new verses add?

One takes a string which is a filepath and adds a file or everything in 
a file. another creates a file or folder based on the string you provide 
as the name and the contents?

Archive::factory()
     ->new_file("xyz.doc", $xyz_file_contents)
     ->new_folder('subfolder')
     ->add_file('/some/local/subfolder/test.txt')
     ->save('archive.bz2', 'bzip2');

**Comment by tomschlick** [comment]
yeah i like that approach. the only thing you would have to add is a 2nd parameter to add_file / add_folder that is the name given to the file/folder when put in the archive, by default it would keep its current name & would put it in the root of the archive.

**Comment by philsturgeon** [comment]
Possible but could be some automatic. I'd prefer two different methods 
that do two different things. Easier to document and less magic.

**Comment by tomschlick** [comment]
No thats what im saying, there would be new_folder & new_file and then there would be add_folder (which adds a current folder & all its contents) & add_file. All i was saying is that there would a 2nd parameter on add_folder & add_file that would rename them instead of keeping the same filename/foldername as the current file system.

**Comment by philsturgeon** [comment]
Ahh yes! Brilliant. We should just talk in binary then there would be 
less room for misinterpretation.

You have my blessing sir!

**Comment by tomschlick** [comment]
Awesome. I'll probably start the class at the end of this week and initially go for full support on .zip, then we can add drivers for tar, gzip, 7zip, rar and whatever else we need to.

**Comment by WanWizard** [comment]
@philsturgeon, @tomschlick, @nerdsrescueme: any progress over the last two months?

**Comment by tomschlick** [comment]
I got it to the driver level and then ran out of free time to work on it. @FrenkyNet was looking at it the other day but IDK if he was doing work on it or not. Here is the branch with my work https://github.com/tomschlick/fuel-core/commits/feature/archive-class

**Comment by WanWizard** [comment]
@tomschlick @FrenkyNet @philsturgeon Is this something for on the 2.0 roadmap?

**Comment by tomschlick** [comment]
+1 for 2.0 roadmap.

Problem was when we were looking for a good class is all of them had incompatible licenses with ours. I'm sure we can take influence from those others but we are gonna have to write one from scratch if we cant find a compatible one.

**Comment by frankdejonge** [comment]
Yeah, I think so, we can at least refactor what we have now, expanding on different types can also be done in a later stage.

**Comment by philsturgeon** [comment]
Tom was on it a while back so left the task to him.

Emailing from my iPhone 4S like a BOSS!

**Comment by philsturgeon** [comment]
We have permission to use this unzip code, just refactor it.

Emailing from my iPhone 4S like a BOSS!

**Comment by WanWizard** [comment]
Added to the 2.0 roadmap.

**Comment by frankdejonge** [comment]
There are several dedicated composer packages that handle this. Knowing that it's fairly simple to add composer to the current setup, I'm closing this in favour of that.
