### ISSUE TITLE
Identify mobile device type with Agent::is_mobile()

### ISSUE THREAD

**Issue by ppawiggers** [fuel/core#291]
With the Agent::is_mobile() function it is possible to determine whether or not it is a mobile device. With CI 2.0 it is possible to determine which mobile device it is, e.g. an iPhone or a HTC. I think that's very useful for using the native apps (like the native Google Maps app. on a phone) in web applications.

For example:

if(Agent::is_mobile('iphone')
{
    $maps_url = "maps:q=alabama"; //maps: is the code to start the native Maps app for the iPhone.
}

**Comment by WanWizard** [comment]
I don't see the point of this feature. 

You can request Agent::properties(), and retrieve everything you need to know about the client device. Or Agent::property() if you want to retrieve a single property value.
