### ISSUE TITLE
Unit tests for Fuel\Core\Arr expecting the wrong exception

### ISSUE THREAD

**Issue by mattm458** [fuel/core#292]
Lines 158, 252, and 271 in arr.php throw InvalidArgumentExceptions while the unit tests expect a Fuel_Exception. Which would be correct in this case? I've got Fuel running in a site development environment and I changed the unit test to expect an InvalidArgumentException because it's more specific.

**Comment by jschreuder** [comment]
[Already fixed in the develop branch](https://github.com/fuel/core/blob/develop/tests/arr.php#L178)
