### ISSUE TITLE
File::copy_dir method is broken

### ISSUE THREAD

**Issue by ghost** [fuel/core#293]
When using File::copy_dir to copy a directory that contains either just files, or a combination of files and directories, I get numerous errors.

The main error I get is:

Fuel\Core\InvalidPathException [ Error ]: Invalid basepath, cannot create directory at this location.

COREPATH/classes/file.php @ line 138

133        $basepath    = rtrim(static::instance($area)->get_path($basepath), '\/').DS;
134        $new_dir    = static::instance($area)->get_path($basepath.$name);
135
136        if ( ! is_dir($basepath) or ! is_writable($basepath))
137        {
138            throw new \InvalidPathException('Invalid basepath, cannot create directory at this location.');
139        }
140        elseif (file_exists($new_dir))
141        {
142            throw new \FileAccessException('Directory exists already, cannot be created.');
143        }

Backtrace

COREPATH/classes/file.php @ line 481
APPPATH/classes/controller/dashboard.php @ line 153
APPPATH/classes/controller/dashboard.php @ line 87
COREPATH/classes/request.php @ line 407
DOCROOT/index.php @ line 42
Prior Non-Fatal Errors

Warning: fileperms() [function.fileperms]: stat failed for /**/fuel/app/config/project_template/Array/ in COREPATH/classes/file.php @ line 481

It looks like the trouble begins on line 476 when it gets the file listing for the directory.

While iterating the files array, it checks to see if the file is an array. This means that the file is actually a directory.

The code at line 481 and 482 tries to create a directory with the wrong path information and then tries to copy a directory with wrong path information. These lines use the $file variable which in this case is an Array. This cannot be passed to the File::create_dir or File::copy_dir methods (as far as I know), so this causes more errors downstream.

I have been examining this code for a couple of hours, but have yet to find a suitable way to fix it without refactoring the entire method.

I have not contributed code to the project yet (but would like to), but am not sure where to begin.

I wanted to file this as an issue regardless, but will continue to see if I can refactor this in a Fuel-centric manner.

Thank you for the great framework.

**Comment by bencorlett** [comment]
There's a method in the file class that creates the directory which you must use. But yes, I agree that this method should indeed call that method if the path does not exist.
