### ISSUE TITLE
Can't clear out 'to' in Email class

### ISSUE THREAD

**Issue by davidia** [fuel/core#294]
Send an email to somebody.

``` php
Email::to('alic@example.com');
Email::text('Something');
Email::send();
```

Attempt to send an second Email

``` php
Email::to('bob@example.com');
Email::text('Something Else');
Email::send();
```

The second email gets delivered to the first recipient as well. Doesn't appear to be a way to stop this and so sending multiple emails is not possible.

**Comment by jschreuder** [comment]
The Email class will be removed over license issues, large chunks of it were taken from CI which is licensed more stricktly than our MIT license.

Unless any of the other devs has a better solution I'll remove it entirely in the next couple of hours. We're still not sure on what will replace it: either a new Email class or an "official" package with some lib like Swiftmailer.
