### ISSUE TITLE
Improve Request 404 exceptions

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#300]
Currently this is handled by a bit of a hack in `Error::exception_handler()`, which was done not to break compatibility this short before the v1.0-final release. This should be removed asap, possible fix is to add a try-catch block around the request in `public/index.php`.

**Comment by jschreuder** [comment]
Fixed by 2784a0fd849bca1ec3c31d93394cef7284418a43

**Comment by tarnfeld** [comment]
Your fix doesn't seem to work or me, it always hits the core 404 view and my _404_ route never gets called, any ideas?
