### ISSUE TITLE
HMVC / Find File / Something

### ISSUE THREAD

**Issue by bencorlett** [fuel/core#302]
Hey,

Since upgrading my dev branch I've run into a problem. I'm doing two HMVC requests to two different controllers in two different modules. Problem is, they're both loading a view like such \View::factory('widget/bar') (http://d.pr/9l1r), as they both have a view under that name. This is usually fine, the website has been up and running for a couple of months now, however I run into a very weird problem, the view appears to still be loaded, however I'm getting a whole heap of undefined variable errors (http://d.pr/gLc2). It could maybe have something to do with this commit: 6201f921ffc2955e57e550651c9d9038e310ef33 but I'm not sure. Renaming the view (http://d.pr/QXRT) lets me get away with it but I can't see what's gone wrong. Looks like something to do with caching views from Fuel::find_file()?

**Comment by WanWizard** [comment]
That commit only deais with FQFN's being passed to Find_file().

Find_file() caches filenames based on:
- the namespace
- the active request uri

This is clearly different for two Requests of two different controllers in two different modules.

If the view appears to be loaded, then Find_file() has done it's work, as it's only job is to return a FQFN based on the name and type of file you're looking for. It does not cache content.

**Comment by bencorlett** [comment]
Well something else must have changed. I don't know what it is however since pulling from develop something has gone funny with it all. And it works on a blank install under the same situation

**Comment by dhrrgn** [comment]
Do you know when you last updated before this time?  Would help narrow things down a bit.

**Comment by bencorlett** [comment]
Yeah I'll have to check hey,

I'll get back to you guys tonight (Australia time :D)

**Comment by dhrrgn** [comment]
I THINK  I have figured this out.  Please test this for me by opening `fuel/core/classes/fuel.php` then go to line 269.

Change this:

`$paths = array_merge($active->paths, $paths);`

To this:

`$paths = $active->paths + $paths;`

Then let me know.

**Comment by dhrrgn** [comment]
Wait...nevermind...posted to quickly...that won't do anything.

**Comment by bencorlett** [comment]
Haha, yeah that just broke the database configuration or something. lol

I'll have a good little play around and I'll send you a zip of the code that's causing it if you'd like. I'ts 11am here and I won't get a chance until like 8 pm tonight

**Comment by dhrrgn** [comment]
Have you had a chance to look at this yet?

**Comment by bencorlett** [comment]
Hey mate I'm so sorry I haven't had a chance yet I've been flat out. I can confirm it is not a one off as well, it's happened In another project. I'll see if I can work it out. I can confirm 100% that the correct view is being loaded each time but the variables aren't being set on the view from the SECOND hmvc request

**Comment by dhrrgn** [comment]
Ah. Sounds like the factory method or render method is screwing something up.  I will take a look tomorrow (it is 7pm Fri. here).

Thanks for the info.  Def. want to get this resolved before final.

**Comment by bencorlett** [comment]
Hey,

My apologies for what I said on the commit. ("I can confirm 100% that the correct view is being loaded each time but the variables aren't being set on the view from the SECOND hmvc request")

The two views looked nearly identical and I thought it was the correct view each time, but as you've found it's the first view being loaded every time but the correct vars being passed. Thank you for the fix though and keep up the good work mate.

Take care
