### ISSUE TITLE
Global Functions

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#310]
I see that Fuel defines a few functions in the global namespace. I can see the benefits of this in terms of their frequency of use however, this has caused us some issues. We are trying to integrate wordpress into a fuel project. Wordpress, as you might know, is old non-namespaced code and redefines (at least) the global __() function.

I feel that defining functions with commonly used names (__, e, etc.) will typically cause issues when integrating Fuel projects with other systems. 

The 2 options that spring to mind are to either namespace these functions or to wrap them in a class.

Does anyone have any thoughts on this?

**Comment by jschreuder** [comment]
Just make sure those functions are loaded in your app/bootstrap.php and Fuel's functions won't be loaded. They're all in `if ( ! function_exists())` conditions.

**Comment by phil-lavin** [comment]
I don't really see that as a solution for 2 reasons.

The first is that the integration is done in a module which should, ideally, be completely portable and not rely on includes being added to the main app to work.

The second is that it's very unlikely that the functions defined in external systems will do the same as they do in Fuel and will, as such, break the Fuel project as Fuel's global functions are referenced by its core.

I appreciate that this is not directly a fuel problem however, as a company, we regularly integrate sites with existing or separate systems. I cannot imagine that we are the only company that does this and I can forsee other people having the same issue.

**Comment by jschreuder** [comment]
For something like completely integrating one product with another I don't think it's unreasonable to require changes to the app/bootstrap.php - your app will most likely contain huge amounts of Wordpress code if you need it this integrated.

Note as well though that Fuel can't do without some of the functions in there, import() in particular comes to mind.

**Comment by phil-lavin** [comment]
Fuel seems to use most of the global functions internally. My point is, rather, that I think that it may be worth taking these functions out of the global namespace having foreseen them causing problems when integrating with many popular external systems.

**Comment by dhrrgn** [comment]
They stay in the global namespace.  I know this sounds like I am being a dick, but hear me out:

We give you a way to override the core functions.  Yes, the core uses those function, so replacing them with another systems functions will break things.  We COULD namespace them, but then that defeats one of the main purposes of them being in the global namespace to begin with.

That is our official stance.  My PERSONAL stance (not that of the entire framework or any other dev) is that I couldn't care less about Wordpress integration with Fuel.  Wordpress is a system built in the time of the dinosaurs, and is still living in that era.  

There are a couple of ways you could go about it: modify the Fuel core (we of course do not recommend this) or Modify the Wordpress core (they won't care/notice anyway).

Why on earth would you want to integrate it into Fuel anyway?  In what way are you integrating it?  Most things could probably be done with simple SQL queries to the WP database.

**Comment by phil-lavin** [comment]
Wordpress is just the example of the moment. I can see this causing problems whilst integrating with many other systems.

I expected that the stance would be one of disregard and, if I were in your boat, I would probably say the same. We take on a lot of clients with existing sites and are often forced to do some kind of integration into old systems. I'm sure many other agencies are in the same position. This rather limits us, and others, in when we can use Fuel as a development platform. We need to be certain that we would never need to integrate with external systems before we can use Fuel on a project - this is a crying shame as it is a dream to develop with.

In this particular instance, we're implementing a module to allow a client's CMS to automatically log the user into Wordpress based on their main CMS login. We could duplicate the code to do this into the module but this would create a dependency on a particular version of Wordpress. We have, on other sites, pulled header/footer/other content segments from the main Wordpress site into a custom e-commerce system.

As I said, Wordpress is only the example of the moment - we have integrated with other systems in the past also (Drupal, Joomla, etc.) and I can imagine similar issues cropping up with those.

I can wholly understand your stance on this but ask that you reconsider the implications of it on the scope of when Fuel may be used on projects.

**Comment by philsturgeon** [comment]
Another personal opinion: Fuel is a framework for building systems. You can build great systems quickly, but integrating systems... that is always going to be a mess.

I got into the web development game 12 years ago and one of the first open source projects I got involved with was PNphpBB - Integrating Postnuke and PNphpBB. Hell it seemed like a good idea at the time, but if we put that time into creating a half decent forum module then we'd have been way ahead of the game and probably spent more time makng money instead of crowbarring the shit into place.

If you want a blog, build a blog. We have all sorts of scaffolding and great packages in place to make this quick and easy, hell there are already a few Fuel blogs out there.

Too many people think "this site needs a blog... ok WordPress. Now I need a shopping cart... lets grab Magento".

That's just not going to work and Fuel developers should not loose any sleep over those who try,

**Comment by phil-lavin** [comment]
This is not a choice integration. The client is a major player and we are adding e-commerce functionality to an existing site. We very rarely attempt to 'crowbar' other code into new sites - in this, and most other instances, we're building on top of an existing system and the client has specifically stated that they wish to keep wordpress.

I can see you're not going to budge on this one. Perhaps we need to consider forking and tailoring Fuel to better handle the requirements of commercial development

**Comment by philsturgeon** [comment]
As jschreuder has already said:  "I don't think it's unreasonable to require changes to the app/bootstrap.php"

**Comment by dhrrgn** [comment]
Also as I stated...almost everything (integration wise) can be done from Fuel with simple SQL queries to the WP database.  You can just write a WP integration package or whatever that handles SSO and such with little effort.  So long as the apps are on the same domain you can read the WP cookies and all that jazz.

I think you are over-thinking this.

**Comment by bencorlett** [comment]
I fully understand the import() function, but i've got a question more than anything...

Why, for example, is the array_to_attr() function just a function and not a static property of, say the Html class? Is there a performance hit by putting it as a static method? Or is it simply just to save on typing?

**Comment by dhrrgn** [comment]
It is because it is used by a bunch of different classes, and we don't want to load a huge class like Html if we don't need to.  This is the function of most of the functions in there.  Some others are just for convenience.

**Comment by bencorlett** [comment]
In PHP, Say I call Html::anchor() 50 times on a page. Will that load the class 50 times or is PHP more clever than that with static methods?

**Comment by dhrrgn** [comment]
No, it only gets loaded once.

**Comment by nerdsrescueme** [comment]
Wouldn't integrating actual Wordpress code into Fuel be the "hard way" of doing things? There is nothing at all cryptic or proprietary about the Wordpress database structure... so if I were tasked with integration, I would simply scrap Wordpress code, and design an interface into their database structure... or even find a means of exporting the data into a new system of my design...

I've never had any issue convincing clients to allow me to move them off of wordpress as long as their data stayed intact. May I ask what is preventing you from simply recreating this functionality?

The reason I ask is that I am in the process of developing a Fuel Blog module, which (in the end) will import data from leading blogging software... I am early in development so I have some flexibility in implementation, so perhaps I could help out.

**Comment by phil-lavin** [comment]
My reason for wanting to utilize the wordpress code is twofold. Firstly, what I want to do cannot be done directly with the database. It requires generating authentication tokens based on wordpress settings and then creating cookies.

Secondly, referencing the database (or attempting to recreate their code in a Fuel friendly way with some constructive copy/paste techniques) is a less future-proof solution. The database structure and elements of the implementation are subject to change at any time. The interface, on the other hand, is not. This is because it is used by plugins. 

For my purposes, it would be 2 lines of code - include the wordpress functions and then make a call to the function which creates the tokens and cookies. Doing it any other way would be significantly more difficult and less maintainable.

@nerdsrescueme - For your purposes, Wordpress does XML exports. I would suggest that you use these, rather than attempt to load the data from the database, for the maintainability reasons that I mentioned earlier.

**Comment by nerdsrescueme** [comment]
Ahh. So you need to keep wordpress in place. Not just get its data. Gotcha.

**Comment by bencorlett** [comment]
There is this other bit of software that is like comparing an Ferrari 599 to, say a GM Daewoo Cruize. It's called PyroCMS. It's also nice and modular and extensible so you don't have to use fuel when you're using it.

**Comment by crynobone** [comment]
I believe WordPress has XMLRPC to do this, if the function not available you can always build it as WordPress plugin.

What you are trying to do now is hack, I seen so some trying to integrate Joomla + CI, WP + CI, Kohana + Joomla but is it proper integration or rather a quick hack so you can finish your job fast and go home?

Even if Fuel going to follow your structure, would it be a burden to everyone else in the community that already uses __(), import() and etc?
