### ISSUE TITLE
Tags are not being parsed in method get_message from error Class

### ISSUE THREAD

**Issue by mjsilva** [fuel/core#315]
There's an error in get_message() method in Class validation\error.

The needle and haystack are switched in strpos.

Patch:

<pre>
Index: fuel/core/classes/validation/error.php
===================================================================
--- fuel/core/classes/validation/error.php  (revision )
+++ fuel/core/classes/validation/error.php  (revision )
@@ -82,7 +82,7 @@
        }
 
        // only parse when there's tags in the message
-       return $open.(strpos(':', $msg) === false ? $msg : $this->_replace_tags($msg)).$close;
+       return $open.(strpos($msg, ':') === false ? $msg : $this->_replace_tags($msg)).$close;
    }
 
    protected function _replace_tags($msg)
</pre>

**Comment by jschreuder** [comment]
Good catch, thanks!
