### ISSUE TITLE
Rename Validation::errors() to singular error() and depricate errors()

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#316]
Should be renamed but not removed until the next version.

**Comment by nerdsrescueme** [comment]
Will Validation still support multiple errors per field? Or is this just a grammatical issue?

**Comment by jschreuder** [comment]
Validation doesn't support multiple errors per field, first rule that fails is the error. If all succeed there is none.

But if you meant if you will still be able to fetch all errors from a validation, that will still be the output when error() is called without params. The change is purely grammatical and necessary because it's actually a fetcher for individual errors (like `input()` fetched individual input arg) that also allows returning everything when no specific error was given.

**Comment by jschreuder** [comment]
Fixed by f5706b5c17acd3bf47ea
