### ISSUE TITLE
Allow add_rule of Validation class to be passed an anomymus function

### ISSUE THREAD

**Issue by Philipp15b** [fuel/core#319]
Hello,
it would be very helpful to be able to pass an anonymus function to `add_rule()` of the Validation class. This would make own validations much easier.

**Comment by jschreuder** [comment]
You can't? It should already be possible...

**Comment by Philipp15b** [comment]
Really? Hidden feature ;)

**Comment by jschreuder** [comment]
From the docs: "The first parameter of the add_rule() method can contain PHP native function names, any valid PHP callback and Closures in addition to the provided validation methods. The method will get the value to be validated as its first argument and any further arguments can be given to the add_rule() method." - http://fuelphp.com/docs/classes/validation.html

**Comment by Philipp15b** [comment]
Oops, did'nt see it...
