### ISSUE TITLE
Make fieldsets nesteable and allow custom wrapping tags

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#320]
Allow one fieldset instance to be a field in another. For output this also needs support for `<fieldset>` wrapper tags instead of `<form>` and should also allow to use none.

**Comment by nerdsrescueme** [comment]
I really like this idea. Could it be possible simply have it function with "groups", kind of like "areas" in the File class? And perhaps when the output is created it could detect whether it is a child or a root instance and automatically output <fieldset> instead of <form> ?

**Comment by jschreuder** [comment]
I have a feeling you're overthinking this, but thing will become more clear when I design this - which won't be for at least another 3 weeks. This is slated for v1.1.

**Comment by nerdsrescueme** [comment]
Quite possibly, I have a tendency to do that. Can't wait to see what you come up with.

**Comment by WanWizard** [comment]
@jschreuder: status update?

**Comment by jschreuder** [comment]
Already did some preperation and let Dan know I wouldn't get round to this till the weekend.
