### ISSUE TITLE
strange behaviour in Arr::flatten_assoc( $array)

### ISSUE THREAD

**Issue by jozefKapicak** [fuel/core#326]
Hi,

<b>ARRAY:</b>

<pre>
$x = array ( array('a'), array('b'), array('c') );
</pre>

<b>CALL:</b>

<pre>
print_r(  Arr::flatten_assoc($x)  );
</pre>

<b>RESULT IS:</b>

<pre>
Array
(
    [0] => Array
        (
            [0] => a
        )
    [1] => Array
        (
            [0] => b
        )
    [2] => Array
        (
            [0] => c
        )
)
</pre>

<b>RESULT SHOULD BE:</b>

<pre>
Array
(
    [0_0] => a
    [1_0] => b
    [2_0] => c
)
</pre>

Looking forward to see final FUEL v1.0.

Best regards

Jozef

**Comment by jozefKapicak** [comment]
<b>SOLUTION:</b>

<pre>
public static function flatten_assoc($array, $glue = '_', $reset = true)
.....
.....
</pre>


<b>ROW:</b>

<pre>
     if (is_array($val) and array_values($val) !== $val)
</pre>


<b>REPLACE WITH:</b>

<pre>
     if (is_array($val))
</pre>

**Comment by WanWizard** [comment]
flatten_assoc() only flattens associative array's, not indexed array's, so in that sense the behaviour of this method is correct.

I've added a flatten() method that also flattens indexed arrays, to avoid breaking the API.

**Comment by WanWizard** [comment]
Fixed in 7e56f1bbb72c18a9edff98a3ee159230d5ee5cff (forget to add the issue number)
