### ISSUE TITLE
Allow for spoofed PUT and DELETE requests.

### ISSUE THREAD

**Issue by dhrrgn** [fuel/core#329]
Allow for "spoofed" PUT and DELETE requests.  Check for a '_request_method' POST variable, if it is set, treat the request as that type.

**Comment by jschreuder** [comment]
I like it, but as an option that is switched off by default and can be switched on by assigning a POST variable name to check.

**Comment by chendrix** [comment]
Definitely. This type of feature is already being implemented in other popular frameworks (Express.js, Rails, etc.) and would be a great feature to have.

I'm unsure how the Controller_Rest checks for the method, but if it's `$_SERVER['REQUEST_METHOD']`, then some piece of Form middleware could simply check for `_request_method` and change the variable.

Also, debatable `_request_method` vs `_method`?

**Comment by jschreuder** [comment]
I was thinking about this: can't we add a generic filter mechanism that can rewrite server vars and other environment stuff based on .htaccess and input? I don't have a clear idea yet, but something along those lines...

I do think '_request_method' is far better, '_method' is non-descriptive and might be needed by the user.

**Comment by jschreuder** [comment]
Closing this in favor of #392
