### ISSUE TITLE
Route statement :segment regex not correct

### ISSUE THREAD

**Issue by WanWizard** [fuel/core#33]
In the Route class, ":segment" is replaced by "([^/]+([^/]*))", which contains a double set of parentheses, giving you $1 and $2.

See http://fuelphp.com/forums/topics/view/1005 for more details.

**Comment by santiagofs** [comment]
The solution you gave ( replacing $this->search = str_replace(array(':any', ':segment'), array('.+', '[^/]*'), $this->path); on the compile statment) seems to be working fine.

**Comment by WanWizard** [comment]
Ok, I'm going push this to the develop branch then.
