### ISSUE TITLE
Fast CGI, htaccess, URIs and GET

### ISSUE THREAD

**Issue by bencorlett** [fuel/core#331]
Hi all,

I believe it's a Fast CGI issue (https://twitter.com/philsturgeon/status/92444625930952704) that's causing URI routing to not work. With the following htaccess setup http://scrp.at/aae, all pages return a 404, they're unroutable with http://d.pr/JVXv turned on. If that's turned off you no longer get 404's all the time. The other temp fix is to put a "?" (without the quotes) after index.php in the htaccess file.

As of July 17, Input::get() and $_GET were both corrupted as well (I'm not sure if this has been rectified since then but I'll find out and add a comment to this issue). All Input::get()'s were returning false and $_GET only had the URI as a key and nothing as the value. (see http://twitpic.com/5rd84b).

I spoke to Dan Horrigan (http://twitter.com/dhorrigan/status/97501755281117185) and he suspects it is a URI class issue (this could explain the routing), however there is something else effecting the $_GET. If you do a print_r($_GET) even on index.php with the setup outlined above, you get the same results, where the URI is the key and nothing as the value.

**Comment by bencorlett** [comment]
Also, I'd like to add that I turned the following extensions off:

http://d.pr/djS9
http://d.pr/cAH8

I don't believe that these are the culprit though.

**Comment by philsturgeon** [comment]
By adding ? after the index.php (a valid fix for FastCGI support) you are setting the query string, and HTTP can only have the one. Anything you add as ?foo=bar on the end URL will all be part of the "first parameter" which is `$_GET = array('/controller/method?foo=bar')` now.

The fix would be to have a look at the REQUEST_URI and do some "?" detection.
