### ISSUE TITLE
Form auto id for multi-dimensional inputs

### ISSUE THREAD

**Issue by bencorlett** [fuel/core#332]
Away from Git ATM, but on line 684 of form.php

$field->set_attribute('id', $this->get_config('auto_id_prefix', '').$field->name);

there should be an $this->get_config('auto_id_separator') or something, and that is used to replace non alpha-numeric characters as if you have multi-dimensional inputs (e.g. people[0][name] as the name) that becomes the ID. You cannot use [] to select in CSS as they're reserved for other selectors nor can you use it in jQuery. Maybe it should do a replace with whatever the user chooses so it becomes people-0-name.

**Comment by WanWizard** [comment]
@jschreuder: fix this? move to 1.2? reject?

**Comment by jschreuder** [comment]
I'll go into all the fieldset/validation/form issues over the weekend.
