### ISSUE TITLE
Send data to view as object or array.

### ISSUE THREAD

**Issue by NateRadebaugh** [fuel/core#335]
We should be able to send data to a view as an object or an array, whichever the developer prefers.

$data->name = 'value' ;
$data['name'] = 'value';

Is this fitting with the standards of the framework?

**Comment by WanWizard** [comment]
what do you mean here with $data? Can you give us some context?

**Comment by NateRadebaugh** [comment]
I'm sorry, this was related to https://github.com/fuel/core/pull/336

Closing.
