### ISSUE TITLE
Problem because of the new is_callable rule

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#337]
I'm running into problems because I was using the DB group "current" which was set using `Config::set("db.active.", "current")`, the problem is that `current()` is a PHP function and `is_callable()` will return true for it. This will be the same problem for many other generic english words as well. Maybe we should say `( ! is_string($var) && is_callable($var))` instead of just `is_callable($var)`.

Maybe even limit to just closures.

**Comment by jschreuder** [comment]
The more I think about it the more I prefer just Closures. Not only does this prevent many english words and 2 value array pairs, but you also couldn't pass an object of a class with an `__invoke()` method. Just Closures allows the dev to call whatever he wants but is never ambiguous.

**Comment by dhrrgn** [comment]
Ya, very good point.  Hadn't thought about that part of it.  I will change them to be like this:

``` php
return ($default instanceof \Closure) ? $default() : $default;
```

Should be a touch quicker too.
