### ISSUE TITLE
Modules - routing issue?

### ISSUE THREAD

**Issue by dlpetrie** [fuel/core#344]
Not sure if this is a bug or intended - I'll give an example as this is the best way for me to describe the issue.

sample code here: http://scrp.at/aaF

Basically if you have a module: 'test' with controller: 'test' and method: 'action_page' you can get to page by both these url's:
site.com/test/page
and
site.com/test/test/page

Not sure if the first occurrence should be accessible like that - or if /module/controller should be required

**Comment by dhrrgn** [comment]
This the intended functionality.

**Comment by dhrrgn** [comment]
That comment was supposed to say "That is the intended functionality". Stupid iPhone auto-correct.
