### ISSUE TITLE
Upload auto processing even when called method is process

### ISSUE THREAD

**Issue by jasonlewis** [fuel/core#350]
I'm not sure if this was the intended behavior, although I do realise that it was intended for the Upload class to auto process. However, it seems odd that it should auto process even when you are manually calling process().

A simple fix for this is to disable auto_process once you copy the upload.php config file in fuel/core/config to fuel/app/config
That said, should it be looked into to prevent the class from auto-running process() if you manually call process()

I was having some issues where it would run the processing twice, and in doing so overwrite the valid property.

**Comment by WanWizard** [comment]
This is intended behaviour, as this is what you normally would want to do if you use the Upload class.

I see no reason why you would insist on calling it manually, but if you want, disable auto_process in the config, that's what the setting is there for.

The logic of determining the valid state has been changed, it now starts with the assumption everything is valid in process(), and sets it back to false when an error is detected. So running process() multiple times shouldn't be an issue anymore.
