### ISSUE TITLE
Crazy Autoloader Problem

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#356]
The following code is in the "seasons" module:

``` php
<?php
namespace Seasons;

use \DataTable\Table;
use \DataTable\Table_Field;

class Controller_Something extends \Admin\Controller_Common {

    public function before() {
        parent::before();
    }

    public function action_index() {
        new \PromoCodes\Model_PromoCode();
    }

}
```

\PromoCodes\Model_PromoCode is a class in the promocodes module. This is NOT always loaded in the config. The above code causes an error that fuel\core\error cannot be redefined. This flashes up for a second and then the browser breaks with an error that the encoding is not supported.

Changing this to, for example, \PromCodes\Model_PromoCode works fine - it just says the class isn't found.

I don't actually want to reference \PromoCodes\Model_PromoCode from \Seasons\Controller_Something, rather this was a poor copy/paste job but the bug does seem important.

Thanks, as ever :)

**Comment by phil-lavin** [comment]
P.S. I'm using latest(ish) develop

**Comment by phil-lavin** [comment]
Ok, so apparently I lie. This isn't the problem at all. The problem is with overriding the before() method. If I comment out this:

``` php
public function before() {
    parent::before();
}
```

It works fine. This confuses me since running that and commenting it out should do exactly the same thing :S

**Comment by phil-lavin** [comment]
Ok, so the issue with this is that the before() declaration isn't compatible with that of its parent. This was logged:

Error - 2011-08-08 08:37:16 --> 2048 - Declaration of Usermanagement\Controller_Welcome::before() should be compatible with that of Admin\Controller_Template::before() in /mnt/pdrive/Clients/richardjames.co.uk/versions/kwok/includes/fuel/app/modules/usermanagement/classes/controller/welcome.php on line 8

However the error that was created (fuel\core\error cannot be redefined) does seem undesirable.

**Comment by jschreuder** [comment]
I'll close this as the basic problem reported here wasn't it and part of the problem was solved by my commit from just now I'll close this issue. I'll try to replicate the faulty error reported and fix that as well.

**Comment by jschreuder** [comment]
I've tried replicating the Error class redefine issue but I never get it by forcing a compatibility warning.
