### ISSUE TITLE
php oil r migrate failed on first migration

### ISSUE THREAD

**Issue by crynobone** [fuel/core#357]
This would only happen if project/app on first migration, problem due to following code

```
    \Config::load('migrations', true);
    $current_version = \Config::get('migrations.version');

    // -v or --version
    $version = \Cli::option('v', \Cli::option('version'));

    // version is used as a flag, so show it
    if ($version === true)
    {
        \Cli::write('Currently on migration: ' . $current_version .'.', 'green');
        return;
    }

    // Not a lot of point in this
    else if ($version == $current_version)
    {
        throw new \Oil\Exception('Migration: ' . $version .' already in use.');
        return;
    }
```

On first run, $current_version would be int(0) while $version would be null, should use === instead of == to solve this bug, pull request on the way

**Comment by philsturgeon** [comment]
Noooo it should not. It should be if $version !== null and $version ==
$current_version.

I fixed this a few times...

**Comment by crynobone** [comment]
This bug is available on v1.0 final :(

**Comment by philsturgeon** [comment]
It may well be but i made the change at least 3 times. Either way, my fix > your fix. STDIN will mark --version=9 as a string, which breaks this.

**Comment by crynobone** [comment]
Thanks for the commit :)
