### ISSUE TITLE
Image class factory arguments should be switched

### ISSUE THREAD

**Issue by ghost** [fuel/core#368]
At the moment <code>Image::factory()</code> accepts two arguments, <code>$config</code>, and <code>$filename</code>. In most cases you're more than likely going to use an image.php config file so shouldn't <code>$filename</code> be the first argument?

**Comment by dhrrgn** [comment]
No.  If you want to load in a file you should actually use `Image::load($filename);`.  The factory method is there to created a new object with specific Config.

**Comment by ghost** [comment]
Oh I'm so so sorry. Blonde moment there....

We all whinge about stupid clients, forgetting that we can be really stupid ourselves sometimes too.
