### ISSUE TITLE
Fieldset to support Optgroups for select dropdowns

### ISSUE THREAD

**Issue by CoolGoose** [fuel/core#369]
Fieldset to support Optgroups for select dropdowns

**Comment by jschreuder** [comment]
It doesn't?

**Comment by jschreuder** [comment]
Comment if you have any proof it doesn't, but as far as I know it supports it without problems.

**Comment by CoolGoose** [comment]
Example form http://scrp.at/aet
Form generates the following dropdown items (None, Array, United States)

The code that should generate this in the fieldset doesn't use the form class:

fieldset_field set_options code

http://scrp.at/aeu
