### ISSUE TITLE
Clarification on Form::button

### ISSUE THREAD

**Issue by agentphoenix** [fuel/core#37]
I noticed that `Form::button` is just an alias to `Form::input` with a type attribute of button. I was just curious why that was done instead of actually creating a button element. As [this page](http://particletree.com/features/rediscovering-the-button-element/) outlines, there are some pretty significant differences with the button element. You've already got the `Form::submit` for a submit button if someone wants, so I was just curious what the reasoning behind the button decision was. Thanks!

**Comment by WanWizard** [comment]
That is no longer true, it has been modified in the develop branch yesterday to use <button>. See 16d8ee6248010edd65c4fc9c0101d0c266423f6a.

**Comment by agentphoenix** [comment]
Must've missed that. Thanks!
