### ISSUE TITLE
Inconsistence in ::load() parameters syntax?

### ISSUE THREAD

**Issue by billmn** [fuel/core#370]
Hey,
there's a reason why Lang::load() and Config::load() has different parameter syntax for modules??

For example :

<pre>
Config::load('module::file');
Lang::load('module\\file');
</pre>

cannot be Lang::load('module::file') ?

**Comment by WanWizard** [comment]
It's not an error in the code, it's an error in the docs.

Both load() method use Fuel::find_file() to load the files, and that's where module support is built in.
