### ISSUE TITLE
newline/output in package bootstrap can break XML REST Responses

### ISSUE THREAD

**Issue by bbanzai** [fuel/core#371]
Kid: Mommy Mommy it hurts when I poke myself in the eye.. 
Mommy:  Don't poke yourself in the eye. 

Normally, that works.. but since third party packages can be loaded.. and the bootstrap can affect response from a controller... It can be hard to track down and you may not go back and test REST responses. 

``` PHP
 \\ new line, text or code here -- remove this \\
<?php

Autoloader::add_core_namespace('Isightserver');

Autoloader::add_classes(array(
    'Isightserver\\Sample'                => __DIR__.'/classes/sample.php',
));

/* End of file bootstrap.php */
```

comes out the back of a rest controller request with the brewer error

``` xml
XML Parsing Error: XML or text declaration not at start of entity
Location: http://localhost:9092/isightserver/rest/moduleinfo.xml
Line Number 2, Column 1:<?xml version="1.0" encoding="utf-8"?>
^
```

with the source of:

``` xml
\\ newline here \\
<?xml version="1.0" encoding="utf-8"?>
<xml><module_name>Isightserver</module_name><author>Your Name</author><version>1.0</version><release_date>X/XX/XXXX</release_date><default_format>json</default_format><current_format>xml</current_format><URL_info><current>http://localhost:9092/index.php/isightserver/rest/moduleinfo.xml</current><segments><segment>isightserver</segment><segment>rest</segment><segment>moduleinfo.xml</segment></segments></URL_info></xml>
```

needs an ob_clean somewhere after initializing packages.

**Comment by dhrrgn** [comment]
Pure PHP files are never to contain any whitespace that would get outputted...period.  That includes a line break at the beginning of the file before the opening PHP tag.

I have seen thousands of PHP files in my many years of PHP development, and not once have I seen a file that was all PHP have a line break at the beginning of the file before the opening tag.  I have seen a lot with it at the end (very bad) but never at the beginning.

I guess we will add it to our coding standards tho so people know not to do it.

For us to prevent it correctly in code would add another layer of buffering which slows things down a touch and takes up more memory...not going to happen.
