### ISSUE TITLE
Make Asset class work with external protocol-less paths

### ISSUE THREAD

**Issue by chendrix** [fuel/core#372]
Currently, the best practice for including externally hosted assets, e.g. google CDN's jquery, is to reference it with a protocol-less path, i.e. `//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js` so that when requested from HTTPS, it doesn't respond with a warning that not all assets are secure.

**Comment by WanWizard** [comment]
As far as I can see, this is supported since April 27th, 2011. It works without problems on 1.1/develop.
