### ISSUE TITLE
Fatal error: Exception thrown without a stack frame in Unknown on line 0

### ISSUE THREAD

**Issue by vamsiikrishna** [fuel/core#379]
Fatal error: Exception thrown without a stack frame in Unknown on line 0

When I delete the default route controller files defined in routes.php

**Comment by WanWizard** [comment]
That happens when you get a fatal error in the error handler.

When you delete the default route, you shouldn't get an error, just a 404 when no other matching route is found.

**Comment by jschreuder** [comment]
As you haven't replied for over 2 weeks I'm going to assume this is resolved.
