### ISSUE TITLE
Problems with sessions

### ISSUE THREAD

**Issue by agentphoenix** [fuel/core#38]
<pre>public function action_page1()
{
    Session::set('foo', 'FOO');
    echo Debug::dump(Session::get('foo'));
    
    echo Html::anchor('welcome/page2', 'Next Page');
}

// output: 'FOO'

public function action_page2()
{
    echo Debug::dump(Session::get('foo'));
}

// output: NULL</pre>

I've run in to some issues with sessions. Maybe I'm doing something wrong, but I can't keep session variables across page requests. I thought maybe it was how I was doing something, but even the vanilla code above doesn't work for me. Am I missing something? I just pulled the latest code from the develop branch about 30 minutes ago.

**Comment by WanWizard** [comment]
Your code works fine here, on a fresh clone of the develop branch. Nothing changed in the config? No errors anywhere (that might be suppressed?) Is app/config/crypt.php generated and does it contain 3 random crypto keys?

Can you check in your browser if the cookie (fuelcid by default) is created?

**Comment by agentphoenix** [comment]
There is no app/config/crypt.php file, nor is there one in the core. The fuelcid cookie does is exist.

**Comment by agentphoenix** [comment]
I created the app/config/crypt.php file and now it crashes Apache on WAMP when it tries to generate the file like it's supposed to. I can try it from my Mac when I get home this afternoon, but for now, it's causing all kinds of problems on Windows.

**Comment by WanWizard** [comment]
If there's no crypt config file, you should have had an error message, as it tries to create it. Do you have error messages suppressed? The Crypt class (that is used by sessions) requires write access on the crypt config file, unless you manually create all required crypt keys.

You have managed to crash Apache by using some PHP code? That's cool... :)

**Comment by agentphoenix** [comment]
Apparently the errors aren't printed out to the browser, but they are in the log file. I'm seeing the following error messages when I try to use the Session class:
- Non-static method Fuel\Core\Crypt::secure_compare() should not be called statically in [REDACTED]\core\classes\crypt.php on line 164
- mcrypt_generic_init() [<a href='function.mcrypt-generic-init'>function.mcrypt-generic-init</a>]: Key length incorrect in [REDACTED]\core\vendor\phpseclib\Crypt\AES.php on line 361 (also line 362)
- mcrypt_generic_init() [<a href='function.mcrypt-generic-init'>function.mcrypt-generic-init</a>]: Key size is 0 in [REDACTED]\core\vendor\phpseclib\Crypt\AES.php on line 361 (also line 362)

If I change the `secure_compare` method to be static (it isn't by default), none of the errors are generated, but neither is the crypt config file (not that it is being generated if that method isn't static though).

**Comment by WanWizard** [comment]
Does your webserver have write access to app/config/crypt.php?

If not, create an empty file, give your wenserver user write access on the file, do a page request (which will update the file), and remove write access.

This is required, as we don't want to distribute Fuel with preset encryption keys (that users probably don't change).

**Comment by WanWizard** [comment]
app/config/crypt.php needs to contain:

```
return array (
    'crypto_hmac' => '123456789012345678901234',
    'crypto_key' => '123456789012345678901234',
    'crypto_iv' => '123456789012345678901234',
);
```

Note that all keys need to have a length that's a multiple of 4, and in base64 encoding. If you create it manually, make sure they're truely random. The crypt class takes care of that if you give it write access.

**Comment by agentphoenix** [comment]
I just pulled the changes you committed to the Crypt class and tried again without creating the config file. Instead of throwing errors, it created the config file and the session work like I expected. Thanks for your quick response to this issue!
