### ISSUE TITLE
Fieldsets: Form Required Mark won't show

### ISSUE THREAD

**Issue by DregondRahl** [fuel/core#382]
From Debug::dump()

``` php
  protected 'name' => string 'title' (length=5)
  protected 'type' => string 'text' (length=4)
  protected 'label' => string 'Article Title' (length=13)
  protected 'value' => null
  protected 'rules' => 
```

Even if in set_form_fields() rules is set to 'required'

**Comment by jschreuder** [comment]
This is way too little information.

First: the only value that might be interesting of this dump (probably Fieldset_Field instance, but you didn't specify) would be the rules - but those aren't there.

Then I'd need to see your template and your required mark.

Without that information I have no idea where to start.

**Comment by DregondRahl** [comment]
Sorry about that, ill try to provide as much as i can, but I don't know much about the class itself.

config/form.php : http://scrp.at/ad7

model : http://scrp.at/ad9

view :  http://scrp.at/ad-

Right now it gives this error, since im using array('required' => true) outside the attributes array. So it should be right. But it gives this error:

``` php
Warning!

ErrorException [ Warning ]: call_user_func_array() expects parameter 2 to be array, boolean given

COREPATH/classes/fieldset/field.php @ line 112:

111:    {
112:    call_user_func_array(array($this, 'add_rule'), $rule);
113:    }

```

Should be this i think.   

``` php
call_user_func(array($this, 'add_rule'), $rule);
```

After trying that fix it gives this Error::notice

``` php
Notice: Invalid rule "1" passed to Validation, not used. in (unknown) [(unknown)]: add_rule 
```

I think something is either wrong in the way im structuring the rules array, or its something with the add_rule method in Fieldset_Field

**Comment by DregondRahl** [comment]
Sorry, finally figured out the structure is just different for the validation rules in the forms than the other methods 

``` php
        $form->add('title', 'Title', array('type' => 'text'), array(
            array('required'), array('min_length', 4), array('max_length', 255),
        ));
```
