### ISSUE TITLE
Upload class to have config presets like Image class

### ISSUE THREAD

**Issue by lukearmstrong** [fuel/core#385]
It would be nice to have be able to set config presets for the Upload class, as you can with the Image class.

So that way if you have various forms for uploading images throughout a CMS, they can all share the same whitelists. Whilst not affecting various forms for uploading other types of files.

It would also be nice to be able to use presets, and still be able to override settings on a per usage basis.

**Comment by lukearmstrong** [comment]
Well to be honest it would probably be useful if all classes could support config presets, and have the presets dealt with by a config class or something, so that the presets work in exactly the same way for all classes.

So priority is in this order.
1. Allow config values to be defined/overridden per usage (even if preset is selected).
2. app/config preset values (if preset selected)
3. app/config values
4. core/config values

**Comment by WanWizard** [comment]
Added to the 2.0 roadmap.
