### ISSUE TITLE
Multiple queries in Mongo_Db failing

### ISSUE THREAD

**Issue by mattm458** [fuel/core#387]
Is there any reason why _clear() isn't called at the end of the get() function before the results are returned? Without it, because of the way the Mongo_Db class works, it's impossible to perform multiple queries on the same database in a single page load, unless I'm missing something obvious. As it is, get() doesn't clear away old constraints, so if I make multiple queries, they're all polluted with leftover constraints from previous queries and no results come back.

**Comment by rjdjohnston** [comment]
You could add the clear on line 626 to achieve the desired result.  Personally I like not having clear in this position, it makes loops and maintaining object settings until explicitly being reset.  Two sides to this coin.

I added a $clear var set to TRUE by default.  When I need to maintain object properties between operations I set $clear to FALSE, I added this line in the beginning of private clear method which stops "clearing".  

```
if ( $this->clear == FALSE ) return;
```

**Comment by WanWizard** [comment]
Call to _clear() has been added in 83f95aff73cdf1bbea9d1c89e95f0c041192bb91
