### ISSUE TITLE
Fieldset_Field  'select' options repeats

### ISSUE THREAD

**Issue by DregondRahl** [fuel/core#393]
When using the ORM set_form_fields() with select options. It makes it appear twice each option in the final dropdown. This started happening after the last push: http://xdat.us/cS6nR.jpg

https://github.com/fuel/core/commit/e25d5975c6ec61a34bc3ff6b96fd6d4f90981854

That change seems to be where the problem is.

**Comment by jschreuder** [comment]
The only way that could happen is if set_form_fields is fully run twice, but as far as I remember there were measures against that. Is your pull from the Orm repo up-to-date as well?

**Comment by DregondRahl** [comment]
Yup updated the ORM too. When i switched the method set_options() with the old one, it worked fine.

Hmm is options ment to be set here: https://github.com/fuel/core/blob/develop/classes/fieldset/field.php#L88
Because i think it gets set here too: https://github.com/fuel/core/blob/develop/classes/fieldset/field.php#L101

**Comment by jschreuder** [comment]
Yeah, I think you got it. Try removing line 88, could you let me know if that solves it?

**Comment by DregondRahl** [comment]
Yup, works fine without line 88
