### ISSUE TITLE
Class loading behaviors

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#395]
Currently we have one of those: an `_init` method is executed when available. But I was thinking about ways to extend on that, for example to autoload config files based on the classname. CI does that, but I don't like to do it always (waste of resources). Thus I started thinking about other ways to solve that, annotations would be awesome but PHP doesn't have those and I don't like the overhead that checking for those adds either.

Then I thought of this:

```
interface ConfigLoader {}
class Something implements ConfigLoader {}

$a = new Something();
var_dump($a instanceof ConfigLoader); // true
```

This would work and add little overhead. For the 1.x branch we can't make `_init` a behavior, but we can add the more general functionality to the autoloader that allows for more types of classloading behavior:

```
interface ConfigLoader {}
Autoloader::add_load_behavior('ConfigLoader', function($classname) {
    Config::load($classname);
});
```

(this would eliminate the need for some `_init` methods in the core btw)

**Comment by dhrrgn** [comment]
Hmm...Not bad.  I need to mull it over for a little bit tho.  I am not entirely happy with the Autoloader as it is anyway, so this could make it in as part of a refactor I guess.

I just don't want the autoloader to become so monolithic that it starts to impede performance.  It is already the bottleneck of the entire app (until you throw DB queries in there).

**Comment by jschreuder** [comment]
We talked about this before and I'm not sure the autoloader could be much faster, there's little to no waste in there - or if there is I can't find it. This shouldn't add any overhead unless you actively add behaviors, and checking a few `instanceof` classes for each loaded class shouldn't add meaningfull overhead.

Also the time reported to be spend in the Autoloader might not be entirely fair as there's some heavier `_init` methods that are executed by the Autoloader.

**Comment by jschreuder** [comment]
@dhorrigan any further thoughts on this?

**Comment by jschreuder** [comment]
@dhorrigan if you don't comment I'm just going to implement it as proposed.

**Comment by tarnfeld** [comment]
Interesting idea, would you this work with subclasses though.. I don't think it would. Say we have the following...

Class A implements ConfigThing
config/a.php

Class B extends A
config/b.php 

That's not right. It should load the parent config file, maybe a static property would be a better idea?

**Comment by jschreuder** [comment]
Good point, though not always necessary. Generally it won't change anything about how these class behaviors would work, just how the Config behavior could work. Reason it's not always necessary is that when you load class B it will also load class A and perfrom its classloading behaviors. Reason I do see use for this is that it would prevent a second search for the config file belonging to B and allow more flexibility.

@dhorrigan I'm moving ahead and implement this.

**Comment by jschreuder** [comment]
Haven't implemented the behavior with other classes yet.

To give the example I used for testing, the Cache class currently starts like this:

``` php
class Cache
{

    /**
     * Loads any default caching settings when available
     */
    public static function _init()
    {
        \Config::load('cache', true);
    }
```

But this can now be:

``` php
class Cache implements \Autoload_Behavior_Config
{
```

**Comment by philsturgeon** [comment]
Is this just more OOP for the sake of more OOP? I like that _init() is pretty obvious and I'm not sure what the downsides are.

**Comment by jschreuder** [comment]
It's not meant to replace `_init()`, it's meant to cleanup init and allow for some more generic tasks to be done more elegantly.

**Comment by philsturgeon** [comment]
Why? If we want to load config then using Config::load seems like a pretty logical way to do things.

**Comment by tarnfeld** [comment]
I don't think it's really needed... It's alway better to be more verbose and have less magic. And how would this work with config files with different file extension, how would it know which one?

**Comment by jschreuder** [comment]
@philsturgeon Config is actually a weak example but it was the easiest to give. This is about allowing some generic loading mechanism for specific classes, to give a callback during autoloading that is not necessarily part of the inheritance of the class (speaking practically, technically it is of course as I use interfaces for this).

@tarnfeld magic is when stuff happens automatically, this isn't magic as you explicitly tell the class it must use a loading behavior.

**Comment by frankdejonge** [comment]
I don't see any reason not to have this. Don't want it? Don't use it. Seems handy in some cases. The only concern I have is performance. All the loader behaviors are iterated through per class load? That seems like quite a workload. Did you run test on this?

**Comment by jschreuder** [comment]
@FrenkyNet it checks whether the class being loaded implements interfaces and if so iterates through the interfaces if any is registerd as a loading behavior. Thus classes without interfaces do very little, those with interfaces only need `array_key_exists()` as extra overhead.

**Comment by frankdejonge** [comment]
@jschreuder: Ok, that's very minimal. What other things do you intend to create behaviors for? I can think of Config, Lang, ... ?

**Comment by jschreuder** [comment]
@FrenkyNet lol, not sure yet. It's a new concept for me as well.

Lang is an easy one like Config, though both are more about making code look better than adding power (which in itself isn't a bad thing of course). But now it's here it adds a new dimension to autoloading which may come in handy down the road.

**Comment by jschreuder** [comment]
One thing I forgot but did say in the initial explanation of the concept: we could easily re-implement support for `_init()` into a behavior - which would no longer assume each class might have an `_init` method but only call such a method when implementing a `Autoload_Behavior_Init` interface.

That way what happens after a class is loaded becomes truly flexible and doesn't do anything "magicly" anymore.

**Comment by philsturgeon** [comment]
Sold. Write up some mega impressive documentation for this feature 
before you do anything else though, or we'll be stuck with another 
absolutely amazing feature I have no idea how to use. I know I'm not the 
smartest dev on the team, but if even I don't get it we can assume a 
vast majority of others wont.

> ---
> 
>   Jelmer Schreuder 
> mailto:reply@reply.github.com
> 19 October 2011 15:28
> 
> One thing I forgot but did say in the initial explanation of the 
> concept: we could easily re-implement support for `_init()` into a 
> behavior - which would no longer assume each class might have an 
> `_init` method but only call such a method when implementing a 
> `Autoload_Behavior_Init` interface.
> 
> That way what happens after a class is loaded becomes truly flexible 
> and doesn't do anything "magicly" anymore.

**Comment by jschreuder** [comment]
Forgot to relate it: 52c5e19512c683e50299de98fe4c64148e6a9488

`_init()` is now a behavior as well but will be used for every class even without extending the interface for it.

**Comment by jschreuder** [comment]
Damn, wait a sec - messed up and committed the non-bugfixed and then merged it wrong.

**Comment by dhrrgn** [comment]
Whoa Whoa, slow down here, don't make any more changes.

I have been trying to make things smaller, simpler, faster, etc.  This just adds a bunch of code and overhead to what do what?  To remove a line or two from some `_init` methods?

Lets go through the issues.
1.  `_init` stays.  Not as a "behavior" but as the the method, which gets called from autoloader, just like it always has.  Period, end of story.  I will remove any code that removes this functionality as it is.  It is just the way it is.
2.  You can try to say its not all you want, but this is Magic.  You implement an Interface and BOOM, it magically loads your config.  You have no idea how it did it, because well, an interface can't implement the body of a method, so how did that code get there? Obviously we know how the code got there, but would someone just picking up Fuel?  No.
3.  I don't see the point in adding 50-100 lines just so we can be lazy and not write a couple lines of code.  Not to mention you have added 3 files.  File loading is (besides DB) the slowest part of any request, and I have worked hard to get the number of files loaded way down, and here we are adding 3 more.  Throwing the interfaces/classes/magic beans into 1 file isn't going to happen either.

Just overall, it is an interesting idea...for a different framework.

**Comment by jschreuder** [comment]
@dhorrigan you liked it at first and didn't reply to my many requests for attention for this.
1. `_init()` is as much magic and a "behavior" as the others, it's a framework specific convention that can't be changed or overwritten.
2. It's not magic, if setting something explicitly than can be configured is suddenly magic than we have a shitload of magic throughout the framework.
3. If it's fileloads you're concerned about just add these 3 to the Autoloader.php file.

**Comment by jschreuder** [comment]
Reset develop to pre-these changes and changed the status to Denied.

Will be making the Autoloader extendable to make this possible through extension.
