### ISSUE TITLE
[v2.0] Require responses to be returned instead of setting them by default

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#397]
I think this was @dhorrigan's original plan but it was nixed not to change the existing architecture too much when introducing the concept. I'm already doing this in my own apps because it leads to much more descriptive code in my opinion. I also allow there for returning a string which is then turned into a default Response with status 200.

**Comment by dhrrgn** [comment]
Yes, I want to do this.  We could probably do this in 1.1 and deprecated $this->response, then remove it in 2.0.

Not sure about returning the string part tho...I guess that could work, but I think it would leave people to doing stuff like:

``` php
return View::factory('404');
```

I don't know.  Maybe.

**Comment by jschreuder** [comment]
Implemented.
