### ISSUE TITLE
Error Reporting configuration per Environment

### ISSUE THREAD

**Issue by lukearmstrong** [fuel/core#400]
This is a feature request.

I wasn't aware of this, but fuel overrides the "error_reporting" and "display_errors" settings in the [public/index.php] file. For now I have commented these out.

Surely a better solution would be to allow these settings to be defined in the [/app/config/config.php] file. Or if they are not defined, then it takes on the settings defined in the [php.ini] file.

Like database settings, these should be dependant on environment.

During development, I would prefer to show all errors in the browser, and not log any errors.

But in production, it would be the opposite way around. I wouldn't show any errors in the browser, but log all errors.

**Comment by jschreuder** [comment]
This is part of #394 and doesn't need a separate issue.
