### ISSUE TITLE
URI Fails on reverse https/http proxy

### ISSUE THREAD

**Issue by moos3** [fuel/core#401]
URI fails to detect if the original url is https or http when using reverse proxy in apache. Setup is this

Apache Reverse Proxy (https/http)
                   ||
                   \/
web1 ---------------------- web xxxx

If incoming url is https:// backend webs see it as http so the forms getting rendered with http:// and not https://.

Solution is to set base_url in app/config/config.php. The URI Class should be able to detect this in some fasion, maybe with a option that is use_ssl = > true, instead of wanting the base url to be set for https.

**Comment by WanWizard** [comment]
You should configure the base_url to what the users of the application need to connect. If that is https, you should configure it as so, even it the site itself is accessed (via the RP) via http.

You can also use relative links in your app by using '/' as your base_url. If the user connects via https, this makes sure all links will be https too...

I don't know of any way of detecting a reverse proxy in the path, and to detect which protocol is being used on the outside. If you do, please re-open this issue.
