### ISSUE TITLE
Declarations in class Image_Imagemagick do not match class Image_Driver

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#405]
When using the ImageMagick library, I see the following in the log file:

Error - 2011-08-17 10:49:57 --> 2048 - Declaration of Fuel\Core\Image_Imagemagick::load() should be compatible with that of Fuel\Core\Image_Driver::load() in /home/_Fuel-1.0/core/classes/image/imagemagick.php on line 17

Error - 2011-08-17 10:49:57 --> 2048 - Declaration of Fuel\Core\Image_Imagemagick::_rounded() should be compatible with that of Fuel\Core\Image_Driver::_rounded() in /home/_Fuel-1.0/core/classes/image/imagemagick.php on line 17

I believe the problem is that the functions do not have the same number of parameters.

In class Image_Driver, the load function is: 
    public function load($filename, $return_data = false)

In class Image_Imagemagick, the load function is: 
    public function load($filename)

Similarly, the functions rounded() do not have the same number of parameters.

**Comment by huglester** [comment]
Hello,

you are probably are using the `master` version of image class. 
It has already been fixed in develop: https://github.com/fuel/core/blob/develop/classes/image/imagemagick.php#L24

**Comment by Mitchell64** [comment]
I just checked the new file, and it looks like it fixes the 2 problems I saw as well as some other things.

Thanks,
Mitchell
