### ISSUE TITLE
Shutdown events in reverse order mean session data cannot be changed on shutdown

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#407]
Is this strictly necessary? The reason I ask is this causes the session save to happen before anything user code has added. This means that a user defined shutdown function cannot modify session data as it's already been saved.

**Comment by WanWizard** [comment]
That's weird, because the idea behind reversing them was that the first events pushed on the stack should be the last one executed, namely the session updates and Fuel cleanup.

**Comment by WanWizard** [comment]
Just checked, Event::register prepends new events, and Event::trigger executes in sequence, so latest first. I guess this is a leftover from before the Event class creation, reversing it is no longer needed.

**Comment by dhrrgn** [comment]
I have merged the request in here https://github.com/fuel/core/commit/823731ac686cbca3c1baee28a3165f48755de6bb
