### ISSUE TITLE
Enable multiple languages at the same time

### ISSUE THREAD

**Issue by bestxp** [fuel/core#416]
Need to add the ability to reset the language of variables from files under the current version of Config:: get ('language')

**Comment by jschreuder** [comment]
I'll rephrase this a bit: language files should be loaded into a key of their own language, thus making it possible to load language files from multiple languages without conflicting. The `Lang::line()` method and corresponding `__()` function should also support an extra $language param to fetch from other than the default language. A wrapper function for changing the language setting in config `Lang::switch()` would also be nice.

**Comment by jschreuder** [comment]
Added the possibility to load different languages into groups by added third param to `Lang::load($file, $group, $language)` - check [this page in the wiki](https://github.com/fuel/core/commit/348d6e76abaf39b1e50d5535ff20b2eae9fd469e) for more information.

Would this solve your problem? If not describe a bit more extensively what you want, prefereably with examples.

**Comment by bestxp** [comment]
iThis is not exactly what you need. 
Although the decision was a recipe on the forum, but it unfortunately affected the change of the kernel (bootstrap.php), but it is not good. 

I wrote about the need to add a feature that would restart all the language files. And not just one. Under the current language of the config. 
That is, if the boot process, I changed the locale, it was said earlier eg lang:: swith ($ lang) or lang:: reload (), I would reload all the language files have been downloaded (eg consider only data from always_load

**Comment by jschreuder** [comment]
If you want to change the language in config you should do it before any file is loaded so you don't have to load twice because the first was useless. Best way to do this is probably to extend the _init() method in your own Lang class extension and detect and switch the language there before any Lang::load() is used.
