### ISSUE TITLE
Upload::get_errors() doesn't take into account UPLOAD_ERR_NO_FILE errors

### ISSUE THREAD

**Issue by andrewwheal** [fuel/core#421]
If no files are uploaded then Upload::get_errors() is empty, whereas I would expect it to report UPLOAD_ERR_NO_FILE errors for all the file fields in the form.

Although whether UPLOAD_ERR_NO_FILE errors are reported on or not you may still need to check for them dependant on whether or not you wanted the upload to be required.

Personally I am currently wanting to make a file upload required.

**Comment by WanWizard** [comment]
The Upload class doesn't deal with form info, it deals with uploaded files.

If there are none, i.e. if $_FILES is empty, there's nothing to process, and nothing to set an error code to...

The only indication that there are valid files is to call process() first (if not called automatically), and check the is_valid() status.

**Comment by andrewwheal** [comment]
I can see what you are saying, would be perhaps useful to be able to do Upload::get_files('my-file-field') to make it easier to check individual fields. I may look into this when I get a chance.

Also, when no files are uploaded $_FILES is not empty, instead it is like below:

```
array
  'image' => 
    array
      'name' => string '' (length=0)
      'type' => string '' (length=0)
      'tmp_name' => string '' (length=0)
      'error' => int 4
      'size' => int 0
```

**Comment by WanWizard** [comment]
I'll have a look at it next week, I'm on the move at the moment...

**Comment by WanWizard** [comment]
I think this issue has been corrected by FrenkyNet's recent modification.

Can you confirm this has fixed the problem?

**Comment by andrewwheal** [comment]
After uploading no files, both get_errors() and get_files() are still empty and is_valid() is true
