### ISSUE TITLE
Issue with image lib (crop_resize)

### ISSUE THREAD

**Issue by huzzi** [fuel/core#427]
I have an image which is width:200px and height:250px, trying  crop_resize on the image produces an image with width:40 and height:200px which is wrong.

 \Image::config(array( 'persistence' => true,
                    ))->load($orig_filename)
                    ->crop_resize(200, 200)
                    ->save($thumb_file);

**Comment by huglester** [comment]
what driver are you using?

**Comment by huzzi** [comment]
using the gd driver.

**Comment by huzzi** [comment]
huglester, were you able to reproduce it?

**Comment by rob-mccann** [comment]
I had a similar issue. I switched to ImageMagick and it seemed to work, does it work for you using Imagick?

**Comment by dudeami0** [comment]
I'll look into it and get back with what I find.

**Comment by dudeami0** [comment]
I wasn't able to reproduce the error with the code you provided. Any way you could send more details (Like the debug) to dudeami0@gmail.com? The original image would help as well.

**Comment by huzzi** [comment]
will do tonight, which version did you test it on?

**Comment by WanWizard** [comment]
@huzzi, @dudeami: is this still an issue on 1.1/develop, or can this be closed?

**Comment by jschreuder** [comment]
no comment after 3 days, going to assume this was invalid - reply with additional info if it's still there.
