### ISSUE TITLE
Format::_from_xml() doesn't work properly with recursion

### ISSUE THREAD

**Issue by kriansa** [fuel/core#432]
When you parse some data from xml using Format::factory($data, 'xml')->to_array(), if in your xml there's more than one level, the sub-levels will be parsed as a empty array.

ex:

``` xml
<xml>
    <servername>test</servername>
    <user>
        <name>John</name>
        <address>CA</address>
    </user>
</xml>
```

Will be parsed as:

``` php
array(2){
    'servername' => 'test',
    'user' => array(2){
        'name' => array(0){},
        'address' => array(0){},
    }
}
```

That's because the simplexml_load_string function convert all the input string in objects/sub-objects of SimpleXMLElement class, so casting the main element as array doesn't work well.

**Comment by digitales** [comment]
I'm still new to git, but I have written a fix and tested it locally. Hopefully it will be accepted into the development branch.

**Comment by kriansa** [comment]
I don't think this is the best way to fix it. You should do it from the "source" of the problem (cuz Format::_from_xml() isn't converting xml to array recursively). If you use Format::factory($data, 'xml')->to_json() for example, it's still going to break the sub-levels. I fixed it, i'm just trying to use this git to commit it... (yeah digitales, i'm so newbie as you in git :P)
