### ISSUE TITLE
[Proposal] Pagination class to allow suffix uri

### ISSUE THREAD

**Issue by crynobone** [fuel/core#435]
### Case Study

Most of the time, pagination would be use to break list of data (in table format) and it's highly restricted to use of uri segmenting. However this has one big limitation mainly when we need to do some filtering to the listing, search by username, date range and etc. 
### Suggestion
- Add Pagination::$suffix_uri static property so we can add query string
- Add static build_get_string method to Uri class, this allow you to filter which $_GET value to look for

I found this to be highly useful and I think it would be great to include it in as core :)

**Comment by tarnfeld** [comment]
I agree, though personally I think this should just use the current GET parameters (not sure where you'd get them from).

**Comment by crynobone** [comment]
It would be nice if we can filter $_GET using something like https://github.com/codenitive/fuel-hybrid/blob/1.1/develop/tests/uri.php

**Comment by WanWizard** [comment]
Pagination class functionality will be reviewed after v1.1.
