### ISSUE TITLE
Uri::current(), Uri::main() says http instead of https

### ISSUE THREAD

**Issue by bproctor** [fuel/core#437]
Uri::current() and Uri::main() both return http:// when visiting called from an https:// site.

**Comment by bproctor** [comment]
a couple of things I should have mentioned.  I'm running nginx and in my config, base_url = null.  I'm looking into what might be causing this...

**Comment by jschreuder** [comment]
This is how it is detected: https://github.com/fuel/core/blob/1.1%2Fdevelop/classes/input.php#L191 - might help you figure out why it fails for you.

**Comment by bproctor** [comment]
Ah yes, nginx doesn't set $_SERVER['HTTPS'] by default.  Thank you.

**Comment by jschreuder** [comment]
Closing this as you have a pull-request on the same issue.
