### ISSUE TITLE
Session_Driver::rotate() if logic

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#439]
The following code seems a bit off to me, but wanted to check before touching it [(original)](https://github.com/fuel/core/blob/1.1%2Fdevelop/classes/session/driver.php#L239):

```
if($this->config['rotation_time'] &&
    ($force or $this->keys['created'] + $this->config['rotation_time'] <= $this->time->get_timestamp()))
```

That requires ration_time to be set and doesn't allow force otherwise, shouldn't it be:

```
if($force or
    ($this->config['rotation_time'] and $this->keys['created'] + $this->config['rotation_time'] <= $this->time->get_timestamp()))
```

Also can I use `Session::instance()->rotate(true);` to solve [this issue](https://github.com/fuel/auth/issues/24)?

**Comment by WanWizard** [comment]
Session_Driver::rotate() is called from the individual drivers write() method, before updating the session cookie, with a parameter 'false'.

This if makes sure rotation happens only if a rotation time has been defined, and if it has expired or if roration is forced. Your observation is correct tough, I'll fix this.

You can manually call Session::instance()->rotate() to trigger rotation, no need to pass 'true', that's default.
