### ISSUE TITLE
DBUtil missing features

### ISSUE THREAD

**Issue by philsturgeon** [fuel/core#44]
It's always possible that I'm being an idiot and I'll be happy to admit it if needs be, but where in the hell is add_fields() functionality? DBUtil seems to be missing this, and scarily still has an awful lot of SQL strings in it. 

My final question on DBUtil, is that it seems to totally disrespect tables prefixes, meaning that migrations (more specifically DBUtil::create_table('foo')) will break whenever a prefix is used.

It might be something for v1.1 but I feel this issues should probably be cleared up before final as... well it's really not final.

**Comment by jtdroste** [comment]
According to RC2 Changelog:

"The DBUtil class now respects the table prefix if set (Fixes #103). (Dan Horrigan)"

**Comment by bencorlett** [comment]
also last i checked you can't specify an engine to use, myisam or innodb etc

**Comment by frankdejonge** [comment]
I've just tested and made pull requests for the missing DBUtil features: add_fields, drop_fields. Also added charset support for databases and tables. + bonus for @bencorlett... support for table engines. Hope you guys like it. If they get pulled, I'll fix the docs for them right away.

**Comment by jschreuder** [comment]
This issue can be closed now as far as i can see, reopen if I'm wrong.
