### ISSUE TITLE
Mongo_DB or_where() fails: don't return any result

### ISSUE THREAD

**Issue by ipalaus** [fuel/core#440]
Hello,

I'm using the Mongo_DB class but I thing there is a bug on or_where() function. I've a code to reproduce this:

```
        $mongo = \Mongo_Db::instance();
        $result = $mongo->get("users_example");

        \Debug::dump($result);

        $user = array(
            "username"  => "example",
            "password"  => "example@domain.tld",
            "more"      => "values"
        );

        $result = $mongo->insert("users_example", $user);

        \Debug::dump($result);

        $result = $mongo->where(array("username" => "example"))->get("users_example");

        \Debug::dump($result);
```

This works perfect, it finally returns me the desired usernames with username=example. But If I try the next:

```
        $mongo = \Mongo_Db::instance();
        $result = $mongo->get("users_example");

        \Debug::dump($result);

        $user = array(
            "username"  => "example",
            "password"  => "example@domain.tld",
            "more"      => "values"
        );

        $result = $mongo->insert("users_example", $user);

        \Debug::dump($result);

        $result = $mongo->where(array("username" => "none"))->or_where(array("email" => "example@domain.tld"))->get("users_example");

        \Debug::dump($result);
```

I don't retrive any of the users with the email=example@domain.tld.

I wish I could help more but new on Mongo.

Thank you in advance!

**Comment by WanWizard** [comment]
Depending on the version of Mongo used, $or can have a different behaviour.

And I don't think this will work, as the where clauses are processed in sequence, while in the Mongo query, you would need $or at the beginning. Try

```
$result = $mongo->or_where(array("username" => "none"))->where(array("email" => "example@domain.tld"))->get("users_example");
```

or even

```
$result = $mongo->or_where(array("username" => "none", "email" => "example@domain.tld"))->get("users_example");
```

and see if that produces the correct result?

**Comment by ipalaus** [comment]
Hello,

I've tried what you mentioned:

```
        $result = $mongo->get("users_example");

        \Debug::dump($result);

        $result = $mongo->or_where(array("username" => "none"))->where(array("email" => "example@domain.tld"))->get("users_example");

        \Debug::dump($result);

        $result = $mongo->or_where(array("username" => "none", "email" => "example@domain.tld"))->get("users_example");

        \Debug::dump($result);
```

But there is no result, output here: http://snipr.it/~fU

PS: It was a error on the insert script, I was adding password="example@domain.tld", but this is corrected on my code an with the first dump you can see there is a valid result.

**Comment by WanWizard** [comment]
You haven't answered my question in regards to the MongoDB version used. Earlier versions don't even support $or.

**Comment by ipalaus** [comment]
Sorry, I'm using MongoDB 1.8.3 (latest on Gentoo/Funtoo potage) and is the latest too comparing with website.

**Comment by WanWizard** [comment]
I'll have to pass this one to @philsturgeon

**Comment by rjdjohnston** [comment]
Try passing an $or query.

```
$query = array('$or' => array( 
                                     0 =>array('username' => 'none',),
                                     1 =>array('real_name' => 'example@domain.tld',),
                  );

$result = $mongo->where($query)->get('users_example");
```

**Comment by ipalaus** [comment]
@rjdjohnston same problem. No results! Thank you!
