### ISSUE TITLE
Config commit had undesired effects

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#442]
This commit... https://github.com/fuel/core/commit/ce89964c9cfbbb5c727b41ab2148de9ca179f443 by @WanWizard has had undesired consequences.

The auth package uses Config::load to load the simpleauth config. The config in our app is being merged with that of the auth package and it is, thus, impossible to override the default roles or groups.

**Comment by jschreuder** [comment]
You mean "to get rid of" right? Good point, those should be comment examples instead of defaults.

**Comment by phil-lavin** [comment]
Yes, it is.

**Comment by phil-lavin** [comment]
I think, rather, there should be a way to have config::load override rather than merge. The issue is because simpleauth config doesn't use a fixed set of keys - I can imagine other configs may follow this principal also.

**Comment by WanWizard** [comment]
I don't consider this a bug, I think recursive merge is the desired behaviour.

However, I can understand that in certain situations you want overwrite instead of merge, so I will add the option to select this on Config::load().
