### ISSUE TITLE
Request factory doesn't auto populate default action into route

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#443]
If you manually create a request, as such:

``` php
$req = \Request::factory('/foo');
```

This will create a request to the foo controller's index action. However, $req->route->action is null.

I do recall this being fixed a while ago but it seems to be present in the latest 1.1/develop.

It does correct routing if a route exists so it's just a small consistency point that the default action should be put in the route's action.

**Comment by jschreuder** [comment]
That isn't a bug and has been the case for a long time, there is not set action thus the default will be used (either "index" or a controller property "default_action"). Only once the request is executed is the action populated.

[edit] This line if you're interested: https://github.com/fuel/core/blob/1.1%2Fdevelop/classes/request.php#L396
