### ISSUE TITLE
Wrong message in Upload if file already exists

### ISSUE THREAD

**Issue by billmn** [fuel/core#444]
Uploading a file that already exists using this config :

<pre>
// if true, add a number suffix to the file if the file already exists
'auto_rename'       => false,

// if true, overwrite the file if it already exists (only if auto_rename = false)
'overwrite'         => false,

// if true, generate a random filename for the file being saved
'randomize'         => false,
</pre>

Upload::get_errors() give :

<pre>
array(1) {
  [0]=>
  array(11) {
    ["field"]=>
    string(11) "file_upload"
    ["key"]=>
    int(0)
    ["name"]=>
    string(32) "02507_sunsetof2010_1920x1200.jpg"
    ["type"]=>
    string(10) "image/jpeg"
    ["file"]=>
    string(14) "/tmp/phpgNa38k"
    ["error"]=>
    int(110)
    ["size"]=>
    int(2005470)
    ["extension"]=>
    string(3) "jpg"
    ["filename"]=>
    string(28) "02507_sunsetof2010_1920x1200"
    ["mimetype"]=>
    string(10) "image/jpeg"
    ["message"]=>
    string(30) "The file uploaded with success"
  }
}
</pre>

The "error" code is right (110 -> UPLOAD_ERR_DUPLICATE_FILE) but the message is wrong

**Comment by WanWizard** [comment]
Nothing wrong in the code, it is using the error code to retrieve the string. 

Maybe an issue in the Lang class concerning numeric array keys?

**Comment by billmn** [comment]
No ... I've checked the upload class, and in the save() method missing Lang::get();

I've added 

<pre>
static::$files[$key]['message'] = \Lang::get('upload.'.static::$files[$key]['error']);
</pre>


before <b>umask($oldumask)</b> ( the last save method line ) and it works.

If you think that is the right method I can send a pull request

**Comment by WanWizard** [comment]
Ok, I misunderstood you. It's about errors while saving(), not in process().
