### ISSUE TITLE
Secure/HTTP (only) Session Cookies?

### ISSUE THREAD

**Issue by joshuarubin** [fuel/core#446]
Why aren't there options to mark the session cookie as secure and/or http_only by default?

**Comment by WanWizard** [comment]
Because nobody has thought of implementing that?

**Comment by joshuarubin** [comment]
LOL, ok, well I put it in and can send a pull request, its pretty trivial though.

**Comment by joshuarubin** [comment]
I just realized that the global cookie config options will work for the session cookie as well. However, I still think that it would be nice to have the options specific for session in case not all cookies should be http only (for example).
