### ISSUE TITLE
Missing argument 2 for Fuel\Core\Response::set_header()

### ISSUE THREAD

**Issue by Arjeno** [fuel/core#45]
I'm trying to get a CSV output with a REST controller. However I'm getting the following error: Missing argument 2 for Fuel\Core\Response::set_header(). Looks like there's a function in the base rest controller calling: 

$this->response->set_header('Content-Type: '.$this->_supported_formats[$this->request->format]); 

With 1 argument but the function itself expects 2 arguments: 

public function set_header($name, $value)

**Comment by Arjeno** [comment]
This is for RC2 btw.

**Comment by philsturgeon** [comment]
I fixed this the other day.

**Comment by dynamicpacket** [comment]
This is not fixed in master branch of fuel/core

**Comment by dynamicpacket** [comment]
diff --git a/classes/controller/rest.php b/classes/controller/rest.php
index 742b144..f379e76 100644
--- a/classes/controller/rest.php
+++ b/classes/controller/rest.php
@@ -100,7 +100,7 @@ abstract class Controller_Rest extends \Controller {
                if (method_exists('Format', 'to_'.$this->request->format))
                {
                        // Set the correct format header
-                       $this->response->set_header('Content-Type: '.$this->_supported_formats[$this->request->format]);
- ```
                    $this->response->set_header('Content-Type', $this->_supported_formats[$this->request->format]);
  
                  $this->response->body(Format::factory($data)->{'to_'.$this->request->format}());
          }
  ```
