### ISSUE TITLE
Model auto sanitization recursion

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#450]
Calling set without the last parameter being false often causes timeouts or internal server errors when used on models.

``` php
// Timeout
$view->set('foo', $product);

// No timeout
$view->set('foo', $product, false);
```

I think this is because of circular references existing on the models.

The obvious solution is to set false as the last param where it happens however you can never be sure that passing an object will never cause this kind of issue and, as such, should probably never escape them. This, naturally, defeats the purpose of the auto sanitization - which seems extremely useful.

**Comment by jschreuder** [comment]
Could you let me know if this fixes it?

**Comment by phil-lavin** [comment]
Fraid it doesn't fix it.

**Comment by phil-lavin** [comment]
Just done some debug code. We've put this in:

``` php
elseif (is_array($value) || $value instanceof \Iterator)
{
    // Add to $already_cleaned variable when object
    is_object($value) and $already_cleaned[] = $value;

    $i = 0;

    foreach ($value as $k => $v)
    {
        $value[$k] = static::htmlentities($v);
        var_dump($v);

        if ($i++ == 10) {
            exit;
        }
    }
}
```

This causes 'id' to be var_dump()ed each time. We're thinking this means that the Iterator on Orm model might be broken :S

**Comment by jschreuder** [comment]
In that case I have no clue, the logic seems sound in both the Iterable implementation in the Orm\Model and in the Security::htmlentities() method. Don't have time to setup a test right now so if you need this fixed now you'll have to try and figure out yourself why it doesn't recognize the loop when checking `$already_cleaned`.

**Comment by phil-lavin** [comment]
Added debug code to orm model. next() is never called.

**Comment by jschreuder** [comment]
I think that's because it goes into a loop before it gets to next, either that or there's a bug in PHP.

**Comment by phil-lavin** [comment]
Ah, shite. I know what it is. I override next() and use it for an entirely different purpose. That's annoying. I think your fix will sort out another issue that @Altreus was having though
