### ISSUE TITLE
Log file permissions

### ISSUE THREAD

**Issue by joshuarubin** [fuel/core#453]
If the log files are changed away from 666 permissions, (but are still writable), then in addition to all my other loggig, I get this error:

```
Error - 2011-09-02 18:36:00 --> 2 - chmod(): Operation not permitted in /var/www/onyz/fuel/core/classes/log.php on line 121
```

Kind of annoying...

Forcing permissions of 666 just seems to encourage bad form.

**Comment by huglester** [comment]
It probably is the problem in your setup. because: 
your web browser is running under user1, and for example while you work from console - you work from user2.

and if logfile is beeing created from console via user2, the web browser (user1) can't write to it..

**Comment by WanWizard** [comment]
You can solve these kind of issues by using a group to which both the webserver user and your commandline user(s) belong to. Set this group on the log file directory, and enable the sticky bit on the group, so that new files in that directory will always be created with the correct group.

chmod values may become configurable in the future (I have situations in which I don't want world writeable files as well), but currently this is what it is. You can re-open this as a feature request if you want.

**Comment by joshuarubin** [comment]
Thanks for the suggestions. However, I don't think I explained myself well enough.

I intentionally changed all of the directories and files away from the 777/666 permissions to 775/664. I kept them owned by my personal user, and group owned by www-data which is the group my php cgi processes are running as.

The fuel app has no problems writing to the logs.

However, because the log files are now owned by a different user, it fails when trying to chmod(666).

See my commit note here:
https://github.com/fuel/core/commit/7c38eb5ae74b67d5338edc63953bde3235fe3f3b#commitcomment-568367

**Comment by WanWizard** [comment]
In a lot of environments, the log file is created with 644 permissions for user webserver, group webserver (or whatever user/group is used). This means that all oil commands, that run on the commandline with a different user, will not be able to write to the logfile. It also means that you, as a user, don't have write access to it either.

This might be acceptable in some situations, but not in others.

So until this can be configured, we need something that allows Fuel to work in all environments. And currently, making this configurable is not on the roadmap, hence my remark about the feature request.

**Comment by joshuarubin** [comment]
Thanks for the update. I understand that maybe you can't change that when files are created, they be created with 666 permissions. However, I still think that it is unnecessary to chmod the file every time `Log::write` is called. If it can't write to the file, then it will not currently throw an error (by your explicit choice). But if it can write to the file, then who cares what permission it is?

It seems silly I have to modify core (by commenting out the chmod line) if I want to keep a log file with reasonable permissions that doesn't contain a bunch of errors in it that the permissions of the file itself can't be changed.

**Comment by WanWizard** [comment]
Understand. I'll add defaults for permissions to the file config file, and modify the file and log classes to use these defaults.
