### ISSUE TITLE
Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by amanhulee** [fuel/core#454]
I ran into a problem while calling consecutive mysql procedures.  The error is:

`Fuel\Core\Database_Exception [ 2014 ]: Commands out of sync; you can't run this command now`

Mysql reference says that:

> This can happen, for example, if you are using mysql_use_result() and try to execute a new query before you have called mysql_free_result(). It can also happen if you try to execute two queries that return data without calling mysql_use_result() or mysql_store_result() in between.

**Comment by WanWizard** [comment]
mysql_use_result() is a C function in the mysql library, and is used internally in PHP.

You could have this problem if your stored procedure returns multiple resultsets. the mysql drivers don't support that, you will have to use PHP's mysqli or pdo drivers. But in either case, Fuel's DB drivers do not support multiple resultsets at the moment.

If you have a requirement for that, please create a feature request.

**Comment by amanhulee** [comment]
Hello WanWizard,

I don't think the procedure I wrote returns multiple resultsets.

I created a test procedure:
`CREATE PROCEDURE `test`.`test_procedure` ()
BEGIN
    SELECT 1;
END`

and a test controller

``````

class Controller_Test extends Controller
{
    public function action_test()
    {
        $result = \DB::query('CALL test_procedure();', \DB::SELECT)
            ->execute();

        $result = \DB::query('CALL test_procedure();', \DB::SELECT)
            ->execute();
        \Debug::dump($result);
    }

} ```


This results in the error I mentioned.

Fuel\Core\Database_Exception [ 2014 ]: Commands out of sync; you can't run this command now [ CALL test_procedure(); ]
``````

**Comment by WanWizard** [comment]
PHP's mysql driver does not support this, switch to mysqli, I'll add support for stored procedures.
