### ISSUE TITLE
Email class: subject broken when in cyrillic (or other non-latin alphabet)

### ISSUE THREAD

**Issue by zbrox** [fuel/core#47]
The problem is that when putting anything in the subject line only the first few characters are read correctly by the mails clients (GMail, Mac OS Mail, Thunderbird) and after that the subject line gets garbled like this "=d0=b7=d0=b0_=d0=bd=d0=be=d0=b2=d0=b0_". This doesn't happen with latin characters.
I've encountered the same issue with Codeigniter and it was in the _prep_q_encoding method. I know it may not be very correct to do it but I've fixed the issue by not using the method on the subject and instead just doing this:

```
$subject = '=?'. $this->charset .'?B?'. base64_encode($subject) .'?=';
$this->_set_header('Subject', $subject);
```

in a MY_Email.php extension.
I'm not sure this is the best possible way (actually I'm sure it's bad:) ), but it'll be great if this bug doesn't continue it's life in Fuel.

**Comment by WanWizard** [comment]
Problem is that q-encoding only supports escaping 8bit ASCII, it doesn't support UTF8.

The email class needs to be modifed to support RFC2047 (MIME for SMTP headers).

**Comment by WanWizard** [comment]
Hmm... Maybe not. I've tested this using SMTP with some russian text in the subject and the body, no problems.

What email configuration do you use?

**Comment by zbrox** [comment]
I've tested this with mail. I haven't tried sendmail or smtp, I guessed it must be the same since it uses the same prep function. 
Currently I'm in the middle of a HDD upgrade, cloning my old disk, but tomorrow (since it's getting kinda late here) I'll give the other methods a try. Thanks for your help!

**Comment by zbrox** [comment]
Btw I forgot to mention that the problem is only for the subject field. No other header fields or the body of the email have scrambled chars.

**Comment by WanWizard** [comment]
Tried SMTP and Mail.

I used "Бу́ря мгло́ю не́бо кро́ет" as test text for both subject and body. No problem (receiving end was Exchange).

I don't have sendmail working in my dev environment, so testing that will mean some work. I did notice in the error message I got back from sendmail ( using $email->print_debugger() ) that the subject was encoded in utf8 quoted printable, which looks like your issue, but is actually how it should be:

```
Subject: =?utf-8?Q?=d0=91=d1=83=cc=81=d1=80=d1=8f_=d0=bc=d0=b3=d0=bb=d0=be=cc=81?=
=?utf-8?Q?=d1=8e_=d0=bd=d0=b5=cc=81=d0=b1=d0=be_=d0=ba=d1=80=d0=be=cc=81?=
=?utf-8?Q?=d0=b5=d1=82!?=
```

Nothing wrong with this...

**Comment by zbrox** [comment]
I had time to test this today and it's my bad or even Apple Mail's bad :) When the subject contains more than one word that has to be wrapped to new lines because of the 72 char limit of the header Mail does some strange things. In GMail everything's fine.
