### ISSUE TITLE
What about a Markdown like class

### ISSUE THREAD

**Issue by ushis** [fuel/core#472]
Hey frameworkers,

i wrote a class for converting plain text in valid HTML (like Markdown) for a fuel app. Do you think, it could be something for the fuel core?

Source: https://github.com/ushis/Output
Docs: http://ushi.wurstcase.net/examples/output/

If yes, i would adapt it to.

Bye, ushi

**Comment by jschreuder** [comment]
We already allow this through the Parser package github.com/fuel/parser which will be included in Fuel 1.1. This will include drivers for many template packages and will have Mustache and Markdown included.

**Comment by ushis** [comment]
Ah ok, great! Thx
