### ISSUE TITLE
PHPUnit failed Fuel\Core\Tests_Html::test_img

### ISSUE THREAD

**Issue by crynobone** [fuel/core#476]
```
$ php oil test
PHPUnit 3.5.14 by Sebastian Bergmann.

...............................................................  63 / 249 ( 25%)
............................................................... 126 / 249 ( 50%)
...................F........................................... 189 / 249 ( 75%)
............................................................

Time: 3 seconds, Memory: 12.00Mb

There was 1 failure:

1) Fuel\Core\Tests_Html::test_img
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-<img src="index.php/image.png" alt="image" />
+<img src="image.png" alt="image" />
```

Code failed in both 1.0/develop and 1.1/develop. After some code digging `\Html::img()` use `\Uri::base(false)` which would never return 'index.php'.

**Comment by jschreuder** [comment]
Doh! Someone fixed the test instead of the code - Html::img() shouldn't return index.php as part of the URL ofcourse.

**Comment by crynobone** [comment]
Which mean using `Uri::create('image.png');` is a wrong way to test `\Html::img()`

**Comment by jschreuder** [comment]
If I remember correctly Html::img() used to include index.php, but it shouldn't and has been fixed. Aparently the person writing the test didn't realize "index.php" shouldn't be part of the Html::img() output and made the test fit the bug instead of realizing he discovered a bug.

**Comment by WanWizard** [comment]
I fixed some of the tests about a week ago, but left the Uri::create() in there. I didn't notice this error because I don't have an index file defined in my test environment. :(
