### ISSUE TITLE
Class 'Error' not found

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#484]
Getting this slightly annoying bug when trying to reference \Auth::login() from a module. I'm using a custom driver which clearly has a problem, however Fuel is not being forthcoming in letting me know what that is.

Screenshot at http://www.imageupload.org/?d=7EC438F91

@Frenkynet said he sometimes gets this, also.

**Comment by jschreuder** [comment]
This is a very weird error, how the hell is it displayed when the Error class isn't found? I would think this might happen when classloading fails and it needs to show an error, the autoloading is switched off after failing to prevent loops if I remember correctly.

Never seen it myself though, can't really track it down if I can't force it.

**Comment by frankdejonge** [comment]
@jschreuder: It's displayed as a normal php error, the non-framework kind. It also in some cases displays a 'class declarations cannot be nested' error. I had this when I forgot to put the namespace declaration in a class that was namespaced but that namespace was aliased to global.

**Comment by phil-lavin** [comment]
My auth group driver extended \Auth\Auth_Login_Driver instead of \Auth\Auth_Group_Driver - this caused the error.

**Comment by WanWizard** [comment]
I'm looking forward to a case where I can reproduce this.

I'm currently assuming that this happens when an errors occurs either before the autoloader (or one of it's dependencies) is operational, or an error which interferes with the autoloaders operations.

That could be solved by testing if the class can be loaded, and if not, load it manually.

**Comment by phil-lavin** [comment]
Is http://www.2shared.com/file/E0XzrUaK/customerauth.html any use for reproducing this?

I have changed it back to extend \Auth\Auth_Login_Driver

To reproduce:
- Add the package to the project
- Load it in the config
- Change your auth.conf to use the \CustomerAuth\CustomerAuth driver
- Create a controller which calls the below code...

``` php
<?php
\Auth::login(\Input::post('email', ''), \Input::post('password', ''))
```

**Comment by WanWizard** [comment]
Getting complaints about missing table customers. So either I don't have your issue, or the code fails before getting to that point.

**Comment by phil-lavin** [comment]
Hm. Just got an e-mail from @WanWizard but the comment isn't here. Has github derped or have you realised the error?

**Comment by WanWizard** [comment]
No, wrong comment. so I deleted it again. ;)

First error i got was weird, until I realized that you probably need a database connection, and my test environment didn't have one setup.

**Comment by phil-lavin** [comment]
Ref table customers, I don't think you have my issue. The code fails, for me, before that method is called. That's sad :(

Is your controller in a module? Mine is. I wonder if the namespace makes a difference.

**Comment by WanWizard** [comment]
No, just pasted it in welcome/index. I'll try a module controller...

**Comment by WanWizard** [comment]
In a module controller, same error (table not found).

In the bootstrap, you can try to add

```
if ( ! class_exists('\\Error'))
{
    // somethings wrong with the autoloader, load manually
    require COREPATH.'classes'.DS.'error.php';
}
```

in front of the call to the Error class. Maybe that will produce the error you're having?

**Comment by phil-lavin** [comment]
Hm... I added that to the core bootstrap before the first \Error call and it stopped that error. I now get another about \Debug not being found.

Phil

**Comment by WanWizard** [comment]
Well, looks like you've definately did something that wrecked the autoloader...

**Comment by phil-lavin** [comment]
A perhaps slightly more useful xdebug backtrace is here: http://www.imageupload.org/?d=EF152BDA1

**Comment by phil-lavin** [comment]
Also, adding some debug to the autoloader to see what is being loaded, I get this...

``` Auth_Login_Driver~~~~
~~~~Auth_Driver~~~~
~~~~CustomerAuth\Auth_Login_CustomerAuth~~~~
~~~~Auth_Group_Driver~~~~
~~~~CustomerAuth\Auth_Group_CustomerGroup~~~~

...XDEBUG ERROR MESSAGE ABOUT \ERROR NOT BEING FOUND COMES HERE...

~~~~Error~~~~
~~~~Debug~~~~
```

**Comment by WanWizard** [comment]
Looking at the xdebug trace, the auth group driver is trying to load CustomerAuth\Auth_Group_CustomerGroup on L#56, which calls Autoloader::load().

Something there breaks the autoloader due to an error, which triggers the error handlers, which can't display anything due to the broken autoloader...

Looking at the customergroup class, I see

```
protected $config = array(

    'drivers' => array('acl' => array('CustomerAuth\CustomerAcl'))

);
```

Shouldn't you need to use a double backslash there? And have leading backslashes? 
Perhaps is crashes on trying to find that class?

**Comment by phil-lavin** [comment]
Double backslash is only required when the single backslash is escaping something, e.g.

'foo\\'

I'm putting some debug in but I'm greatly confused and can't find any logical flow...

The error occurs in the forge method of auth\classes\group\driver.php when it does this...

``` php
<?php
$driver = new $class($config);
```

i.e. if I put a die before, it dies. If I put a die after, it doesn't. The class it's actually trying to load here is CustomerAuth\Auth_Group_CustomerGroup. It does this successfully because the autoloader returns and the __construct method is called. The __construct method also finishes execution as putting a die() at the end of it kills the app's execution.

My understanding is that when __construct() finishes, it should return (in a sense) from the new call and assign the result to $driver. It appears to break somewhere between finishing the constructor and returning from the new call.

This baffles me :S

**Comment by phil-lavin** [comment]
Hummm... Slightly more progress...

Commenting out the return in the set_error_handler() closure in the core bootstrap forces Fuel to give me the actual error...

ErrorException [ Error ]: Class CustomerAuth\Auth_Group_CustomerGroup contains 7 abstract methods and must therefore be declared abstract or implement the remaining methods (Auth\Auth_Login_Driver::perform_check, Auth\Auth_Login_Driver::login, Auth\Auth_Login_Driver::logout, ...)

It almost seems as if the error handler closure can't autoload classes in some instances.

**Comment by phil-lavin** [comment]
Further backed up by the fact that if I do this, I get the "Class Tits not found" error and the debug in autoloader shows that it is never called for class Tits:

``` php
<?php
set_error_handler(function ($severity, $message, $filepath, $line)
{
    new Tits();
    return \Error::error_handler($severity, $message, $filepath, $line);
});
```

**Comment by phil-lavin** [comment]
Further to that... and this is a mindfuck...

If I extend \Auth\Auth_Login_Driver and don't implement the abstract method it requires, the error handler defined in the core bootstrap is called when the error triggers. This produces an insane error.

If I extend \Auth\Auth_Group_Driver and don't implement one of the abstract methods, the error handler defined in the core bootstrap is NOT called. This produces a sane error.

**Comment by WanWizard** [comment]
Hmm... Hit a PHP bug? What version are you running?

**Comment by phil-lavin** [comment]
So the problem is that an E_STRICT is being generated because of a function incompatibility. This triggers the error handler which does not even attempt to use the autoloader when using \Error. Rather it just throws a fatal error.

It's seemingly a php problem. Reproduced simply by this test case...

http://codepad.viper-7.com/818u2x (included file is http://codepad.viper-7.com/xyCn8C)

You can see that the error handler is triggered by an E_STRICT error but the autoloader isn't used.

In this test case, the error handler is triggered by an E_WARNING error (the include fails) and the autoloader is used:

http://codepad.viper-7.com/siY05v

Currently battling with the morons in ##php on Freenode who claim this is not an issue and it's documented by this...

"The following error types cannot be handled with a user defined function: E_ERROR, E_PARSE, E_CORE_ERROR, E_CORE_WARNING, E_COMPILE_ERROR, E_COMPILE_WARNING, and most of E_STRICT raised in the file where set_error_handler() is called."

Regardless... I'll report this as a bug in the hope that someone with a clue will see it. Until that time, I'd suggest Fuel works around it by manually including the required classes in the error handler closure. A better way might be to manually call the autoloader for the required classes.

**Comment by phil-lavin** [comment]
Someone already filed this as a bug in Feb. It has had no interest, apparently. I have added a comment but don't expect much. https://bugs.php.net/bug.php?id=54054

Workaround would be best, me thinks.

**Comment by jschreuder** [comment]
Don't have time to test it, but you could try adding something like this to all the error handling functions:

```
! class_exists('Error') and Autoload::load('Error');
```

Though that would still fail if the error occurs before the autoloader has been loaded, on the other hand that might be acceptable.

**Comment by phil-lavin** [comment]
It requires this to work...

``` php
<?php
! class_exists('Error') and Autoloader::load('Error');
! class_exists('Debug') and Autoloader::load('Debug');
```

It only seems to be set_error_handler() that has the bug. The shutdown function and exception handlers are fine.

**Comment by WanWizard** [comment]
@dhorrigan, can we accept this workaround?
