### ISSUE TITLE
DB::select.....->as_object(\Model_...) >> Exception [ Error ]: Could not execute Model_ProductColour::__construct()

### ISSUE THREAD

**Issue by lukearmstrong** [fuel/core#488]
I'm trying to use as_object() to return some models, which extend \Orm\Model, based on the results.

Here is the code:
http://scrp.at/aoc

I managed to work around it though, but it left me wondering what was wrong with as_object().

Here is the workaround:
http://scrp.at/aod

**Comment by jschreuder** [comment]
It might be caused by the backslash prefix in as_object(), when providing classnames as strings they don't need to include the backslash as they always start from global (will need the full namespace though when you don't want them from global).

**Comment by WanWizard** [comment]
@jschreuder: can this be closed? 

ORM models are not compatible at the moment with as_object() and I think you said that is not going to change.

**Comment by jschreuder** [comment]
Yeah, probably had something to do with that - it can thus be closed.
