### ISSUE TITLE
Bug on find_by_pk() in Model_Crud

### ISSUE THREAD

**Issue by billmn** [fuel/core#489]
That method cannot be called because the `__callStatic()` catch `find_by_` and search a column with name "pk"

**Comment by jschreuder** [comment]
Actually that should work fine, `__callStatic()` is only called when the actually called method doesn't exist - as `find_by_pk()` exists that shouldn't happen.

**Comment by billmn** [comment]
Oh sure!! I'm sorry, I've retested code and it works fine ... sorry again
