### ISSUE TITLE
Using Model::find()->where('id', 'IN, $ids) returns models ordered by id, not in the order they were in the array.

### ISSUE THREAD

**Issue by lukearmstrong** [fuel/core#495]
The code below pulls out the item ids of a product, and orders them by colour, then size.

The IDs are then put into an array, and sent to [\Model_Item::find()->where] to return models.

Problem is, the models that are returned are ordered by item.id, and not the order they were in the array.

This is because the array key on the returned array of models is the item id, so I believe PHP is ordering them based on that.

``` php
$rows = \DB::select('items.id')
            ->from('products')
            ->join('items', 'INNER')
                ->on('items.product_id', '=', 'products.id')
            ->join('colours', 'INNER')
                ->on('colours.id', '=', 'items.colour_id')
            ->join('sizes', 'INNER')
                ->on('sizes.id', '=', 'items.size_id')
            ->where('products.id', $product_id)
            ->where('products.deleted', 0)
            ->where('items.deleted', 0)
            ->where('colours.deleted', 0)
            ->where('sizes.deleted', 0)
            ->order_by('colours.name', 'ASC')
            ->order_by('colours.type', 'ASC')
            ->order_by('sizes.order', 'ASC')
            ->order_by('sizes.name', 'ASC')
            ->execute()
            ->as_array();

        if (empty($rows))
        {
            return array();
        }

        $ids = array();

        foreach ($rows as $row)
        {
            $ids[] = $row['id'];
        }

        return \Model_Item::find()->where('id', 'IN', $ids)->get(); 
```

**Comment by lukearmstrong** [comment]
Doh, just realised MySQL is returning them in the order of the ID.

**Comment by lukearmstrong** [comment]
This worked.

``` php
$rows = \DB::select('items.id')
    ->from('products')
    ->join('items', 'INNER')
        ->on('items.product_id', '=', 'products.id')
    ->join('colours', 'INNER')
        ->on('colours.id', '=', 'items.colour_id')
    ->join('sizes', 'INNER')
        ->on('sizes.id', '=', 'items.size_id')
    ->where('products.id', $product_id)
    ->where('products.deleted', 0)
    ->where('items.deleted', 0)
    ->where('colours.deleted', 0)
    ->where('sizes.deleted', 0)
    ->order_by('colours.name', 'ASC')
    ->order_by('colours.type', 'ASC')
    ->order_by('sizes.order', 'ASC')
    ->order_by('sizes.name', 'ASC')
    ->execute()
    ->as_array();

if (empty($rows))
{
    return array();
}

$ids = array();

foreach ($rows as $row)
{
    $ids[] = $row['id'];
}

$items = \Model_Item::find()->where('id', 'IN', $ids)->get();

uasort($items, function($a, $b) use($ids) {
    $a = array_search($a->id, $ids);
    $b = array_search($b->id, $ids);

    return $a < $b ? -1
        :  $a == $b ? 0
        :             1;
}); 

return $items;
```

**Comment by WanWizard** [comment]
This is a work-around for the fact that to_object('Model_Item') doesn't work. I suggest we get busy fixing that instead.

**Comment by jschreuder** [comment]
@WanWizard as I've stated before the to_object type of hydration has problems because it can make a row which has already been loaded exist for a second time in runtime (the Orm can't prevent this) which is bad and undercuts one of the important assumptions of the Orm's architecture.

**Comment by WanWizard** [comment]
I know what the problem is. I merely suggest we start looking for the solution. ;)

**Comment by lukearmstrong** [comment]
@jschreuder I realise that could potentially become a scenario when doing a complex query, such as using LEFT JOINs, but surely it should be down to a developer to ensure they aren't doing that.

I think, as @WanWizard has stated, the priority should be to get to_object() working first.

Then if there is a solution to prevent it, then work towards that... but I can't think of one other than for the developer to be made aware of the potential problems associated with having the same model exist twice. (Which I assume are, do something to one, it won't be reflected in the other).

Anyway, for now I am happy doing the above, and thanks for the work that you have done on the Orm package. It is the main reason we decided to move from CodeIgniter to Fuel.

**Comment by jschreuder** [comment]
To be honest I really don't care about this type of hydration. It's probably slower and needs more memory and it's impossible to prevent double IDs as the objects are already created at the point `__construct()` is called. The only thing left to do would be to throw an exception, effectively killing this type of hydration. Which is what my personal preference is to do, as the only thing this seems to do is to create problems.

> I can't think of one other than for the developer to be made aware of the potential problems associated with having the same model exist twice. (Which I assume are, do something to one, it won't be reflected in the other).

You may think you understand the downside of having the same object exist twice in runtime, but all I can say about that is "good luck" for when you run into a bug that is probably impossible to solve without changing all DB calls to Orm calls.

> Then if there is a solution to prevent it, then work towards that...

I have only a little bit of time to spare which I'd much rather spend on fixing actual bugs then to patch something up that I never intended to support. Or could possibly ever work reliably without creating bigger problems for unsuspecting devs who didn't fully realize the downside of the method they were using.

**Comment by lukearmstrong** [comment]
@jschreuder Well if that's the case, what is to_object(Model) for? For models that don't extend Orm?

If you don't have time to put towards getting this working, and have more urgent priorities, would you accept a pull request to fix it if I do find time to get it working?

Or would you rather to_object() not work with Orm Models at all?

**Comment by jschreuder** [comment]
Remember that the Orm is a package and not part of the core, nothing in the core is tailored exlusively for the Orm. The to_object() method uses PHPs internal functions for hydration of new instances which works in a weird way that sets the properties on the object before `__construct()` is called. But as `__set()` still works they are actually set correctly, though slow in comparison to normal hydration as using magic methods is a lot slower than just passing the array and setting it internally.

I would accept a pull-request for this, but only if it makes sense. As I said I don't think it's possible to truly fix this, I won't accept anything but a good solution.

> Or would you rather to_object() not work with Orm Models at all?

If it's impossible to solve this in a good way I'd much rather stop it working at all. So probably yes.
