### ISSUE TITLE
Default config file for pagination

### ISSUE THREAD

**Issue by rclanan** [fuel/core#498]
Would it be possible to get a default config file loaded into the core for pagination? The other classes have defaults under core/config. Would be nice to have one for pagination.

**Comment by WanWizard** [comment]
There is no need for a default config file, the default is defined in the class. You only need a config if you want to override the class defaults.

**Comment by rclanan** [comment]
That's correct, I was wanting to override the template for the pagination.

**Comment by WanWizard** [comment]
Then create a config file in app/config.
