### ISSUE TITLE
disabled state for pagination

### ISSUE THREAD

**Issue by rclanan** [fuel/core#499]
Would it be possible to get a disabled state added to the previous and next buttons? As for that to be controlled by the templates like 'active_state' & 'active_end' are?

**Comment by WanWizard** [comment]
What is it that you are trying to achieve? 

These are merely links, displayed when there are pages to link to. Even if you disable them, you can still just type the URL in (or update the page number in the current URL) to navigate, you don't need the previous/next buttons.

**Comment by rclanan** [comment]
Better styling on the front end. By adding disabled state to the previous or next button gives indication for CSS to be able to style it a certain way. 

An example would be like this: https://github.com/codenitive/fuel-hybrid/blob/develop/classes/pagination.php

The CSS example that I am trying to "achieve" is something like this: http://ikreativ.com/projects/workless/ (scroll down the pagination)

That was why I was looking for a default config file to override the current template for the pagination output.

**Comment by crynobone** [comment]
Just to add, the structure I use in Fuel Hybrid is based on Twitter's Bootstrap pagination structure http://twitter.github.com/bootstrap/#navigation

```
   <div class="pagination">
<ul>
<li class="prev disabled"><a href="#">&larr; Previous</a></li>
<li class="active"><a href="#">1</a></li>
<li><a href="#">2</a></li>
<li><a href="#">3</a></li>
<li><a href="#">4</a></li>
<li><a href="#">5</a></li>
<li class="next"><a href="#">Next &rarr;</a></li>
</ul>
</div>
```

**Comment by crynobone** [comment]
Also do consider that following template is defined BUT not even implemented in \Fuel\Core\Pagination:
- previous_start
- previous_end
- next_start
- next_end

**Comment by WanWizard** [comment]
Pagination class functionality will be reviewed after v1.1.
