### ISSUE TITLE
Response body overloaded if 404 when using template controller

### ISSUE THREAD

**Issue by stigchristian** [fuel/core#50]
If there is a 404 error when using the template controller, the Controller_Template after() method is overloading the body response.

This may be solved by adding a second condition to core/classes/controller/template.php line 53:

FROM:       if ($this->auto_render === true)

to:

TO:     if ($this->auto_render === true && $this->response->status != 404)

Making sure $this->response->body is not overloaded by the after() method.

**Comment by crynobone** [comment]
What happen if the default 404 route point to a controller using \Controller_Template, doesn't it make it unable to display a customize 404 page if you would like to have one?

**Comment by stigchristian** [comment]
The issue is solved if you make  $this->auto_render = false in the 404 action on the controller, or change the template to e.g. a 404-error template.
