### ISSUE TITLE
[Proposal] Adding parameters to DB::query, automatic quoting and escaping

### ISSUE THREAD

**Issue by polmartinez** [fuel/core#505]
Suggestion:

for all query methods, add a new metod that replace variables into que query string.

For example, I use this class for implementing a autocomplete query string:

$result = DB::query(
                new DBP('SELECT name, surname, surname2 FROM users WHERE id=:id',
                    array(
                        'id' => $this->id,
                ))
            )
            ->as_object()
            ->execute()
            ->current();

**Comment by frankdejonge** [comment]
I think this is exactly what the Database_Query::bind and ::param functions do:

```
$query = \DB::query('SELECT name, surname, surname2, FROM users WHERE id=:id');
$query->param(':id', $id);
$query->bind(':id', $id); // binding, can change later
$query->as_object()->execute()->current();
```

This has the same results.

**Comment by polmartinez** [comment]
thanks! ;)
