### ISSUE TITLE
Routing question / issue

### ISSUE THREAD

**Issue by polmartinez** [fuel/core#511]
For example: I've this routing configuration

`return array(
    '_root_' => 'index', // The default route
    '_404_' => '404', // The main 404 route
    'company/members(:any)' => 'company/members/index',
    '.*/index' => '404',
);`

In my Controller_Company_Members Controller, how I get the routing result ( in this case 'company/members/index')? when I using more parameters in the uri, for pagination for example.

Thanks

**Comment by frankdejonge** [comment]
Use the $1.

'company/members(:any)' => 'company/members/index/$1',

This is in the docs btw.

**Comment by polmartinez** [comment]
I's ok, but how I get the literal 'company/members/index' or 'company/members/index/$1' of the result of the routing?
I use this string for create a menu and check the selected item.
thanks

**Comment by frankdejonge** [comment]
it's the first param of your function :)

**Comment by frankdejonge** [comment]
If you need more help, hop by on irc:  irc.freenode.net channel #fuelphp
