### ISSUE TITLE
Router and url_suffix

### ISSUE THREAD

**Issue by mloza** [fuel/core#513]
In the newest version of fuel Router don't recognize route with url_suffix, without it everything seems to be ok.

**Comment by dhrrgn** [comment]
This seems to work fine for me.  What exactly is happening?  Can you give us what your 'url_suffix' option is set to, and what URI you are trying to go do and what issue you are seeing.

**Comment by mloza** [comment]
I have url_suffix set to .html, with fuel downloaded from site all is working fine but when I have updated to the latest from git urls with suffix eg. http://sample.com/news.html was not working. In router configuration I have something like 'news' => 'news/show_all'

**Comment by WanWizard** [comment]
Just tested this again on the latest 1.1/develop, but I can't reproduce it.

Given the fact that this is a two week old issue with no response, I'm going to close it. If you can provide more details of what goes wrong, I'm happy to reopen it again.
