### ISSUE TITLE
404 Response Header not present when using FastCGI (Fix included)

### ISSUE THREAD

**Issue by lukearmstrong** [fuel/core#515]
I'm not sure what the issue is, but I've noticed our 404 page isn't responding with a 404 in the headers, it is responding with 200.

``` php
class Controller_Error extends Controller_Template
{
    public function action_404()
    {
        $this->response->status = 404;
        $this->template->content = View::forge('error/404');
    }
}
```

The PHP manual explains that a [different 404 header is required for FastCGI Servers](http://php.net/manual/en/function.header.php). We are using PHP FPM as our server needs to run PHP 5.2.x and PHP 5.3.x simultaneously, so the former is an Apache module, and the latter is using FastCGI.

So I can only assume that your code does send a 404 error when running PHP as an Apache module, though I have not tested it.

Here is what I did to make our 404 page return a 404 header:

``` php
class Controller_Error extends Controller_Template
{
    public function action_404()
    {
        $this->response->set_header('Status', '404 Not Found'); 

        // The above doesn't work without this line, even though the manual says it should.
        $this->response->send_headers();

        $this->template->content = View::forge('error/404');
    }
}
```

**Comment by jschreuder** [comment]
Not sure why autoclose didn't work but this is fixed by 1c4a9b95583f3d4785addcb39130a5b7ae7d4c31
