### ISSUE TITLE
$this->request->controller returning prefixed controller

### ISSUE THREAD

**Issue by DregondRahl** [fuel/core#516]
I was having some problem with the auth class redirecting in a loop, so I compared the output of $this->request->controller with 1.1 and 1.0.

1.1 develop dumping  $this->request

``` php
 [controller] => \Controller_App
```

1.0 develop its

``` php
[controller] => app
```

Auth class checks controller as 'app' so when it sends ' \Controller_App' it always returns false for has_access().
I'm not sure if its a core bug, or if Auth need to be updated to use the changed controller result. or is there an alternative for this

``` php
        if ( ! $access = Auth::instance()->has_access(array($this->request->controller, $this->request->action)))
        {
            //Response::redirect('denied');
        }
```

**Comment by WanWizard** [comment]
Where is this code? There is not a single line in the Auth package that access $request?

**Comment by DregondRahl** [comment]
Its not part of Auth directly; has_access() needs the controller and action to compared with the roles permissions. So the way I have been, and a handfull of others have been handling Auth was passing '$this->request->controller' as the controller in a  before() method similar to this : http://scrp.at/arm. 

Previously it returned just the controller without the '\Controller_' part so now that has changed. Is there another way of passing the controller into the has_access() method or does the Core/Auth class need any changes ?

**Comment by WanWizard** [comment]
I think you're on the wrong track. If you strip namespace and prefix from the class name, the name passed to Auth is no longer unique. What are you going to do with \Module\Controller_App?

You should change your code to use the complete string set by the Request class. I do not consider this a Fuel issue.

**Comment by huglester** [comment]
WanWizard, 

but in 1.0, how it works is: 
echo $this->request->action - gives index
echo $this->request->controller - gives app
echo $this->request->module - gives blog
echo $this->request->directory - gives admin

or maybe this behavior was changed in 1.1? 

because if the Dregond does:
echo $this->request->controller - he gets \Controller_App

Thank you!

**Comment by WanWizard** [comment]
For v1.1, the entire route processing has been rewritten, and as a result, the route found returns other information then in v1.0.

So if you use this information, this has to be changed when migrating to 1.1.

**Comment by DregondRahl** [comment]
Currently the SimpleAuth class uses the controller/location to determine permissions.

https://github.com/fuel/auth/blob/1.1/develop/config/simpleauth.php

WanWizard is correct that using modules that have the same controller name would conflict. But currently there would be no way to check the location from a base controller, and would need has_access() written on each controller. So the real issue is when migrating from 1.0 to 1.1 how would we do a location check from a base controller ? would we just use the controller as is like this ?

``` php
'user'  => array('\Controller_App' => array('index','view','create')), // default rights
```

**Comment by WanWizard** [comment]
The short answer is: configure whatever you intend to pass as a condition to has_access(). 

If that is $request->controller, and that contains the namespace and the full class name, then yes,that's what you have to configure.

**Comment by philsturgeon** [comment]
This got me initially and was a bit of a pain but it kinda makes sense. That IS the name of the controller afterall.

If you want to get to the URL segment that covers the controller then you can get to it here: 

```
Request::active()->route->segments[0]
```

Otherwise `str_replace('\\Controller_',` :D

**Comment by crynobone** [comment]
Just a curiousity, since in 1.1 $this->request->controller return \Controller_App.
1. Does $this->request->module return Blog or blog?
2. Does $this->request->action return index or action_index?

**Comment by philsturgeon** [comment]
A module would only ever be blog, as that IS the name of the folder, but I agree. There is an issue of consistency here and so far the answers from WanWizard just seem to be "yeah but it changed so deal with it".

I'd like us all to have a conversation about which would be the ideal solution.

What do you think @dhorrigan?

**Comment by WanWizard** [comment]
Eh, not entirely correct.

My response was that the current behaviour is correct, the old 1.0 behaviour isn't. 'App' is not a unique identifier of a controller, but '\Controller_App' is.

The other elements of Request should return the following:
-> module: 'blog', in lower case, as that is the requirement for the module name
-> controller: '\Namespace\Controller_Name', so fully qualified, including namespace, and in the correct case
-> action: 'index', as that is the action that is being called.
-> method: 'action_index', as that is the method that called. (note: action != method).

**Comment by philsturgeon** [comment]
Great, as long as there is some reasoning behind it. That chunk would be a good entry for the docs.

**Comment by WanWizard** [comment]
@frenkynet, seen phil's comment?
