### ISSUE TITLE
"Undefined offset" error using current() in DB class

### ISSUE THREAD

**Issue by billmn** [fuel/core#519]
Using the current() method in DB class like :

<pre>
DB::select()->from('pages')->where('id', $id)->execute()->current();
</pre>

If there aren't results by the query :

<pre>
Notice!

ErrorException [ Notice ]: Undefined offset: 0

COREPATH/classes/database/result/cached.php @ line 51:

50: // Return an array of the row
51: return $this->_result[$this->_current_row];
52: }

</pre>

Would be better to get an empty array

**Comment by frankdejonge** [comment]
If you use current, you must be sure that there is a result, else use count() first to see if it empty. Returning an empty array would result in checking for an empty array when you should have checked for an empty result.

**Comment by dhrrgn** [comment]
Hmm...not sure this should be closed.  We should throw an exception if current() is called when there are no results.  This would make code really clean.

**Comment by frankdejonge** [comment]
@dhorrigan: Returning null would be consistent with the normal result from ->current(), might be better to go with that so when switching to cached nothing has to change.

**Comment by dhrrgn** [comment]
True, null is fine, although in the future (in v2.0) we will be throwing exceptions.

**Comment by bencorlett** [comment]
I know that this has nothing to do with me really, but I agree with Dan 100%

Exceptions
