### ISSUE TITLE
Routing to modules from the main config

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#520]
This is kind of confusing me and I'm assuming it's a bug.

I have an (:any) route at the bottom of my routing config to route anything which isn't matched to Controller_Front. This works fine.

I have then added this above that route:

``` php
<?php
'account/(:any)' => 'account/$1',
'account' => 'account',
```

I have also put a `var_dump(static::parse_match($match));` just above the return in the core router class.

The results are as follows:

If I access site.com/account the `var_dump` dumps null but the `_root_` route from the account module's routing config is picked up and it works fine.

If I access site.com/account/login the var_dump dumps a Route object and shows it's matched "account/(:any)". It, however, doesn't pick up the route I have defined for this in the module's routing config and thus shows a 404.

**Comment by phil-lavin** [comment]
Sorry, I lie. It doesn't print null - it prints the full route which it is following.

**Comment by frankdejonge** [comment]
If I'm not mistaking: The first route that matches is used, so if you have a route for with (:any) will be matched first. So if you put the account/login route before that you it should work.

**Comment by phil-lavin** [comment]
Well, yes. However this really defeats the point of having module specific routing configs.

**Comment by crynobone** [comment]
True but based on my understanding, you already overwrite module specific routing configs by adding _I have an (:any) route at the bottom of my routing config to route anything which isn't matched to Controller_Front. This works fine._

**Comment by frankdejonge** [comment]
I think this is all solved when module routes are prepended to the routes array, I've just added Arr::prepend to allow this. Will do some tests later today.

**Comment by phil-lavin** [comment]
I see you added the Arr code, will this be used to fix this?

**Comment by frankdejonge** [comment]
That's the plan, still need to test some more and then I'll show it to the others.

**Comment by frankdejonge** [comment]
Fixed: https://github.com/fuel/core/commit/6d624a45a03926a801e8f2d9a3ce82d9515714a8

**Comment by phil-lavin** [comment]
Thanks :)
