### ISSUE TITLE
Error uploading files with capitalized extensions

### ISSUE THREAD

**Issue by okhayat** [fuel/core#521]
I just noticed, when I try to upload a file with a capitalized extension, e.g. DC001.JPG or .Jpg, the file extension is considered not allowed when specified in config as ext_whitelist
My config file has: 'ext_whitelist' => array('jpg'),
If the file extension character case doesn't match the one specified in ext_whitelist an error is thrown.
I modified https://github.com/fuel/core/blob/1.1/develop/classes/upload.php#L266 adding strtolower() and problem is fixed:
$files[$key]['extension'] = strtolower(ltrim(strrchr(ltrim($files[$key]['name'], '.'), '.'),'.'));

**Comment by WanWizard** [comment]
This has been fixed sometime ago in 1.1/develop.

**Comment by okhayat** [comment]
Good, but shouldn't it be fixed in 1.0.x branch?

**Comment by WanWizard** [comment]
I'm not sure if we're planning on backporting anything. 

If needed you can just take the class from the 1.1/develop repository, it doesn't have any dependencies with other classes.
