### ISSUE TITLE
Session:   Redis::instance() undefined function problem

### ISSUE THREAD

**Issue by wenchen** [fuel/core#524]
--- old/core/classes/session/redis.php  2011-08-23 20:20:06.000000000 +0000
+++ new/core/classes/session/redis.php  2011-09-28 22:48:40.187097770 +0000
@@ -57,7 +57,7 @@
                if ($this->redis === false)
                {
                        // get the redis database instance
-                       $this->redis = \Redis::instance($this->config['database']);
-                       $this->redis = Redis::instance($this->config['database']);
              }
      }

**Comment by jschreuder** [comment]
What undefined function problem? You are no longer taking the class from global and thus disallowing extending the Redis class.

Next time include a bit more info, better to describe (and pull-request) than to include a diff with a very limited description.

If this is about what your IDE thinks: that's not a bug, we are thinking about solutions for your IDE though - but as it's not an actual bug it's not at the top of our priority list.
