### ISSUE TITLE
Stop controller when controller::before returns false

### ISSUE THREAD

**Issue by kriansa** [fuel/core#526]
Well, it would be much more easier if when the method controller::before returns false, the action just wouldn't be called, because we could do login and data validations without being forced to use exit() on it, making useless the profiler or pseudo-vars like {mem_usage}.

**Comment by jschreuder** [comment]
The before() method isn't meant for this, it's meant to setup your controller (load stuff). This is more application internal routing logic, for which the router() method is much more suited.
