### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by Solovej** [fuel/core#532]
info@info.rr -> rr no such domain.
info@info.shyerrett   -> shyerrett no such domain.
etc. :)

list of all domains http://en.wikipedia.org/wiki/List_of_Internet_top-level_domains

now, If I enter info@zuzu.cooooom - validation will passed

**Comment by jschreuder** [comment]
Code examples that triggered this? As far as I know we use `filter_var($email, FILTER_VALIDATE_EMAIL)` everywhere, thus this might be a PHP bug.

**Comment by jschreuder** [comment]
Thought about this for a bit more: the truth is that it's pretty much impossible to write a complete function that does this. Which is also the reason why PHP didn't attempt it and only validates if the given emailaddress is syntactically correct. A reason for not disallowing non official top-levels is that they may be used in intranets.

This won't be changed in the Core and will be kept in line with the native PHP email validation.
