### ISSUE TITLE
Remove Fuel::value and replace it with a global function.

### ISSUE THREAD

**Issue by frankdejonge** [fuel/core#535]
The function has nothing to do with the Fuel class. I propose something like `callback_value()`.

**Comment by jschreuder** [comment]
I agree but prefer a more functionally descriptive than the current name, maybe something like `parse_value()`

**Comment by frankdejonge** [comment]
That's a good name. I think we don't need to deprecate Fuel::value, just remove and add as global. @dhorrigan: does this fly with you?

**Comment by dhrrgn** [comment]
parse_value() is OK.  Not sure about making it a global proc function...what is the reasoning?

**Comment by frankdejonge** [comment]
The reason is that like the other global functions it's generic, widely used, but doesn't belong to a class. The ::value function has nothing to do with the Fuel class.

**Comment by jschreuder** [comment]
@dhorrigan any final judgement on this?

**Comment by dhrrgn** [comment]
I left it in the Fuel class because i dont want to clutter up the global namespace with more procedural functions.  We will re-discuss this for 2.0.
