### ISSUE TITLE
DB queries missing ` for field names

### ISSUE THREAD

**Issue by DregondRahl** [fuel/core#537]
When doing INSERTS the field names are are not in ` which causes this error. 

``` php
Fuel\Core\Database_Exception [ Error ]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group, registered_ip) VALUES ('Dregond', 'd0+rnzAUaA1eP2kvrwi73dKWqMskZdIcy/dUHc' at line 1 with query: "INSERT INTO fuel_users (username, password, email, group, registered_ip) VALUES ('Dregond', 'd0+rnzAUaAfgfgWqkMskZdIcy/dUHciMpH8=', 'moo@gmail.com', 1, '127.0.0.1')"
```

Taken from Auth class create_user()

**Comment by DregondRahl** [comment]
backtraced and found the problem

https://github.com/fuel/core/blob/1.1/develop/classes/database/pdo/connection.php#L18

``` php
protected $_identifier = '`';
```

adding backtick to that seems to solve it.

**Comment by jschreuder** [comment]
Needs to be based on the SQL server used, not all SQL types use the backticks for identifiers. I think the DSN always starts with the SQL driver ('mysql', 'sqlite', etc) and we might base the setting on that.

**Comment by dhrrgn** [comment]
Fixed here https://github.com/fuel/fuel/commit/a1fdc33317138bd2aad75742d1d5caf6c4d41ee5
