### ISSUE TITLE
Fieldsets: treat validation rules and html attributes as separate entities

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#543]
References the comments after the fix was put in place at https://github.com/fuel/core/issues/514

**Comment by jschreuder** [comment]
Moving this to next version - no plans to look into this for 1.1.

**Comment by WanWizard** [comment]
@jschreuder is this on the roadmap for Fieldset refactoring?

**Comment by jschreuder** [comment]
Won't matter anymore, it'll be decoupled and there'll be fully rewritten mapping logic from fieldset to forms where I'll keep this problem in mind.

**Comment by WanWizard** [comment]
Closing this one. Will not be changed in 1.x, will be completely rewritten for 2.0
