### ISSUE TITLE
Bug in core/classes/controller/rest.php

### ISSUE THREAD

**Issue by jsidhu** [fuel/core#55]
Going from RC1 to RC2 I noticed my Rest controllers stopped working, further investigation lead me to the following typo/bug:

Line 103 in core/classes/controller/rest.php is incorrect:

``` php
$this->response->set_header('Content-Type: '.$this->_supported_formats[$this->request->format]);
```

it should be something like this (from RC1):

``` php
$this->response->set_header('Content-Type', $this->_supported_formats[$this->request->format]);
```

-js

**Comment by philsturgeon** [comment]
Already fixed in develop.
