### ISSUE TITLE
Feature request (Validation) - Do not run rules when value is empty and not required

### ISSUE THREAD

**Issue by Savageman** [fuel/core#550]
Because right now we need to add this redundant validation::_empty() check in every validation rule and it's kind of a shame.

The _empty() function is not even static so we cannot access it in our custom rules when we don't extend the Validation class. Wow.

**Comment by frankdejonge** [comment]
This is by design. This allows a value to not be required but have other rules that run when it is set. If you want to have them required, add that rule.

**Comment by frankdejonge** [comment]
You can access _empty like so: $this->_empty()

**Comment by jschreuder** [comment]
Not sure what you mean with "Wow." but if that's a wiseguy comment I strongly suggest you leave it out next time if you want to be taken seriously.

It's a small edit to make `_empty()` static, no problem there - I'd say: change it and pull-request.

Not running rules for non-posted fields is already possible by setting the second param of `Validation::run()` to `false`.

**Comment by Savageman** [comment]
Sorry if I looked mean, this wasn't intended. I'll be kinder from now on. :s

Indeed, the small change to make _empty() static would fit me like a charm.

Also I didn't understood the 2nd param of `Validation::run()` I believe it would works for me too passing an array of the fields I want to skip when null.

But it's still weird for me that every validator has to check for `_empty()` before doing the validation.

Thanks, I have 2 solutions for this to work now. Yeay !
