### ISSUE TITLE
Prevent Main Controller Handler Execution from before() Method

### ISSUE THREAD

**Issue by joshuarubin** [fuel/core#552]
Please see my commit comment here for a suggestion about being able to easily stop execution after running the before() method of a controller.

https://github.com/fuel/core/commit/02fee9ca641f40396d81c649b1b2928caed03978#commitcomment-637597

**Comment by dhrrgn** [comment]
We have decided against this many times, and our minds are still not changed.  `before()` is not meant for this.  `before()` is meant purely as a way to setup your controller before executing an action.  You should use the `router()` method to do all authentication/authorization.

**Comment by joshuarubin** [comment]
Ok, so in the case of the REST controller, it already uses a router to do two things:
1. set the output format
2. call the proper action method

If I redefine the router, then I have to choose between calling parent::router() at the beginning so that it sets the output format properly, but will execute the action (not something I always want), or to call parent::router() only after confirming authentication (but then I have to reimplement the output format detection logic from the rest controllers router in my router).

Is there any better way to do this?

**Comment by joshuarubin** [comment]
I was able to work around the issue by changing the routing resource (to `unauthorized`) if the user is not authorized, and then calling `parent::router($resource, $arguments);`

This is still a bit messy because for rest controllers, I have to create a `<Input::method()>_unauthorized` method for every input::method I need to support, but at least it works.
