### ISSUE TITLE
Autoloader not calling init

### ISSUE THREAD

**Issue by shulcsm** [fuel/core#553]
https://github.com/fuel/core/blob/c570951403ff74f5c918ee13cf20443ac1fc526a/classes/autoloader.php

With this commit autoloader is not calling _init() of assets class

**Comment by jschreuder** [comment]
Additional problem: when the load is a PSR-0 class it won't reset `static::$auto_initialize` because it's returned immediately after.

**Comment by dhrrgn** [comment]
Oops.  I will fix this.
