### ISSUE TITLE
Duplicate keys for Fieldset_Field set_options inconsistency

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#560]
There's an inconsistency in the way Fieldset_Field adds options. Because it uses Arr::merge() numeric keys are appended if they already exist whereas string keys are replaced. This causes inconsistent behaviour. It means you can have duplicate <option> values if they pass an is_int() check but you can't if you have string values.

It is probably desirable that the field supports duplicate values, regardless of type, as these are valid and useful in HTML.

I didn't want to spend any time proposing a fix for this as I am unsure of your intentions for the workings of this field.

**Comment by jschreuder** [comment]
What exactly is the use of duplicate values? Seems like a very bad practice?

It is indeed a problem that numeric keys aren't respected, that should be fixed.

**Comment by phil-lavin** [comment]
Main use would be for usability. What is the same to the system is not necessarily the same to the user. It's not an issue for me in this case - I'm just having issues using numeric keys, though it does seem that if HTML supports it then so should the Fieldset.

**Comment by jschreuder** [comment]
It seems mostly clutter to me, haven't been able to think of a single case where I'd use that and think it a good practice. Mostly adds clutter and makes lists longer without adding actual options. But it is indeed allowed by (X)HTML, if you can think of a good way to implement it I'm open to it. Personally I don't care about it as I still consider it bad practice.

The other issue isn't as easy to fix as it seems on first glance: it needs to be able to work with optgroups (nested array) and merge those just like the upper level. Probably something like this:

``` php
<?php

$merge = function($current, $new, $merge) {
    foreach ($new as $k => $v)
    {
        if (is_array($v))
        {
            $current[$k] = is_array($current[$k]) ? $v : $merge($current[$k], $v);
        }
        else
        {
            $current[$k] = $v;
        }
    }
    return $current;
};

$this->options = $merge($this->options, $values, $merge);
```

I don't have time to test it, right now but this should pretty much do it.

**Comment by jschreuder** [comment]
The same-key issue isn't going to be addressed, but I'm open to any fix someone else creates under the conditions I first layed out.
