### ISSUE TITLE
DB::list_tables() paramaters, not accepting DB connection

### ISSUE THREAD

**Issue by swt83** [fuel/core#565]
The `DB::list_tables($like, $db)` wants to be fed two params, the second of which is the "database connection".  I'm reading connection to mean this:  `$db = \Database_Connection::instance('something');`  This is the same connection I'm passing to ->execute() methods.  I'm finding that in the case of list_tables() and list_columns() it won't accept the connection, and just wants the instance name instead: `$query = DB::list_tables(null, 'something');`.  Maybe it's a documentation thing, just wanted to share this.

**Comment by frankdejonge** [comment]
This has been fixed in the development branch.

**Comment by frankdejonge** [comment]
You can view it here: http://fuelphp.com/dev-docs/classes/database/db.html#/method_list_tables
