### ISSUE TITLE
DB::Insert() doesn't return inserted_id with postgres, PDO

### ISSUE THREAD

**Issue by shulcsm** [fuel/core#566]
Postgres isn't returning last inserted id so It's not working like expected. Also auth relys on it. Dunno about possible workarounds but it must be atleast documented. Also something like DB::next for sequences would be nice.

**Comment by WanWizard** [comment]
With Postgresql, PDO's lastinsertid() method only works if you pass a sequence name to it. 

I don't see an easy way for the driver to determine the sequence name for any given INSERT query.

**Comment by shulcsm** [comment]
Can we have a way to pass a sequence name or methods for manual operation with sequence?

**Comment by WanWizard** [comment]
Can't see an easy way without structurally changing the DB driver(s).

@dhorrigan, @jschreuder: any comments?

**Comment by WanWizard** [comment]
Going to add a connection() method to the database connection driver driver that will allow access to the raw connection object. This allows custom access for methods unsupported by the drivers:

```
\Database_Connection::instance()->connection()->lastInsertId('sequence');
```

Note that you will have to do this directly after the insert query, otherwise the value is lost.

**Comment by WanWizard** [comment]
See 2552470f79fe4b3d71300d7f5e621f1362cd8abb

**Comment by Djuki** [comment]
@WanWizard This solution is not correct. With this connection method you make driver connection objects, available, and you call PDO method directly. What happens when user change database driver to MySqli for instance ?

Database_Connection should be expand with new abstract method last_insert_id() and every driver need to implement it.

Please @dhorrigan and @philsturgeon , i want your opinion about this subject and my solution.

**Comment by WanWizard** [comment]
This was a quick fix.

The database drivers and query builder are up for a complete redesign for v2.0. This is one of the many issues to be solved to make the database layer truely platform independent.

**Comment by philsturgeon** [comment]
Yep agreed with @WanWizard, this will be part of the proper rebuild for 2.0.

**Comment by Djuki** [comment]
@WanWizard @philsturgeon Thank you for fast answers. I forked core, and commit last insert id implementation.

https://github.com/Djuki/core/commit/fdcf81f7dbfd599c2b813572eb9391f14a206b97

Now we can call DB::last_insert_id() method to get last insert id, and I changed PDO, MySql and Mysqli drivers.

Whatt do you think, Can this peace of code be part of FUEL ? Should i pull request ?

**Comment by shulcsm** [comment]
Speaking of postgres compatibility. Looks like DBUtils aren't compatible as well so things like migrations are not usable :( 
I assume we won't see 2.0 in near future. Is it worth trying to fix these issues now or just wait for 2.0?

**Comment by WanWizard** [comment]
The big change for 2.0 is that all platform dependent SQL has to move from the generic classes to the platform driver classes. This includes DBUtil SQL, but also the SQL compilation functions of the Query Builder.

All platform drivers are going to be PDO based, so they will all share a generic interface.

I've already setup a local branch for this, and started the work. As soon as it is ready for testing I'll push it. I'm going to need test users for this, as I don't have all platforms available (MSSQL, PostgreSQL, Oracle).

**Comment by Djuki** [comment]
When we can expect 2.0 ? 

I am developing in FUEL, and i want to keep my core up to date. Can we we expect compatibility with 1.1 version.

**Comment by WanWizard** [comment]
It's still not sure if the next one is going to be 1.2 or 2.0.

We use a x.y.z. version scheme:
.z: bug fixes only
.y: function changes possible, deprecation before removal
.x: everything can change

In case of the DB layer, don't expect compatibility. But we'll try to limit the changes to search&replace operations, we have applications in the field too...

**Comment by Djuki** [comment]
Thank you very much.

**Comment by younes0** [comment]
+1 for the commit.
We are a lot of postgresql guys and can't work with the ORM / Model_Crud...

**Comment by WanWizard** [comment]
The 2.0 query builder is already finished, see http://github.com/FrenkyNet/Cabinet. I even have it running in a 1.3 app.

**Comment by younes0** [comment]
Thanks, I can't wait to see Fuel 2. But in the meanwhile, I need an urgent fix.
There's this workaround with Postgresql, consisting of getting the last insert_id by right after an insert : 

```
   // Using Model_Crud
   $user->save(); // inserting a new record
   $user->user_id: // returns null :(
   $lastval = \DB::query('SELECT LASTVAL()')->execute();
   $user->user_id = $lastval[0]['lastval'];
```

But it's dirty and not session isolated.
