### ISSUE TITLE
config.php fle not being loaded

### ISSUE THREAD

**Issue by ralf57** [fuel/core#572]
After updating my installation with the latest stuff from branch 1.1 the app/config.php file is not loaded anymore

**Comment by jschreuder** [comment]
This is probably a bug on your side due to merging or something like that, I tested this in 2 apps and my clean copy of the dev branch without trouble.

**Comment by ralf57** [comment]
You were right,
for some reasons the merge was not successful.
I cloned anew and it worked.
thanks and keep up the good work!
