### ISSUE TITLE
Failed test on Fuel\Core\Test_Agent

### ISSUE THREAD

**Issue by crynobone** [fuel/core#574]
```
1) Fuel\Core\Test_Agent::test_browser
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-Firefox 3.6
+Firefox

/fuel/core/tests/agent.php:43

2) Fuel\Core\Test_Agent::test_property with data set #0 ('Browser', 'Firefox 3.6')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-Firefox 3.6
+Firefox
```

**Comment by crynobone** [comment]
Using the available agent checker:

http://browsers.garykeith.com/tools/agent-checker.asp and using the agent string from Test_Agent class it tally with the Actual output. We should update the Test case with the correct expected output.

See attachment: http://d.pr/RFIf

**Comment by WanWizard** [comment]
Can you send a pull request for this?
