### ISSUE TITLE
Logging Timestamp

### ISSUE THREAD

**Issue by jsidhu** [fuel/core#58]
The log class should take into account the 'server_gmt_offset' config.

 Current setting the server_gmt_offset  or the default_timezone in config.php has not effect on the Timestamps ('log_date_format') written out to the log files.

I understand this is to help with misconfigured servers, but if its an option then it should work =)

Edit:  The core/classes/log.php currently gets the date using php's date() using the format described as 'log_date_format' in config.php. So if you're php time is off, you need to edit php.ini and set the 'date.timezone' setting. For me it was 

``` php
date.timezone = US/Pacific
```

**Comment by dhrrgn** [comment]
If you look in fuel/app/bootstrap.php the default timezone is set there.

**Comment by jschreuder** [comment]
@dhorrigan
This was an issue with servers that were configured wrong, where their own timezone was incorrect. The Date class solves this by correcting all times using the server_gmt_offset config, the PHP timezone setting isn't the issue - it's the timezone the server thinks it's in that is.
