### ISSUE TITLE
Agent class properties method

### ISSUE THREAD

**Issue by muhittin** [fuel/core#587]
In doc comment on properties method of Agent defined return type as string. But returns an array of properties. (Line: 267)

**Comment by WanWizard** [comment]
This is no longer the case in 1.1/develop.

**Comment by muhittin** [comment]
This isn't fixed on 1.1/develop. You can see this mistake on classes/agent.php on line 260 (https://github.com/fuel/core/blob/1.1/develop/classes/agent.php#L260)

**Comment by WanWizard** [comment]
Ok, I thought it referred to the documentation.
