### ISSUE TITLE
Name-spacing alteration.

### ISSUE THREAD

**Issue by ollym** [fuel/core#588]
Underscores are so ambiguous. Why don't you use namespaces instead?

```
namespace Auth;
abstract class Auth_Login_Driver extends \Auth_Driver { ... }
```

Might as well be

```
namespace Auth\Login;
abstract class Driver extends \Auth\Driver { ... }
```

A big change - maybe for 2.x ?

**Comment by jschreuder** [comment]
Better support for subnamespaces will be available in v1.1. We'll probably take a good look at the classnames for 2.0, and something along those lines is likely.
