### ISSUE TITLE
APC cache is filled with unused Fuel_Cache_Properties entries

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#591]
This is causing us some issues with the server. The cache is being filled with a lot of entries labelled with a hash such as "5c5f7d6538bb5a3945f6940a7149951c". These each have serialized data prefixed by "Fuel_Cache_Properties".

Having come into work this morning, APC was full of these, most of which were never hit by a cache lookup. They seem to have a timeout of 1319012003 seconds.

We've cleared APC to free up the space but they're steadily coming back in and will cause the same problem in a few hours. Is this a bug?

**Comment by phil-lavin** [comment]
I've realised those entries are ones that I am creating, but only 1 of these gets hits. The main entry by the name I set in the cache config (fuel-ob-new) gets a lot of hits but has this as its content...

array (
  'shop-page-data-men-1----loggedin-2' => 
  array (
    0 => '9884f58847d2e50b0af921f9302a8cf4',
    1 => NULL,
  ),
)

9884f58847d2e50b0af921f9302a8cf4 is the only Fuel_Cache_Properties that gets hits.

**Comment by phil-lavin** [comment]
Ok, so there seems to be 2 issues here. The first is that apc_add() is being given a unix timestamp rather than a TTL. This is making the expiry time crazy. I tried to submit a fix for this but github throws a 404. Sad :(

The second is that the fuel-ob-new index above only appears to have 1 item in it and, as such, nothing else is getting hits.

**Comment by phil-lavin** [comment]
Just been through this with @frenkynet on IRC but he had to go. It's probably better that Jelmer has a look at this as we're not sure what the best solution is. Findings are as follows...

The index isn't built right because it uses apc_add() around line 315 of apc.php. It should use apc_store() else it'll never overwrite the original. 

The apc_add() call in the _set() function should probably also be apc_store() else it's not possible to overwrite cache values. This same call is what sends a unix timestamp and not a TTL. One solution would be to minus time() from expiration as it's passed in but I saw unprep_contents() handles this by modifying $this->expiration so it might be better done in a different way.

**Comment by phil-lavin** [comment]
There's also a fuel-ob-new__DIR__ entry created. I'm not sure what it does but I presume it's not supposed to be named that and rather __DIR__ should be evaluated to the directory.

**Comment by WanWizard** [comment]
The **DIR** entry is a node index entry, which was introduced in one of the other drivers to simulate the functionality from the file driver.

In that driver you can have a key like "this.that.other", which will create a "this/that/other" file structure, and allows you do delete groups by deleting "this" or "this.that". For APC (but also redis and memcached) you have direct access (a flat storage structure) so you need to track which belong together, so you can delete them in one go.

**Comment by WanWizard** [comment]
Sorry, wrong button... :(

**Comment by phil-lavin** [comment]
Should it be the evaluated version of __DIR__ or the literal string '__DIR__'? The APC and memcached drivers quote it so it doesn't evaluate.

This doesn't seem to break anything that I'm doing. The other 2 problems are certainly bugs, however.

**Comment by WanWizard** [comment]
I don't think it matters, as long as it can be accessed.

I didn't have any issues when I wrote the memcached driver.

**Comment by phil-lavin** [comment]
I don't think this fixes the TTL issue
