### ISSUE TITLE
Page rendered in {exec_time}s using {mem_usage}mb of memory.

### ISSUE THREAD

**Issue by bumperbox** [fuel/core#592]
this shows without the placeholders replaced on a 404 page in the default install of version 1.0.1

i would contribute some code, but i only installed fuel a couple of minutes ago to try it out, so i dont' have enough knowledge yet to make those changes

**Comment by WanWizard** [comment]
That must have been fixed some time ago, I don't have that issue here on 1.1/develop, and haven't seen that happen for quite some time.
