### ISSUE TITLE
Module specific 404 routing not working

### ISSUE THREAD

**Issue by darklow** [fuel/core#594]
In case of 404 error framework tries to load app default 404 route, not the one specified in modules/MODULE/config/routes.php
It looks like in the HttpNotFoundException of index.php file Config class doesn't know yet about Modules routes config.

**Comment by WanWizard** [comment]
That depends. 

Like all other module items, a 404 route defined at the module level is only available within the request for that module.

**Comment by darklow** [comment]
Didn't quite understand your comment, but let me explain by real example
I have module named **admin**

Configs are:
app/config/routes.php: `'_404_'   => 'web/404'`
app/modules/admin/config/routes.php: `'_404_'   => 'admin/404'`

Now when i go to address:
/admin/non_existing_dir/
Framework show's nothing but blank page.

When i tried to dump `Config::$items` in public/index.php i can see that Config doesn't contain any routes config from admin module, but only from app config.

`$route = Config::get('routes._404_')` Variable $route in this case is: "web/404" and not "admin/404" as i think it should be

Therefore following script tries to load web/404 controller in the admin module, which i think is wrong.

``` php
catch (HttpNotFoundException $e)
{

    if ($route = Config::get('routes._404_'))
    {
        $response = Request::forge($route)->execute()->response();
    }
    else
    {
        throw $e;
    }
}
```

**Comment by WanWizard** [comment]
I was refering to the moment the module routes are loaded. But your 404 is triggered from a module, so that's not an issue.

I don't think the catch should use Config information there, as that doesn't contain the current route list.

Can you dump \Router::$routes at that point, and see if that does correctly lists "admin/404" as the `_404_` route? (can't test at the moment).

**Comment by darklow** [comment]
Yes, i can confirm, `\Router::$routes` contains correct `_404_` route as specified in module config.

**Comment by WanWizard** [comment]
Ok. Does this work?

```
catch (HttpNotFoundException $e)
{
    $route = array_key_exist('_404_', Router::$routes) ? Router::$routes['_404_'] : Config::get('routes._404_');
    if ($route)
    {
        $response = Request::forge($route)->execute()->response();
    }
    else
    {
        throw $e;
    }
}
```

**Comment by darklow** [comment]
Yes, now it routes correctly. 
Just with a small fix: `Router:$routes['_404_']` is object(Fuel\Core\Route), so it works when i used `->translation` key:

``` php
catch (HttpNotFoundException $e)
{ 
    $route = array_key_exists('_404_', Router::$routes) ? Router::$routes['_404_']->translation : Config::get('routes._404_');
    if ($route)
    {
        $response = Request::forge($route)->execute()->response();
    }
    else
    {
        throw $e;
    }
}
```

**Comment by WanWizard** [comment]
Thanks for the feedback. Fixed.
