### ISSUE TITLE
Can't do upper case view names

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#595]
I had a view named sizecharts/KN313.php. Doing render('sizecharts/KN313') returned view not found. Also doing render('sizecharts/kn313') didn't work.

I had to rename the view to kn313.php and do render('sizecharts/kn313')  to make it work.

**Comment by WanWizard** [comment]
lower-case filenames (for all files) is by design.

see http://fuelphp.com/docs/general/coding_standards.html under "File Naming".
