### ISSUE TITLE
"SHOW PROCESSLIST" query don't return data

### ISSUE THREAD

**Issue by polmartinez** [fuel/core#605]
For example, using this code:

```
$list = \DB::query('SHOW PROCESSLIST')
        ->as_object()
        ->execute();
```

The response is an integer :(

**Comment by frankdejonge** [comment]
Could you supply more that this? What did you do/try? What did you get returned?

**Comment by frankdejonge** [comment]
I think this is fixed when you do it like this:

```
$list = \DB::query('SHOW PROCESSLIST', \DB::SELECT)
        ->as_object()
        ->execute();
```

**Comment by WanWizard** [comment]
@FrenkyNet: maybe we should make DB::SELECT the default if the type can not be determined?

edit: no, that might be dangerous. Specifying it like this is a better option...

**Comment by frankdejonge** [comment]
@WanWizard: agreed. Closing this issue.

**Comment by polmartinez** [comment]
it's Ok, thank guys!

**Comment by jschreuder** [comment]
@WanWizard not sure about dangerous, but it would be breaking BC in a big way. (which indeed might be very dangerous)

**Comment by WanWizard** [comment]
Dangerous in the sense that currently everything other then SELECT, INSERT and UPDATE will return affected_rows. 

If you default to SELECT, suddenly a query object will be returned, which might not be present for all possible SQL statements. And indeed it will break all code expecting an integer being returned...
