### ISSUE TITLE
Router will route to abstract classes

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#606]
When you do http://fuel-url/template it will attempt to route to `Controller_Template` ending in an exception because you can't instantiate an abstract class instead of showing a 404. We need some way to prevent this. I think checking beforehand is a little too much unnecessary overhead (needs ReflectionClass)? Or may be acceptable as it's only one per request?

Other solution might be to catch the ErrorException for instantiating abstract classes specificly, though that may be a bit hacky:

``` php
<?php
try
{
    // instantiate controller
}
catch (\ErrorException $e)
{
    if (strpos($e->getMessage(), 'Cannot instantiate abstract class') === 0)
    {
        throw new \HttpNotFoundException();
    }
    throw $e;
}
```

**Comment by jschreuder** [comment]
That's what I said.

**Comment by frankdejonge** [comment]
Ok that was dumb. The performance penalty from using reflection class is minimal, because it's not an operation that happens ofter during requests. But the try/catch doesn't feel hacky to me.

**Comment by frankdejonge** [comment]
I think we have to use the ReflectionClass way. The try catch will also catch other exceptions thrown in the initiation. Which would result in a invalid 404 throwing.

**Comment by WanWizard** [comment]
Maybe it's a better option to not call the abstract classes 'Controller_', because they aren't.

**Comment by jschreuder** [comment]
@WanWizard a valid point but ultimately not doable right now because we'd break BC.

@FrenkyNet it's hacky because it depends on the exact wording of the exception message, which may change.

**Comment by WanWizard** [comment]
@jschreuder: we can add the hack, and deprecate.

**Comment by jschreuder** [comment]
I think that'd do, let's wait what the boss thinks and implement /@dhorrigan

**Comment by dhrrgn** [comment]
I've an idea...let me write up an example and see if it sticks.

**Comment by dhrrgn** [comment]
Ok, how about this http://scrp.at/aDa  It uses ReflectionClass for the entire execution.  Overhead is very very minimal, and is used in a lot of frameworks in the same type of way.

For the record, this code is production ready...I did test it with all possible failures (including abstract class).
