### ISSUE TITLE
Module Routing Problems

### ISSUE THREAD

**Issue by CoolGoose** [fuel/core#616]
Hi guys. 

I have the following main routes.php file http://scrp.at/aD9
And an users module with users and admin classes

The routes file in the module are like http://scrp.at/aD-

Doing \Debug::dump(\Router::get('user_update')); on admin/users/index returns NULL (even if the views and others load correctly)

Doing it on users/admin/index returns the correct value.

Any ideas ? :)

Tyvm

**Comment by WanWizard** [comment]
Module routes are only loaded when you load the module, that is when your URI request causes a module controller to load.

The URI 'admin/users/index' is in your app, so it doesn't load the module routes, hence NULL is returned.

**Comment by CoolGoose** [comment]
Well it's loading the same module in both cases, it's just once it loads it trough a custom route, and once directly. (sorry for the late reply, was away from a pc for a few days.

**Comment by WanWizard** [comment]
Ok, so if I understand it correctly:
- when you directly request a module controller through the URI, it works.
- when you get to the module controller via app routing, it doesn't.

Do you expect the URI to be routed by the app routes to a module controller, then the module routes to be loaded, and then the determined app route to be processed again to check for module routes? Or is this just about the reverse routes being available?

**Comment by CoolGoose** [comment]
Just about the reverse routes being available.

**Comment by kbanman** [comment]
I just ran into what I think is this same issue. I would think that once the router has figured out that it's routing to a module that the module's routes should be loaded and considered.

**Comment by WanWizard** [comment]
When the first segment of the URI points to a module, the module routes are loaded.
So reverse routes should work inside the module itself. Are you saying that is not the case?

If not, more information please. Do you arrive at the module directly? Or via a global route?

**Comment by kbanman** [comment]
Let's say I'm routing requests from `admin/users` to `users/admin`, where `Users` is a module.
If I have a route specified in the module that says to forward `users/admin` to `users/admin/users`, it is ignored.

**Comment by WanWizard** [comment]
Ok, clear. Routes are not processed recusively at the moment. This is also true for global routes, once a route match is found, no further lookup is done.

If you require this, I'll make this a feature request instead of a bug report.

**Comment by kbanman** [comment]
Yes, I would very much like this functionality.

**Comment by WanWizard** [comment]
Moving this to the roadmap for 2.0, when routing is going to be revised anyway.

**Comment by frankdejonge** [comment]
@jschreuder did you take a look at this for 2.0?

**Comment by WanWizard** [comment]
@FrenkyNet, current 2.0 codebase doesn't do this, correct? 

Do we need to address this? Perhaps optional?

**Comment by frankdejonge** [comment]
@WanWizard in 2.0 all routes should be registered for a module, we don't do routes config lookup. So if a module is bootstrapped, we're in the clear.

**Comment by WanWizard** [comment]
In the current 2.0 codebase, when you add a module to the application, it's routes will be loaded into the application router object, so they will all be available. This is independent of the bootstrap. So this can be closed.
