### ISSUE TITLE
PostgreSQL DB->update()->set() fails when column name is pgsql reserved word

### ISSUE THREAD

**Issue by darklow** [fuel/core#622]
``` php

$update_array = array(
    '"cast"'    => 'test',
    'crew'      => 'test'
);

$q = \Db::update('table')->set($update_array)->where('id', $id)->execute();
```

Throws an SQL error:

```
Fuel\Core\Database_Exception [ Error ]: SQLSTATE[42601]:
Syntax error: 7 ERROR: syntax error at or near "cast"  LINE 1:  UPDATE item_movie SET cast = '', ...
```

Because DB builder removes quotes from column names and _cast_ is reserved word in postgresql, there is no way i can update table using DB->update() method in this case.

Also i can't use DB::expr() object as array key.

Maybe there must be some workaround added, so that quotes wont be removed?
Or probably other solution would be add columns() values() methods to Database_Query_Builder_Update. So i could use DB::expr() for column name.

**Comment by WanWizard** [comment]
The Query builder quotes identifiers automatically (all of them), unless there is no identifier configured in the configuration for this database connection (or passed as a custom config if you manually created the instance).

Check your db.php. See https://github.com/fuel/fuel/blob/1.1/master/fuel/app/config/db.php#L16 for an example.

**Comment by younes0** [comment]
Thank you. 

So for postgresl users, add :
 'identifier'   => '"'

Please add this in the documentation.

**Comment by WanWizard** [comment]
Done. https://github.com/fuel/docs/commit/71923527af3cbd631a15224fffc123de4aaac07b
