### ISSUE TITLE
Validation Error Messages

### ISSUE THREAD

**Issue by agentphoenix** [fuel/core#64]
In the process of using the Validation class, I ran in to problems with validation errors. Fuel contains a method to pull back all the fields that were validated in a `key => value` array, but the same can't be said of errors. Instead, it returns a **massive** array that contains everything under the sun. While that may be useful in some cases, in most, developers would just want to know the field that failed and the message(s) associated with that field.

I do realize the `error()` method exists, but I really shouldn't have to manually go through every field in the form and check it that way just to get a `key => value` array of the field and the validation messages. Any chance this could be patched up or am I the only one that's having this issue?

Thanks!

**Comment by jschreuder** [comment]
Just echo the Validation_Error objects, they'll output as error messages and the fieldnames are already used as keys.

**Comment by swt83** [comment]
I have this same issue.  The documentation says that $val->errors() will return a nice array of name=>error pairs, just as $val->validated() and $val->input() do.  It does not seem to function as it should, and would require me to loop thru each input to prepare such a list.

**Comment by jschreuder** [comment]
It does return name => error pairs, it's an array of `Validation_Error` objects indexed by fieldnames. Other than that I'll just repeat what I said 6 months ago:

> Just echo the Validation_Error objects, they'll output as error messages
