### ISSUE TITLE
Missing constant: const STAGE in core/classes/fuel.php

### ISSUE THREAD

**Issue by jozefKapicak** [fuel/core#65]
class Fuel {

/**
- Environment Constants.
  */
  const TEST = 'test';
  const DEVELOPMENT = 'dev';
  const QA = 'qa';                                   <---  need to be changed to: const STAGE = 'qa';  
  const PRODUCTION = 'production';

fuel/app/config/db.php 
-  'qa' => array(
-  Fuel::STAGE => array(

Jozef

**Comment by crynobone** [comment]
It's there https://github.com/fuel/core/blob/develop/classes/fuel.php#L48

**Comment by dealunited** [comment]
Okey, seems good now.
