### ISSUE TITLE
Validation::error()

### ISSUE THREAD

**Issue by zoe-edwards** [fuel/core#651]
Just switched to using `Validation::error()` instead of `$val->errors(` because of the error I got in 1.1, but I get these errors:

```
Runtime Notice!

ErrorException [ Runtime Notice ]: Non-static method Fuel\Core\Validation::error() should not be called statically, assuming $this from incompatible context

APPPATH/classes/controller/register.php @ line 58:
$errors = Validation::error();
```

```
Notice!

ErrorException [ Notice ]: Undefined property: Controller_Register::$errors

COREPATH/classes/validation.php @ line 521:
return $this->errors;
```

**Comment by jschreuder** [comment]
That is because, like Validation::errors() it's a dynamic method. The :: is a scope indicator and used to define a method as a member of a class, thus it being noted as `Validation::error()` doesn't mean it's static.

The second error is probably caused because PHP starts messing up in weird ways when calling dynamic methods staticly.

**Comment by zoe-edwards** [comment]
So how do I call it into an array? The Docs haven’t been updated yet.

**Comment by jschreuder** [comment]
It's the same method, nothing changed but its name.

**Comment by zoe-edwards** [comment]
Ah, so how do I call it non-statically? It just returns `null` if I var_dump, and still generates the same error.

(I promise I’ll update the Docs if you tell me! :) )

**Comment by jschreuder** [comment]
Here's how it works: https://github.com/fuel/core/blob/1.1/develop/classes/validation.php#L521

**Comment by zoe-edwards** [comment]
Oh I see errors() has been replaced with error(), so I still use `$val->error()`. Completely missed the point. Shouldn’t program on a Sunday night. Thanks for your patience @jschreuder.
