### ISSUE TITLE
Profiler throws lot of notices

### ISSUE THREAD

**Issue by darklow** [fuel/core#660]
When i enable profiling=> true in config file and database profiling is also on.
Profiler works fine, except screen is full of notices:

```
ErrorException [ Notice ]: Undefined index: possible_keys
COREPATH/vendor/phpquickprofiler/display.php @ line 258:
```

```
ErrorException [ Notice ]: Undefined index: key
COREPATH/vendor/phpquickprofiler/display.php @ line 259:
```

```
ErrorException [ Notice ]: Undefined index: type
COREPATH/vendor/phpquickprofiler/display.php @ line 260:
```

```
ErrorException [ Notice ]: Undefined index: rows
COREPATH/vendor/phpquickprofiler/display.php @ line 261:
```

This could be easilly fixed by correcting line **257** in **COREPATH/vendor/phpquickprofiler/display.php**:

``` php
if(isset($query['explain'])) {
```

to 

``` php
if(isset($query['explain'], $query['explain']['possible_keys'])) {
```

**Comment by WanWizard** [comment]
Do you have some additional information on this issue? Which query triggers this?

Looking at the code, it doesn't seem possible that $query['explain'] exists, but $query['explain']['possible_keys'] doesn't.

**Comment by darklow** [comment]
Well this ir really strange. 
I have two identical PostgreSQL DB profiles for different databases (both using pdo driver).  Both have profiling=true
If i use same query (just different table_name) for one of them notices appears, on another DB, there are no notices at all. I think the problem is not in queries, but in database itself. But i cant detect the difference on first database, why 

Then i dumped the following line 60 in core/classes/profiler.php 

``` php
dump(static::$query);
```

And output for both queries is ALMOST the same, except one of them (the one that throws notices) by some reason has EXPLAIN prefix in 'sql' key. And i have no idea why. Because all the queries works fine

Notices shown:

``` php
\DB::select()->from('item')->limit(1)->execute();

array(2) {
  ["sql"]=>
  string(55) "EXPLAIN SELECT * FROM item LIMIT 1"
  ["time"]=>
  float(0.0017879009246826)
}
```

Without notices

``` php
\DB::select()->from('task')->limit(1)->execute('cache');

array(2) {
  ["sql"]=>
  string(47) "SELECT * FROM task LIMIT 1"
  ["time"]=>
  float(0.0060238838195801)
}
```

**Comment by WanWizard** [comment]
If you have database profiling activated, the profilers reruns your select's with the EXPLAIN keyword to get extra details. I'm pretty sure that is MySQL specific. 

Apart from the fact that it runs your queries again, it's not a problem, the SQL error (if any) is caught and hidden by the profiler. But in this case the entire 'explain' entry is missing from the result, which is caught by the first isset(). Not sure why you still have these notices.

I've updated the code anyway. Some of the explain values could be something else then a string, in which case they should be suppressed as well.
