### ISSUE TITLE
Core/DB Query Builder ORDER BY RAND()

### ISSUE THREAD

**Issue by zoe-edwards** [fuel/core#661]
I’d like to add this in, but I’m not sure which branch to do it in?

I was going to write it so if you use `order_by('rand()')`. The builder will convert it to `ORDER BY RAND()` rather than `ORDER BY `rand()`` like it does at the moment.

I appreciate that it’s not recommended to use that method to sort randomly, but in RAD and some other tasks it’s very useful.

Feedback?

**Comment by WanWizard** [comment]
Can't you pass a DB::expr() to order_by()?

**Comment by jschreuder** [comment]
`->order_by(DB::expr('RAND()'))`

**Comment by zoe-edwards** [comment]
Seems reasonable.
