### ISSUE TITLE
File class chmod permission problems

### ISSUE THREAD

**Issue by huglester** [fuel/core#664]
Hello, 

Today I have faced chmod problems when using File class.

Seems that it get's incorrect chmod values from config (file.php) file.
I could not track down the problem, but to reproduce you can:

Open File class, _init() method, and add:

```
var_dump(\Config::get('file'));
exit;
```

right after after the:
\Config::load('file', true);

and you will get these chmod values, which are unknown where to come from...

```
    [chmod] => Array
        (
            [files] => 438
            [folders] => 511
        )
```

But if you replace the load params with:
\Config::load('file', true, true);

you will get correct values:

```
    [chmod] => Array
        (
            [files] => 0666
            [folders] => 0777
        )
```

Anyone has an idea what can be causing this?

Thank you

**Comment by jschreuder** [comment]
438 & 511 are the base-10 equivalents of the octal 0666 and 0777 values. When you prefix a number with zero PHP will interpret it as octal - which is correct as these are octal numbers. Only thing is that they're output as base-10 numbers, which should still be the same number and thus not cause a problem.

Is this causing any actual problems? Otherwise I don't see a problem here.

**Comment by huglester** [comment]
but the problem is that, in the Config file, those values are written as string:

```
'files'  => '0666',
```

The other thing is, that if I for example add `files2` to the config, (like: 'files2'  => '0777',)
and leave the: \Config::load('file', true);
I get the value of `files2` correct:

```
    [chmod] => Array
        (
            [files] => 438
            [files2] => 0777
            [folders] => 511
        )
```

So I started to think that this value is overwritten somewhere/somehow, not sure where/how

**Comment by huglester** [comment]
As I understood, the problem is hidden in Log class, in the _init() method:

``` php
    public static function _init()
    {
        \Config::load('file', true);

        // make sure the configured chmod values are octal
        $chmod = \Config::get('file.chmod.folders', 0777);
        is_string($chmod) and \Config::set('file.chmod.folders', octdec($chmod));

        $chmod = \Config::get('file.chmod.files', 0666);
        is_string($chmod) and \Config::set('file.chmod.files', octdec($chmod));
    }
```

as we can see, it checks for a string, and 'converts' it to octdec

**Comment by jschreuder** [comment]
Ok, so basicly there's nothing wrong?

**Comment by jschreuder** [comment]
I'll rephrase that: it might be better if they were set as octal numbers in config and those lines should be gotten rid off (can't due to BC though).

But functionally there's nothing wrong, everything should work exactly as expected.

**Comment by huglester** [comment]
I use the create_dir() method, but if I pass it only the basename and new directory name, like:

\File::create_dir($basepath, $name), it gets wrong permissions on newly created dir: 0551

and if I switch to: \Config::load('file', true, true);
directory is created with valid, write'able permissions

So probably create_dir() method should be modified?

**Comment by jschreuder** [comment]
Taking a quick looks there's a few pieces of bad code here:
- The config rewriting in the Log class should be removed, wrong place to do this as you shouldn't rewrite one class's config in another. (@WanWizard) It's a recent fix thus can be removed without caring about BC.
- The create_dir() method always uses octdec() without checking if it gets a string or int which causes your problem.
- The config file defines the chmod values as strings, these should be octal to begin with.

**Comment by WanWizard** [comment]
Code came from a pull request, which introduced another bug that I tried to fix here (but obviously I missed a dependency).

In the original design the values were defined as string everywhere, to avoid these issues. This is the reason it is still defined as string in the config. From what I remember defining them as octal didn't fix the issue, so many there's some inconsistency in the way the different PHP functions use this value (can't remember what the issue at the time was).

**Comment by WanWizard** [comment]
Is this still an issue? If so, maybe a check for is_string before converting it to octal?

**Comment by huglester** [comment]
I'd say that this is still an issue.. because the config values from Config, make my directories with permission 511 instead of 777

**Comment by jschreuder** [comment]
ec68c4622eea81ee43a2e3e0f5b4a2ac86824963
