### ISSUE TITLE
No UNIQUE in DBUtil create_table

### ISSUE THREAD

**Issue by sandrews06** [fuel/core#670]
Was trying to create a migration based on the table in the simpleauth example, and quickly realized there was no means to assign a unique field while creating a table.

**Comment by WanWizard** [comment]
What is the definition of a "unique field"?

If you mean index, the create_index() method support creating indexes of type UNIQUE (in 1.1/develop).

**Comment by sandrews06** [comment]
whoops....I'm an idiot....didn't see that.
