### ISSUE TITLE
previous_start/previous_end of Pagination don't work.

### ISSUE THREAD

**Issue by liuxinnian** [fuel/core#676]
Hi guys.

When try to set customs style for pagination , previous_start/previous_end, next_start/next_end don't work. 

The problem is :

in pagination.php, the keys ' previous_start' , 'previous_end ' , 'next_start', 'next_end' of $template  never used in next_link() and prev_link().

**Comment by WanWizard** [comment]
I don't think this will be fixed anymore.

The pagination class, in it's current form is going to be removed from the core, as it is application specific, and should be implemented using a view that generates the partial for the pagination navigation block.

If and in what form core functionality will remain is still under discussion.

**Comment by WanWizard** [comment]
See #689
