### ISSUE TITLE
[Revamp] Session : store the security data in the backend instead of the cookie

### ISSUE THREAD

**Issue by Savageman** [fuel/core#678]
Security data = ip address + user agent + created + updated

Discussed here: http://fuelphp.com/forums/topics/view/6014

**Comment by alexwhitman** [comment]
I wouldn't rely on IP address.  It can easily change on a mobile phone/device if switching between WiFi and 3G or even switching between 3G services.

**Comment by WanWizard** [comment]
You can already configure if you want to use that or not.

**Comment by WanWizard** [comment]
Moved to the 2.0 roadmap.
