### ISSUE TITLE
Improved profiler

### ISSUE THREAD

**Issue by quasiperfect** [fuel/core#682]
Please add/modify the profiler to provide the same information like the one in Codeigniter
PHP Quick Profiler is nice but it take a lot of screen space and it doesn't have all the information the CI one provides

**Comment by WanWizard** [comment]
Can you be more specific?

**Comment by quasiperfect** [comment]
@WanWizard thanks for responding

place the profiler info under not over the application (most of the time i want to see the page and if i spot some problems i need the profiler info)

add SESSION DATA, GET DATA, POST DATA, CONFIG VARIABLES etc

i offer to build the layout(css,html,javascript) of the profiler (if needed) post the idea here and based on feedback to make modifications until a final version is accepted but i lack the knowledge to implement the php part

**Comment by WanWizard** [comment]
Fork the core repository, make your changes, and send us a pull request...
