### ISSUE TITLE
Connection and notice bugs in Model_Crud->count() method and postgresql new item save()

### ISSUE THREAD

**Issue by darklow** [fuel/core#685]
## 1. Connection bug in count() method

Model_Crud->count() method always uses active connection, because there is no connection name specified. Lines with execute() - 249, 262 should be

``` php
execute(isset(static::$_connection) ? static::$_connection : null)->get('count_result')
```

instead of just

``` php
execute()
```
## 2. Notices in count() method

Line 240: `if ( ! is_array($where[0]))` throws notices, i think it should be just: `if ( ! is_array($where))`
## 3. New item save() method and PostgreSQL

About PostgreSQL. So far i have tested Model_Crud works fine until you want to save() new item. 
As you may already know PostgreSQL doesn't return currently inserted primary key. So usually you select new ID from sequence before and pass it to the set() $array. And it works, item is saved correctly, however it returns following

``` php
array(2) { 
    [0]=> bool(false)
    [1]=> int(1) 
} 
```

I think it could harm anyone if in case `$result[0] === false` you could check if there is no primary key in $vars array and if it is, use that as ID. That fixes all the problems with PostgreSQL and new item save().

``` php
if ($result[1] > 0)
{
    if($result[0] === false && isset($vars[static::primary_key()]))
    {
        $result[0] = $vars[static::primary_key()];
    }

    $this->set($vars);
    $this->{static::primary_key()} = $result[0];
    $this->is_new(false);
}
```

And now if we use following code, everything works fine

``` php
$source = \Entora\Model_Source::forge(array('name'=>'test', 'id'=>123));
var_dump($source->save());
```

Returns:

``` php
array(2) { 
    [0]=> int(123)
    [1]=> int(1) 
} 
```

**Comment by WanWizard** [comment]
That only works if you set the value of the primary key manually, which isn't really the insert_id, is it?

**Comment by darklow** [comment]
Yes, it works if you set primary key value manually, which is normal for postgresql. And that change i mentioned, it will work only in situations if insert query was successful, and no insert_id was returned, so i think there is no harm for other sql databases.
