### ISSUE TITLE
Suggestions for Model_Crud class

### ISSUE THREAD

**Issue by darklow** [fuel/core#686]
First of all thanks for the great un really handful class.
Here are some thought on small yet handy improvements:
### 1. Add $select argument to find_by() and other find_... methods.

In case you have large tables with lot of columns and some columns with really big data, selecting all by using '*' could very slow and inefficient. For example you have table article, with "id, title, body" where body contains really large data and for list you only need "id, title" then why select large body? Or in my case i have one column with large serialized data cache, which slows down select significantly if i use them in selects when not needed.

Therefore in such cases these find_... functions are useless, because we cannot specify columns we want to select.
### 2. Default variable for selecting right columns instead of all by '*'

Another idea for same problem was to add default proteced variable $_select or something like that, so that if specified Model_Crud for all find_... methods could use $_select array instead of '*'

``` php
class Model_Item extends \Model_Crud {

    protected static $_table_name = 'item';

    protected static $_select = array('id', 'title', 'date');
```

**Comment by tomschlick** [comment]
I'm not really a fan of the first idea. Its just parameter spam, if you need to do a complex statement to define your query you should just be using the syntax already in place to do so using the ->select() methods.

I believe you can already do the second by defining the properties. I dont know if that actually limits it in the db query but it definatly limits the results.

**Comment by darklow** [comment]
ok, actually i just now found out about nice hook method pre_find() where i can set default ->select() columns if no other are specified. Thanks.

**Comment by darklow** [comment]
I tried but event if i can access $query in pre_find() i still cant change already existing select to "$_table_name.*" all i can do is just add more columns by $query->select() and there are no methods to empty or remove previously added columns.

tomschlick what did you meant by? 

> I believe you can already do the second by defining the properties. I dont know if that actually limits it in the db query but it definatly limits the results.

Is really the only option to override whole find() method, to enable support custom columns for find_... methods?

Only one line - 169 changed from:

``` php
$config = $config + array(
    'select' => array(static::$_table_name.'.*'),
    'where' => array(),
    'order_by' => array(),
    'limit' => null,
    'offset' => 0,
);
```

to 

``` php
$config = $config + array(
    'select' => isset(static::$_select) ? static::$_select : array(static::$_table_name.'.*'),
    'where' => array(),
    'order_by' => array(),
    'limit' => null,
    'offset' => 0,
);
```

``` php
class Model_Item extends \Model_Crud {

    protected static $_table_name = 'item';

    protected static $_select = array('id', 'title', 'date');
```

i think it could be great improvement.

**Comment by WanWizard** [comment]
I don't see what the issue is here.

If you want to select some columns, just use

```
Model_Name::find( array('select' => array('id', 'title') );
```

If you want defaults, override the find() method using a base class

```
class Model_Base extends \Model_Crud
{
    protected static $_default select = array();

    public static function find($config = array(), $key = null)
    {
        if ( ! isset($config['select']) and ! empty(static::$_default_select))
        {
            $config['select'] = static::$_default_select;
        }
        return parent::find($config, $key);
    }
}
```

And then your model

```
class Model_Item extends \Model_Base
{
    protected static $_default_select = array('id', 'title', 'date');
}
```

Problem solved.

**Comment by darklow** [comment]
Thanks on really good suggestion, never thinked on that extending find method solution. First idea was to override whole find()
