### ISSUE TITLE
[Feature] Module(/Package) Dependencies

### ISSUE THREAD

**Issue by andrewwheal** [fuel/core#688]
It would be really useful to be able to define a Module's dependencies perhaps in a config file which is automatically looked for when a module is loaded. This would list other modules and packages that it depends on so that they can be loaded.

This could also be implemented in Packages, however, they already have bootstraps which could do "manual" loading of dependencies.

**Comment by phil-lavin** [comment]
My thought is that a bootstap.php for modules, similar to packages, would be ideal. When a module is loaded, you can execute arbitrary code, including resolving dependencies.

**Comment by WanWizard** [comment]
This will be addressed in 2.0, where everything is a package.

**Comment by andrewwheal** [comment]
That's great, any ideas on how soon it is likely to be implemented on the develop branch?

I know estimates like these can be impossible but a rough guesstimate would be good (e.g. 1 month, 6 months, 1 year)

**Comment by WanWizard** [comment]
This is already implemented in 2.0/develop. But nothing else is, and there's still work on the core. Only when that is finished will we start merging current functionality.

No indication as to when, but I think 6 months is a better guess then 1 month...

**Comment by andrewwheal** [comment]
Cheers @WanWizard, I look forward to testing out 2.0

**Comment by frankdejonge** [comment]
2.0 has composer support handling all the dependancies, closing this issue.
