### ISSUE TITLE
Add URL to log

### ISSUE THREAD

**Issue by marcopax** [fuel/core#697]
Hi guys!
I have a simple request about the log generated by Fuel: surfing throught the site I can't see any error, but sometime I found a log error in the log folder.

In every line I can see the name of file and the line where the error appear... But not the url that generate the error: it is possibile to modify the log to save it?

Thank you!

**Comment by WanWizard** [comment]
This is a bug in the Request class, which doesn't log the request URI in the correct location, and therefore always reports "" on the main request.

This has been fixed in a70fd1cb4f8472f73fb46a674540c7c14d194936

**Comment by marcopax** [comment]
Thank you very much :)
