### ISSUE TITLE
blank screen if a controller's class name is wrong

### ISSUE THREAD

**Issue by johnnyfreeman** [fuel/core#703]
I tried to track this one down so I could send a pull request but it's pretty elusive. Here's what I got:

File: `app/classes/controller/test.php`

```
<?php

class lksdfkjsf extends Controller
{
    public function action_index()
    {
        return Response::forge('HELLO!!');
    }
}
```

If I go to http://my_url/test, I get a blank screen. I've get nothing in Apache's logs and nothing is written to Fuel's log file except this:

`Info - 2011-12-02 16:55:00 --> Fuel\Core\Request::forge - Creating a new Request with URI = ""`

That's it.

Seems there should be _some_ indication that something is wrong.

**Comment by WanWizard** [comment]
If the request class can't find the controller, it throws an HttpNotFoundException, which is caught in your index.php to load the 404 route.

So either your using a pre-1.1 index.php that doesn't catch this exception, or you have an issue with your 404 route.

**Comment by johnnyfreeman** [comment]
Nope. I'm using a 1.1 index.php and I can see where it is supposed to catch a HttpNotFoundException but apparently something else is happening before a HttpNotFoundException is ever thrown.

To be sure, I just downloaded the latest from the 1.1/develop branch. I went into the Welcome controller and changed the name of the classname to something random. Same results.

**Comment by WanWizard** [comment]
Still can not reproduce this.

I did exactly the same, and I got

```
Fatal error: Cannot redeclare class blahblah in APPPATH/classes/controller/welcome.php on line 53
```

Followed by the traditional "Oops, an unexpected error occurred" screen. Not a white screen in sight.

In Development mode, I get the full error.

**Comment by johnnyfreeman** [comment]
Just ran this same test on another server and got the "cannot redeclare" error you mentioned. So, false alarm on the white screen. However, as you said, error message isn't appropriate for what's happening.

**Comment by WanWizard** [comment]
Altough the message is not explaining the correct error, it does give you the defined class name, the name of the file the class is defined in, and the line number. This makes it easy to find your mistake.

If logic is added to the autoloader to determine if the file loaded contains the correct class, you will have to throw an exception if that is not the case, loosing all that information.

So we'll leave it like this for now.
