### ISSUE TITLE
Still core reference to removed Html::br() in Error class

### ISSUE THREAD

**Issue by komita1981** [fuel/core#716]
[edited, this was:]
**Method br not exists in Html core class**
Error - Call to undefined method Fuel\Core\Html::br() in COREPATH/classes/error.php on line 186

**Comment by jschreuder** [comment]
A few methods were removed from the HTML class in v1.1: [Changelog](https://github.com/fuel/core/wiki/Changelog-v1.1).

**Comment by komita1981** [comment]
In version 1.1 in class error in method  show_php_error there are still:
echo $e->getMessage().Html::br();

**Comment by jschreuder** [comment]
No there isn't: https://github.com/fuel/core/blob/1.1/master/views/errors/php_fatal_error.php - I think you have that in a view overwrite of your own.

**Comment by jschreuder** [comment]
Sorry, misread - you're right.
