### ISSUE TITLE
Base URL duplication while Uri::create() and Response::redirect()

### ISSUE THREAD

**Issue by axelitus** [fuel/core#718]
Using the following statement:

```
\Response::redirect(Uri::create('process'), 'location');
```

while using a `base_url` in config duplicates the `base_url` part.

Example:

```
config['base_url'] = '/my_subfolder/';
\Response::redirect(Uri::create('my_controller');    // One would think that this will redirect to /my_subfolder/my_controller
```

Instead the Response object will try to redirect to `/my_subfolder/my_subfolder/my_controller` because on line  96 of the `response.php` file the url gets Uri::create()'d again thus prefixing it again with the `base_url`.

Shouldn't the Response object check if it needs to be Uri::create()'d or should the Uri::create() method handle this?

EDIT:
Or the way both methods work is fine and I should not mix them?

**Comment by WanWizard** [comment]
You should use redirect() either with a full URL (including the scheme and hostname, like the example in the docs), or with a URI for the current website.

In your example you should use

```
\Response::redirect('my_controller');
```

to generate the correct redirect. There is no need to use Uri::create() here.

**Comment by axelitus** [comment]
Yes that was my first appreciation. I really don't recall where I saw this piece of code and copied it... and since then I've been using it like that. Thanks. Then we should not mixed those things :) (fixing redirect calls()....)
