### ISSUE TITLE
iOS fullscreen mode and Agent::is_mobiledevice()

### ISSUE THREAD

**Issue by kbanman** [fuel/core#725]
When running a web app in [iOS fullscreen mode](http://developer.apple.com/library/safari/#documentation/appleapplications/reference/SafariHTMLRef/Articles/MetaTags.html), `Agent::is_mobiledevice()` incorrectly returns false;

**Comment by aranw** [comment]
Do you mean `Agent::is_mobile()`

**Comment by kbanman** [comment]
That's been deprecated: https://github.com/fuel/core/commit/e745431aef170b14ef8fe080d87edca25b72473e

**Comment by aranw** [comment]
Ah well that means its related to browscap not Fuel...
