### ISSUE TITLE
Missing rollback to SAVEPOINT for DB transactions

### ISSUE THREAD

**Issue by billmn** [fuel/core#726]
I think that can be useful get a way to set some SAVEPOINT for DB transactions.
Then, it can be simple rollback to this savepoint with something like  :

<pre>DB::rollback_transaction($db, $savepoint)</pre>

or

<pre>DB::rollback_to($savepoint)</pre>

**Comment by jschreuder** [comment]
I remember looking into this earlier and running into many inconsistencies between DB engines in the way it was implemented, which made me decide against implementing it back then. It would be good to add such details to the feature request to see if it's even possible in a way that doesn't make it too engine specific.

**Comment by billmn** [comment]
I don't have experience with other DB engines other than MySQL ... I don't know how I can be useful for you

**Comment by WanWizard** [comment]
@FrenkyNet Can we add this on the list for QB2?

**Comment by frankdejonge** [comment]
We sure can. I'll put it on my list!

**Comment by WanWizard** [comment]
Ok, marked as "Accepted" for the 2.0 milestone.

**Comment by frankdejonge** [comment]
This doesn't fit into the driverless design the 1.x line has. Since 2.0 will not have it's own query builder I'm closing this. It's already accounted for in Cabinet.
