### ISSUE TITLE
Controller_Template $auto_render options has become useless

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#743]
I got to this conclusion while updating the docs for this controller type. This is what the current `after()` method looks like:

``` php
<?php
    public function after($response)
    {
        // If the response is a Response object, we don't want to create a new one
        if ($this->auto_render === true and ! $response instanceof \Response)
        {
            $response = $this->response; 
            $response->body = $this->template;
        }

        return parent::after($response);
    }
```

Which means that you can prevent "auto-render" without switching it off, all you have to do is return a Response object. I think we should get rid of the property and just do this:

``` php
<?php
    public function after($response)
    {
        // If nothing was returned default to the template
        if (empty($response))
        {
            $response = $this->template;
        }

        // If the response is a Response object, we don't want to create a new one
        if ( ! $response instanceof Response)
        {
            $response = $this->response;
            $response->body = $response;
        }

        return parent::after($response);
    }
```

Thus: it uses the template View unless you return something, in which case the return overwrites the template.

Note that I already removed any mention of `$auto_render` from the docs.

**Comment by WanWizard** [comment]
I wonder if this is really useful.

I had a similar discussion in the forums about Controller_Rest. Like Controller_Template, it is a special type of controller, for a specific purpose.

Like you shouldn't use Controller_Rest to return anything else then a data structure, you should not use Controller_Template to return anything else then a template (a view).

Why add constructions to work around the original purpose of the controller?

**Comment by jschreuder** [comment]
I don't think you got my proposal and what the issue is.

Currently it doesn't matter at all what the setting of $auto_render is when you return a Response object, that always supersedes. My opinion is that it should work as it used to when nothing is returned (which means it sets `$this->template` as the body of the Response), but always let the response of the controller overwrite that instead of only when a Response object is returned. That will remain consistent with the old usage, will remain consistent with the current way it works and is consistent with the way a normal controller works.

Only difference is that it will accept any non-empty return to overwrite the template instead of just Response objects.

**Comment by WanWizard** [comment]
Yes I did. And I agree with it.

I'm only saying that in my opinion the Controller_Rest and Controller_Template are special controllers, built for a specific purpose. In the case of template, the methods should work with $this->template, and not return anything. I don't think we should include code in it that provides workarounds for it's standard behaviour.

**Comment by jschreuder** [comment]
I agree about the Rest controller, that's a really specific controller. The Controller_Template is a more generic one and only has a little additional functionality, disallowing bypassing that is a bit strickt and not really necessary.

It's also worth to note that my proposed new `after()` method gets a lot less complex once we remove `$this->response`:

``` php
<?php
    public function after($response)
    {
        return parent::after(empty($response) ? $this->template : $response);
    }
```

**Comment by WanWizard** [comment]
Hmm... Don't agree with you on that point, but ok.

This doesn't work, because $this->template is a View object, which will be returned by the parent::after() method as-is, which will cause a warning in the logs, since controllers are required to return a Response object now.

**Comment by jschreuder** [comment]
Not just Response objects: [strings, Views, ViewModels or anything than can be cast to string is also allowed](https://github.com/fuel/core/blob/1.1/develop/classes/request.php#L480)

**Comment by WanWizard** [comment]
He, is that new? Forget my rambling...

**Comment by WanWizard** [comment]
Any progress on this @jschreuder?

**Comment by jschreuder** [comment]
It's been open long enough without objections, I'll code it up.

**Comment by WanWizard** [comment]
@jschreuder gentle reminder... ;-)
