### ISSUE TITLE
Caching config option doesn't prevent caching drivers

### ISSUE THREAD

**Issue by dmyers** [fuel/core#744]
I noticed something different that I thought was working in 1.0, but I could very easily be wrong on this.

I thought that the caching option in the core config.php that if you set it to false would prevent the drivers from caching so in the case a development environment you would disable, but leave enabled on production.

What do you guys think? Also, I love Fuel, really hope I can contribute with it as much as possible. :)

**Comment by WanWizard** [comment]
The 'caching' option in the config file only refers to caching paths used in the Finder class only. 
It has no relation to caching elsewhere.

**Comment by dmyers** [comment]
Oh okay nevermind. Just wondered.
