### ISSUE TITLE
Validation_Error class __construct method root namespace missing

### ISSUE THREAD

**Issue by darklow** [fuel/core#745]
I think this line 64 in core/classes/validation/error.php

`public function __construct(Fieldset_Field $field, $value, $callback, $params)`

should be with the beginning backslash

`public function __construct(\Fieldset_Field $field, $value, $callback, $params)`

Otherwise i get an error when extending core class in bootstrap:

```
Argument 1 passed to Fuel\Core\Validation_Error::__construct() 
must bean instance of Fuel\Core\Fieldset_Field, instance of Fieldset_Field given
```

**Comment by jschreuder** [comment]
This is weird, any extension of `Fuel\Core\Fieldset_Field` will also be an instance of that, thus this is the right way.

You'll have to use `Fuel\Core\Fieldset_Field` in your extension though as the typehint (which matches just `Fieldset_Field` inside the `Fuel\Core` namespace).
