### ISSUE TITLE
Add a function to DB to fetch one row at a time

### ISSUE THREAD

**Issue by mattlindesay** [fuel/core#750]
I have a large table that I need to process a record at a time and using the current DB class blows out my memory limit on execute().

I was thinking of extending the DB and PDO classes to add an execute_only() and fetch() function or something along those lines, so that I can loop through the records fetching one at a time rather than try (and fail) to read the whole table into memory.

Can you please consider this for the upcoming DB rewrite?

**Comment by jschreuder** [comment]
Why not just do something along these lines:

``` php
<?php
$offset = 0;
$query = DB::select()->from('table')->limit(10);
while ($result = $query->offset($offset)->execute() and $result->count() > 0)
{
   // do stuff
   $offset += 10;
}
```

I don't really think we need to automate every usecase, this seems a perfectly reasonable solution to me.

**Comment by mattlindesay** [comment]
Thanks Jelmer - I'll give that a go.

**Comment by mattlindesay** [comment]
OK that does the trick. Thanks again.
