### ISSUE TITLE
Get params in controler action with Request object and routing

### ISSUE THREAD

**Issue by Djuki** [fuel/core#759]
In ViewModel we can get request param like this

$this->name = $this->request()->param('name', 'World');

Controller should have request method to return Request object,
 so we can get parameters from it, without need to add parameters in action controller. Instead params in action methods we can just set up proper route

return array(
'_root_' => 'welcome/index', // The default route
'_404_' => 'welcome/404', // The main 404 route

'hello(/:name)?' => array('welcome/hello', 'name' => 'hello'),
);

This is way Zend read params from request.

**Comment by WanWizard** [comment]
That does not give you a request (as in GET or POST) param, it will give you a named segment in the URI.

And controllers do have the request object available in $this->request. So

```
$this->name = $this->request->param('name', 'World');
```

will work nicely in a controller method...

**Comment by WanWizard** [comment]
@Djuki This has been open without a response for 3 months. Any comments? If not I'll close it.

**Comment by WanWizard** [comment]
No response.
