### ISSUE TITLE
Can't pass DB::select->from->execute results to views

### ISSUE THREAD

**Issue by kapv89** [fuel/core#775]
you can't pass the array of objects you get from DB::select->from->execute results to views without doing a as_array on the result .. you get a security error ...

**Comment by jschreuder** [comment]
This isn't a bug, it's the result of the way the QB output considers itself to be immutable. You can still pass it if you pass it using `$view->set('result', $result, false)` and it won't be put through output encoding. For the moment this'll stay this way, we me reconsider the immutability of DB results when we revamp the QB for v2.
