### ISSUE TITLE
Core\Asset Remote instance doesn't respect path

### ISSUE THREAD

**Issue by fform** [fuel/core#776]
If you set the uri in the Asset::forge, it will always append "assets/" to the url. If you try to set the path locally to be empty, you get an error about the file not exiting.

Asset shouldn't change the url if you are setting it explicitly. 

It would also be great if an asset could be remote and local as the example below. I have a subdomain (assets.domain.com) that points to domain.com/assets/ so the file is available locally but should be accessed by the client through another url (cookie-less domain on nginx). Examples below

Asset::forge('remote',array('url'=>'http://assets.domain.com/'));
echo Asset::instance('remote')->css('bootstrap.css');
// Outputs:   http://assets.domain.com/assets/css/bootstrap.css?1326604172
// Expected: http://assets.domain.com/css/bootstrap.css?1326604172

Or
Asset::forge('local',array('paths'=>array('assets/'),'url'=>'/'));
echo Asset::instance('local')->css('bootstrap.css');
// Outputs:   /assets/css/bootstrap.css?1326604172

Or
Asset::forge('remote',array('paths'=>array(), 'url'=>'http://assets.domain.com/'));
echo Asset::instance('remote')->css('bootstrap.css');
// Error:  Could not find asset: bootstrap.css

**Comment by frankdejonge** [comment]
Can you try doing it like:

Asset::forge('remote',array('paths'=>array('/'), 'url'=>'http://assets.domain.com/'));
echo Asset::instance('remote')->css('bootstrap.css');

I think that should work.

**Comment by fform** [comment]
No go.

When it can't find the file locally, it fails on line 202 of /classes/assets/instance.php

The problem is that $this->find_file($filename, $type) returns the file with the local path prepended. Find file needs an attribute to turn the prepending off if you've override the url. If I replace line 205 with this

   $raw or $file = $this->_asset_url.($this->_asset_url=='/'?$file:preg_replace("/assets\//", '', $file)).($this->_add_mtime ? '?'.filemtime($file) : '');

It works. Basically I'm manually stripping the assets folder. If my assets domain was just the same root folder as my application domain this wouldn't be a problem. 

In my setup assets.domain.com/css/bootstrap.css is the same as domain.com/assets/css/bootstrap.css and that file is located in /public/assets/css/bootstrap.css

**Comment by WanWizard** [comment]
Asset::render() always does a find_file(), unless the filename requested contains a scheme ( :// ).
It does not support an asset instance which points to a different host to serve static assets. 

I'll check it out.
