### ISSUE TITLE
Date class to use PHP's DateTime

### ISSUE THREAD

**Issue by WanWizard** [fuel/core#787]
The current Date implementation is based on PHP's "old" procedural functions for parsing dates, which is troublesome on Windows. Emulating strptime() only works with US dates, as the format is ignored.

Why not use PHP's DateTime class for this? It can handle everything, and is fully supported on Windows.

Downside, the old strftime() formats no longer work, and have to be replaced by new formats supprted by CreateFromFormat().

**Comment by WanWizard** [comment]
@jschreuder @dhorrigan Any comments on this?

**Comment by jschreuder** [comment]
From http://nl3.php.net/manual/en/datetime.format.php

> This method does not use locales. All output is in English.

This makes the whole DateTime class essentially useless.

**Comment by bencorlett** [comment]
Wouldn't it be easier to write something that integrated this with Fuel's Lang class to translate the output?

Maybe the Lang class could use regexes if it doesn't and the date class could run the translation for output through these?

**Comment by jschreuder** [comment]
It's not easier and far more limited, the current function work perfectly for everyone but windows users trying to recognize patterns (output is fine though). I'm completely open to solutions that improve windows support, but this is superior for everyone else - including windows users that don't need pattern recognition.

**Comment by WanWizard** [comment]
I think that makes it very complex. It might be easier to just write the full functionality of strptime() in a separate class and call that if needed. There are plenty of open source versions around, if you can read C++...

**Comment by jschreuder** [comment]
@bencorlett BTW I'm fine with making your code from just now the default instead using either strtotime() or your method.

Another solution might be to make the function that is used for recognition configureable, thus make it possible to use another instead of strptime() by configuration. That keeps things consistent for almost everyone, and would allow for better solutions on windows. Defaulting to a closure with your code.

**Comment by WanWizard** [comment]
Well, it doesn't really works fine on Windows systems, this is what triggered the discussion this evening on IRC. If you pass a date string in non-US notation to it, it fails because it ignores the pattern.

It has now been replaced by Ben by something that can at least understand the basics in a pattern, but still looking for a better solution...

**Comment by jschreuder** [comment]
Quoting myself:

>  for everyone but windows users trying to recognize patterns

How did I ever deny the problem there? I've been aware of it from the beginning and you can see that clearly from the code, it's hard to code this without being aware there's a problem. At the time Dan and I deemed it not important enough to follow through on further.

[edit]
For the completeness of this discussion, actually strtotime() doesn't just US formats:

> Dates in the m/d/y or d-m-y formats are disambiguated by looking at the separator between the various components: if the separator is a slash (/), then the American m/d/y is assumed; whereas if the separator is a dash (-) or a dot (.), then the European d-m-y format is assumed.
> To avoid potential ambiguity, it's best to use ISO 8601 (YYYY-MM-DD) dates

And about the number of year digits:

> If the number of the year is specified in a two digit format, the values between 00-69 are mapped to 2000-2069 and 70-99 to 1970-1999. See the notes below for possible differences on 32bit systems (possible dates might end on 2038-01-19 03:14:07).

http://nl3.php.net/manual/en/function.strtotime.php

**Comment by bencorlett** [comment]
@jschreuder @WanWizard, is this at all a possibility?

http://www.php.net/manual/en/class.intldateformatter.php

```
<?php
$df = new IntlDateFormatter('nb_NO',
    IntlDateFormatter::FULL, IntlDateFormatter::FULL,
    'Europe/Oslo');
echo $df->format(time());
```

**Comment by jschreuder** [comment]
No, very few people will have that available and most will not be able or willing to install that to get things to work.
