### ISSUE TITLE
Validation validated()

### ISSUE THREAD

**Issue by dbpolito** [fuel/core#791]
When you do not add the field on validation method and you do not fill that field on a form and you call $val->validated('field') it returns false instead of a empty string and the query generated is field = '0', when the field is filled works fine. Thoughts?

**Comment by jschreuder** [comment]
That it works exactly as intended and returns false when the requested field isn't found. When running `$validation->validated('field')` you are asking if the field you specified validated, and when it wasn't it returns `false` - quite logical I'd think.

How you put it into a query is up to you, the Validation class doesn't care about that and shouldn't. The only thing I might want to change about this is to have it throw an exception when you request a field that's not part of the fields added to validation, as you shouldn't request a non-existing field.

Also you can add a second param to `Validation::validated()` that changes the default output for non validated fields and non-existing fields: https://github.com/fuel/core/blob/1.1/develop/classes/validation.php#L510

**Comment by dbpolito** [comment]
Right, but the issue for me is that i do not want this field validated, so i was trying to add with no rules on add_field but the method gives a warning if we don't add a valid rule. Would be great if we could could not set the rule on the add_field method regarding this:

$val->add_field('field1', 'Field 1', 'required');
$val->add_field('field2', 'Field 2'); // Not work

$val->add_field('field1', 'Field 1', 'required');
$val->add('field2', 'Field 2'); // Work!

So the point is if there is no third param works as add method

**Comment by jschreuder** [comment]
Don't use `$val->add_field()` with 2 params, it's there for one reason only: to allow passing rules as a piped string (an antiquated and soon to be deprectated method). It's not the preferred method, that's `$val->add('field1', 'Field 1')` which will work fine.

**Comment by dbpolito** [comment]
So what way would you recommend to use? $val->add('field1', 'Field 1') and when needs validation use $val->add('field1', 'Field 1')->add_rule('required')?

**Comment by jschreuder** [comment]
That's the preferred way, the `add_field()` piped-string business was only in there to help some CI folks with the transition.

**Comment by dbpolito** [comment]
Right, i really appreciate your assistance, thanks for that. ;)
