### ISSUE TITLE
Cannot create a config file using an absolute path

### ISSUE THREAD

**Issue by Savageman** [fuel/core#807]
`Config::save('/my/absolute/path/to/file', array())` will fail if the file does not exists.

This is because the finder returns false (since the file does not exists), and the save() method prepends APPPATH.'config' in front of the absolute path.

See [pull request #714](https://github.com/fuel/core/pull/714)

**Comment by Savageman** [comment]
Thanks. Super fast!

**Comment by WanWizard** [comment]
We aim to kill... eh... to please... :-)
