### ISSUE TITLE
Cannot update a file if the parent directory is not writeable

### ISSUE THREAD

**Issue by Savageman** [fuel/core#810]
`File::update()` returns an error if:
- the file already exists and is writeable ;
- the directory contaiing the file is not writeable.

In other words, my file is writeable, but I cannot update it because the directory is not.

**Comment by WanWizard** [comment]
And what do you suggest has to be done to fix this?

**Comment by Savageman** [comment]
Don't throw an error if the file exists and is writeable.

Actual code:

```
if ( ! is_dir($basepath) or ! is_writable($basepath))
{
    throw new \InvalidPathException('Invalid basepath, cannot update a file at this location.');
}

if ( ! $file = static::open_file(@fopen($new_file, 'w'), true, $area) )
{
    throw new \FileAccessException('No write access, cannot update a file.');
}
```

Proposed new code:

```
// Test the opening of the file directly
if ( ! $file = static::open_file(@fopen($new_file, 'w'), true, $area) )
{
    // Check why it failed afterwards
    if ( ! is_dir($basepath) or ! is_writable($basepath))
    {
        throw new \InvalidPathException('Invalid basepath, cannot update a file at this location.');
    }
    throw new \FileAccessException('No write access, cannot update a file.');
}
```

I'm not sure wether this could work or has deeper implications elsewhere.
The same applies to append().

**Comment by jschreuder** [comment]
This looks like a good idea in most places of the File class: first try and then try to figure out why it failed. Saves a few filesystem calls as well. Only the file_exists check be done before trying with create, move & copy.

Could you code it up and pull-request?

**Comment by Savageman** [comment]
I'm busy this week-end. Will do that next week if it's ok :)

**Comment by WanWizard** [comment]
@Savageman any progress? We need this in the next few days if it is going to be part of 1.2.

**Comment by Savageman** [comment]
Thanks for the reminder. I forgot :(

I made 3 commits so you can cherry-pick a subset of the modifications if needed.

I'm not sure the change to the copy() function is so good (because of the error supression operator), but if yes then we can do the same for get_size() and get_permission().

**Comment by WanWizard** [comment]
This was dealt with here: https://github.com/fuel/core/commit/c17a88336ef390ece10d655eb7da2cd3a79c6d00
