### ISSUE TITLE
404 is thrown for empty response in Controller_Rest

### ISSUE THREAD

**Issue by acairns** [fuel/core#813]
I don't think this is correct - what about 204 response?

For a case study: I've just made a PUT request to update an entity in my database.
I dont need to respond with an additional information, but I want to return 204 to let my SDK know everything was fine.

$this->respond( array(), 204 ); // this shouldn't throw a 404

**Comment by frankdejonge** [comment]
you could alter the $no_data_status right before this.

**Comment by frankdejonge** [comment]
Like so: 

```
$this->no_data_status = 204;
$this->respond(array());
```

**Comment by acairns** [comment]
If this is new in 1.1/develop, I don't see this as a good idea.
The controller shouldn't be responsible for the status code of a response.
If we are to be returning a Response object, shouldn't the status be set on that?

$response = \Response::forge();
$response->set_status( 204 );
return $response;

or

return \Response::forge( array(), 204 );

**Comment by WanWizard** [comment]
If you craft and return your own Response instance, this is the way you should do it.

If you use the response() method to craft your response from an array of data, the $no_data_status property is used, as you don't have access to the crafted Response instance. You could call response() first, and then set $this->response->status, but that is clumsy.

I agree that 204 is a more logical status code to return. I'll fix that.
