### ISSUE TITLE
Remove Asset::accepts_charset()

### ISSUE THREAD

**Issue by Savageman** [fuel/core#818]
The "Accept-Charset" header is not sent by browser anymore. There's no use for that.

http://hsivonen.iki.fi/accept-charset/

**Comment by WanWizard** [comment]
It's in the Agent class, not in the Asset class.

As long at it's in the official specs, it will remain in the class, as it is meant to allow you to query the features of the user agent. If the browser doesn't send it, the method will tell you that.
