### ISSUE TITLE
[fuel issue] Setting wrong value for DOCROOT in oil file

### ISSUE THREAD

**Issue by antitoxic** [fuel/core#821]
Issues are not enabled for the [Fuel repository](https://github.com/fuel/fuel) so I'm adding the issue here.

I'm using oil tasks with `cron` to retrieve images from a web service and upload them to the public directory.

The problem is the oil file sets `DOCROOT` constant wrongly to the current directory whereas the public directory is `./public` or something else if you've changed it.

Oil can't really know what's the public directory.  It's either have to be hardset or execute oil with the `./public` as current working directory and then setting `DOCROOT` as `getcwd()`.

If `DOCROOT` is set to `getcwd()` developers will be able to make make a 2 line bash script and execute the oil with `./public` as current working directory.

**Comment by frankdejonge** [comment]
For BC reasons we're not changing this in the upcoming 1.2 release, but in the 2.0 release it will point to that directory (already implemented). For now you can just change the path in your Oil file which will have the same effect.
