### ISSUE TITLE
ORM Slug Observer

### ISSUE THREAD

**Issue by aranw** [fuel/core#823]
Not as much a issue but more of something that looks odd and think could be altered. 

Basically I have a place called Herbert's Bar in my database, and it has a slug generated for it. But when the ORM Slug Observer generated the slug it came out as 

```
herbert-s-bar
```

and I thought it should really be generated as 

```
herberts-bar 
```

Thoughts?

**Comment by frankdejonge** [comment]
This is not a problem with the ORM Slug Observer, but with the Inflector's friendly_title function. I'll discuss the removal of quotes.

**Comment by aranw** [comment]
Ah ok wasn't sure if it used the Inflector's friendly_title function or not.
