### ISSUE TITLE
Tasks do not use the cascading filesystem

### ISSUE THREAD

**Issue by WanWizard** [fuel/core#827]
Title is self explanatory.

The result of this is that you can't call a task method from your application, you have to manually find and include the file first. This is the same method 'oil refine' is using.

It would be better to have them obey the rules of the CFS, or to have a core class that allow you to access tasks from your application, like is implemented for migrations.

**Comment by tomschlick** [comment]
+1

**Comment by dberry37388** [comment]
+1

**Comment by WanWizard** [comment]
Has been added to the 2.0 roadmap.
