### ISSUE TITLE
Rest Controller: No longer able to have parameters in URL because \Input::extension() is broken.

### ISSUE THREAD

**Issue by lukearmstrong** [fuel/core#835]
I have a large existing site that uses the Rest Controller extensively to return json to be used by Javascript.

After updating the core I happened to notice I was getting a error when doing a GET request to this URL `/shop/productrest/change_colour.json/345/`

ErrorException [ Warning ]: Missing argument 1 for Shop\Controller_ProductRest::get_change_colour()

``` php
<?php

namespace Shop;

class Controller_ProductRest extends \Controller_Rest
{
    public function get_change_colour($product_colour_id)
    {
        // stuff that used to work
    }
}
```

This is because a [change](https://github.com/fuel/core/commit/ab5bcf209161addfd503eb96ff8f91e5215903bf#classes/controller/rest.php) was made to Controller_Rest to use \Input::extension() to determine response format. But this is broken if you have parameters in your URL, so it doesn't return the extension, it returns `json/345/` as the extension, and sets `/shop/productrest/change_colour` as the URL, losing the parameters!

I've come up with a temporary fix because I couldn't figure out the regex to do the same thing.

Links to follow...

**Comment by lukearmstrong** [comment]
https://github.com/fuel/core/pull/836

**Comment by jschreuder** [comment]
I think that part of this problem is that this isn't the correct format to pass additional params. You want to implement REST thus you should use REST means, meaning that the ID should be passed as a GET param: `/shop/productrest/change_colour.json?id=345`

**Comment by lukearmstrong** [comment]
Yeah, I'll just rewrite all of my javascript and rest controller methods, that makes so much better sense than fixing a bug.

**Comment by jschreuder** [comment]
You're missing my point: it's not a bug. Read up a bit on REST and you'll learn that a URL for REST shouldn't contain unique identifiers, those should be part of the input GET/POST/PUT/DELETE params.

**Comment by lukearmstrong** [comment]
[What I have done isn't wrong](http://microformats.org/wiki/rest/urls), but yes, I agree your suggestion is better.

Rewriting Rest Controller methods and Javascript would be a very time consuming task.

**Comment by jschreuder** [comment]
Ok, that wasn't in my book. Though there's an important difference between your URLs and the URLs in that document:

```
/people/1.json
/shop/productrest/change_colour.json/345/
```

The file extension should be at the end.

We shouldn't have code in the core that encourages or enables bad practice. Now if you made a mistake earlier on and the bottom line is that the rewrite isn't worth the effort that's your problem in the end, but shouldn't be a hard one to fix: create an extension of the Input class in your app that overwrites the core method and makes your urls possible.

**Comment by lukearmstrong** [comment]
Bad example, I quickly googled, then noticed what you pointed out after I posted my response.

[Wikipedia](http://en.wikipedia.org/wiki/Representational_state_transfer#RESTful_web_services) seems to suggest there is no standard, so without a standard who is to say what is right and what is wrong?

> Unlike SOAP-based web services, there is no "official" standard for RESTful web services.[13] This is because REST is an architecture, unlike SOAP, which is a protocol. Even though REST is not a standard, a RESTful implementation such as the Web can use standards like HTTP, URI, XML, etc.

[13] http://rest.elkstein.org/2008/02/what-is-rest.html

**Comment by jschreuder** [comment]
You're right, it's not a standard - but that doesn't mean it's completely without any rules. It's more of a principle, the Wikipedia article you referenced puts it quite well under the heading **central principle**:

> An important concept in REST is the existence of resources (sources of specific information), each of which is referenced with a global identifier (e.g., a URI in HTTP). In order to manipulate these resources, components of the network (user agents and origin servers) communicate via a standardized interface (e.g., HTTP) and exchange representations of these resources (the actual documents conveying the information).

The concept of a "global identifier" is also why I dont put the ID in the path but in the query params. I feel that within the path it becomes part of the identifier and thus breaks the principle.

But that's not really the point here. The point is that the path you're using isnt a good path, there is a file in the middle and the slashes continue as if it's a directoryname instead of a file with extension. And that is why I think that type of path isn't a good path. With the extension at the end everything should work fine.

EDIT: you just made me realize this code should probably use pathinfo() instead of a regex, but that won't change anything for you.
