### ISSUE TITLE
Fuel\Core\Asset should not throw exception on asset not found

### ISSUE THREAD

**Issue by richard-myers** [fuel/core#845]
It would be useful if the asset class would not throw an exception when an asset is not found or at least has the option to instruct it to continue without the exception.

In my own case I want it to check and see if there is a "custom.css" file and if its found in one of the asset paths include it but if the file does not exist simply continue and pretend I never wanted to load the file.

a simple `continue;` would be a handy alternative to the current exception.

**Comment by jschreuder** [comment]
[Use try-catch](http://php.net/manual/en/language.exceptions.php)

**Comment by richard-myers** [comment]
But then you can't use the render function on a group of assets and would need to render assets one at a time ie. include each one separately

...sort of beats the point of groups?

**Comment by jschreuder** [comment]
The importance of specific details. That is a fair point and should be discussed.

**Comment by jschreuder** [comment]
@WanWizard @FrenkyNet what do you guys think? I propose adding a config value for `"fail_silently"` that defaults to `false` (thus current behavior), but prevents exceptions when `true`.

**Comment by richard-myers** [comment]
Thanks, would be useful if something could be sorted. I should probably of been more specific in original message.

**Comment by frankdejonge** [comment]
@jschreuder I just wanted to opt that as the solution. A config setting would be the way to go. I'll dive into this. Made it a feature request instead of invalid.

**Comment by frankdejonge** [comment]
Fixed here https://github.com/fuel/core/commit/a7de6c3370cbbad158d71214dafc7cd3a0d1c657
