### ISSUE TITLE
File::read() and Format::forge() - Cannot Convert CSV Files

### ISSUE THREAD

**Issue by swt83** [fuel/core#846]
I see some closed issues regarding CSVs and the Format class, here is something I'm encountering:

```
// read csv file as string
$csv = \File::read($path, true);

// convert csv to array
$array = \Format::forge($csv, 'csv')->to_array();
```

The above will fail to convert properly because the File::read() will strip out "\n" characters, which the CSV conversion requires to detect new lines.

**Comment by swt83** [comment]
I figured out a little more.  The _from_csv() method assumes that lines endings are always "\n", mine are "\r".  Furthermore, the _from_csv() method assumes that all values are wrapped in double quotes.  It's not broken, just won't work for my file.

**Comment by frankdejonge** [comment]
The format class should have config settings for this. Keeping this open to remind me.

**Comment by frankdejonge** [comment]
This was added. Closing issue.
