### ISSUE TITLE
Config::get/set behaving wrong when value has leading zero

### ISSUE THREAD

**Issue by huglester** [fuel/core#848]
Hello everyone,

Playing with File class, I spotted that chmoded dir's/files have wrong permissions.

after searching around where the bug is, it seems that config class does not play nicely with values which has leading zeroes:

here are some tests:

```
    \Config::set('test_val', 0777);
    echo \Config::get('test_val');
    // returns 511

    \Config::set('test_val', 777);
    echo \Config::get('test_val');
    // returns 777

    \Config::set('test_val', '0777');
    echo \Config::get('test_val');
    // returns 0777 
```

It's a Linux machine.
FuelPHP 1.1-dev

Thanks

**Comment by frankdejonge** [comment]
Hey huglester. I've done some testing, and when you normally var_dump(0777) it will print out in(511) as well. So this is not an issue with FuelPHP but with php itself.

**Comment by jschreuder** [comment]
This is not an issue at all: these values are octal ([as they're prefixed with a zero](http://php.net/manual/en/language.types.integer.php)) and the octal value 0777 equals 511 decimal. Which is fine.

Check out the explanation in http://nl.php.net/manual/en/function.chmod.php for the $mode argument.
