### ISSUE TITLE
Image Class - Large Image resize exhausts memory

### ISSUE THREAD

**Issue by mikebranderhorst** [fuel/core#852]
The Image Class is fantastic!

But when resizing large images (+/- 2.5mb+) you'll get errors.

Case: I have a large jpg and want to resize it to 1080 height 75 quality (landscape and portrait).

```
$config = array('quality' => 75);

$file = 'image.jpg'; // large image

$image = \Image::forge($config)->load($file);

$sizes = $image->sizes();

$image->resize(ceil(($sizes->width / $sizes->height) * 1080), 1080)->save($file);

```

After trying for a while I just did it the old fashion way:

```
$url = 'http://...'; // remote large image

ini_set('gd.jpeg_ignore_warning', 1);

$src_image = @imagecreatefromjpeg($url);

if ( ! $src_image)
{
    if ($stream = @fopen($url, 'r'))
    {
        $src_image = @imagecreatefromstring(stream_get_contents($stream));

        fclose($stream);
    }
}

if ($src_image)
{
    $src_w = imagesx($src_image);
    $src_h = imagesy($src_image);

    $dst_w = ($src_w / $src_h) * 1080;
    $dst_h = 1080;

    $dst_image = imagecreatetruecolor($dst_w, $dst_h);

    if ($dst_image)
    {
        if (imagecopyresampled($dst_image, $src_image, 0, 0, 0, 0, $dst_w, $dst_h, $src_w, $src_h))
        {
            if (imagejpeg($dst_image, $file, 75))
            {
                // log and add info to db
            }
        }

        imagedestroy($dst_image);
    }

    imagedestroy($src_image);
}
```

This way is to the eye three times faster and without errors and a nice image.

I have no time to dig in the very huge but nice Image Class.

I saw a few things playing with the class:

1) Missing a fallback driver, say imagick default and gd as fallback.
2) It gave me images one pixel width and xxx height or 1 pixel height...
Maybe an extra dimensions (sizes) check at some places?
3) Missing a max width / max height setting to say always fit a screen size for example 1920x1080.
4) a watermark is not remembered, if you set it, resize, save and resize and save again the second is without watermark.

```
$image
->watermark(...)
->resize(...)->save_pa('', '-resize-1')
->resize(...)->save_pa('', '-resize-2')
->resize(...)->save();
```

5) some images gave me an error on resize but doing this did the trick (resize first to it's own dimensions)

```
$config = array('quality' => 75);

$file = 'image.jpg'; // large image

$image = \Image::forge($config)->load($file);

$sizes = $image->sizes();

$image
->resize($sizes->width, $sizes->height)
->resize(...)
->save($file);

```

6) having three load choices would be nice: file, url and resource
7) Image::load($original)->resize(...)->save($new)->output(); saves $new output $original
8) Image::load($original)->resize(...)->output()->save($new); saves $original output $new
9) Image::load($file)->output(); exit; is very slow, this is much quicker (also without the extra headers):

```
$size = getimagesize($file);

$fp = fopen($file, 'rb');

if ($size and $fp)
{
    header('Last-Modified: '.gmdate('D, d M Y H:i:s', filemtime($file)).' GMT');

    if (filemtime($file) == strtotime(\Input::server('HTTP_IF_MODIFIED_SINCE')))
    {
        header('HTTP/1.1 304 Not Modified');
    }

    header('Content-Type: '.$size['mime']);
    header('Content-Length: '.filesize($file));

    fpassthru($fp);

    exit;
}
```

**Comment by dudeami0** [comment]
In your first example, as a note, you can do this:

  $image->resize(null, 1080)->save($file);

and it will automatically keep AR ratio with the height being 1080.

The reason the library is so slow (For GD anyways), is because of the fixes/hacks to make GD support transparency (for the most part) and other fixes. I personally think GD is terrible, and only made the driver for people in strict shared hosting environments. If at all possible, use the IMagick extension, else imagemagick binaries.

Now for your numbers:

1) Just switch to GD if needed? GD fallback automatically will make people think imagemagick/imagick is working when its just falling back to GD.
2) Not sure on this one, give me an example image to test.
3) Could add the option, but seems a little unnecessary
4) Nothing is remembered after each save/output, unless you set the 'persistence' config value to true.
5) That is interesting, again some example images would be nice.
6) Again, could be added, but seems unnecessary (Especially since resources only work with GD).
7+8) Set persistence to true in the config
9) This is again due to the slow GD explanation above. Also, nothing is ran manipulation-wise before save, save_pa, or output is called.

**Comment by mikebranderhorst** [comment]
Thanks for the feedback

```
In your first example, as a note, you can do this:

$image->resize(null, 1080)->save($file);

and it will automatically keep AR ratio with the height being 1080.
```

Nice, didn't know this

```
The reason the library is so slow (For GD anyways), is because of the fixes/hacks to make GD 
support transparency (for the most part) and other fixes. I personally think GD is terrible, and 
only made the driver for people in strict shared hosting environments. If at all possible, use 
the IMagick extension, else imagemagick binaries.
```

Good to know, but jpg does not need transparency so the class could know this and should work without the fixes/hacks.

1) true
2) I'll see if I can get one (I should have given one right away, now I use my own script thus I need to do some rewriting to get the specific image out of 250.000 images (I had about only 10 images with this problem, maybe it was an simple error but I use the script with a from so never saw an error))
3) I don't see why this is unnecessary. For example you have a screen 1920x1080 and you have landscape and portrait photo's that are bigger and you just want to have them resized to fit the screen. The dimensions are not always the same due to cropped photo's. It would be nice to have a function say box_resize(1920, 1080) and the input image is resized to fit the box. Same for crop, box_crop(1920, 1080) to have centered full screen crop for example.
4) nice, didn't know about persistent config setting
5) > 2) 
6) this has nothing to do with the used library, load is a class function thus the function load could handle all thee methods and the class figures out if the library supports it and else use file_get_contents or put it into a temp file first or whatever.
9) ? I wrote the script for GD as well and everything is way faster, so the "slow GD" I can not place here, both (the class and I) use GD and mine example is x times faster.

The reason I wrote this issue is to give some feedback. In the end I stopped using the class because if you have to edit thousands of images every day, speed is important whether it uses GD or something else. I use iMagick now but the speed improvements by making a custom script seems odd. There shouldn't have no difference in speed by using a custom script or the class both using the same library.

**Comment by WanWizard** [comment]
@dudeami any further comments?

**Comment by dudeami0** [comment]
3) From the sounds of it resize() or crop_resize() will do the trick. resize(1920, 1080) will keep it within that bounding box of 1920x1080, and you can toggle padding with the 4th argument.

6) I still do not see a lot of use for this, at least the resource part of it. Yes it would be cool, but under used in my opinion.

9) The image library will always be slower. Some optimizations could probably be made, but I do not have the time at present to run through the code and make these optimizations.

The image library was built for basic image manipulation. If your editing 250k images a day, no, the library is not for you. It can probably go faster, but will never go as fast as a custom GD script.
