### ISSUE TITLE
Lowercase controller name in module

### ISSUE THREAD

**Issue by huglester** [fuel/core#855]
Hello,

somehow it does happen that one of my controllers has lowercase name:
string(30) "Mailboxes\Controller_mailboxes" 
- I'm not sure why is that, tried removing routes.php file from module
- also in app/config/routes.php there are no specific routes to route to mailboxes module... 

I tried to rename controller to Mailboxes to Mailboxe (missed S at the end) - and then $this->request->controller started to report: Mailboxes\Controller_Mailboxe

Thanks

**Comment by WanWizard** [comment]
How do you request this controller?

Using http:\example.org\mailboxes (and have the router fill in the default controller name and action?) or http:\example.org\mailboxes\mailboxes\index ?

Could be that the autodetection logic in the router is missing a ucfirst()...

**Comment by huglester** [comment]
Hello WanWIzard, just tested:

http://example.com/mailboxes/mailboxes/index
I get string(30) "Mailboxes\Controller_Mailboxes" 

and: 
http://example.com/mailboxes
I get string(30) "Mailboxes\Controller_mailboxes"
