### ISSUE TITLE
Inflector Str called from global namespace

### ISSUE THREAD

**Issue by gator92** [fuel/core#865]
Throughout the Inflector class, the Str static function calls are referenced from the global namespace. However, it seems like it's actually located in the Fuel\Core namespace (the same as Inflector).

**Comment by frankdejonge** [comment]
This is all throughout the framework, it's the way we allow people to extend classes. If not found in global, the autoloader searches for the first class in a package that's mapped to global, and then defaults to the class in Fuel\Core. So what you see is correct, but not an issue, it's the solution ;)

**Comment by gator92** [comment]
Thanks for the information. For the moment, I'm using the Inflector class, one of the better I've come across, as a standalone component, so I'll adjust accordingly.
