### ISSUE TITLE
Date::create_from_string Multi Format

### ISSUE THREAD

**Issue by maitrepylos** [fuel/core#868]
Hello, it would be possible to have the possibility of creating a date following a predefined format, little as Datetime

[code]

/\* Date::create_from_string($input,$format, $pattern_key) */

Date::create_from_string("01/04/2011","d/m/Y");  //April 1st, 2011

[/code]

Thanks

**Comment by jschreuder** [comment]
That is already possible: http://docs.fuelphp.com/classes/date.html#/method_create_from_string - though the documentation lacks the point that you can also directly input a pattern (a strftime() pattern).
