### ISSUE TITLE
Html::prep_url() with empty string

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#869]
When using the prep_url method with the $url parameter blank, the return value is 'http://'

This behavior causes a problem when validating a url in a form. When the form field is empty, the prep_url() method returns 'http://' which is then an invalid url.

I would suggest that if the $url parameter is empty, then prep_url() return an empty string.

**Comment by frankdejonge** [comment]
Htm::prep_url expects a url to be passed into the function. If your input is empty, don't pass it through Html::prep_url(). I believe you're using some kind of custom validation rule for this?

**Comment by Mitchell64** [comment]
No, I'm only using basic customization rules. The code for the website field looks like below. This will fail if the website field is not required and left blank because prep_url() will return the string "http://" which will fail when valid_url() is called.

```
$form->add('website',
        'Website',
        array(
            'type' => 'text',
            'value' => empty($data->website) ? '' : $data->website,
            'size' => 50,
            'maxlength' => 2048,
        ),
        array(
            array('trim'),
            array('Html::prep_url'),
            array('valid_url'),
        )
    );
```

**Comment by frankdejonge** [comment]
We discussed this, and this is in conflict with the purpose of this function and not just a drop-in url fixer. I'd suggest you make your own validation function that covers the functionality you require, which is very easy.

**Comment by Mitchell64** [comment]
Actually, I did have to make my own validation function. You mentioned that "this is in conflict with the purpose of this function." Just out of curiosity, what is the purpose and why would it be in conflict to return an empty string if an empty string was sent to the function?

**Comment by frankdejonge** [comment]
The input should never be empty. That's one. It prepends a schema when there is none available. The only thing wrong with it now, is that is doesn't throw an UnexpectedValueException when the input is empty, which it actually should.

**Comment by Mitchell64** [comment]
Ok, I'll continue to use my validation rule. Thanks for taking the time to examine and explain.
