### ISSUE TITLE
migrate:down doesn't work

### ISSUE THREAD

**Issue by peter-fritchley** [fuel/core#875]
The new migrate down (supplying a version) doesn't seem to work. I think the problem resides in \Fuel\Core\Migrate::find_migrations() as it seems to be returning the wrong direction when called from \Fuel\Core\Migrate::version().

**Comment by WanWizard** [comment]
I didn't have an issue migrating down here. Are you migrating using the "old" version numbers, or do you use a different prefix?

**Comment by peter-fritchley** [comment]
I have 8 migrations numbered 001_users.php to 008_categories.php (all in the app).

**Comment by WanWizard** [comment]
In 1.1 the migration logic was split between the migrate task and the migrate class. I tried to merge while retaining the current design. In hindsight not a good idea.

I'm going to rewrite the migration logic, it's a bit of a mess now.

**Comment by WanWizard** [comment]
Migrations are completely rewritten, and the old behaviour (up/down without a version) has been restored.

Could you check if this fixes your problem? I don't seem to have issues anymore migrating up or down here.

**Comment by peter-fritchley** [comment]
Yes that seems to have fixed the issue. 

Many Thanks.

**Comment by WanWizard** [comment]
Thanks for the feedback.
