### ISSUE TITLE
Invalid formatting of validation rules between Fieldset_Field and ORM

### ISSUE THREAD

**Issue by NykO18** [fuel/core#876]
I'm just posting this one real quick because I encountered it in my project and though it was really a bummer.
Basically, I have a list of validation fields with rules and I'm trying to add a new field with the exact sames rules as another field (kind of validation inheritance). So what I'm doing is this :

```
$validation
    ->add('password', 'password')
    ->add_rule('required')
    ->add_rule('min_length', 6);

$validation
    ->add(
        'new_password',
        'New password',
        array(),
        $validation
            ->fieldset()
            ->field('password')
            ->rules
    );
```

This part is working as intended. The field **new_password** inherits of all of the **password** field rules. Problem is when this system is coupled with the ORM built-in validation. In the ORM Model you have to declare the field like this :

```
protected static $_properties = array(
    'password' => array(
        'data_type'  => 'varchar',
        'label'      => 'Password',
        'validation' => array('required', 'min_length' => array(6)),
    ),
);
```

The problem arise when you're trying to do the inheritance later on :

```
$validation = Validation::forge();
$validation ->add_model('MyModel');
$validation
    ->add(
        'new_password',
        'New password',
        array(),
        $validation
            ->fieldset()
            ->field('password')
            ->rules
    );
```

The **min_length** rule is not correctly parsed and copied in the **new_password** field and the error message reads :

```
The field New password has to contain at least (array) characters.
```

I guess this is because the ORM rules have their own format which is different from the native rules (namely **'min_length' => array(6)** instead of **'min_length' => 6**). All in all, a pretty minor issue, but still cringe worthy since it took me a couple of hours to figure this one out. Let me know if there's a better way!

**Comment by jschreuder** [comment]
This is not a bug, the ORM uses the correct format which is the exact same format as is used within the Validation class. The problem with copying the ORM rules didn't arise because the format there is different, but because you formatted them wrong.

All rules allow multiple arguments to be passed to them, necessary or not. Which is why the default format in the ORM and in the Validation class internally is `'rule' => array()` to allow those params in the array.

To add multiple params in the Validation class you'd use `$val->add_rule('rule', 1, 2, 3, 4)` which would become `array('rule' => array(1,2,3,4))`. Just like `$val->add_rule('min_length', 6)` becomes `array('min_length' => array(6))`.

**Comment by NykO18** [comment]
Wait, what? If I use just **6** as the **min_length** inside the ORM Model (instead of **array(6)**), I get this :

```
Warning!
ErrorException [ Warning ]: array_unshift() expects parameter 1 to be array, integer given
PKGPATH/orm/classes/observer/validation.php @ line 107:

Warning!
ErrorException [ Warning ]: call_user_func_array() expects parameter 2 to be array, integer given
PKGPATH/orm/classes/observer/validation.php @ line 110:
```

And if I use **array(6)** inside the **add_rule()** (instead of just **6**), I get this :

```
The field Password has to contain at least (array) characters.
```

So... how I am supposed to use the same format for both?
Could you explain me how I _"formatted them wrong"_? I really don't understand.

**Comment by jschreuder** [comment]
First of all, the example code from you original post was correct:

`'validation' => array('required', 'min_length' => array(6)),`

But you said later:

> I guess this is because the ORM rules have their own format which is different from the native rules (namely 'min_length' => array(6) instead of 'min_length' => 6).

Which is not true, this is exactly the same as how it is saved inside the Validation object. Also it will map to $field->add_rule() just like you would use it.

Now as to the error you seem to be getting always for some reason: why don't you var_dump `$validation->fieldset()->field('password')->rules` both from a Model provided field and from a user provided field to see what is different.

It may also be that 1.2 will solve your issue as there are some differences in the 1.1/develop branch (will be released as 1.2) to the 1.1/master branch (= 1.1 final). But from a quick look I didn't see any significant changes for this issue.

**Comment by NykO18** [comment]
Well, they are both different. I'm still talking about the examples inside the original post. If I dump the values, there is obviously something going on :

`var_dump($validation->fieldset()->field('password')->rules);`

```
array
  0 => 
    array
      0 => string 'required' (length=8)
      1 => 
        array
          empty
  1 => 
    array
      0 => string 'min_length' (length=10)
      1 => 
        array
          0 => int 6
```

`var_dump($validation->fieldset()->field('new_password')->rules);`

```
array
  0 => 
    array
      0 => string 'required' (length=8)
      1 => 
        array
          0 => 
            array
              empty
  1 => 
    array
      0 => string 'min_length' (length=10)
      1 => 
        array
          0 => 
            array
              0 => int 6
```

And it goes on, and on, and on... If I continue copying the rules from one element to another, it keeps embedding the rules deeper and deeper inside sub-arrays :

`var_dump($validation->fieldset()->field('new_new_password')->rules);`

```
array
  0 => 
    array
      0 => string 'required' (length=8)
      1 => 
        array
          0 => 
            array
              0 => 
                array
                  empty
  1 => 
    array
      0 => string 'min_length' (length=10)
      1 => 
        array
          0 => 
            array
              0 => 
                array
                  0 => int 6
```

**Comment by NykO18** [comment]
Any new insight on this, you closed the issue but didn't conclude if there really was an issue or not regarding my last comment?
