### ISSUE TITLE
Migration of Packages should use loaded package paths and not assume everything is in PKGPATH

### ISSUE THREAD

**Issue by richard-myers** [fuel/core#881]
The Migration class currently assumes ALL packages exist within the PKGPATH but the default config file implies users can place packages at any path they want ie. array('mypackage' => APPPATH.'packages/mypackage/')

I suggest that the Fuel\Core\Migrate::_find_package() be moved to

``` php
private static function _find_package($name = null)
{
    $loaded_packages = \Package::loaded();
    $files = array();

    if ($name == null)
    {
        foreach($loaded_packages as $package_path) {
            $files += glob($package_path.'/'.\Config::get('migrations.folder').'*_*.php');
        }
    }
    elseif (isset($loaded_packages[$name]))
    {
        $files = glob($loaded_packages[$name].'/'.\Config::get('migrations.folder').'*_*.php');
    }

    return $files;
}
```

Its also worth altering the code (starting line 76) in the Oil Migrate task to:

``` php
// if true - get all packages
if ($packages === true)
{
    // get all packages that have files in the migration folder
    foreach (\Package::loaded() as $package_name => $package_path)
    {
        if (count(glob($package_path.\Config::get('migrations.folder').'/*.php')))
        {
            static::$packages[] = $package_name;
        }
    }
}
```

Apologies for not making this a pull request - I'm still getting to grips with Git

**Comment by WanWizard** [comment]
Scrap my previous comments...

You can even load packages at runtime from any given path, which you will never be able to migrate.

I think I prefer to leave the current code as is, and add an option to specify custom paths, which would allow you to store your migrations files where ever you want, even if they are totally unrelated to packages or modules...

**Comment by richard-myers** [comment]
Totally forgot about the loading of packages manually instead of auto loading. Will leave my overridden class in place for now and wait and see what you come up with as an alternative solution.

**Comment by WanWizard** [comment]
@philsturgeon Any thoughts on this?

**Comment by philsturgeon** [comment]
I'd leave this as is. We're meant to be tagging up 1.2 any time now and 2.0 has already got much better logic for finding migrations, so no need to work on this too.
