### ISSUE TITLE
Empty array item does not serve given default

### ISSUE THREAD

**Issue by mikebranderhorst** [fuel/core#884]
For example if I use:

```
$abc = Input::server('ABC', 'some default');
```

If ABC does not exist the default "some default" is returned.
But if ABC does exist but is empty the default will not be returned.

I don't know if this is by design or not.

https://github.com/fuel/core/blob/1.1/develop/classes/arr.php#L60

Shouldn't this code:

```
                if ( ! is_array($array) or ! array_key_exists($key_part, $array))
                {
                    return \Fuel::value($default);
                }
```

be:

```
                if ( ! is_array($array) or empty($array[$key_part]))
                {
                    return \Fuel::value($default);
                }
```

I know I can do:

```
$abc = Input::server('ABC') ?: 'some default';
$abc = '123 '.$abc.' 456';
```

but this would be nicer:

```
$abc = '123 '.Input::server('ABC', 'some default').' 456';
```

**Comment by frankdejonge** [comment]
This is by design, a param in an array can be empty and still be what you want without falling back to default.
