### ISSUE TITLE
Missing message in Upload error for duplicated file

### ISSUE THREAD

**Issue by billmn** [fuel/core#894]
I've set Upload configuration to doesn't "auto_rename" and "overwrite" files.

When I upload a file tthat already exists I found the error in Upload::get_errors() array, but missing the "message" key (I've checked and 110 is the right error code)

<pre>
array(1) {
  [0]=>
  array(11) {
    ["name"]=>
    string(9) "grain.gif"
    ["type"]=>
    string(9) "image/gif"
    ["error"]=>
    bool(true)
    ["size"]=>
    int(4982)
    ["field"]=>
    string(11) "file_upload"
    ["key"]=>
    bool(false)
    ["file"]=>
    string(36) "/Applications/MAMP/tmp/php/phpwZuBW7"
    ["errors"]=>
    array(1) {
      [0]=>
      array(1) {
        ["error"]=>
        int(110)
      }
    }
    ["extension"]=>
    string(3) "gif"
    ["filename"]=>
    string(5) "grain"
    ["mimetype"]=>
    string(9) "image/gif"
  }
}
</pre>

**Comment by WanWizard** [comment]
All messages are added after processing using the upload language file. 

Does this exist and is it up to date (i.e. does it contain a string for UPLOAD_ERR_DUPLICATE_FILE)?

**Comment by billmn** [comment]
Yes and all other messages works fine ... and yes, I have \Upload::UPLOAD_ERR_DUPLICATE_FILE in lang file

**Comment by WanWizard** [comment]
I can not reproduce it:

```
'errors' => 
  array
    0 => 
      array
        'error' => int 110
        'message' => string 'A file with the name of the uploaded file already exists' (length=56)
```

This suggests there must be an issue with your language file. Maybe one exists in app (or elsewhere, like in a module) that doesn't have this?

**Comment by WanWizard** [comment]
@billmn any feedback?

**Comment by billmn** [comment]
No ... there aren't any "upload.php" language file in other folders.
I don't know why but I have the same problem with another project in FuelPHP (that use the last version of CORE, ..) 

I think that I can test upload in another new project with clean FuelPHP files this evening and update this issue soon

**Comment by WanWizard** [comment]
Ok. I'm very interested to see what happens, as I can't reproduce it here.

**Comment by billmn** [comment]
Ok ... I have the same error on a fresh install.

I've created a repo for you : https://github.com/billmn/fuel-upload-test
I know, the code is horrible, but is only a test :)
- If you try to upload, it's ok
- If you try to upload without files the message is right
- If you try to upload again the same file :
  <pre>
  array(1) {
  [0]=>
  array(1) {
    ["error"]=>
    int(110)
  }
  }
  </pre>

**Comment by WanWizard** [comment]
Thanks for taking the time, this made finding it a breeze!
