### ISSUE TITLE
[Feature] Different Paths

### ISSUE THREAD

**Issue by gwainor** [fuel/core#895]
Hello,

I checked the Package class and saw, there is no option for additional paths.

To explain this Let's say I am creating a Website network. Same host but different domains. So since core files are the same, I would place the core folder to htdocs/../fuel/core.

Then since I will use some of the packages network wide, I will place the packages folder to htdocs/../fuel/packages. I will place the packages like Auth to the general packages place. But What if I want to create a package only to one site of the network, If I place them to general packages path, there will be massieve of files and folders in there. Even if someone hacked one of my sites, they will probably easyly access other sites packages (yes a little dreaming :D ) Or There could be same named packages but does different things.

I hope you get my point. There could be a array in app/bootstrap.php that I can define different paths for packages, views, models, migrations. So I won't have to write same paths when I load the package like `\Package::load('MyPackage', APPPATH.'packages/')`

Ofcourse this is not a must-have feature but it will be good.

**Comment by WanWizard** [comment]
The Package class does support multiple locations, but indeed only on individual load. Same goes for the package section of always_load in the config.

However, nothing else supports multiple paths at the moment, so implementing that (like was done for modules) through the entire framework is quite an undertaking.

I don't expect this for the 1.x branch, but 2.0 should support this.

**Comment by WanWizard** [comment]
You can now do stuff like

```
/**
 * To enable you to split up your additions to the framework, packages are
 * used. You can define the basepaths for your packages here. By default
 * it defined the standard PKGPATH location defined in your index.php
 */
'package_paths' => array(
    PKGPATH,
    COREPATH.'..'.DS.'packages'.DS,
),
```

Which will load packages from the app's PKGPATH, and if not found, from my centrally installed package path (in my case COREPATH points to a server-wide core installation)
