### ISSUE TITLE
Uri::create method retrieves current url when passing empty string as uri

### ISSUE THREAD

**Issue by santiagofs** [fuel/core#896]
Uri::create method with an empty string passed as $uri should retrieve route for the base url.

I suggest replacing:
`$uri = $uri ?: static::string();`
for
`$uri = is_null($uri) ? static::string() : $uri;`

This came across when handling a dynamic menu, one of its links was for the home page.

**Comment by WanWizard** [comment]
Both `Uri::create()` and `Uri::create("")` will return the base_url.

If you are not using 1.1/develop, then this issue is already fixed.
