### ISSUE TITLE
New Inflector method: auto singularize / pluralize words

### ISSUE THREAD

**Issue by ronan-gloo** [fuel/core#90]
I think it's one of the most overused feature when working with strings, the ability to return a plural / singular string automatically.

A simple code suggestion with comments: [gist code](https://gist.github.com/950500)

Sadly, i have no good method name to propose.

**Comment by bencorlett** [comment]
that's a sweet idea. so sick of

<?=count($items)?> item<?=count($items) != 1 ? 's' : null?>

**Comment by jschreuder** [comment]
This is one of those cases where I'm not sure if it's not too specialized for the core. One the one hand it looks like something that is often needed, on the other hand I'm not sure if this is good practice and saves enough to warrat a specialized method. Strings meant for user output are in best-practice put into lang files, the Inflector is meant more for core usage to singularize model names and pluralize table names and stuff like that.

Also you'll stand a better chance of having this accepted by closing this and writing it yourself and doing a pull-request.

**Comment by philsturgeon** [comment]
Not sure about this, its already pretty simple: 

```
<?= count($items) > 1 ? 'items' : 'item' ?>
```

**Comment by bencorlett** [comment]
count(items) !== 1

**Comment by philsturgeon** [comment]
$bar == 28?

**Comment by bencorlett** [comment]
28 items
1 item
0 items

**Comment by philsturgeon** [comment]
Sorry if my quick-fire pseudo code contained bugs :p Either way, this is not something that needs a method, documentation, unit tests, etc.
