### ISSUE TITLE
Migrations no longer work on < php5.3.3

### ISSUE THREAD

**Issue by rob-mccann** [fuel/core#902]
PHP 5.3.2 and below try to call the migrate function as a constructor for the Migrate class but throws a fatal error because it is a static function.

Here's some background info from the php docs that seems relevant

> As of PHP 5.3.3, methods with the same name as the last element of a namespaced class name will no longer be treated as constructor. This change doesn't affect non-namespaced classes.

Presumably the migrate function needs renaming?

n.b. Ubuntu 10.04 LTS uses 5.3.2 in it's repo

**Comment by jschreuder** [comment]
Probably better to solve it by adding a `__construct()` method, that should supersede the constructor assumption for `migrate()`. (clearly docblocked that it's just for 5.3.2 compat)

**Comment by rob-mccann** [comment]
There's now a 'redefining already defined constructor' error thrown (line 604).

**Comment by WanWizard** [comment]
Grrr... 

What a stupid implementation. Which idiot came up with this error? Would it not have been easier to just take __construct() instead of bailing out with a failure?

**Comment by WanWizard** [comment]
Pushed a fix for this (sorry, wrong issue number in the commit message)

**Comment by rob-mccann** [comment]
No cigar, my friend. Same error, line 279 :(

**Comment by WanWizard** [comment]
So, you can't have __construct() AND a method called the same as the class? This is plain stupid!

**Comment by WanWizard** [comment]
I gave up. The migrate() method is no more...
