### ISSUE TITLE
Not counted config directive errors.throttle

### ISSUE THREAD

**Issue by ghost** [fuel/core#905]
In app config we have:
    'errors'  => array(
        // How many errors should we show before we stop showing them? (prevents out-of-memory errors)
        'throttle'     => 10,
    ),

but in static method \Error::error_handler() fuel tries to read Config::get('errors.throttling', 10) and then \Config::get('error_throttling', 10).

It seems someone forgot to change either config or error class.

**Comment by WanWizard** [comment]
@FrenkyNet does this close this issue?

**Comment by frankdejonge** [comment]
Commit message typo, closing now.

**Comment by ghost** [comment]
Nope there is one more place to fix in \Error::error_handler(): 
Config::get('errors.throttling', 10)

Should be:
 Config::get('errors.throttle', 10)

Or app config.php should be changed to errors.throttling..

**Comment by WanWizard** [comment]
Looks like that is fixed now.

**Comment by ghost** [comment]
Maybe.. can't find latest app config.php file in repo (

**Comment by WanWizard** [comment]
looking in the wrong repo? (it's in fuel/fuel)

**Comment by ghost** [comment]
Yes, I looked there but it's 3 month old, so I thought it's an old one or something.
But if it is a correct place to look, then problem still exists!
Inconsistent config names (errors.throttle vs errors.throttling):
    'errors'  => array(
        // Which errors should we show, but continue execution?
        'continue_on'  => array(E_NOTICE, E_WARNING, E_DEPRECATED, E_STRICT),
        // How many errors should we show before we stop showing them? (prevents out-of-memory errors)
        'throttle'     => 10,
        // Should notices from Error::notice() be shown?
        'notices'      => true,
    ),

**Comment by WanWizard** [comment]
I searched the entire core for "errors.throttling" but found none. "errors.throttle" is correct and used in both the config file and the two locations in the Error class where this value is used.

So I haven't got a clue what you're on about. Is your core up to date? Are you looking at the wrong branch?

**Comment by ghost** [comment]
Did I missed something?

https://github.com/fuel/core/commit/6a3fef70e479d7ed4212944999e757dc8e5088ee

**Comment by ghost** [comment]
Hmm just checked code in repo, indeed it's fixed.. Hmm but no comment on commit that fixed it ((  OK then everything is ok now, sorry
