### ISSUE TITLE
Validation, input issue

### ISSUE THREAD

**Issue by shulcsm** [fuel/core#908]
In case if you want to validate incomplete array (you probably would, this is why you are validating it in the first place) https://github.com/fuel/core/blob/1.1/develop/classes/validation.php#L493 it checks the global input for missing key which obviously is unwanted behaviour

**Comment by vindavs** [comment]
+1.
Example: 

``` php
$_POST = array('foo' => 'bar');
$validation = Validation::forge()->add_field('foo', 'Foo', 'required');
assert($validation->run(array()) === false); // fails
```
