### ISSUE TITLE
Validation run on child Fieldset objects

### ISSUE THREAD

**Issue by BenExile** [fuel/core#909]
When validation is run on a Fieldset that has sub-sets (added via `$a->add($b)`, for instance), any validation errors that occur are not accessible as Fieldset_Field::error() returns false in each case and because of this the `error_class` is not applied to any field of a child fieldset when the form is built.

The result I would expect would be that the validation class ran recursively over it's children and the `error_class` was applied, and/or the inline message was displayed (where appropriate), when the form is built.

**Comment by WanWizard** [comment]
This is very complex due to the way the relation between validation, fieldset and form classes is setup.

We have decided not to address this issue in the 1.x development train, but address it in 2.0, which has a completely different way of dealing with fieldsets and validation.

**Comment by BenExile** [comment]
Thanks for confirming. Is there a timescale for the release of 2.0? The roadmap looks great :)

**Comment by jschreuder** [comment]
No timescale, but the Kernel package ('the core of the core') is pretty much done (though there may still be some API tweaking). The Core package is another story, that's far from ready at this point. We think we'll release the first beta this summer.

**Comment by jschreuder** [comment]
You can find 2.0 on github.com/fuelphp btw.
