### ISSUE TITLE
DBUtil:modify_fields produces incorrect SQL when renaming columns

### ISSUE THREAD

**Issue by bunchjesse** [fuel/core#910]
When renaming fields, you should use `ALTER TABLE...CHANGE` instead of `ALTER TABLE...MODIFY` which is what is currently hard-coded.

This issue originates from a change this commit: cd151a68b961f11074e461f268dfd06441140f22. However, simply reverting this commit would re-introduce the original issue that prompted the change. A possible fix would probably check to see if you're renaming the field and adjust the `alter` type appropriately.
#### Test Code

```
\DBUtil::modify_fields('members', array(
    'creation_date' => array('name' => 'created_at', 'type' => 'INT', 'default' => 0),
    'modified_date' => array('name' => 'modified_at', 'type' => 'INT', 'default' => 0),
));
```
#### Produces this SQL

```
ALTER TABLE `members` 
MODIFY `creation_date` `created_at`  INT DEFAULT '0' NOT NULL,
MODIFY `modified_date` `modified_at`  INT DEFAULT '0' NOT NULL
```

Note: This SQL would be fine if we weren't renaming the columns.
#### But Should Produce this SQL

```
ALTER TABLE `members` 
CHANGE `creation_date` `created_at`  INT DEFAULT '0' NOT NULL,
CHANGE `modified_date` `modified_at`  INT DEFAULT '0' NOT NULL
```

**Comment by WanWizard** [comment]
Looked at that original commit, but changing MODIFY back to CHANGE doesn't really affect the other modifications.

@FrenkyNet, what do you think?

**Comment by bunchjesse** [comment]
@WanWizard Right, but if you hard code it back to CHANGE, it will fail if you don't change the name of the field.

For instance, this isn't valid either:

```
ALTER TABLE `members` 
CHANGE `creation_date` INT DEFAULT '0' NOT NULL,
CHANGE `modified_date` INT DEFAULT '0' NOT NULL
```

**Comment by frankdejonge** [comment]
I think the best option now it to create (yet another) param to force using change, in the next query builder this should be an option too. That's the only way to really fix this. We're trying to address 2 different scenario's in one function where one excludes the other.

**Comment by bunchjesse** [comment]
Given the current setup, adding a `DBUtil::change_fields()` method makes the most sense to me. I'll submit a pull request if you agree.

**Comment by frankdejonge** [comment]
Adding the param will move $db (which we want as the last param) and therefor break BC, so a change_fields function is the way to go. If you send a pullrequest, also add it to the docs and request a pull for that as well. Thanks!

**Comment by frankdejonge** [comment]
In the docs it must be really clear what the difference is between the 2 functions though. Keep that in mind.

**Comment by frankdejonge** [comment]
@bunchjesse Wait a second, I think I have a better solution.

**Comment by bunchjesse** [comment]
OK, if it doesn't work out, here is the docs pull request: https://github.com/fuel/docs/pull/339
