### ISSUE TITLE
AutoLoader problems when multiple class defined in the same file

### ISSUE THREAD

**Issue by krtek4** [fuel/core#913]
I'm having a problem with the `AutoLoader` when multiple classes are defined in the same class.

In the Auth package, the `classes/auth.php` file defines two classes : `Auth` and `AuthException`.

Now, if I try to extend the `AuthException` class in one of my own file, logically the `AutoLoader` load the class from the file and everything is fine. (It is important to note that I haven't done any access to the `Auth` class for now, `AuthException` is the first class from this file I try to access)

**But**, since the file was included, the `Auth` class is now also accessible and thus the `AutoLoader` is not called when trying to access the `Auth` class. As a result, the `_init()` method of the `Auth` class isn't called.

I've resolved this by explicitly accessing the `Auth` class before doing my inheritance, but I think this should be corrected in the `AutoLoader`. Sadly I haven't the slightest idea how to correct this. Each class from a file could be initialized, but this could raise other problems.

**Comment by WanWizard** [comment]
The autoloader can't deal with multiple classes.

Please create an issue for this in the Fuel/Auth repo issue tracker, so those two can be split.

**Comment by krtek4** [comment]
Problem is the same case also presents itself in the core :
- classes/request.php
- classes/httpexceptions.php
- classes/theme.php
- classes/ftp.php
- classes/config.php
- classes/fuel.php
- classes/cache.php
- classes/request/driver.php
- classes/redis.php
- classes/package.php
- classes/file.php

I know some of the file I have listed are not concerned, but this is all the core files which contains more than one class definition (mainly Exception).

Each time someone will inherit or use one of these exception before trying to load the "main class", the error will arise.

**Comment by WanWizard** [comment]
Looked at this again.

These exceptions are specific for the class they're defined with, you should not use them other then in relation to this class. So it's fine to use them if you extend one of these classes, as the original will be loaded too.

You should not define a new class, and reuse one of these exception classes.

**Comment by krtek4** [comment]
The problem persists if I declare the following :

```
class MyException extends ExceptionA {}

class MyClass extends A {}
```

The autoloader will find the reference for `ExceptionA` first, load the file, and when the declaration for `MyClass` will be reached, the `_init()` method of `A` won't be called.

**Comment by WanWizard** [comment]
I understand that you can come up with a scenario in which it fails.

My point is that you shouldn't do that. If you just extend a core class, or extend a core class AND its exception class at the same time, there is no issue.

As I wrote before, you should not use your own exceptions in your own classes, and then extend a core exception.

**Comment by krtek4** [comment]
> > its exception class at the same time, there is no issue.

This particular scenario fails. You can try it :

```
class MyAuthException extends AuthException {}

class MyAuth extends Auth {}
```

in the same file will results in the `_init()` method of `Auth` to never be called. Sure your an workaround this pretty easily, for example by moving the declaration of the new exception afterward.

BTW,  I understand that a fix for this problem is really hard to find and I'm not asking for one. Just some documentation somewhere for people having the same problem that I did. It took me a while to figure out what was happening.

**Comment by WanWizard** [comment]
That's what I said. It's not needed and rather pointless to do

```
class MyAuthException extends AuthException {}
```

And if you don't, you don't have the problem. Do this instead:

```
class MyAuthException extends Exception {}
```

The issue can not be resolved other then creating separate files for all exception classes, which is a waist of file I/O given my previous statement, or by adding very complex code to the autoloader to detect which classes are defined in the file loaded.
