### ISSUE TITLE
Make sessions initialize more lazily

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#918]
While thinking about [this topic](http://fuelphp.com/forums/topics/view/8789), I started wondering why we don't initialize sessions more lazily? Is it really necessary to initialize a session when we don't or haven't saved anything to it? Could it be better to only initialize when something is written to it or when something is fetched from it and there already is a session?

This might save a lot of data-retrieval on a website where only part of the visitors are logged in for example.

**Comment by WanWizard** [comment]
Sessions only auto-initialize if the "auto_initialize" key in the session config file is true (which is the default).

The reason behind making this default is that if you don't use the session in your request, your session cookie is not refreshed so it might expire when you don't expect it. So for "normal" usage auto initialize is fine.

Those that don't want it, can switch it off in the config.

**Comment by jschreuder** [comment]
I know all that, I may have even been the one that added the auto_initialize config.

What I meant is far later in the process. When I use Session::get() a session will always be present, whether a value had been saved to it or not. Just by the act of checking for a session value I am initializing one. My point was if we can't change that to only initialize a session when it's actually needed. Which means only when a value is set upon it or when a value already has been set upon it.

**Comment by WanWizard** [comment]
Ok, this is about creating a new session?
