### ISSUE TITLE
Form::checkbox should allow no attribute value

### ISSUE THREAD

**Issue by ziadoz** [fuel/core#92]
It would be useful if `Form::checkbox()` allowed for a toggle checkbox to be created, by omitting the `value` attribute if the parameter passed is `null`.

``` php
/*
Array ( 
    [enable_foo] =>
    [enable_bar] => on
);
*/

<?php echo Form::open(); ?>
    <?php print_r($_POST); ?>

    <?php echo Form::checkbox('enable_foo', null, array('checked' => 'checked')); ?>
    <input type="checkbox" name="enable_bar" checked="checked" />

    <?php echo Form::submit('Submit'); ?>
<?php echo Form::close(); ?>
```

**Comment by jschreuder** [comment]
That would be invalid HTML: http://www.w3.org/TR/html401/interact/forms.html#h-17.4 and as far as I know this is still the case for XHTML1.1, thus I would consider this correct behavior.
