### ISSUE TITLE
\Input::real_ip() doesn't take into account CSV

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#921]
A lot of proxies will send CSV data in the headers. We discovered an issue yesterday where a proxy sent something along the lines of "192.168.1.5,23.44.55.66, 10.20.30.40" as the HTTP_X_FORWARDED_FOR. The fix was to assume that all headers could be CSV, split on the comma, loop and return the first IP address which is not in a private range (as decided by a CIDR check). 

Is this worth me implementing?

**Comment by WanWizard** [comment]
If you have multiple proxies chained you will indeed receive a comma-separated list (officially, comma+space separated, so make sure to trim the results).

I don't agree with filtering it on range type, most of my apps run in an intranet context, all real IP's will be 10.x.y.z. When you filter on private IP, this method would become useless for me.

Perhaps a better solution is to add a second parameter, whose default value causes the first IP (= client IP) to be returned, and the non-default value the first public IP. You can use filter_var() for that, combined with the FILTER_FLAG_NO_RES_RANGE and FILTER_FLAG_NO_PRIV_RANGE flags.

**Comment by phil-lavin** [comment]
Put another commit in there to correct the use of $_SERVER. It's better tracked at #936

**Comment by WanWizard** [comment]
Pull request was merged and documented.
