### ISSUE TITLE
Lazy session creation with simpleauth bug

### ISSUE THREAD

**Issue by raquo** [fuel/core#928]
I am using simpleauth with all default settings – cookie based sessions, auto_initialize true, etc. Everything used to work, but after I've updated to latest 1.1/develop today, `Auth::instance()->login(...)` throws the following error:

```
ErrorException [ Notice ]: Undefined index: user_agent
COREPATH/classes/session/driver.php @ line 478:
elseif ($this->config['match_ua'] and $cookie[0]['user_agent'] !== \Input::user_agent())
```

And it does not log me in.
The fuelcid cookie does get created with this content (encrypted):

```
/a:3:{i:0;a:4:{s:11:"previous_id";N;s:10:"session_id";s:32:"md5_hash_here";s:7:"created";i:1335050500;s:7:"updated";i:1335050500;}i:1;a:2:{s:8:"username";s:5:"raquo";s:10:"login_hash";s:40:"md5_hash_here";}i:2;a:0:{}}
```

Note that it doesn't have the user_agent key, since the `Session_Cookie::create` method doesn't get called (as far as I can tell).
Subsequent attempts to `Auth::instance()->login(...)` while already having that cookie don't fix the problem.

I think this bug was probably introduced somewhere in 63998ad9dc65cc971a78c847ec910899b5d691da (#918). I can't fix it myself :/

**Comment by WanWizard** [comment]
The create() method is called from the write() method. Issue is probably that SimpleAuth calls the rotate() method, which doesn't check if it's a new session.
