### ISSUE TITLE
Wrong return type in phpdoc for Input::get()

### ISSUE THREAD

**Issue by darklow** [fuel/core#932]
By some reason there is `return void` for Input::get phpdoc block

``` php
/**
 * Gets the specified GET variable.
 *
 * @param   string  $index    The index to get
 * @param   string  $default  The default value
 * @return  void
 */
public static function get($index = null, $default = null)
{
  return (func_num_args() === 0) ? $_GET : \Arr::get($_GET, $index, $default);
}
```

**Comment by WanWizard** [comment]
Can you send a pull request?

**Comment by darklow** [comment]
I wish, but i haven't set up contribution environment yet as required in contribution documentation. Maybe someone who has it, can do a fast fix? Thanks.
Correct `@return` phpdoc i gues must be the same as for post() method
`* @return  string|array`
