### ISSUE TITLE
Uniform URI Structure

### ISSUE THREAD

**Issue by jcldavid** [fuel/core#937]
I think Fuel should implement a uniform URI structure to make all URLs enforce a trailing `/` (forward slash?). 

```
    // URL: http://localhost/
    Uri::base();
    //output: http://localhost/

    // URL: http://localhost/controller/index/
    Uri::current();
    //output: http://localhost/controller/index
```

**Comment by jschreuder** [comment]
I would agree in general but I would certainly not enforce a trailing slash, instead I'd propose to strip the trailing slash when present and thus handle both with & without the same. This has already been implemented in 2.0.

The reason for stripping it is that enforcing it leads to weird URLs when using a suffix/extension, like `http://localhost/controller.html/`.

**Comment by jcldavid** [comment]
Oh, that would be better. then just use `url_suffix` in the config to enforce a trailing slash?

**Comment by jschreuder** [comment]
That could work, but you'd have to call on `Input::extension()` in order to get the trailing slash... (which is kinda useless of course)

**Comment by WanWizard** [comment]
The difference between the two is that the base URL (as the name implies) is used a base for constructing URL's, so the trailing slash is always needed. It is never meant as a means of returning the hostname.

Uri::current() points the the current page, which is never a directory, and therefore always without trailing slash. Even though it might look like a directory to you, it is actually a page name, without a file extension.

So imho this behaviour is correct.
