### ISSUE TITLE
File::copy to new file using area restrictions fails

### ISSUE THREAD

**Issue by iturgeon** [fuel/core#941]
File::copy is throwing a OutsideAreaException error when it shouldn't

config/files.php:

```
'areas' => array(

     'media' => array(
        'basedir'        => PKGPATH . 'pckg/media/',
```

Code that copies/renames a file into another directory:

```
$from = PKGPATH . 'pckg/media/uploads/img_1147.jpg';
$to = PKGPATH . 'pckg/media/n1nlI.jpg';
File::copy($from, $to, 'media');
```

File::copy uses Fuel/Core/File_Area::get_path() which will end up running realpath() on the source and target paths,
realpath() returns false on the target because:

```
realpath() returns FALSE on failure, e.g. if the file does not exist.
```

This ends up setting $path to false within Fuel/Core/File_Area::get_path() which will kill it's functionality, and throw an error in this case.

So... I suggest the following to get around the issue of realpath checking for a file that doesn't yet exist... rather have it check for the directory (which we expect to exist in this case)

Fuel/Core/File::copy()

```
public static function copy($path, $new_path, $area = null)
{

    $path      = static::instance($area)->get_path($path);
    $new_file  = basename($new_path);
    $new_path  = static::instance($area)->get_path(dirname($new_path)) . DS . $new_file;

    if ( ! is_file($path))
    {
        throw new \InvalidPathException('Cannot copy file: given path is not a file.');
    }
    elseif (file_exists($new_path))
    {
        throw new \FileAccessException('Cannot copy file: new path already exists.');
    }
    return copy($path, $new_path);
}
```

**Comment by iturgeon** [comment]
I can initiate  a pull request if I'm not doing something insane here.

**Comment by WanWizard** [comment]
This is not the correct solution, as there are more methods that use get_path(), and might have the same issue, like File::rename().

It would probably be better to give get_path() a second parameter to indicate the filename should be stripped if true (so only the path is checked, which must exist). The copy() and rename() methods can then use this second parameter on their $new_path calls...

**Comment by WanWizard** [comment]
@jschreuder, mind looking at this? I see get_path() being called all over the place while being passed a filename instead of a path. If this issue is valid, not a lot of the File classes actually works..

**Comment by jschreuder** [comment]
Actually this shouldn't be able to rename, that's what the rename method is for. But you are right that this cannot work currently, though that has little to do with `get_path()`, which is just a method to ensure that the given path is a full path and falls within the expected FileArea. The problem is that the `$new_path` variable should include the filename which it currently doesn't.

The solution here is to change the `$new_path` declaration to the following:

``` php
<?php
$new_path  = rtrim(static::instance($area)->get_path($new_path), '\\/').DS.basename($path);
```

**Comment by iturgeon** [comment]
Agreed, the above change will change copy to prevent renaming (docs need to mention this?)

However `File::rename()` is plagued by the same issue where `real_path()` will be called on a new path+file when using area restrictions.

**Comment by WanWizard** [comment]
That is what I meant, File::rename() uses basically the same logic as File::copy(), thus hitting the same issue().

**Comment by WanWizard** [comment]
@jschreuder No, the issue is that get_path() fails when an area is active, and the path passed to get_path() contains a filename. So the filename needs to be stripped, get_path() needs to operate on the path only.
