### ISSUE TITLE
version update

### ISSUE THREAD

**Issue by it-can** [fuel/core#942]
the version should be updated to 1.2 if I am not mistaken...

https://github.com/fuel/core/blob/1.2/develop/classes/fuel.php#L37

**Comment by it-can** [comment]
I see it has already been fixed! thanks

**Comment by WanWizard** [comment]
We're still busy with the preparations. Once finished it will be branched to 1.2/master.

**Comment by it-can** [comment]
ok nice... I always use a develop version, I like new features ;-)

**Comment by WanWizard** [comment]
Maybe not a good idea now, 1.2/develop is broken at the moment until we are finished removing deprecated code...

**Comment by it-can** [comment]
ok, thanks for the heads up... I'll switch back to 1.1/develop for the moment...

**Comment by WanWizard** [comment]
After 1.2 has been released, we'll create a 1.3/develop as the new active development branch. Once that appears you can switch to that to be on the bleeding edge again.

**Comment by it-can** [comment]
Ok cool, thanks for the info! Is there some sort of planning for this?

**Comment by WanWizard** [comment]
1.2 RC is planned for today.
