### ISSUE TITLE
Arr::is_assoc doesn't work properly for assoc arrays with numeric indices

### ISSUE THREAD

**Issue by Daniel15** [fuel/core#949]
Arr::is_assoc doesn't work correctly when you have an associative array with numeric indices.

Example:

``` php
$test = [5 => 'foo', 15 => 'bar'];
Arr::is_assoc($test); // false
```

One [alternative I saw on StackOverflow](http://stackoverflow.com/a/265144/210370) is this:

``` php
return array_values($arr) === $arr
```

But I haven't tested this in all scenarios.

Additionally, this function should probably use the "array" typehint which was introduced in PHP 5.1:

``` php
public static function is_assoc(array $arr)
```

**Comment by WanWizard** [comment]
Well, that's because it is not an assoc array, it has numeric keys only.

An indexed array is an array with only numeric keys, and if not, it's an associative array.

**Comment by Daniel15** [comment]
So even if the numbers are not incremental, the array is still classified as "indexed"? I use arrays like this as lookups and wouldn't consider them as indexed arrays.

**Comment by WanWizard** [comment]
At the moment, yes. I haven't found any reference to the requirement that an indexed array needs to have consecutive keys. 

Do you have a use case where this is required?

**Comment by Daniel15** [comment]
I was trying to look but couldn't find much. 

I forgot the original issue I encountered due to this (I really should have written it in this issue). If I remember it I'll add it in here. 

But there's some cases when arrays with numeric keys are used like associative arrays (like if you have a lookup of ID => Name or something similar).

**Comment by WanWizard** [comment]
I understand that, but that doesn't make it an assoc array.

The only question is: is an array with non-consecutive numeric index values an assoc array or not?

**Comment by WanWizard** [comment]
@jschreuder any comments on this?
