### ISSUE TITLE
Allow custom Environments to be defined

### ISSUE THREAD

**Issue by darrentaytay** [fuel/core#963]
Currently there are 4 predefined constants in Fuel - Development/Test/Stage/Production.

If you create a new environment in your config folder such as /fuel/app/config/demo, you can add your configs etc. and that's fine - however, you can't run Oil and specify that environment as it looks for a Constant that matches your environment passed in:

\Fuel::$env = constant('\Fuel::'. strtoupper($env)) ?: \Fuel::DEVELOPMENT;

This restriction should be lifted or there should be a way of being able to define your own environment constants.

**Comment by WanWizard** [comment]
Issue has been dealt with in https://github.com/fuel/oil/commit/d14f9478bd31412e46bcf3e4d6535ee6f964bcd6

**Comment by darrentaytay** [comment]
Thanks for this!
