### ISSUE TITLE
Validation::_validation_match_field() - ErrorException if a field doesn't match 

### ISSUE THREAD

**Issue by quetzyg** [fuel/core#964]
When validating a field to see if it matches a previous one, I get the following notice:

Notice!

ErrorException [ Notice ]: Trying to get property of non-object

COREPATH/classes/validation.php @ line 684:

683:    $validating = $this->active_field();
684:    throw new \Validation_Error($validating, $val, array('match_field' => array($field)), array($this->field($field)->label));
685:    }

Steps to reproduce:
- Create a validation object and add a match_field rule:
  $val = Validation::forge();
  $val->add('password_confirm', 'Password (confirm)')->add_rule('match_field', 'password');
- Submit the fields with different values so they don't match
- Run the validation:
  $val->run()

I was only aware of this after setting Fuel::$env from  Fuel::PRODUCTION to Fuel::DEVELOPMENT

**Comment by WanWizard** [comment]
This has nothing to do with the validation rule.

You get this error because there is no fieldset field defined for the field 'password'. The validation class needs to access that field to retrieve the field label.

So make sure all fields referenced in rules are defined:

```
$val->add('password');
```

**Comment by quetzyg** [comment]
You are absolutely right!
Sorry for the false positive :)
