### ISSUE TITLE
In special cases the Image class produces 1 pixel wide output

### ISSUE THREAD

**Issue by TamasBarta** [fuel/core#967]
If you are using the crop_resize function, some rounding problems might occur. It takes two steps, to resize, and to crop, but with some values, after the first step, you can get a 1 pixel narrower than desired, and in this case, the final output will be 1 pixel wide.
I only reviewed the problem very shallow, so it might not be exactly there, it could be a gd library bug, since I had no possibility to test it with imagemagic yet.

**Comment by WanWizard** [comment]
Could you add some code examples to reproduce this, the current description is very vague...

**Comment by TamasBarta** [comment]
``` php
Image::load(DOCROOT . $path)->
                    crop_resize($width, $height)->
                    output();
```

Where the source image is 3872x2592pixel, and $width = 690, and $height = 260.
In my case all the images are portrait images compared to 690x260 so I can ignore the x offset when cropping, so I resolved it at the moment by replacing

``` php
        $x = floor(($sizes->width - $width) / 2);
```

with 

``` php
        $x = floor(max(0, $sizes->width - $width) / 2);
```

at line 362 in fuel/core/classes/image/driver.php (that's where the two step I mentioned takes place)

I hope that's enough information.
By the way, you work quite fast, I'm impressed :)
