### ISSUE TITLE
Validation valid_string error message is strange

### ISSUE THREAD

**Issue by kenjis** [fuel/core#968]
Test code:

``` php
        $post = array(
            'f1' => 'abc',
        );

        $val = Validation::forge('valid_string_test');
        $val->add('f1', 'F1')->add_rule('valid_string', 'numeric');
        $val->run($post);
        $test = $val->error('f1')->get_message();
        var_dump($test);
```

Result:
`string(54) "The valid string rule valid_string failed for field F1"`

Lang file:
`'valid_string'  => 'The valid string rule :rule failed for field :label',`

valid_string has array flags, so I can't change lang file to `The valid string rule :param:1 failed for field :label'`.

**Comment by WanWizard** [comment]
In this example, :param:1 is replaced by "numeric" without problems, so what exactly doesn't work?

**Comment by kenjis** [comment]
In this example, current code shows **The valid string rule valid_string failed for field F1**. There is no ":param:1" in lang file. So ":param:1" is not replaced by "numeric".

And if we'll change to use ":param:1", it could be "Array", because valid string can take array as its param.

I put the running code:

``` php
<?php

class Controller_Tests_ValidString extends Controller
{
    public function action_index()
    {
        $post = array(
            'f1' => 'abc',
        );

        $val = Validation::forge('valid_string_test');
        $val->add('f1', 'F1')->add_rule('valid_string', 'numeric');
        $val->run($post);
        $test = $val->error('f1')->get_message();
        var_dump($test);

        return '';
    }
}
```
