### ISSUE TITLE
More detailed error logging

### ISSUE THREAD

**Issue by Daniel15** [fuel/core#970]
Currently, exceptions and errors are logged to the log file with messages like this:

> Error - 2012-05-19 12:13:57 --> 8 - Undefined offset: 0 in /var/www/myapp/live/fuel/app/classes/blah/blah.php on line 197

These are okay, but they don't give much information about the error. I can tell which line the error occurred on, but can't really tell what caused it (whether it's due to my code being bad, or bad input, or what), nor can I tell what actually called the specified file (it could be any page on the site that uses this class). This makes it hard to replicate the error.

Ideally I'd like to see a stack trace and all the POST and GET data associated with the request. In the ASP.NET world, [ELMAH](http://www.hanselman.com/blog/ELMAHErrorLoggingModulesAndHandlersForASPNETAndMVCToo.aspx) does this really well, giving a lot of details about the error and allowing you to store error details pretty much anywhere (in a database, or XML file, or in memory)

**Comment by WanWizard** [comment]
As not everyone would like this, I don't think the core should be modified.

This might be a candidate for a new core event, so can plug an app method in that will take care of this.

**Comment by Daniel15** [comment]
Make it an option, perhaps? 
Or if not, some way for the app or a module or some sort to take over the logging would be great.

**Comment by WanWizard** [comment]
That is already possible, simply extend the Error class in your application (or a package).

**Comment by Daniel15** [comment]
True, but it'd be a little bit easier and cleaner if the call to `logger` was in a separate method (so I could override just the logging method, instead of having to copy and paste the whole of `Error::exception_handler` into my app.

**Comment by frankdejonge** [comment]
@Daniel15 you can in fact override the `logger` function. The function is defined in `core/base.php`, so you can set it in the earlier loaded `app/bootstrap.php`.

**Comment by Daniel15** [comment]
@FrenkyNet  That won't override the message that is being logged, though (for example, if I want to add more information from the exception) as `logger` takes a string as its input.

**Comment by frankdejonge** [comment]
@Daniel15: Can't you use the debug backtrace to get the information you need?
