### ISSUE TITLE
Feature Request:  Validation rule that allows 'require' of field when another field is not empty

### ISSUE THREAD

**Issue by jwalton512** [fuel/core#972]
Would allow a non-required field to be required when another non-required field is completed.

For example, with the following fields in a form:  Address, City, State, Zip
- Address is not required
- If Address is completed, City, State, and Zip should become required

An example implementation would be:
$val->add_field('city', 'City', 'required_with[address]')

**Comment by huzzi** [comment]
+1

**Comment by jwalton512** [comment]
opened pull request
https://github.com/fuel/core/pull/973

**Comment by jschreuder** [comment]
Closed as it's dealt with by #973
