### ISSUE TITLE
Form::select, OPTION=0 never get SELECTED.

### ISSUE THREAD

**Issue by dealunited** [fuel/core#98]
Hi 

EXAMPLE:

$aStatus = array (  '' => '',  
                               -1 => 'status -1',  
                               0 => 'status 0',  
                               1 => 'status 1',  
                               2 => 'status 2'
                               );

Form::select('status', $iStatus=0, $aStatus, array() );

If option $iStatus=0, the option in dropdown is newer SELECTED.

May be it is checked on empty(), should be checked on != " "

Jozef

**Comment by dealunited** [comment]
here is that place in core/classes/form.php

public static function select($field, $values = null, Array $options = array(), Array $attributes = array())
{
.....
.....
$attributes['selected'] = empty($attributes['value']) ? '' : $attributes['value'];
.....
.....
$selected = empty($attributes['selected']) ? array() : array_values((array) $attributes['selected']);

**Comment by jschreuder** [comment]
https://github.com/fuel/core/commit/d08afc79abcbe399b600655f6ca6d2d2b68ac6cc
