### ISSUE TITLE
[Suggestion] Separate Controller_Rest and the authentication

### ISSUE THREAD

**Issue by Savageman** [fuel/core#989]
We could need the REST, but without the authentication.
The goal of this is to have a lighter Controller_Rest, and less coded loaded.

**Comment by WanWizard** [comment]
Authentication is optional, so what is the issue, the handful of lines of code?

**Comment by Savageman** [comment]
Yes, unneeded code is loaded.
I'm thinking about Controller_Hybrid which I'm not sure needs that at all.

**Comment by WanWizard** [comment]
The Controller_Hybrid extends Controller_Rest and adds some action specific code. I am not in favour of crippling the controller, which means we can no longer extend, we will have two base controllers with the same Rest code, and two base controllers dealing with Rest calls that don't have the same functionality.

@jschreuder @philsturgeon Comments?

**Comment by Savageman** [comment]
Hum. I think you're right. Can't think of a nice implementation without traits in PHP 5.4.

**Comment by philsturgeon** [comment]
Yeah this is getting down the line of multiple inheritence and I'd much rather avoid it until PHP 5.4.

REST for example can have Authentication as a trait, but you could also add that to anything else. AJAX again should be a trait (error if asked non-AJAXy), etc.

Hybrid kinda makes sense but seems like a temporary solution until traits are used.

**Comment by WanWizard** [comment]
Based on these comments I close this issue.
