### ISSUE TITLE
Allow complex WHERE clauses for DB class

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#99]
Currently, it appears that the WHERE clause must contain 3 parameters. It would be nice to allow the user to enter their own complex where clause such as:

$query->where("((t.timestamp =
            (SELECT MAX(timestamp) FROM client_history WHERE client_id = t.client_id))
            OR
            (t.timestamp IS NULL)
            )"

I suggest that if parameters 2 and 3 to the function and_where() in where.php are null, then the function _comple_conditions() in  builder.php ignores parameters 2 and 3 ($op and $value in _comple_conditions() and also does not apply any quotes or escaping.

**Comment by jschreuder** [comment]
Already possible: you can create a query object and use that as a subquery in another query object and there are methods and_where_open()/and_where_close() or or_where_open()/or_where_close().

EDIT: And if you want to add values that aren't escaped they need to be wrapped in a Database_Expression object which can be done through [DB::expr()](http://fuelphp.com/docs/classes/database/db.html#method_expr)

**Comment by Mitchell64** [comment]
Thanks for your reply. Is this documented anywhere and are there any
examples?

Thanks,
Mitchell

**Comment by jschreuder** [comment]
Not really, the query builder only has some simple docs still and needs a lot more.
