### ISSUE TITLE
Different Language file WITHOUT group

### ISSUE THREAD

**Issue by Miguel-Herrero** [fuel/core#995]
If I try to load a different language file, but without assigning a group, shouldn't this work? `Lang::load('example', '', 'es');`

It doesn't (at least as I expected), because I have to fetch line as `Lang::get('.hello');`(you see the dot before line's identifier?) If it is not an issue, why do I have to assign it to a different new group when changing from one language to another?

I tried to load the default language `Lang::load('example');` and a different language with a different group `Lang::load('example', 'test', 'es');` to see if I could work with both at the same time and it is not possible neither…

**Comment by WanWizard** [comment]
I don't see why that shouldn't work. It will just create an element in the loaded languages array with "" as the key. 

And I've just tested this:

```
\Lang::load('test', '', 'es');
var_dump(\Lang::$lines);
var_dump(\Lang::get(".hello"));
```

And this works fine. It loads the language file en/test.php (I don't have "es" here), the first dump shows it's loaded with the empty string as key, and the second dump returns the requested language string without problems.

Are you sure a language file called 'example' exists? if not, it will simply not load anything.

**Comment by Miguel-Herrero** [comment]
No, with the dot before it WORKS perfectly. That was not my question.

What I am asking is that I will have to code it before hand differently if I want to change betwen languages or not, because if I code it like

```
Lang::load('test');
Lang::get("hello");
```

it will work with the default language, but if for some reason I want to change language, THIS WOULDN'T WORK:

```
Lang::load('test', '', 'es');
Lang::get("hello");
```

and I would have to change all the lines of my application to 

```
Lang::get(".hello");
```

even when calling to default language, because this

```
Lang::load('test');
Lang::get(".hello");
```

wouldn't work either (I would have to use `Lang::load('test', '', 'en');` instead)

Wouldn't it be possible (and easier) to keep `Lang::get("hello")` with the new changed language? (if there was no group, I mean):

```
Lang::load('test', '', 'es');
Lang::get("hello");
```

**Comment by WanWizard** [comment]
Ah, ok. So you're saying that `Lang::load('test', '', 'es');` doesn't overwrite `Lang::load('test');`?

That is because the default group isn't "" (empty string), it's NULL. 

The first one creates a multi-dumensional array, with "" as key:

```
array("" =>
    array("beer" => "cerveza")
)
```

With a $group = NULL it will create

```
array("beer" => "cerveza")
```

Which is what you want.

**Comment by Miguel-Herrero** [comment]
Exactly! I looked at the Lang Class code and saw what you said about default NULL group.
Thank you for your time, Harro.
