### ISSUE TITLE
 Number of values in to_assoc must be even.

### ISSUE THREAD

**Issue by thpoul** [fuel/core#999]
Based on the documentation http://docs.fuelphp.com/classes/uri.html#/method_to_assoc when using `\Uri::to_assoc();` and the number of values is odd it should return NULL, instead I get this error:

``` php
BadMethodCallException [ Error ]: Number of values in to_assoc must be even.
COREPATH/classes/arr.php @ line 227
```

**Comment by WanWizard** [comment]
This is correct, and mentioned in the https://github.com/fuel/core/wiki/Changelog-v1.2.

This means the docs haven't been updated to reflect this change. I'll update the docs.
